### ISSUE TITLE
Focusing a sp-menu with no enabled sp-menu-item causes infinate loop

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1009]
### Expected Behaviour
A sp-menu with no enabled sp-menu-item can be focused normally, or can't obtain a focus.

### Actual Behaviour
Call focus on such a sp-menu causes infinate loop, makes the browser stop responding.
### Reproduce Scenario (including but not limited to)
For example, a dropdown will try to focus its menu when opened.
```html
<sp-dropdown label="Select a Country with a very long label, too long in fact">
    <sp-menu>
        <sp-menu-item disabled>
            Deselect
        </sp-menu-item>
        <sp-menu-item disabled>
            Select inverse
        </sp-menu-item>
        <sp-menu-item disabled>
            Feather...
        </sp-menu-item>
        <sp-menu-item disabled>
            Select and mask...
        </sp-menu-item>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-item disabled>
            Save selection
        </sp-menu-item>
        <sp-menu-item disabled>
            Make work path
        </sp-menu-item>
    </sp-menu>
</sp-dropdown>
```
#### Platform and Version
Latest Edge & Firefox
@spectrum-web-components/bundle:  0.15.5

**Comment by OpportunityLiu** [comment]
Will also happen when the `selected` `sp-menu-item` is `disbaled`

**Comment by Westbrook** [comment]
Thanks for the issue. 🙏  Our current working branch had looked into better support for the `empty `menu element, but great catch on the `[disabled]` item context. We will work to get a fix (for both) into our next release.

**Comment by Westbrook** [comment]
This update was released today. Sorry for the delay.

Let us know if you run into any other issues in this area.
