### ISSUE TITLE
sp-styles/font.css is not a valid css file

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1010]
https://github.com/adobe/spectrum-web-components/blob/ca5537c53a0a45068d849bfe8d4a2b22c43afea2/packages/styles/fonts.css#L73-L80

Nested selectors are not currently supported by most browsers

**Comment by Westbrook** [comment]
This update has been released today. Sorry for the delay.

Let us know if you run into any other issues here.
