### ISSUE TITLE
Esc key does not dismiss dialog opened with sp-dialog-wrapper

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1036]
### Expected Behaviour

Pressing **Esc** key should close a modal dialog. Since the dialog could be opened via keyboard, it should be dismissable via keyboard.

### Actual Behaviour

Pressing **Esc** has no effect. Workaround is to click the X in the top right corner or outside of the dialog area to dismiss it. 

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper
2. Click the first Toggle Dialog button on the page (under the "Small" Example)
3. With the dialog now open, try pressing Esc. Nothing happens
![image](https://user-images.githubusercontent.com/15110225/101133124-0130d280-35bd-11eb-9ec3-49fff0a13362.png)

#### Platform and Version
Tested on Chrome 87 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
N/A

**Comment by Westbrook** [comment]
This is outlined in #710 and #866, but the functionality here exists, but is not yet being used in the documentation site for this element. Great to have it called out so clearly, however, so thanks!

**Comment by davidclark87** [comment]
@Westbrook sorry I'm not following - doesn't this behavior on the documentation site imply the component has an a11y issue, at least when configured with the options shown?
