### ISSUE TITLE
After opening sp-dialog, user should not be able to tab through content beneath the dialog

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1037]
### Expected Behaviour

After a modal dialog is opened, the dialog should contain its tab sequence; i.e. the user should only be able to tab to UI elements within the modal (see [WAI ARIA practices](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal)).

For reference see [React Spectrum Dialog](https://react-spectrum.adobe.com/react-spectrum/Dialog.html). Upon opening a dialog, focus goes to the dialog element, then is contained within the dialog.

I'm not clear what defines whether an sp-dialog is 'modal', it looks like perhaps those with "underlay" should be considered modal.

### Actual Behaviour

After opening a dialog on the SWC documentation site, focus unexpectedly goes to the `<docs-component>` element beneath it, and pressing tab cycles through the many elements beneath the dialog. Eventually focus is eventually give to the dialog.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper
2. Click the first Toggle Dialog button on the page
3. With the dialog now open, notice focus is now on the `<docs-component>` element. Judging by RS3, it should be on the `<sp-dialog>`. 
![image](https://user-images.githubusercontent.com/15110225/101134635-8d43f980-35bf-11eb-8a9b-f4e53f56370d.png)
4. Press tab. Notice focus is still on some element beneath the dialog. It should instead be on the X button in the modal.
![image](https://user-images.githubusercontent.com/15110225/101134694-a3ea5080-35bf-11eb-95fd-395e5bc2def1.png)

#### Platform and Version
Tested on Chrome 87 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
N/A

**Comment by davidclark87** [comment]
Looks like this may be a dupe of https://github.com/adobe/spectrum-web-components/issues/710 though that bug is closed so I'm not clear that this behavior should still be possible to encounter.

**Comment by Westbrook** [comment]
As outlined in that issue and elsewhere, this currently only documents that visual half of the dialog, and not the overlay as modal functionality that can be used with it.

**Comment by davidclark87** [comment]
OK, so I'm assuming this should stay open similar to https://github.com/adobe/spectrum-web-components/issues/1036#issuecomment-739033169 till the documentation is updated to reflect the intended, a11y-friendly API usage
