### ISSUE TITLE
Arrow key navigation through sp-radio-group sometimes gets stuck

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1038]
### Expected Behaviour

Should be able to press Left/Right keys to enable different Radio buttons

### Actual Behaviour

In some sequences, pressing Left/Right eventually appears to have no effect, i.e. they stop changing the selected radio button.

#### Steps to Reproduce

Here's one reliable way to repro, though I've hit this with a few different assortments of keystrokes.
1. Go to https://opensource.adobe.com/spectrum-web-components/components/radio
2. With the mouse, scroll to the first Radio group example. Note Option 1 is selected.
3. Click Option 4 to select it.
4. Press left key three times. As expected, Option 1 is now selected.
5. Press right key. Unexpectedly, Option 1 is still selected.
![image](https://user-images.githubusercontent.com/15110225/101137158-3b04d780-35c3-11eb-9aae-b84f2484b596.png)

#### Platform and Version
Tested on Chrome 87 on Mac.

#### Sample Code that illustrates the problem
See docs above

#### Logs taken while reproducing problem
Nothing logged to console

**Comment by Westbrook** [comment]
Oh, yeah, the cycle does sometimes get broken after it's been clicked. I'll track it down.
