### ISSUE TITLE
Feature request: Support automatic activation of sp-tab upon receiving focus

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1039]
### Expected Behaviour

The [WAI-ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-19) recommend automatically activating tabs when they receive focus (e.g. when you navigate to the tab by keyboard), _unless_ this causes UI latency.

FWIW automatic activation is the default behaviour in [React Spectrum](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#keyboard-activation) and perhaps should be here too.

### Actual Behaviour

Tabs do not activate upon receiving focus by default, nor is this configurable.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/tabs
2. Click on Tab 1 in the first example
3. Press the Right key to select the next tab. Note it does not activate.
![image](https://user-images.githubusercontent.com/15110225/101140944-7d7ce300-35c8-11eb-8df6-4e37f3d13c8f.png)

#### Platform and Version
Tested on Chrome 87 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
N/A

**Comment by davidclark87** [comment]
I named this 'Feature request' as it feels like an enhancement to me, but perhaps technically it is an a11y issue.

**Comment by Westbrook** [comment]
The link you've listed here seems attached to the Toolbar pattern, as opposed to the tab pattern:

Tabs are listed as having the options for [Manual Activation](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html) and [Automatic Activation](https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html) and I could definitely see value in surfacing this as an option in the future.

**Comment by davidclark87** [comment]
@Westbrook apologies for the incorrect link; fixed it to the [intended URL](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-19) now. 

To be clear here's the paragraph in that doc I was trying to refer to:
>It is recommended that tabs activate automatically when they receive focus as long as their associated tab panels are displayed without noticeable latency. This typically requires tab panel content to be preloaded. Otherwise, automatic activation slows focus movement, which significantly hampers users' ability to navigate efficiently across the tab list. For additional guidance, see § 6.4 Deciding When to Make Selection Automatically Follow Focus.

**Comment by Westbrook** [comment]
This makes sense to me. As per #676, we haven't yet bound tabs to tab content in any way, so we didn't have any control over `without noticeable latency`. Solving these together seems like a good idea.

**Comment by Westbrook** [comment]
Moving this conversation to #1280 where we're discussing the changes needed to ship a more broadly accessible `sp-tabs` patterns while also expanding to support automatic tab activation.
