### ISSUE TITLE
Overlays do not work correctly in Edge

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#104]
### Expected Behaviour

The `overlay-trigger` and `overlay-root` elements should allow you to open overlays in all mainstream browsers.

### Actual Behaviour

The overlay items are not hidden when they are not open, and they do not move to the correct positions when opened.

<img width="354" alt="Screen Shot 2019-08-07 at 3 28 32 PM" src="https://user-images.githubusercontent.com/154097/62592641-0b3eb480-b928-11e9-844b-180fb1bf9225.png">

**Comment by Westbrook** [comment]
@cuberoot can you confirm whether or not #320 closes this issue?

**Comment by Westbrook** [comment]
I'm no longer seeing this issue in Edge 18. 🍾  If there are extended recreation steps, please feel free to reopen.
