### ISSUE TITLE
Multiple items appear in focussed in <sp-menu> when using keyboard navigation

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1040]
### Expected Behaviour

Only one item should indicate focus at a time

### Actual Behaviour

Tabbing to the element gives focus to the first menu item, then pressing the down/up arrows indicates focus on both the new expected item _and_ the first item.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/menu/examples
2. Press tab to give focus to 'Deselect'
3. Press down and up keys any number of times

![menu-items](https://user-images.githubusercontent.com/15110225/101143374-a652a780-35cb-11eb-809d-78d9e2b9d0e4.gif)

#### Platform and Version
Chrome 87, Mac 

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
Nothing logged to console

**Comment by davidclark87** [comment]
I see what I believe is unexpected behaviour using the mouse too. LMK if I should file a separate bug. Clicking the first menu item leaves it "stuck" in the hover state. Clicking other menu items does not have this effect.
![menu-sticky-hover](https://user-images.githubusercontent.com/15110225/101143762-3395fc00-35cc-11eb-8f6c-13a5215b5890.gif)

**Comment by Westbrook** [comment]
Looks like something about the `focus-visible` polyfill is getting a little out of wack...I hate that thing. There's a couple of other "button refactor" processes that are ongoing that may also help to wash this out.
