### ISSUE TITLE
Full screen modal layout breaks on narrow viewport (e.g. Pixel 2)

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1041]
### Expected Behaviour

Probably a question for the Spectrum team, but perhaps the buttons could wrap.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/15110225/101145281-680ab780-35ce-11eb-8cf7-5cc674308268.png)

#### Steps to Reproduce
1. Using your phone, or desktop Chrome in device view (I used Pixel 2)
2. Go to https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper 
3. Click the Fullscreen mode section's Toggle Dialog button

#### Platform and Version
Pixel 5, and Chrome 87 Mac (Pixel 2 simulation)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
N/A

For reference, this is the equivalent [React Spectrum behaviour](https://react-spectrum.adobe.com/react-spectrum/DialogTrigger.html#fullscreen) - it shifts the buttons to the bottom of the modal for narrow viewports:

![image](https://user-images.githubusercontent.com/15110225/101145337-7fe23b80-35ce-11eb-8f5c-b4bbac7ce686.png)

**Comment by Westbrook** [comment]
I thought I saw this being updated in Spectrum CSS somewhere, but this is an issue there as well. I'll follow up with the right issue linkage and feedback to get this cleared up at that level.

**Comment by davidclark87** [comment]
FYI I just re-tested this and the styling is arguably a little cleaner now, though still not ideal IMO. The rightmost button is now clipped by the edge of the dialog rather than extending over the edge of it.

![image](https://user-images.githubusercontent.com/15110225/105409867-f1f5fa80-5be5-11eb-8ee9-49645d3adaea.png)

**Comment by Westbrook** [comment]
Yep, the Spectrum CSS for this still displays like: 
![image](https://user-images.githubusercontent.com/1156657/105412191-5f178900-5c02-11eb-9be0-9f0fc6d6c7b3.png)

@lazd do you foresee this being the sort of thing that normalizes and React Spectrum works to merge its fork of Spectrum CSS back into `main` over the next couple of months?

**Comment by lazd** [comment]
Hmm, I'm not sure. I don't know if RSP is moving things around with media queries or with JS... We already have the grid-based Dialog code from RSP's initial refactor in Spectrum CSS, but no media queries to move things around.

**Comment by Westbrook** [comment]
@lazd just checked and it looks like this is all CSS on the React Spectrum side. Should I create an issue for Spectrum CSS to follow up with getting that change in, or do you think it's something that will just happen when the forks are merged over the course of the spring?

![image](https://user-images.githubusercontent.com/1156657/108913119-8abdd280-75f7-11eb-9673-7e30f30b16ff.png)

![image](https://user-images.githubusercontent.com/1156657/108913153-98735800-75f7-11eb-8b0d-ecb0ffbcf8a2.png)

**Comment by lazd** [comment]
@Westbrook yeah that's the idea, I don't have a timeline but @GarthDB can probably speak to that.

**Comment by Westbrook** [comment]
Realize this actually comes from https://github.com/adobe/spectrum-css/issues/1306, so hopefully an easy fix!
