### ISSUE TITLE
Enter key should trigger pressed UI state in <sp-button> and <sp-action-button> 

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1042]
### Expected Behaviour

When one of these button types is in focus, pressing Enter key should make the button look pressed, just like pressing the Space key.

Screenshot of Space key interaction:
![button-press](https://user-images.githubusercontent.com/15110225/101203934-46d2b700-3620-11eb-9906-e0c930c5ad29.gif)

### Actual Behaviour

The Enter keypress causes no visual change in the button, though the expected event handler is invoked.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/action-button or https://opensource.adobe.com/spectrum-web-components/components/button
2. Tab to one of the buttons
3. Press Enter

#### Platform and Version
Tested on Chrome 87 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
Nothing logged

**Comment by Westbrook** [comment]
Interesting find. Wonder what the browser is doing there that doesn't cause the pseudo class to change. Will review close.

**Comment by Westbrook** [comment]
For reference, it seems that the native interaction with a button via the keyboard is for interactions with `Space` to equate to a click on `keyup`, a single event, while interactions with `Enter` should do so on `keypress`, a streaming event while the key stays depressed. Further a "button like"-anchor would only receive these commands on `keydown` of `Enter` to further complicate things.

https://stackblitz.com/edit/keyboard-to-click?file=index.js

This report likely stems from how the React Spectrum library completely synthesizes these semantics with its `onPress` interaction. Before following their lead blindly, we should review the benefits of this internally and with the accessibility team. For my money, departing from native accessibility should never be done lightly.

Further, we _should not_ move towards a similar abstraction of `click` as it seems the `onPress` consumes the keyboard interactions and prevents them from triggering `click` interactions making it easy for someone new to the library to create inaccessible interfaces without their knowledge.

**Comment by davidclark87** [comment]
>@Westbrook This report likely stems from how the React Spectrum library completely synthesizes these semantics with its onPress interaction. 

Well inferred :) I did not realize this contradicted the native button behavior when I wrote the bug, agree we'd want to check this is really desirable.

FYI, I ran the above code sample on Safari and Firefox, and both anchor and button show the streaming event behavior in those browsers.
