### ISSUE TITLE
Buttons in <sp-action-group> or <sp-button-group> should be arrow key navigable

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1043]
### Expected Behaviour

I couldn't find literature on this, but the equivalent React Spectrum behaviour is for buttons in such groups to be navigable by arrow key; perhaps that is the recommended practice? Filing this issue to raise the question.

In [RS3](https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html), tab navigates to the first item in the group; then arrow keys navigate to other items in the group. Any subsequent tab press navigates out of the group entirely.

![action-group](https://user-images.githubusercontent.com/15110225/101204831-b5644480-3621-11eb-9e2a-f57b3695e3a3.gif)

### Actual Behaviour

Buttons in the group can only be reached via tab, arrow keys have no effect.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/action-group or https://opensource.adobe.com/spectrum-web-components/components/button-group
2. Tab to the first example and try pressing arrow keys to navigate between buttons in the group

#### Platform and Version
Tested on Chrome 78 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
N/A

**Comment by Westbrook** [comment]
This is something we're adding in #998 for Action Group, and I guess it could be added for Button Group. There is some difference to the AOM of the selectable items that I makes me think a non-selecting group should NOT have arrow key navigation, but adding it generally isn't a big difference in work.

**Comment by Westbrook** [comment]
@davidclark87 Can you confirm the origin of you thought that this functionality was available in the `Button Group` patter for React Spectrum? I'm not currently seeing this in that pattern, and as this is now available in `sp-action-group`, I'd love to close this issue.

**Comment by davidclark87** [comment]
@Westbrook Good question... Now that I look at the React Spectrum [ButtonGroup](https://react-spectrum.adobe.com/react-spectrum/ButtonGroup.html), I don't actually recall playing with it before 😕 I suspect I somehow made a mistake when opening this issue, and that it should only have applied to action group in the first place. The new SWC action group behavior looks good so I think we should close this, thanks!
