### ISSUE TITLE
Pressing Up key on sp-dropdown should open the menu

### ISSUE THREAD

**Issue by davidclark87** [adobe/spectrum-web-components#1044]
### Expected Behaviour

Though I don't see it mentioned in [WAI-ARIA authoring practices](https://www.w3.org/TR/wai-aria-practices-1.2/#combobox), I would suggest pressing the Up arrow key on a closed sp-dropdown should open the menu. 

* This would provide symmetry with the Down key which has this effect. 
* [Native `<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Examples) has this behavior at least on Chrome (Mac), as does RS3's [Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html).

### Actual Behaviour

The Up key has no effect on the dropdown (it just scrolls the page upward).

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components/components/dropdown
2. Tab to the nearest sp-dropdown
3. Press Up key. The menu remains closed and the page scrolls up. For contrast now press Down key, notice the dropdown menu opens.

#### Platform and Version
Tested on Chrome 87 (Mac)

#### Sample Code that illustrates the problem
See docs

#### Logs taken while reproducing problem
Nothing logged

**Comment by Westbrook** [comment]
I don't see this experience in a native select element. I actually see `up` open the options, but not close them...straight forward to add, however.

**Comment by davidclark87** [comment]
@Westbrook isn't that what I am describing in the issue? 

With native `<select>`, pressing **Up** or **Down** opens the menu. By contrast, with `sp-dropdown`, only pressing **Down** opens the menu.

**Comment by Westbrook** [comment]
Oh, sorry I misread it as "up closes the open" dropdown. Thanks for making me read it again.

**Comment by Westbrook** [comment]
Released
