### ISSUE TITLE
setting the selected item in an sp-dropdown to disabled causes the page to become unresponsive

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1060]
### Expected Behaviour
It the selected menu item becomes disabled in a dropdown, either the selection is auto-cleared or remains selected even though the item is disabled.

### Actual Behaviour
The page hangs -- I'm guessing there's an infinite loop here.

#### Steps to Reproduce
Select an item in one of the examples on the dropdown documentation page. Using the web inspector, add a `disabled` attribute to the same menu item.

Note that this doesn't seem to reproduce with just `sp-menu`

**Comment by adixon-adobe** [comment]
Our test page makes this reproducible, but it doesn't seem like that likely a scenario. Still... hanging the page is bad!

**Comment by Westbrook** [comment]
Some of this effect is _hopefully_ mitigated by the changes in `next` that prevent a similar infinite loop:  https://github.com/adobe/spectrum-web-components/commit/98cc45b95e99a53e39576ecc43365f9c020d3409#diff-b9cace30081552e1a2c474c35ae00ff7a5c7abe3d7c6b4722179e06d56d4ceb0

We should align on getting `next` into `main` as fast as possible after the new year. There will bumpy releases for consumer between now and when Spectrum CSS goes stable 3.0, but at some point preventing that pain causes divergence issues and fix blockage...

**Comment by Westbrook** [comment]
@adixon-adobe this issue came up in your test suite, right? Can you confirm whether it persists in the new version? It should be good to go, and I'd love to close this issue, but I was never able to successfully recreate in order to do so.

**Comment by adixon-adobe** [comment]
It's fixed -- thanks!
