### ISSUE TITLE
Cannot use @spectrum-web-components/styles with Snowpack

### ISSUE THREAD

**Issue by alenaksu** [adobe/spectrum-web-components#1066]
### Expected Behaviour
Build Imported css files from `@spectrum-web-components/styles` using Snowpack

### Actual Behaviour
Snowpack build fails because it expects to find the file entry in the package.json `exports` field.

**Error**
`Package "@spectrum-web-components/styles" exists but package.json "exports" does not include entry for "./core-global.css".`

### Reproduce Scenario (including but not limited to)

1. Create a new snowpack project running `npx create-snowpack-app new-dir --template @snowpack/app-template-minimal` (replace `new-dir` as you prefer)
2. Install `@spectrum-web-components/styles`
3. Import spectrum css into index.css
4. Run `npm run build`

#### Platform and Version
Ubuntu 20.04.1 LTS
Node.js v15.5.0
Npm 7.3.0

Snowpack@2.18.5
@spectrum-web-components/styles@0.6.1

#### Sample Code that illustrates the problem

index.css
```css
@import '@spectrum-web-components/styles/core-global.css';
@import '@spectrum-web-components/styles/fonts.css';
@import '@spectrum-web-components/styles/theme-dark.css';
@import '@spectrum-web-components/styles/scale-medium.css';
```

**Comment by Westbrook** [comment]
Thanks for the report!

I had thought that the current `exports` listing:
```
    "exports": {
        "./": "./"
    },
```
Meant that ALL files were "exports", but it's still a pretty new part of the ecosystem and not all tools relate to it in the same way. It's possible that exports in other packages might have quietly been suffering this issue as well. We'll take a deeper look at this after the new year.

**Comment by Westbrook** [comment]
Reference for addressing this repo wide: https://nodejs.org/api/packages.html#packages_subpath_patterns

```
"exports": {
    "./features/*": "./src/features/*.js"
  },
```

Folder mapping is apparently deprecated...

**Comment by alenaksu** [comment]
Hi @Westbrook and happy new year! I checked on the snowpack repo and I found out it doesn't support wildcard right now, there's an opened PR actually that should do that, but it seems that the deprecated mapping will not be supported anyway.

**Comment by Westbrook** [comment]
@alenaksu you wouldn't happen to be able to share the PR you found for the wildcard support? Want to make sure what sort of time scale we're looking at there. Nothing like an overly strict tool not supporting the breadth of the tech by which they apply that strictness 😬

**Comment by alenaksu** [comment]
Sure, it is this one https://github.com/snowpackjs/snowpack/pull/2146. 
At this point maybe I could close this issue as it is not a strictly related problem with spectrum web components. What o you think?

**Comment by Westbrook** [comment]
It _does_ seems that the deprecated mapping will be added in that PR: https://github.com/snowpackjs/snowpack/pull/2146/files#diff-b4fa7b37bfd5fb84f984d88c0cbfe8b4482fa2618d6c57808f4a26ed7959272eR280, so feel free to close as you'd like. It seems that once this sort of listing works at all, you'll be good to go!

We will need to move to the wild card syntax at some point, however. This extended background would be useful in outlining that work, hopefully something we can take on officially, once that PR is landed.

**Comment by alenaksu** [comment]
If I'm not wrong, this statement should ignore `./`: https://github.com/snowpackjs/snowpack/pull/2146/files#diff-b4fa7b37bfd5fb84f984d88c0cbfe8b4482fa2618d6c57808f4a26ed7959272eR285

There is also a test case that suggests that https://github.com/snowpackjs/snowpack/pull/2146/files#diff-5c1457a2d41ec66f0cec4f600dad5b7d57cf3b11370ccc42c37fff33bb953253R167

Closing the issue, thanks for your time!
