### ISSUE TITLE
Size `xs` and `xxs` of sp-icon is not working

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1086]
### Expected Behaviour

Size of sp-icon should work as documented.

### Actual Behaviour

In the type file, only `'s' | 'm' | 'l' | 'xl'` is documented, at <https://opensource.adobe.com/spectrum-web-components/components/icon>, the range is  xxs to xxl.

#### Platform and Version
@spectrum-web-components/icon@0.7.0

#### Sample Code that illustrates the problem
```html
<sp-icon size="xxs" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="xs" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="s" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="m" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="l" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="xl" name="ui:Arrow100" dir="ltr"></sp-icon>
<sp-icon size="xxl" name="ui:Arrow100" dir="ltr"></sp-icon> 
```
#### Logs taken while reproducing problem
![图片](https://user-images.githubusercontent.com/13471233/104542191-040ff000-565e-11eb-9496-e093c353985b.png)

**Comment by Westbrook** [comment]
Thanks for this note, I see where we missed the correct listing of values there. To be clear Spectrum design has removed the `xxs`, `xs`, and `xxl` sizes of icons and we have done the same with this release. 
![image](https://user-images.githubusercontent.com/1156657/104597882-e33aa100-5643-11eb-9c6b-f5183cb53a14.png)
We'll make sure to have the copy on that page updated soon.
