### ISSUE TITLE
@spectrum-web-components/dialog should have deps of @spectrum-web-components/button-group

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1087]
### Expected Behaviour
![图片](https://user-images.githubusercontent.com/13471233/104551522-02502780-5672-11eb-83cb-c541f1ca33d1.png)

### Actual Behaviour
![图片](https://user-images.githubusercontent.com/13471233/104551383-c0bf7c80-5671-11eb-8073-9a0387f4693f.png)

#### Steps to Reproduce
import only `'@spectrum-web-components/dialog/sp-dialog.js'` and open a dialog.

#### Platform and Version
@spectrum-web-components/dialog/sp-dialog.js@0.4.0

**Comment by Westbrook** [comment]
Indeed it should. Thanks for pointing this out!
