### ISSUE TITLE
Close button of fullscreen sp-dialog at wrong position

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1088]
### Expected Behaviour
Close button at top right corner.
![图片](https://user-images.githubusercontent.com/13471233/104555237-7c83aa80-5678-11eb-8df7-52ec74f70134.png)

### Actual Behaviour
Close button at bottom right corner.
![图片](https://user-images.githubusercontent.com/13471233/104555187-64ac2680-5678-11eb-9728-fd7b18dee379.png)

#### Steps to Reproduce
```html
<sp-dialog mode="fullscreen" dir="ltr" dismissable="">
  <h2 slot="heading">Dialog title</h2>
  Content of the dialog
</sp-dialog>
```
#### Platform and Version
@spectrum-web-components/dialog/sp-dialog.js@0.4.0
#### Logs taken while reproducing problem
`.close-button` has `grid-area: closeButton`, but in `.grid`, its
```
grid-template-areas:
        ". . . . ."
        ". heading header buttonGroup ."
        ". divider divider divider ."
        ". content content content ."
        ". . . . .";
```
does not have such an area.

**Comment by Westbrook** [comment]
Nice catch! Thanks for letting us know.

I'll circle back with the design team on this, it may be that the ability to have a fullscreen dialog be `dismissable` is not intended and we need to update out logic, or possibly they've also missed testing this combination (as we have at the SWC level 🙈). Once I have more info, I'll post next steps herein.
