### ISSUE TITLE
Top Nav depends on URL for state / does not respond to changes to `selected`

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1097]
### Expected Behaviour

`<top-nav>` can be used with *or without* URL changes / href attributes in its navigation items.

(I expected this based on the [component description](https://opensource.adobe.com/spectrum-web-components/components/top-nav), [selected API](https://opensource.adobe.com/spectrum-web-components/components/top-nav/api), and the optional nature of [href](https://github.com/adobe/spectrum-web-components/blob/main/packages/top-nav/src/TopNavItem.ts#L56).)

This is important since not every type of app-level navigation calls for URL changes.

### Actual Behaviour

`<top-nav>` is unable to show selection changes without URL changes.

### Reproduce Scenario (including but not limited to)

https://webcomponents.dev/edit/2imTnzXud4nWm4OVQVYt

#### Steps to Reproduce

Try to navigate. Open the console and see that the component is re-rendering with the correct "mode," but changes to `selected` are not reflected in the UI.

#### Platform and Version

`├─ @spectrum-web-components/top-nav@0.1.0`

#### Sample Code that illustrates the problem

```js
    <sp-top-nav selected=${this.mode}>
        <sp-top-nav-item value="design" label="design" @click=${this.selectMode('design')}>
          Design
        </sp-top-nav-item>
        <sp-top-nav-item value="prototype" label="prototype" @click=${this.selectMode('prototype')}>
          Prototype
        </sp-top-nav-item>
      </sp-top-nav>
```

### Suggested fix

A quick hack to have `<top-nav>` check for value via `getAttribute` (rather than direct property access) made this work locally.

I'll bet that making the [item's value](https://github.com/adobe/spectrum-web-components/blob/main/packages/top-nav/src/TopNavItem.ts#L42) a reflected property and providing some [guards in case it's already set](https://github.com/adobe/spectrum-web-components/blob/main/packages/top-nav/src/TopNavItem.ts#L76) could sort this out with minimal changes.

I can ship a fix, but I wanted to open an issue first to discuss and to make sure that this isn't just user error.

**Comment by Westbrook** [comment]
There are specific accessibility differences here between the URL/tab stop realities of a “top nav” and the content/selection change realities of a “tabs” UI. It _may_ be that you mean to apply this via the `sp-tabs` UI here? I’ll need to revisit these with our accessibility team before we can commit to accepting specific changes here.

**Comment by hunterloftis** [comment]
Thanks - and maybe I should back up a little to mention what I'm trying to do. I hope to use [application modes](https://spectrum.adobe.com/page/application-frame/#Application-mode) without URL changes. The mode options themselves will be managed and limited dynamic state, and the user's most recent state will be pulled from storage when visiting the app (rather than pulled from the URL).

**Comment by hunterloftis** [comment]
Oh wow yeah I was overthinking it. `sp-tabs` + a few lines of CSS and I've got my controlled header component. Thanks!
