### ISSUE TITLE
Top Nav transitions into its initial selected state, rather than rendering the correct state immediately

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1098]
Sorry to drop a bunch of issues in! You can see I've been hooking the rough navigation states together this evening...

### Expected Behaviour

`<top-nav>` immediately renders its first selected state, then transitions to any new state upon user interaction.

### Actual Behaviour

`<top-nav>` immediately renders in an un-selected mode then transitions to whatever its first selection is.

### Reproduce Scenario (including but not limited to)

https://opensource.adobe.com/spectrum-web-components/storybook/iframe.html?id=top-nav--selected&viewMode=story#page-2

#### Steps to Reproduce

Refresh the page and watch the transition:

https://user-images.githubusercontent.com/364501/104674067-f899e480-56b0-11eb-983a-3b9f0be70d8a.mp4

### Possible fix

A first guess at how to fix this is overriding the [indicator's transition value](https://github.com/adobe/spectrum-web-components/blob/main/packages/tabs/src/spectrum-tabs.css#L99) on mount, allowing the component to render, and then restoring the transition value once the indicator has been rendered in its initial place.

Happy to PR for this as well!

**Comment by Westbrook** [comment]
This makes sense to me. Testing the animation with the first item seemed a little fun, but having the animation to a later item IS too much. We'd be happy to take a RP on this!

Please take into account this pattern applies to both the TopNav and the Tabs UIs. Let me know if there is any support we can lend to this effort.

**Comment by hunterloftis** [comment]
Thanks! Your suggestion of swapping TopNav with Tabs mitigated the issue for me (it's back to that 'kinda cool' short into transition), so it may take me using a wide menu again to get inspired to fix it :grin:
