### ISSUE TITLE
Horizontal tooltip arrows mis-render when nested in overlay triggers

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1099]
I isolated that tooltip issue. Maybe I'm using overlay incorrectly?

### Expected Behaviour

`<sp-tooltip placement="left">` renders its shape identically whether or not it's within `<overlay-trigger>`.

### Actual Behaviour

A `<sp-tooltip>` within `<overlay-trigger>` with a horizontal `placement` (left, right, left-end, etc) will render its arrow as if it's in a "bottom" placement.

### Reproduce Scenario (including but not limited to)

https://webcomponents.dev/edit/tf6L6yRntuzjJsCUE9Ek

#### Steps to Reproduce

Hover over the various action buttons:

https://user-images.githubusercontent.com/364501/104680204-57655b00-56bd-11eb-8db4-b8792c659b75.mp4

**Comment by hunterloftis** [comment]
Inspecting a little more, it looks like the `transform: rotate(-90deg)` is still applied to the "tip" class, but is being overridden by the dynamic style on the tip element itself:

```
style="position: absolute; top: 0px; transform: translate(0px, 8px); margin-left: 0px; margin-top: 0px;"
```

Changing the inline style to this fixes it:

```
style="position: absolute; top: 0px; transform: translate(0px, 8px) rotate(-90deg); margin-left: 0px; margin-top: 0px;"
```

**Comment by Westbrook** [comment]
Thanks for hunting the source here down.

This likely means this needs to be handled in https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/popper-arrow-rotate.ts

Happy to see if you're able to see a fix therein. Otherwise, we should be able to dive in on Tuesday.
