### ISSUE TITLE
Suggestion: include divider sizes in CSS variables

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1107]
I've defined my application's UI with Spectrum's [scale css vars](https://github.com/adobe/spectrum-css/tree/main/components/vars/css/scales). Swapping between "medium" and "large" works beautifully! It's a great feature of this design system.

The only exception to that is incorrect Divider width (hardcoded at 2px). I haven't been able to find a Spectrum CSS var that maps to the [Divider specification](https://spectrum.adobe.com/page/application-frame/#Dividers) of medium-scale: 2px, large-scale: 1px.

**Comment by Westbrook** [comment]
Checking with Spectrum CSS/DNA about shipping this in the scales packages. Will report back!

**Comment by Westbrook** [comment]
@hunterloftis for you current research did you end up simply binding the divers measurement to scale? In which case, should we start shipping then ourselves in the interim? A la, https://dividers--spectrum-web-components.netlify.app/storybook/?path=/story/styles--dividers

**Comment by hunterloftis** [comment]
Yep, I ended up binding it to whether or not the frame is being rendered on a mobile device (or with the `platform="mobile"` attribute override), which is also what drives the theme's `scale`.
