### ISSUE TITLE
ActionButton: Removing size attribute doesn't default to medium

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1108]
### Expected Behaviour
If I programmatically remove the size attribute from sp-action-button, it properly defaults to the medium size.

### Actual Behaviour
Doing so breaks the layout (there's no left/right padding). I caught this in a test page where I want to explicitly test the default behavior. If I change the size and then go back to the default it breaks.

#### Steps to Reproduce
You can just remove the size attribute in the debugger on the docs page.

**Comment by adixon-adobe** [comment]
Right now this just looks like a doc/test page issue for us.

It might make sense to add a `default` tab to the docs for t-shirt sizing as well, since you don't have to pass in the size parameter (and if you did, you'd probably hit this issue on the doc pages too).

**Comment by Westbrook** [comment]
@adixon-adobe the functionality in question here was added a while back. I'm not sure how I feel about a `default` tab in the docs...do you see that as a particularly useful addition? I _think_ we should suggest as close to final usage as possible, but can likely be moved on this with little effort.

**Comment by adixon-adobe** [comment]
As it looks like the core issue here is fixed I'm fine closing this.

That said, there's a pattern in play in SWC that sort of bothers me. There are a lot of places where we update attributes to **be** the default value. This isn't something that happens with built-in html elements -- they can properly handle their defaults without updating. I can see that following the steps in this bug lead to the `size="m"` attribute getting re-added to the element.

These sorts of updates can be problematic with data binding -- I don't think it's likely to be an issue with cases like this where the value isn't likely to change, but for attributes that fire an event on change it can lead to infinite update cycles.

I know I've brought this up before. My feeling is that this is an anti-pattern, but maybe where pragmatism says it's useful to do it anyways right now. If that's where we're at, I'll try to stop bringing it up up 😅

**Comment by Westbrook** [comment]
This comes from a trick in Spectrum CSS where by t-shirt sized elements don't work without their `--size*` class name, which parallels to the `size="*"` attribute. I'd love to manage this locally, but it's a pretty high traffic surface on their end, and I'm not sure of a good path to manage our relationship to those rules, sans something like DSS in the future.

Generally, I do like that you bring up questions about sprouting. We should absolutely stay as far away from this when _stateful_ as possible. I'm not sure we can keep it out of our library in that case 100% of the time, but ensuring we make a solid contract (via events, or what not) to clarify binding practices is definitely important.

Do you see this sort of visual delivery attributes as needing a more complex management system (while we continue to sprout the default)? I'd be happy to better understand the issue it might rise and look into what forms of clarity we can bring to this.

Do you know (of hand) of other attributes that you're particularly worried about acting this way? You had great feedback on things like the `sp-toast` element and similar help from the user space will help to continually push the library to higher levels of quality.

**Comment by adixon-adobe** [comment]
I think as long as the visual delivery attributes handle attribute changes we should be fine.

Boolean attributes are the most problematic (as if you're auto-adding them it means they can't be properly set/updated by clients). I believe that was the issue with `sp-toast`, and it's also why I wanted the `sp-menu` in elements like `sp-picker`, as they were adjusting values like `selectable` on content provided by the client.

**Comment by Westbrook** [comment]
This was fixed at some point along the way. See https://webcomponents.dev/edit/XhMmQNejm6LCukG5ZwJR/ for a demo.
