### ISSUE TITLE
sp-dialog-wrapper in not placed in the middle on firefox

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1112]
### Expected Behaviour
On Chrome:
![图片](https://user-images.githubusercontent.com/13471233/104829861-349c9780-58b3-11eb-8cde-377e9fcff4a8.png)

### Actual Behaviour
On Firefox:
![图片](https://user-images.githubusercontent.com/13471233/104829857-2484b800-58b3-11eb-969e-55892a8c9a4c.png)

#### Platform and Version
Firefox Developer Edition 85.0b9
#### Sample Code that illustrates the problem
https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper

**Comment by Westbrook** [comment]
Nice catch! Looks like we are being a little overzealous with out PostCSS processing and adding some out-of-date sizing properties to Firefox. We'll get a fix for this out in this weeks release.

Thanks.
