### ISSUE TITLE
Correct slider label usage isn't documented

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#1113]
### Expected Behaviour
Documentation (README) and on site documents adding a label to your `sp-slider` like so:
`<sp-slider label="Slider Label"...`

### Actual Behaviour
Labels don't show up when using the `label` attribute

#### Platform and Version
Spectrum 0.16.0 (tested on FF and Chrome on Mac, but I think its just a doc issue)

Looks like you've switched over to slots for the label, and using an attribute is deprecated. No biggie, but it got me stuck for a bit thinking it was me or a bug.

**Comment by Westbrook** [comment]
Without any more information, I'd bet you have a space character, or new line, or any text node inside of your `sp-slider` node. We've added the slotted label as a fallback (as it's easier to style when `sp-slider:not(:defined)`, but it should not replace the `label` attribute. Can you confirm that you are delivering this element as:
```
<sp-slider label="Slider Label"></sp-slider>
```
and not as:
```
<sp-slider label="Slider Label"> </sp-slider>
```
or as:
```
<sp-slider label="Slider Label">
</sp-slider>
```
If you're using the first, there may be some other regression we've not encountered. In that case, can you supply any more usage information?

If it's the usage of a text node that's causing this...
This is a general web components reality, however as we move to supporting better load time style delivery of our elements, we'll likely be doing this more and more. Can you think of a quality place in the documentation that you'd expect information about usage "gotchas" like this one?

**Comment by bengfarrell** [comment]
thanks! You're correct I usually put the end tag on a different line if my attributes are getting long, and that caused the issue:

` <sp-slider label="Choose pattern size"
            @input=${(e) => scope.chooseDistance(e)}
            min="5" max="20" step="1"
            value=${scope.shapeDistance}>
    </sp-slider>`

In terms of documenting gotchas, I usually just crack open the README for each component from my npm modules as a second resort when I don't have an answer from the main open source site. If there was a gotchas section in each README, I'm sure I would've seen it right off.

**Comment by Westbrook** [comment]
You can still do line breaks, in fact I just clean this up with HTML minification, but the most important thing is the the angle braces touch `><`. A gotchas section for components with this pattern makes sense, I’ll use this issue to track adding that for now.

**Comment by bengfarrell** [comment]
Yup, I think this has bitten me in the past too - i think i'd more categorize this as my fault and I should just make sure the angle braces touch from now on as a code style I enforce on myself. Where it's bitten me in the past, I don't think it was web components related at all, and was easier to debug because it was just inserting an extra char and mucking with my layout. In this case the underlying cause is a bit hidden and it just ends up looking like SWC is broken.
