### ISSUE TITLE
Textfield: Maxlength attribute isn't working as expected

### ISSUE THREAD

**Issue by chad-schroeder** [adobe/spectrum-web-components#1118]
### Expected Behaviour

The `maxlength` attribute should prevent the user from typing indefinitely once the character count is reached.

### Actual Behaviour

The `maxlength` attribute has no effect and the user can type indefinitely.

#### Steps to Reproduce

This should limit entry to 2 characters:

`<sp-textfield maxlength="2" id="name-0" placeholder="Enter your name"></sp-textfield>`

**Comment by OpportunityLiu** [comment]
The hard limit of `maxlength` will prevent users to input with IME.
