### ISSUE TITLE
Card does not trigger change event when "selected" property changes

### ISSUE THREAD

**Issue by angelcabo** [adobe/spectrum-web-components#1126]
### Expected Behaviour
Per the docs, the `change` event:

> Announces a change in the `selected` property of a card

When I enable `toggles` on the card and then I click to mark the card as selected, I would expect a change event for the card to be triggered.

### Actual Behaviour

No change event is triggered when the select property on the card changes. However, if I select the card using the `space` key instead of using the mouse to click the checkbox toggle, I get the change event on select change.

For some reason, clicking toggles to select the card and using the keyboard each use different internal methods to handle the selection change: https://github.com/adobe/spectrum-web-components/commit/84cf1a9758b1e357f18efac5763d17d6a4db0578#diff-525c78aaeabede662df68e6dfffddfe8346f5f32732d19bf3a7e8f05433a2a94R108.

#### Steps to Reproduce

1. Create a basic `<sp-card>` element with `toggles` and a `@change` event handler.
2. Click to select the card in the UI.
3. Observe no change event triggered.

#### Platform and Version

macOS 10.14.6
Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)
@spectrum-web-components/bundle 0.15.8

#### Sample Code that illustrates the problem

```javascript
<sp-card heading="Card Heading" subheading="JPG Photo" toggles @change="${this.handleCardChange}">
    <img
        slot="cover-photo"
        src="https://picsum.photos/200/300"
        alt="Demo Image"
    />
    <div slot="footer">Footer</div>
</sp-card>
```

**Comment by Westbrook** [comment]
Thanks for the issues on this!

I can recreate the issue here: https://webcomponents.dev/edit/cPZ0Vz21NiYTlEpRsA59

We'll get on cleaning up this wiring shortly.
