### ISSUE TITLE
menu-item keyboard focus shouldn't show

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1136]
### Expected Behaviour
Hovering over a menu item should just make that item hovered, and there shouldn't be styling on menu open.

### Actual Behaviour
When you open a dropdown or action menu, the first item has hover styling (maybe for keyboard focus? But it doesn't get the blue bar). If you hover over the second item, both show the same hover styling.

**Comment by Westbrook** [comment]
Can you share screenshot on this? I've got `focus` styling on "Deselect" and `hover` styling on "Feather" in the documentation pages for `sp-action-menu`.

![image](https://user-images.githubusercontent.com/1156657/105557498-66aa6100-5cda-11eb-9ca3-30270a326a96.png)

Would _could_ talk about not throwing visible focus into the list when opening with a pointing device, but I feel like there's a tricky needle of accessibility that we'd be threading... I've a meeting with James next week, and can bring it up with the accessibility team there.

**Comment by adixon-adobe** [comment]
I wasn't testing with the latest, and it used to be that the blue bar was missing when you opened the menu, so at least now they're visually distinct.

Why don't you bring it up with the accessibility team. I think your suggestion of not throwing visible focus when opened with a pointing device makes sense as some nice polish (assuming that it still actually has keyboard focus and would become visible on up/down arrow).

**Comment by Westbrook** [comment]
Making some progress on this: https://westbrook-menu--spectrum-web-components.netlify.app/components/action-menu 

While I work out some expected test results, would love to hear your thoughts.
