### ISSUE TITLE
sp-action-menu popover should not resize when selecting longest item

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-web-components#1139]
### Expected Behaviour

The popover should remain the same size regardless of selection.

### Actual Behaviour

Notice when the "Select and mask..." is selected, the popover menu becomes wider. When the "Select and mask..." item is deselected, the popover menu becomes less wide.

https://user-images.githubusercontent.com/77195/105788624-b9338980-5f35-11eb-9304-338e6bde5705.mov

**Comment by Westbrook** [comment]
fixed by #1172
