### ISSUE TITLE
sp-sidenav should issue a 'change' event

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1156]
### Expected Behaviour

I would expect any component that has a `value` attribute to issue a `change` event when it changes. I am working with an internal framework that makes that assumption.

### Actual Behaviour

I cannot see any event from the side-nav when the selection value changes.

**Comment by Westbrook** [comment]
For reference, the `sp-sidenav-item` elements are dispatching a `sidenav-select` event that roughly parallels this situation.

I agree that it makes sense to have a `change` event in this context. In doing so, should we contain the `sidenav-select` event with `event.stopPropagation()`, etc. and inform consumers to _only_ listen for the `change` event from the outside?

**Comment by cuberoot** [comment]
A good question. My gut says yes? You could still listen directly to that event on the individual items if you want. It's one of those things where people can log another issue if there's some scenario we haven't thought of.
