### ISSUE TITLE
Spectrum controls should not prevent touch scroll

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1161]
### Expected Behaviour
Starting a touch/scroll from a spectrum control shouldn't prevent parent element scrolling unless it has internal content that scrolls.

### Actual Behaviour
Controls like button, dropdown, action button/menu all prevent touch scrolling

### Steps to Reproduce
Go to the doc pages and try to begin a scroll on a touchscreen device (or in Chrome's device debugging mode). 

### Related issue

https://github.com/adobe/spectrum-css/issues/1128

### Additional info

I'm not seeing this issue for checkbox, switch or radio button, so it isn't all controls. I also don't think I'd expect this to work with overlays (I could also see that being real challenging with the re-parenting involved).

**Comment by Westbrook** [comment]
This originates from `touch-action: none;` listings like https://unpkg.com/browse/@spectrum-css/button@3.0.0/dist/index-vars.css#L42 in Spectrum CSS for the various button elements, picker element, and slider element. I can recreate this situation in https://opensource.adobe.com/spectrum-css/button-cta.html let's review with the team why they chose to use this property.

**Comment by adixon-adobe** [comment]
Sounds good. I also compared to the native `<select>` and `<button>` elements, and those do allow touch scrolling.

**Comment by Westbrook** [comment]
Upstream is good here and our docs are looking like it, too. Feel free to reopen if you’re seeing something more here.
