### ISSUE TITLE
Required attributes?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1170]
When `sp-progress-bar` applied `role="progress"` to itself the implication is that `label` (which applies a visible label to the shadow DOM) or `aria-label/lledby` is required to ensure the accessibility of the element. We'd like to ensure that here and in other locations where element sprout roles onto themselves these sorts of requirements are maintained at more than just the documentation level.

Can TS or lit-plugin or something else support the inclusion of required attributes?

If not, can we do so with a SWC specific linting plugin?

If not, should we add runtime warnings (possibly a development build 🙈) to clarify the absence of these attribute?

**Comment by hunterloftis** [comment]
For 1.0: at least one instance of the end-to-end workflow of a dev build, so we can add component support for it over time.
