### ISSUE TITLE
sp-menu-group section header has too little bottom margin

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-web-components#1171]
### Expected Behaviour

[spectrum-css](https://opensource.adobe.com/spectrum-css/menu.html) looks like:

<img width="180" alt="Screen Shot 2021-02-04 at 12 29 53 PM" src="https://user-images.githubusercontent.com/77195/106951539-bd556900-66e4-11eb-809b-14ab92c190fa.png">

### Actual Behaviour

SWC looks like:

<img width="180" alt="Screen Shot 2021-02-04 at 12 28 57 PM" src="https://user-images.githubusercontent.com/77195/106951402-96973280-66e4-11eb-9ad7-5340a6253e5b.png">

**Comment by Westbrook** [comment]
Thanks for the issue. Looks like this comes from our nesting the group children into a `div` as opposed to another `sp-menu`. Likely more complicated that just swapping that in, but, if you were interested in trying that out, I'd be very happy to accept a PR with that in it.

If not, I do know that this pattern is next on the Spectrum CSS list to receive t-shirt sizing. That being the case more complex refactors will likely be held for when that is available; likely the next 2-4 weeks.
