### ISSUE TITLE
Getting startet 404

### ISSUE THREAD

**Issue by Fabioni** [adobe/spectrum-web-components#1190]
## Problem

When I am browing to the side https://opensource.adobe.com/spectrum-web-components/getting-started I get the following errors in my console:
<img width="950" alt="Bildschirmfoto 2021-02-14 um 15 55 36" src="https://user-images.githubusercontent.com/45362676/107880109-15f2e600-6edd-11eb-9678-9d58a37c25d3.png">

The same thing happends when I want to try out the WebComponents in my own project with:
```
<script
    src="https://jspm.dev/@spectrum-web-components/bundle/elements.js"
    type="module"
></script>
```

The example click-me button also render just as this, no component is working at all:

<img width="731" alt="Bildschirmfoto 2021-02-14 um 15 58 00" src="https://user-images.githubusercontent.com/45362676/107880172-6bc78e00-6edd-11eb-9b46-53292d8a76f5.png">

## What I tried:
- deactivating adblocker

I appreciate your help to get the "getting started" working for me. Its hard to dive into the topic if even the getting started code does not seem to work.

**Comment by Westbrook** [comment]
Thanks for reporting this, I'm not sure why this stopped work, but will dive deeper on this during the week. It's possible JSPM has decided to alter its use of the `exports` entry in `package.json` to a newer version. The specification there has been pretty fluid and while an important tool for auto-processing CDNs like this and unpkg or Skypack, it's been trouble to keep up with as a library vendor. My apologies for this happening!

In the mean time, remember that this quick start approach does not preclude using NPM packages directly, as would be important to do when you were ready to tune your application for production. Each of our packages has installation instructions on their individual pages of the documentation. You can also get started by forking this project: https://webcomponents.dev/edit/JWGqd9YV0d63ZVKERLuj/src/index.ts or the starter for any one of our element starters here: https://webcomponents.dev/org/adobe

I'll try to get back to you with more information later in the week.

**Comment by Westbrook** [comment]
There are deeper issues at play here that we've yet to find.
