### ISSUE TITLE
Review and refine contributor documentation

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#1199]
To build a good contribution model, we should make sure our docs surrounding our process for creating a component are clear. This card is the masterpost for all related contributor docs issues. I will link related issues below, as well as add comments in the meantime so we can keep track of what needs to be done.

**Comment by najikahalsema** [comment]
@castastrophe via #1763 said:
> Description of issue
> A call-to-action near the components documentation for what to do if you don't see what you're looking for.
> 
> Q1: Is it in Spectrum CSS yet?
> Y Find the issue for the missing component and add a note of your needs and what your timeline is.
> N Q2: Is it part of the Spectrum project?
> Y Link to who to contact with the Spectrum CSS team
> N Link to who to contact with the Spectrum design team

**Comment by hunterloftis** [comment]
A subset of some potential "Getting Started" content applies to contributors:

**Getting Started with Spectrum Web Components**

I want to:
- use Spectrum Web Components in my Web-Component-centric app
- use Spectrum Web Components in my React app
- build a new component that's part of the Spectrum design system
- build a new app-specific component that is not part of the Spectrum design system

**Comment by Westbrook** [comment]
@Rajdeepc this seems related to our convo this week.

**Comment by Rajdeepc** [comment]
Yes let me assign this to myself. Thanks
