### ISSUE TITLE
[Tabs] Support overflow pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1207]
Ensure responsive delivery of `sp-tab` elements by supporting the "with overflow" pattern of delivery outlines here: https://opensource.adobe.com/spectrum-css/tabs.html#basictabswithoverflow

**Comment by Westbrook** [comment]
Spectrum also support a "scrolling" pattern than delivers some use controls for moving to see all of the available Tabs:
[
<img width="345" alt="image" src="https://user-images.githubusercontent.com/1156657/201188961-2050b95a-61cf-4415-bec0-b60e1d588164.png">
](https://spectrum.adobe.com/page/tabs/#Too-many-tabs)

Delivering this interface as a decorator for the `<sp-tabs>` element should make it relatively easy for users to opt-in to leverage this capability. This could take the shape of:

```
<sp-tabs-overflow>
    <sp-tabs>
        <sp-tab>1<sp-tab>
        <sp-tab>2<sp-tab>
        <sp-tab>...<sp-tab>
        <sp-tab>N<sp-tab>
        <sp-tab-panel>1<sp-tab-panel>
        <sp-tab-panel>2<sp-tab-panel>
        <sp-tab-panel>...<sp-tab-panel>
        <sp-tab-panel>N<sp-tab-panel>
    </sp-tabs>
</sp-tabs-overflow>
```

Things that we should take into account for an initial release:
- `<sp-tabs>` usage with and without `<sp-tab-panel>` elements
- Resize observing for overflow, depending on how this is done, there may be benefit to sharing this work between this and an updated version of https://github.com/adobe/spectrum-web-components/blob/main/packages/tabs/src/Tabs.ts#L200
- these styles are not currently provided by Spectrum CSS, so maybe we could get them added to Core Tokens for the future @pfulton?

Things that could be included, but are acceptable for future scope:
- major visual differentiation between Express and Classic delivery (likely expressed in the form of fully opaque buttons vs ones that are placed on a gradient of transparency)
- managing overflow of `<sp-tabs direction="vertical">` elements
- properties to customize scroll distance
- access to managing scroll behavior beyond directly addressing `sp-tabs::part(tablist)`, though maybe that's enough

**Comment by pfulton** [comment]
Pinging @GarthDB for visibility on the tokens side of things here.
