### ISSUE TITLE
slider in rtl behaves strangely

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#1212]
### Expected Behaviour
slider should move to the left when dragging to the left

### Actual Behaviour
when starting the move to the left the slider jumps to the right

### Reproduce Scenario (including but not limited to)
https://5ff71f580d1b2204cd8c82d7--spectrum-web-components.netlify.app/components/theme/#embedding-themes

#### Steps to Reproduce
https://5ff71f580d1b2204cd8c82d7--spectrum-web-components.netlify.app/components/theme/#embedding-themes
1. go to the "light" slider which is in rtl
2. click on the handle and while clicking drag slightly left
3. the handle jumps right

#### Platform and Version
MacOS 11.2.1 chrome Version 88.0.4324.182 (Official Build) (x86_64)

#### Logs taken while reproducing problem

https://user-images.githubusercontent.com/1724479/108933631-57cc0c80-7600-11eb-9bbb-058f77f8e1df.mov

**Comment by Westbrook** [comment]
Very interesting, it looks like the position calculation is incorrect when it's in the doubly scoped or embedded theme. Thanks for letting us know!

Can you confirm that when you visit https://opensource.adobe.com/spectrum-web-components/components/slider and the content direction for the entire page is switched to RTL (something that apparently doesn't work in that preview site you've been reviewing) that you also experience a more anticipated interaction with the slider?

**Comment by jnurthen** [comment]
This seems to work fine at https://opensource.adobe.com/spectrum-web-components/components/slider
