### ISSUE TITLE
Clarify start of work via API/code review guidelines

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#1216]
Identify and define guidelines for contributors to SWC to follow before beginning their contribution. Key things to consider:

* What have our past contributors done? Did anyone (contributors or SWC team) find it helpful? What was missing?
* How will a contributor notify SWC that they want to work on a project? Which methods of communication are most useful (high visibility, easy to access and find, etc)? 
* How can we help our contributors prioritise work? 
* How can we verify API guidelines as they relate to React Spectrum or Spectrum CSS? 
* API surface review tasks: can we make this clearer or easier to leverage? 
* How extensive do we want this process to be?

**Comment by Westbrook** [comment]
Bump.
