### ISSUE TITLE
tabIndex errors in action-group with selects="single"

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1230]
### Expected Behaviour

This is a messy real-world use-case that I haven't yet condensed into a minimal reproduction. I'd appreciate any ideas on what might be causing it, but I know it may be hard to diagnose based on the information I can share. At the moment it can be reproduced here:

https://dg-spectrum-parcel.vercel.app/

I'm using `sp-action-group` with `selects="single"` to manage a dynamic sidebar. There are several things that might be interfering with the selection behavior:

- The `sp-action-button`s rendered by the sidebar depend on the top-level navigation mode of the application.
- The action buttons are wrapped by `overlay-trigger`s to provide tooltips
- I'm following a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) pattern to manage the selection state, using [preventDefault on the change event](https://opensource.adobe.com/spectrum-web-components/components/action-group#selects).

### Actual Behaviour

```
Uncaught (in promise) TypeError: Cannot set property 'tabIndex' of undefined
    at HTMLElement.manageSelects (ActionGroup.js:212)
```

### Reproduce Scenario (including but not limited to)

https://dg-spectrum-parcel.vercel.app/

#### Steps to Reproduce

Navigate on the left and right sidebars while toggling between "Play" and "DM" modes.

#### Platform and Version

```
"@spectrum-web-components/accordion": "^0.3.1",
    "@spectrum-web-components/action-group": "^0.3.1",
    "@spectrum-web-components/action-menu": "^0.8.1",
    "@spectrum-web-components/actionbar": "^0.6.1",
    "@spectrum-web-components/avatar": "^0.6.0",
    "@spectrum-web-components/button": "^0.12.0",
    "@spectrum-web-components/card": "^0.7.1",
    "@spectrum-web-components/dialog": "^0.5.1",
    "@spectrum-web-components/dropdown": "^0.10.1",
    "@spectrum-web-components/field-label": "^0.2.1",
    "@spectrum-web-components/icon": "^0.8.1",
    "@spectrum-web-components/icons": "^0.6.1",
    "@spectrum-web-components/icons-workflow": "^0.5.1",
    "@spectrum-web-components/menu": "^0.6.1",
    "@spectrum-web-components/overlay": "^0.9.0",
    "@spectrum-web-components/popover": "^0.8.0",
    "@spectrum-web-components/slider": "^0.8.1",
    "@spectrum-web-components/switch": "^0.6.1",
    "@spectrum-web-components/tabs": "^0.4.1",
    "@spectrum-web-components/textfield": "^0.7.1",
    "@spectrum-web-components/theme": "^0.7.0",
    "@spectrum-web-components/toast": "^0.7.1",
    "@spectrum-web-components/tooltip": "^0.7.1",
    "@spectrum-web-components/top-nav": "^0.1.0",
```

#### Sample Code that illustrates the problem

```ts
return html`
            <sp-action-group vertical selects="single" @change=${this.onToolChange}>
                <dg-action-button value="move" label="Move" .icon=${HandIcon} placement="right" ?selected=${'move' === tool}></dg-action-button>
                <dg-action-button value="scribble" label="Scribble" .icon=${ScribbleIcon} placement="right" ?selected=${'scribble' === tool}></dg-action-button>
                <dg-action-button value="ping" label="Ping" .icon=${EventsIcon} placement="right" ?selected=${'ping' === tool}></dg-action-button>
            </sp-action-group>
            ${this.renderPopover(tool)}
        `

// ...

onToolChange(e:Event) {
        e.preventDefault()
        const selected = e.target.selected[0]
        if (['move', 'scribble', 'ping'].includes(selected)) this.toolPlay = selected
        this.toolDM = selected
    }
```

#### Logs taken while reproducing problem

```
ActionGroup.js:212 Uncaught (in promise) TypeError: Cannot set property 'tabIndex' of undefined
    at HTMLElement.manageSelects (ActionGroup.js:212)
```

**Comment by Westbrook** [comment]
Thanks for this report. While your usage is probably fairy common, I can be fairly certain that this comes in someway from the code currently assuming that assigned nodes, which are required to be direct children, would be those that are the “buttons” in this example. That is to say, we’ve not prepared for `overlay-trigger` elements placing themselves between the `sp-action-group` and the `so-action-button`s it should be managing. I can take a look at that this week and see if we can’t have a fix for this soon.

**Comment by hunterloftis** [comment]
Please let me know if I can help. I've added several complicating factors to the `selects="single"` setup, so I wasn't too surprised that it threw.

**Comment by Westbrook** [comment]
If you get there first, I’d start with this line: https://github.com/adobe/spectrum-web-components/blob/2e702e45516cb736ea930fdf927e457c10439e8e/packages/action-group/src/ActionGroup.ts#L36 Moving to a mutation observer that tracks children and filters for the same `sp-action-button` _might_ be all that’s needed, but I’d have to dig in to be sure.

**Comment by hunterloftis** [comment]
I ended up needing to provide more complex logic anyway for the sidebar & panel (than just single-select), so for now I've sidestepped this :)
