### ISSUE TITLE
multiple overlay problem

### ISSUE THREAD

**Issue by atoy40** [adobe/spectrum-web-components#1234]
### Actual Behaviour

There is a bug when a second overlay (in this example a picker menu) is opened into a dialog overlay. The whole document grows in height and the dialog "window" is moved to the bottom of the document.

#### Sample Code that illustrates the problem

Just open the dialog, and then open the picker.
https://codesandbox.io/s/spectrum-wc-picker-in-dialog-063wt?file=/src/index.js

Anthony.

**Comment by atoy40** [comment]
@Westbrook  I realize with your workarround there is another important problem : the picker doesn't seems to work in this case, it doesn't select the entry you pick.

**Comment by Westbrook** [comment]
Ah, indeed. I see why that is, but not quite how that is. Will investigate further.

Thanks for helping to dig into this!
