### ISSUE TITLE
sp-menu should be deprecated from popover menu classes

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1235]
### Expected Behaviour
Our APIs have minimal DOM structure, and limits invalid usage when possible.

### Actual Behaviour
As illustrated in #1189, the underlying `sp-menu` can lead to invalid DOM states, and is ultimately redundant with the `sp-picker`, `sp-split-button` & `sp-action-menu` elements when used in that context.

### Proposal

Deprecate the `sp-menu` element in these contexts, and use `console.warn` to indicate this usage pattern will be removed in a future version.

**Comment by Westbrook** [comment]
@adixon-adobe was there more work that you wanted to do to this issue post #1237?

**Comment by adixon-adobe** [comment]
No - the next round will be tackling #1189 so I'll close this!
