### ISSUE TITLE
[Overlay] Clarify style/theme resolution/throwing in the documentation

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1267]
Things projecting into an `active-overlay` element expect to benefit from either a global application of Spectrum CSS custom properties or have lived within an `sp-theme` scope in order to have their theme context resolve appropriately while the overlay is open, clarify this in the docs.

Styles applied to content thrown into an overlay will not be associated with that content when an overlay is open. Clarify the requirements of an encapsulated component, inline styles, or a `<style>` element contained in the thrown content.

cc: @aashritandon92

**Comment by Westbrook** [comment]
@aashritandon92 I've added the proposed `Styling` section to https://westbrook-overlay-styles--spectrum-web-components.netlify.app/components/overlay-trigger does it seem clearly outline the options we discussed oh so long ago now?

**Comment by aashritandon92** [comment]
> @aashritandon92 I've added the proposed `Styling` section to https://westbrook-overlay-styles--spectrum-web-components.netlify.app/components/overlay-trigger does it seem clearly outline the options we discussed oh so long ago now?

It looks good to me. Thanks for adding that!
