### ISSUE TITLE
[Button] a11y review

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1272]
### Feedback

❌ Space is scrolling the page, not activating the button - Chrome, Safari / MacOS 11.2.1
？- focus gets moved to the page when clicking the “Handling Events” button. Could be the sp-alert component at fault.

### Path forward

1. Prevent default...
2. This is specifically when the VO is on? Needs in depth review.

cc @jnurthen

**Comment by jnurthen** [comment]
This is with and without VO.

**Comment by Westbrook** [comment]
I can't seem to recreate the second issue here. Can you reconfirm on the newer build URL or we can set some time for you to show me what I might be doing wrong in trying to recreate?

**Comment by jnurthen** [comment]
I was wrong above - this was just with VO and it doesn't always happen

In the attached video the first 2 times it didn't happen but the 3rd attempt did

https://user-images.githubusercontent.com/1724479/111229622-72f8bf00-85a3-11eb-8293-fed7a06d1842.mov
