### ISSUE TITLE
Documentation example issues with `sp-dropzone`

### ISSUE THREAD

**Issue by Alos** [adobe/spectrum-web-components#1292]
* In the Dropzone example (in the README) the attribute: `viewBox` is duplicated.
* Missing slot attribute. Parent element <sp-dropzone> only allows named slots as children. Should the `sp-illustrated-message` have a slot attribute with: 'default'?

**Comment by Westbrook** [comment]
Thanks for checking in on this @Alos. This definitely seems like a documentation only issue. For reference, while the slot in the `sp-dropzone` is listed as `default`, it should be listed as "default" or the slot into which all content with out a specific `slot` value will be placed into. Look for this update, soon!
