### ISSUE TITLE
Feature request: sp-dropzone does not show dropped file.

### ISSUE THREAD

**Issue by Alos** [adobe/spectrum-web-components#1293]
It would be cool if the sp-dropzone would show the name if file dropped.

**Comment by Westbrook** [comment]
Based on the current design assets available to us internally, I don't think we'll see this added. The idea that the `sp-dropzone` takes content into a default slot means there are lots of options for this UX in a real application.

Check out just one option here: https://webcomponents.dev/edit/Ttzj7MSxiWF5Q6PWZj5A/src/index.ts In this (very simplified) case the images dropped into the `sp-dropzone` element are then displayed as `sp-card` children with a preview, their file name, and image size. Notice how the entire drop event is available in the `detail` of `sp-dropzone-drop`. In this way light DOM can be customized with the information from the `dataTransfer` listing to customize the usage of the `sp-dropzone` in many ways.

**Comment by Westbrook** [comment]
Closing as works as expected.
