### ISSUE TITLE
Improve sp-slider-color interface

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#13]
The proposed `sp-slider-color` implementation in #10  is initially not going to implement a proper interface for color sliders.

We should implement a more natural interface, allowing min and max color values, selection of which channels are mutated by the slider, and possibly better control over the gradient used.

**Comment by Westbrook** [comment]
@benjamind seeing as Spectrum CSS has deprecated this variant of the slider: https://opensource.adobe.com/spectrum-css/components/slider/#Color do you still want to track this work? I'd almost say we should just pull `color` support from the package all together, but will leave that decision up to you.

**Comment by benjamind** [comment]
Given that the gradient design is still present here - https://spectrum.adobe.com/page/slider/#Gradient I think this will be coming back, either by Spectrum CSS or as something we take on styling ourselves? After all we know of at least two projects at Adobe that need these color and gradient style sliders...

**Comment by Westbrook** [comment]
[`gradient`](https://spectrum.adobe.com/page/slider/#Gradient) and [`color`](https://spectrum.adobe.com/page/color-slider/) being different (but easily confusable) concepts/implementations, could we benefit from a little more clarity around this (or an alternate) issue to benefit whoever ends up taking on this work?

Reviewing to make sure issues are actionable and related to ongoing goals. Issues don't cost money, so keeping it around either way won't hurt.

**Comment by benjamind** [comment]
Agreed, feel free to rewrite to make this clearer. I think maybe just something detailing that we want to be in conformance with the Spectrum design for sliders, not just the Spectrum-CSS implementation would be good?

**Comment by Westbrook** [comment]
Now that there is a verified [Color Slider](https://opensource.adobe.com/spectrum-css/colorslider.html) component, let's look at adding that component when a need for this sort of interface becomes a priority rather than attempting to support the deprecated `color` variant of `sp-slider`.
