### ISSUE TITLE
Dialog / Dialog Wrapper examples only allow the dialog to be shown once

### ISSUE THREAD

**Issue by dwabyick** [adobe/spectrum-web-components#1313]
I'm not sure if this is exactly a bug, but it does _seem_ like a bug to a new user. When I goto these components, I can only pop up the dialog once.

https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper

Likewise, the demo pages show similar behavior, and since we toggle the `this.open` property, it seems like it should be reopenable. 
https://webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/RSDikStPmUPSioVpCsYb/src/index.ts?branch=master

**Comment by Westbrook** [comment]
@dwabyick thanks for submitting this issue! Pretty important little bug underneath there, but the fix is looking good in https://westbrook-overlay-trigger--spectrum-web-components.netlify.app/components/dialog-wrapper
