### ISSUE TITLE
Menus should scroll when there isn't enough height

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-web-components#1323]
### Expected Behaviour

Menus that would be bigger than the window dimensions should scroll.

### Actual Behaviour

https://user-images.githubusercontent.com/77195/112363836-2a23c300-8c93-11eb-9e1f-7d8b20d5dd4e.mov

**Comment by Westbrook** [comment]
Let's make sure we get a visual regression test lined up on this so we don't have this again in the future. 

Possibly related to:
#697
#910
