### ISSUE TITLE
Provide a way to target the input inside sp-textfield

### ISSUE THREAD

**Issue by joekukish** [adobe/spectrum-web-components#1332]
### Expected Behaviour

There should be a mechanism to add a class, or target the the input inside the sp-textfield (for example by adding part="input".

### Actual Behaviour
There is no API to be able to target this item via CSS.

**Comment by Westbrook** [comment]
We're tracking the interaction this sort of request has with Spectrum CSS here: https://github.com/adobe/spectrum-css/issues/743 There are a number of local remedies, but we're looking to structure the right universal remedy in partnership with the CSS team. For visual delivery specific issues there should likely be CSS custom property API surface supplied by the CSS to support this sort of customization without reaching into the elements.

Can you speak more to your use case here? I'm a bit worried that simply having access to customize the visual delivery of an element is not going to fully support the experience you are putting together here.

**Comment by joekukish** [comment]
@Westbrook Given the following expect InputGroup markup

```html
<div class="spectrum-InputGroup">
  <div class="spectrum-Textfield spectrum-InputGroup-textfield">
    <input type="text" placeholder="Type here" name="field" value="" class="spectrum-Textfield-input spectrum-InputGroup-input">
  </div>
  <button class="spectrum-Picker spectrum-Picker--sizeM spectrum-InputGroup-button" tabindex="-1" aria-haspopup="true">
    <svg class="spectrum-Icon spectrum-UIIcon-ChevronDown100 spectrum-Picker-menuIcon spectrum-InputGroup-icon" focusable="false" aria-hidden="true">
      <use xlink:href="#spectrum-css-icon-Chevron100" />
    </svg>
  </button>
</div>
```

The input itself is expected to have `spectrum-InputGroup-input`. Given that this is part of the ShadowDOM, I have no way to tell the `sp-textfield`, that the internal element should have a class.

To be able to address this locally, I renamed the SpectrumCSS from `.spectrum-InputGroup-input` to `.spectrum-InputGroup-textfield::part(input)`, and then added `part="input"` to the internal input. (via `input.shadowRoot?.firstElementChild?.setAttribute('part', 'input')`). and it works as expected.

Given that i'm dwelling into the `shadowRoot`, I figure there should be forward compatible to do so. Adding part="input" inside `sp-textfield` would address this for me, but I recognize there should be a common pattern across the component library.

**Comment by najikahalsema** [comment]
In theory, core token updates for this pattern will make this level of customisation possible. However, patterns requiring this (eg combobox) manage this on their own.
