### ISSUE TITLE
nvmrc is out of date

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1345]
### Expected Behaviour
This works
```
nvm use
yarn install
```

### Actual Behaviour
Get this error:
```
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
error @adobe/spectrum-web-components@0.0.9: The engine "node" is incompatible with this module. Expected version ">=14.15.3". Got "12.18.3"
error Found incompatible module.
```

**Comment by Westbrook** [comment]
Ha. I’ve created so many `.nvmrc` files and am only just in this issue learning that this is how you use it. 🙈 Sorry I missing this in the upgrade last week.

**Comment by adixon-adobe** [comment]
No worries. It might be possible for CirceCI to integrate with this and run with the version here, which would catch issues like this.

There'e also an `lts/*` option. I like having control over version changes, but it can be useful if you want to catch breaks immediately.

Leaving this open in case you want to open any followup issues -- otherwise this can be closed.
