### ISSUE TITLE
Documentation: sp-field-label demo broken

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#1349]
Checkout the demo for [sp-field-label](https://webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/fDq5bpzNQJzUUyEq6ENR/src/index.ts), which is broken due to the sp-popover element

**Comment by Westbrook** [comment]
Thanks, updated to use `sp-picker` instead of `sp-dropdown`.
