### ISSUE TITLE
sp-picker requires multiple clicking to choose item when in scrolling state

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#1361]
### Expected Behaviour
Menu items in an sp-picker should be easily clickable (one click and done)

### Actual Behaviour
When the sp-picker doesn't have enough room and needs to scroll there is some weird jumpy scroll position behavior when clicking, and selecting a menu item requires multiple clicks

### Reproduce Scenario (including but not limited to)
Create a long-ish menu with an sp-picker. Resize your browser such that it needs to scroll when open. Now try to use the picker.

#### Sample Code that illustrates the problem
https://webcomponents.dev/edit/rlz62LTQSuyMdK4cCf8W/src/index.ts
Make sure to resize the browser small such that the popover menu needs to scroll

**Comment by Westbrook** [comment]
Can you help confirm a possible fix? https://westbrook-menu--spectrum-web-components.netlify.app/storybook/?path=/story/picker--custom

@kaiortmanns this _should_ be what you were seeing as well 🤞🏼

**Comment by bengfarrell** [comment]
That looks right to me! thanks!

**Comment by Westbrook** [comment]
Want to tweak some things with the open/close functionality while I'm in here, but this will definitely be on the queue for release sometime next week!

**Comment by bengfarrell** [comment]
Excellent!
