### ISSUE TITLE
Browser support range?

### ISSUE THREAD

**Issue by matthias-ccri** [adobe/spectrum-web-components#1365]
Hi there,

I'm wondering what range of browser versions are officially supported by spectrum web components? It doesn't seem like there is an official statement, but the #3 search result for "spectrum web components browser support" says this:

> It will not support older browsers and will only target modern ever-green browsers that fully implement the Custom Elements V1 specification, e.g. Chrome, Firefox, Safari. Polyfills will be avoided as much as possible.

From https://awesomeopensource.com/project/adobe/spectrum-web-components

The problem is, I don't know where this came from or whether it's correct.

The reason I'm wondering is because we like spectrum-wc a lot and it's probably the top WC library out there. But we have to support some older browsers, and I've run across an issue that involves polyfills, but I'm not sure if it's worth reporting an issue against spectrum.

Thanks for your time,  
Matthias

### Expected Behaviour

N/A

### Actual Behaviour

N/A

### Reproduce Scenario (including but not limited to)

N/A

#### Steps to Reproduce

N/A

#### Platform and Version

https://github.com/adobe/spectrum-web-components/commit/1bd2f11dc1f2485a583e02fb5163ec5f5804df66

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by Westbrook** [comment]
Hi @matthias-ccri, thanks for reaching out and for you kind words. 🙇🏼 We'd certainly like to do our best to live up to them, however we do have to make some hard decisions as to where we invest our time.

The quote you've listed is from our [README.md](https://github.com/adobe/spectrum-web-components#spectrum-web-components). While we do not spend a lot of time addressing pre-API compliant browsers, with polyfill those browsers should be supported a good amount of the time, except IE11 for which I wouldn't make even caveated suggestions of support both for the overall cost of our library doing so and the lack of benefits to end users of implying that they can continue to use a browser that does not receive security updates.

For all issues, we prefer to approach them individually, so feel free to submit what you're seeing and we can have a conversation around what you're seeing. With these sorts of edge case issues, it will be particularly important that you list our extensive recreation steps that include not only the release you're leveraging and the browser versions, but the complete sub-version string of the browser in questions, the OS and version/sub-version strings leveraged, the same for any polyfills, any build steps that you leverage locally to support the delivery of the elements/your features, and any other information about your local context that you can. While we supply https://webcomponents.dev links to support recreation in most modern contexts, it would also be useful if you were able to boil a full repo with your simplified reproduction case.

Best case, it's a quick fix and we can get something into the library that makes _everyone's_ like a little easier. Worse case, we make something as a known issues 😓. Across the middle, there are lots of options. In cases where we are not able to make internal investment towards a fix, we're happy to support and accept PRs from you and your team whenever possible. 🙏🏼 

In that way, I'm going to close this issue now, but please feel free to open issues with specific context on what your seeing and we can discuss the possible paths forward.

**Comment by matthias-ccri** [comment]
Thank you, I see it is from the readme! I must not have read that. :sweat_smile:  I will create a separate issue with the issue I'm seeing. Thanks!
