### ISSUE TITLE
isSameNode incompatibility with webcomponentsjs polyfills

### ISSUE THREAD

**Issue by matthias-ccri** [adobe/spectrum-web-components#1367]
Followup to https://github.com/adobe/spectrum-web-components/issues/1365, I understand non-evergreen browsers are not officially supported, but I'm making this issue for consideration and documentation I suppose. Let me know whether this may be enough grounds to merit a workaround.

The issue:
The official webcomponents/polyfills make Node.isSameNode fail, when the argument is a shadow root. See https://github.com/webcomponents/polyfills/issues/436. The workaround would be to just use alternate equality checks like `===` instead of `isSameNode`.

### Expected Behaviour

No error

### Actual Behaviour

Error is thrown:
Firefox 60: `TypeError: Argument 1 of Node.isSameNode does not implement interface Node.`
Chromium 46: `TypeError: Failed to execute 'isSameNode' on 'Node': parameter 1 is not of type 'Node'`

#### Steps to Reproduce

Note: I was unable to use webcomponents.dev since it uses the nullish coalescing operator (`??`) in its preview page.

This codesandbox does throw the error.

https://codesandbox.io/s/spectrum-tooltip-issamenode-repro-1v8in

#### Platform and Version

This error is seen in these browsers:
- FF 60.0 ESR
- FF 52
- FF 45
- Chrome 57
- Chrome 46
- maybe Chrome 57? tooltips don't work at all, so I can't confirm or deny.

Note: I can assist with older browser testing. There is a way to run browsers in docker containers by mounting your host X11 socket into them (works on linux). Let me know.

#### Sample Code that illustrates the problem

```html
  <overlay-trigger>
    <button slot="trigger">Hover me</button>
    <sp-tooltip slot="hover-content">Tooltip</sp-tooltip>
  </overlay-trigger>
```

#### Logs taken while reproducing problem

None

**Comment by Westbrook** [comment]
I can't think of any reason not to accept a PR that replaces usage of `.isSameNode` for `node === otherNode`. Would you be interested in submitting one? 

I wonder if there is perf or related benefits to using `.isSameNode` as available in newer browsers. If so, we might be able to maintain that in modern browsers while still falling back with a big of a helper method that wrapped a check or a try/catch. 🤔

**Comment by matthias-ccri** [comment]
I can certainly submit an MR for that.

I would not expect there to be a performance boost from `.isSameNode`. The opposite, if any. And still, would it matter unless the call is in a hot code path? We'll see.

**Comment by Westbrook** [comment]
Closes by https://github.com/adobe/spectrum-web-components/pull/1369 look for a new release tomorrow sometime.
