### ISSUE TITLE
Textfield: add support for select()

### ISSUE THREAD

**Issue by joekukish** [adobe/spectrum-web-components#1377]
### Expected Behaviour
Current HTMLInputElement elements support `select()` to be able to select the text inside the input. This is currently not available at `sp-textfield`.

**Comment by Westbrook** [comment]
For curiosities sake I’d be interested DOM hearing what you’re building with this. But, sounds like a good idea. Could I interest you in making a PR for this? Hopefully we shouldn’t need much more than:

```
public select(): void {
    this.focusElement.select()
}
```

And a test, to watch for regressions. 

From the support matrix on MDM it looks like we can forgo any fallbacks the one question would be should we synthetically add the focus call to simplify usage?

Thoughts?

**Comment by joekukish** [comment]
@Westbrook If you check Photoshop, it is common that when you click on a textfield, the text is automatically selected as a way to ease overriding it. I'm currently replicating this behavior that's why I need this API.

**Comment by joekukish** [comment]
@Westbrook I can do a PR for this. Thanks!

**Comment by Westbrook** [comment]
Yeah, that sounds useful. Thanks for sharing!

In that it's click bound, we can probably skip doing anything fancy with the focus?
