### ISSUE TITLE
Add 'u' flag to be consistent with  "pattern" attribute of <input> element

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#1388]
https://github.com/adobe/spectrum-web-components/blob/8acfee43ce3be5d4a6da4cf1179d3400bca77968/packages/textfield/src/Textfield.ts#L231

see: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

**Comment by Westbrook** [comment]
Thanks for the issue. Can you confirm that I'm reading this as an `<input>` element will also ways interpret its `pattern` attribute as a regex with the `u` flag?

If so, would you be interested in submitting a PR for this? In particular, adding a test to this fact, so we don't regress in the future, would be much appreciated!

**Comment by OpportunityLiu** [comment]
I've tested on the latest Chrome & FireFox, seems that the `<input pattern>` will allow `\p{}` patterns, as the MDN said.
