### ISSUE TITLE
progress circle shows 100% full in dark theme with any value on Safari

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1392]
### Expected Behaviour
The documentation here shows up correctly on all browsers: https://opensource.adobe.com/spectrum-web-components/components/progress-circle

### Actual Behaviour
On Safari, the progress spinner is 100% full for the variants examples.

**Comment by adixon-adobe** [comment]
It's weird that the `over background` example displays correctly. In the internal test page we have for this on our site we see it sometimes fully filled or fully empty (including for over-background examples).

**Comment by Westbrook** [comment]
I'm seeing this not work at the Spectrum CSS source. https://opensource.adobe.com/spectrum-css/progresscircle.html

In both contexts, it appears that the intermediate version works, which makes me think there's something small that we could do locally to trick that back into working in the mean time...

**Comment by Westbrook** [comment]
Alex, are you still seeing this. I've just revisited these URLs and it seems our implementation is working, but Spectrum CSS' isn't? Can you confirm?

**Comment by adixon-adobe** [comment]
@Westbrook sorry for the delay in responding. We are still seeing this on our test page. I'll reach out with some more details on slack.

**Comment by Westbrook** [comment]
Can you share extended OS and browser versions where you're experience this? Safari Version 14.1.1 (16611.2.7.1.4) and TP Release 127 (Safari 15.0, WebKit 16612.1.18.11.3) don't seem to be displaying this in macOS 11.4...

**Comment by Westbrook** [comment]
The upstream change associated to this got into the library in the last release. However, our tools seem to be converting your fix to just `transform: translateZ(0);` for some reason. @hunterloftis can you confirm whether that's still correcting this issue?

**Comment by hunterloftis** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/364501/148422563-17e64885-1401-4140-aeeb-6ad4f4767296.png)
