### ISSUE TITLE
Switch click doesn't take right after initialization

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1402]
### Expected Behaviour
I can run automation that clicks really fast and the clicks work.

### Actual Behaviour
Somewhere between switch 0.6.1 and 0.7.5 a very early click doesn't take (the switch stays off).

### Reproduce Scenario (including but not limited to)
We can reproduce this consistently in our automation, but not with every click.

#### Steps to Reproduce
1. Initialize a switch
2. programmatically click it really fast

Result: switch stays off even though it was clicked.

**Comment by adixon-adobe** [comment]
I'm hoping this is something can can add a unit test that reproduces, but if not I can try to get a repro scenario outside of our site. I will admit not having fully narrowed this down to spectrum web components (but it started failing after our update so it seems really likely).

**Comment by Westbrook** [comment]
Can you share a rough code path you’re seeing this with? All of our elements are async, or should be, so this may be an expected/required update.

**Comment by adixon-adobe** [comment]
Here's the rough workflow (this is in our share menu):

1. Click a tab that causes new settings options to display
2. Click 3 switches once they're visible
3. Wait for them to be "checked"

Usually at least one of the switches is unchecked after those steps, and if I watch the automation I'll see that switch toggle on/off.

**Comment by adixon-adobe** [comment]
I'm now thinking that this is not be a component issue after digging deeper on our side. I haven't been able to repro with some local testing that should break things. I'll close this for now.
