### ISSUE TITLE
Typescript error in icons-ui custom-tag component

### ISSUE THREAD

**Issue by kaseyhinton** [adobe/spectrum-web-components#1403]
### Expected Behaviour
I can import and use sp-popover without a typescript compile error.

### Actual Behaviour
I get a typescript compile error. I've tried excluding the problem file in my tsconfig but because I am importing the files they are still seen by tsc due to [module resolution](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-is-a-file-in-the-exclude-list-still-picked-up-by-the-compiler) i guess.

#### Steps to Reproduce
Just importing the sp-popover and running tsc gets me the error. 
The workaround I ended up having to do so I could still use these components is not import the components
as es modules demonstrated in the sample code but to use script tags so i can bypass the typescript compilers module resolution.
```html
    <script src="./node_modules/@spectrum-web-components/popover/sp-popover.js" type="module"></script>
    <script src="./node_modules/@spectrum-web-components/overlay/overlay-trigger.js" type="module"></script>
```

#### Platform and Version
"lit-element": "^2.4.0",
"typescript": "^4.2.3",
"@spectrum-web-components/overlay": "^0.11.4",
"@spectrum-web-components/popover": "^0.9.6",

#### Sample Code that illustrates the problem
```ts
import '@spectrum-web-components/popover/sp-popover.js';
import '@spectrum-web-components/overlay/overlay-trigger.js';
```

```bash
npm run tsc
```

#### Logs taken while reproducing problem
```bash
node_modules/@spectrum-web-components/icons-ui/src/custom-tag.ts:30:5 - error TS2322: Type 'unknown' is not assignable to type 'string | TemplateResult'.
  Type 'unknown' is not assignable to type 'TemplateResult'.

 30     return values.reduce(
        ~~~~~~~~~~~~~~~~~~~~~
 31         (acc: string, v, idx) =>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 33         strings[0]
    ~~~~~~~~~~~~~~~~~~
 34     );
    ~~~~~~


Found 1 error.
```

**Comment by Westbrook** [comment]
I'm sorry to hear you're running into this. To help us get down to the root here, would you mind sharing your `tsconfig.json`? Or possibly a repo with a reproduction of this issue? I'm not seeing this error locally, but want to help track down what your seeing so we can help clear it up. Thanks!

**Comment by kaseyhinton** [comment]
@Westbrook  I have set up a repo to demonstrate the issue I am running into [here](https://github.com/kaseyhinton/typescript-spectrum-web-component-example). Thanks for looking into this!

**Comment by Westbrook** [comment]
Possible path forward in https://github.com/kaseyhinton/typescript-spectrum-web-component-example/pull/1 🤞🏼

**Comment by aarondrabeck** [comment]
The problem is, at least in this component, the td, js and ts.d are all in the same folder.  Typescript will then parse the TS files thus differing TS configs will always be an issue for end-users. 

A better structure would be something like:

```
/lib
   - component.js
   - component.ts.d

/src
   - component.ts

package.json
  ....
   main: ./lib/component.js
  ...
```

Now the TS is available to look in the NPM package, but never parsed or re-compiled.

**Comment by Westbrook** [comment]
Interesting, but that seems like bad form on Typescript's part. In the case of the repro, yes `import "@spectrum-web-components/popover/sp-popover";` was used, which is contrary to our documentation, but for TS to still reach in like that with `import "@spectrum-web-components/popover/sp-popover.js";` is disappointing. 

If this really in the only correction to that issue, it's be hard to commit to doing anything in this are until Typescript formally supports [Export Maps](https://github.com/microsoft/TypeScript/issues/33079). Otherwise, we'd have a wide scale breaking change that we just don't have the stomach for at this time.

**Comment by kaseyhinton** [comment]
Yeah I was disappointed that typescript was reaching into those files as well. Especially after specifying in the tsconfig that I wanted to exclude them. It took a bit of searching to find the docs that specified that with module resolution they will just outright disregard the exludes in tsconfig. We are still going to be able to use spectrum components in the meantime we are going to remove the typescript files with a postinstall script `    "postinstall": "rm -rf node_modules/@spectrum-web-components/**/**/*.ts"
`

**Comment by taylorcenters** [comment]
I'm running into the same issue with 
@spectrum-web-components/tags

```
ERROR in /User/me/myapp/node_modules/@spectrum-web-components/icons-ui/src/custom-tag.ts(30,5):
30:5 Type 'unknown' is not assignable to type 'string | TemplateResult'.
  Type '{}' is missing the following properties from type 'TemplateResult': strings, values, type, processor, and 2 more.
    28 |         return customTemplateLiteralTag(strings, ...values);
    29 |     }
  > 30 |     return values.reduce(
       |     ^
    31 |         (acc: string, v, idx) =>
    32 |             (acc as string) + (v as string) + strings[idx + 1],
    33 |         strings[0]
    ```
    will try Kasey's solution in the meantime as well

**Comment by davidkudera** [comment]
Is there any specific reason why `.ts` files are published too? Usually, only `.js` and `.d.ts` are included.

Here is also a slightly better command for removing `.ts` files from `node_modules`. The difference is that it ignores `.d.ts` files which are actually useful.

```bash
find node_modules/@spectrum-web-components -type f -name '*.ts' ! -name '*.d.ts' -delete
```

**Comment by kaseyhinton** [comment]
@davidkudera Yeah I agree that the `.ts` files shouldn't be published. Probably a good example of this is the material web component packages. They only publish a `.js`  and matching `.d.ts` files. I think expecting consumers of these web components to have a matching tsconfig/typescript environment isn't maybe the best approach if you want widespread adoption of the spectrum components.

**Comment by Westbrook** [comment]
So, it looks like we're getting close to a path forward here. If any of yall were interested in doing a test with some pre-releases, it would be great to get a more complex pass on this new package shape before a full release (hopefully sometime this week): https://github.com/adobe/spectrum-web-components/pull/1533#issuecomment-859970153

**Comment by davidkudera** [comment]
@Westbrook it seems to be working just fine for us. Thank you 👍

**Comment by Frikki** [comment]
Yes, it looks good.
