### ISSUE TITLE
[Action Button] a11y review

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1418]
### Feedback

- `<sp-action-group>` elements without a `selects` value errantly remove the `role` from `sp-action-button` children.
- Action button with hold affordance (all browsers)
  - ❌ no affordance to screen reader users that there is a secondary action
  - ❌ not possible for a screen reader to trigger the secondary action
- selected contrast not high enough

### Path forward

1. ~Update logic to assume that all children need to resolve back to `role="button"` rather than `role="undefined"`~
2. Will review with Spectrum design, they finalized on the way to do this in non-screen read contexts knowing that it wasn't really screen reader accessible but "committing to finding one" 😬 
3. Tracking here: #755

cc @jnurthen

**Comment by hunterloftis** [comment]
A subset of this is necessary for 1.0: 

Action button with hold affordance (all browsers)
❌ no affordance to screen reader users that there is a secondary action
❌ not possible for a screen reader to trigger the secondary action

specifically, accepting custom strings is _not_ part of the 1.0 requirement.
