### ISSUE TITLE
Documentation for icon usage needs updating

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#1421]
### Expected Behaviour
We've updated our icon usage from something like 

`<sp-icon>
      ${CircleIcon()}
 </sp-icon>`

to 
`<sp-circle-icon></sp-circle-icon>`

in recent versions. However, our live documentation doesn't go into the usage of the latter, and I, personally, as well as other users, should be informed on this alternate usage via our docs. 

### Actual Behaviour
Only one type of usage is detailed in our documentation. 

### Reproduce Scenario (including but not limited to)
https://opensource.adobe.com/spectrum-web-components/components/icons-workflow

**Comment by adixon-adobe** [comment]
Saved me filing this issue! I think it's be awesome to have something like https://spectrum.adobe.com/page/icons/ with some handy copy functionality for copying the import code.

**Comment by Westbrook** [comment]
We're already 3/4 of the way there, too. Between the copy code functionality in the demos and https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/icons-workflow--elements Before #1415 it's kind of hard to code split in the docs build and the icons in this set come out to maybe 144KB minzipped 😨 but would love to see this pushed forward after!
