### ISSUE TITLE
Some styling properties are not applied correctly when buttons are not direct children of action group

### ISSUE THREAD

**Issue by isabellaminca** [adobe/spectrum-web-components#1434]
### Expected Behaviour

For example border radius on the buttons should be set accordingly within a compact action group where buttons are wrapped with tooltip.

![Screenshot 2021-05-05 at 16 59 55](https://user-images.githubusercontent.com/15520550/117153122-59197280-adc3-11eb-8ddb-78ea246bcef8.png)

### Actual Behaviour

Border radius is the same for all buttons.

![Screenshot 2021-05-05 at 16 57 33](https://user-images.githubusercontent.com/15520550/117152938-2b342e00-adc3-11eb-929c-c8eb65fd44ed.png)

#### Steps to Reproduce

Create a compact action group where buttons are wrapped with tooltip

**Comment by Westbrook** [comment]
`justified` is also not passed correctly here:
![image](https://user-images.githubusercontent.com/1156657/117165452-80584b80-ad93-11eb-9797-30832f6a43e3.png)
vs
![image](https://user-images.githubusercontent.com/1156657/117165486-89491d00-ad93-11eb-9ae3-a5b16faa38cc.png)
AND
![image](https://user-images.githubusercontent.com/1156657/117165543-9534df00-ad93-11eb-9921-8485eabcfed5.png)
vs
![image](https://user-images.githubusercontent.com/1156657/117165586-9ebe4700-ad93-11eb-92ba-911cd1f291d3.png)

**Comment by Westbrook** [comment]
@isabellaminca, @stanvladut, wanted to update y’all on the progress here. 

Checkout the following: https://westbrook-action-group--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-group-tooltips--selects-single

I’m going to be doing an additional round of checking for edge cases and then we should have a PR ready for review on the in the coming days. 

Thanks for your patience!

**Comment by stanvladut** [comment]
@Westbrook looks good to me from what I've tested so far. 

While testing, I've tried enabling the `justified` property for vertical alignment, but it seems not to work, I'm not sure if that's intended or not though.
Also, not sure if it's a storybook issue or not, but disabling and re-enabling the `quiet` property does not bring the borders back.

**Comment by Westbrook** [comment]
Fixed in #1494
