### ISSUE TITLE
<sp-icon .. name="ui:ChevronDownSmall" stopped displaying icon after update 

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/spectrum-web-components#1442]
I updated my npm dependencies at my icon disappeared from:

```
            <sp-icon slot="icon" size="xxs" name="ui:ChevronDownSmall"></sp-icon>
```

The JS Console reports an error:

```
Unable to find icon ChevronDownSmall  at HTMLElement.applyIconToElement (popup.js:216)
```

Can someone remind me/point to (clear) docs on how to properly import icons for use with Spectrum Web Components?

I tried importing `@spectrum-web-components/icons-ui` and specifically importing a smalled named chevron web component (sp-icon-chevron75) and using that in place of the above `<sp-icon...`, like `<sp-icon-chevron75>` .. but that didn't work either.

Thanks

**Comment by bengfarrell** [comment]
I think icons usage did change recently. The docs under icons-ui covers the latest usage: https://opensource.adobe.com/spectrum-web-components/components/icons-ui

It looks like the latest is to just import the icon directly from the package:
`import { Chevron100Icon } from '@spectrum-web-components/icons-ui';`

And then to use:
`<sp-icon>${Chevron100Icon()}</sp-icon>`

**Comment by davidjgonzalez** [comment]
@bengfarrell .. when i follow the `icons-ui` instructions, and do

```
import '@spectrum-web-components/icon/sp-icon.js';
import { Chevron75Icon } from '@spectrum-web-components/icons-ui';

...

          <sp-icon>
                ${Chevron75Icon()}
            </sp-icon>
```

the "Chevron" icon renders as the ellipsis (3 dots) ... which i think? is a placeholder for when the icon cannot be located/displayed. Is there something i have to do do load the supporting svgs or something?

**Comment by bengfarrell** [comment]
Hiya - yep, I think things are a bit in flux, so I def don't blame you for being confused. I think @Westbrook had a good explanation for using icons, but what you're struggling with a bit is using icons in context now.

Here's what I think you're looking for: https://webcomponents.dev/edit/K1PXjwmftX0FV56PpstS/

To explain, in many situations in SWC, you'll need to denote that your `<sp-icon>` is a slot inside something else.

In my link, I have a normal button where I do `<sp-icon slot="icon"...>`. In normal buttons, you can just add the icon and it'll show up. But the alignment is kinda bad. For `<sp-button>`, adding it to the icon slot lets SWC know how to deal with it.

The complexity of the `<sp-action-menu>` makes things a bit trickier with the added bonus of some deprecated behavior.

Here (I'm not sure how much it's negatively affecting things) you should not use `<sp-menu>` inside an action-menu anymore. The action-menu assumes that it'll have a menu, and if you look at your console log you'll see a message indicating this.

The larger issue here though, is that you can't just put whatever inside the action menu. Notice how that `<span>' has the attribute `slot="label"`. Unlike the button, if you left this slot out, the `<sp-action-menu>` component is not able to handle it. This component ONLY handles "named" slots. So if you slot something in here and don't give it a name, it'll get added as a child, but fall outside the Shadow DOM managed by the component and just not get rendered. 

This is also why you see the three dots. This is the default icon for the `<sp-action-menu>` component. To change this component, the icon that you're slotting in needs to have the `slot="icon"` attribute. This lets the action menu that this particular child/slot it intended for the icon.

Hope that helps!

**Comment by davidjgonzalez** [comment]
Forgot to follow up - I got it working between @bengfarrell  and @Westbrook 's samples! here's what i had to do to effectively recreate `<sp-icon slot="icon" size="xxs" name="ui:ChevronDownSmall"></sp-icon>`. I was thrown for a loop since the docs (and the old "name" attr) made it seem like this should be in the Icons UI project, in fact there is something similar in the Icons Workflow project that renders the same as before. Using Icons UI chevron75, the chevrons were still way too big (and don't seem to respect the "size" attribute either)

```
import "@spectrum-web-components/icons-workflow/icons/sp-icon-chevron-down.js";

...

  <sp-action-menu id="actionMenu_jira_${kt}" placement="bottom-end">
            <sp-icon-chevron-down size="xxs" slot="icon"></sp-icon-chevron-down>

            <span slot="label">Blah</span>

            <sp-menu-item>
               Blah
            </sp-menu-item>             
</sp-action-menu>
```

**Comment by Westbrook** [comment]
@davidjgonzalez that's great news. I glad you're back to a place where this is working close to intended!

In that case, I'd like to close this in favor of #1421. If you think there is something specific to this issue you'd like us to address, please feel free to reopen. Thanks!
