### ISSUE TITLE
Color slider user drag behavior

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#1454]
### Expected Behaviour
Dragging the slider should follow your pointer

### Actual Behaviour
Slider loses drag behavior mid-stream and just stops when testing on mobile, or mobile simulated dev tools

### Reproduce Scenario (including but not limited to)
Just open Chrome's mobile sim and try to drag the color slider (even with a mouse)

**Comment by Westbrook** [comment]
This has been fixed!
