### ISSUE TITLE
More variant of split button can have value change

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1456]
### Expected Behaviour
It looks like the More variant of SplitButton shouldn't actually have a value. It's definitely not supposed to have the button text change when selecting a different option. Here's the contribution docs link for reference: https://spectrum-contributions.corp.adobe.com/page/split-button-beta/

### Actual Behaviour
If you click the default action and then another action, but button text / selection chagnes.

### Reproduce Scenario (including but not limited to)
Easy to repro in the docs.

**Comment by adixon-adobe** [comment]
I think I can address this with the work for #1189 by making the underlying menu unselectable with the "more" variant

**Comment by Westbrook** [comment]
This should be in line with the expectation here? https://westbrook-menu-selects--spectrum-web-components.netlify.app/storybook/?path=/story/split-button--more-cta
