### ISSUE TITLE
Extend <sp-menu/> to support Menu Nested pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#146]
### Expected Behaviour
<sp-menu /> can have nested menus like https://opensource.adobe.com/spectrum-css/menu.html#nested

### Actual Behaviour
It cannot.

**Comment by simshanith** [comment]
Link in expected behavior is broken

**Comment by Westbrook** [comment]
Link updated!

With this pattern having been deprecated at the Spectrum CSS level if you and your team have a specific use case in mind for this, we should gather it as a feature request and share it up to the Spectrum team for "officializing". Happy to support communication between your team and theirs in anyway we can: +1-ing your direct request (usually via Slack), gathering your request and reporting it to the team in our regular syncs, or inviting you an upcoming sync to represent your usecase directly. There's also a new ["list item" (Adobe internal link)](https://spectrum-contributions.corp.adobe.com/page/list-item-beta/) pattern coming together that hints at possibly featuring more clear recommendations here that we could be a part of helping develop.

Looking forward to how this comes together!

**Comment by Westbrook** [comment]
@spdev3000 I've gotten an early draft of this together at https://westbrook-sub-menu--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu--submenu

This leverages the following DOM based API:
```
<sp-menu>
    <sp-menu-item>
        Label
        <sp-menu slot="sub-menu"> ... </sp-menu>
    </sp-menu-item>
</sp-menu>
```

Don't have much more than a working click, but it's helping to outline the issues we'll face. Most of all, to allow for this DOM structure this has to be added after the selection work in #1189. I'm seeing some green lights start to popup in CI there, so hopefully it'll be ready for a PR sometime this week, and then we can get into supporting this more fully.

I'd like to also support an API along these lines as well:

```
<sp-menu>
    <sp-menu-item
        submenu=${idref | HTMLElement}
    >
        Label
    </sp-menu-item>
</sp-menu>
```

I think there's some niceties that this presents an application developer, but while I want to support them I'll make sure that doing so isn't negatively effecting getting a working version together and published of the fully DOM based API.

Lots of keyboard, a11y, etc. work to do once the selects lands, so keep on eye out for that PR as another set of eyes could help move that along.

**Comment by Westbrook** [comment]
@spdev3000 FYI: with the Menu selection code landing today, I'll be moving focus onto this feature for you and the team tomorrow and next week! I'll take a look at your repo for anything I can see about your local implementation, but please share any learning/requests you might have run into to date here.

**Comment by Westbrook** [comment]
https://sub-menu--spectrum-web-components.netlify.app/storybook/?path=/story/menu--submenu

To dos:
- [ ] document `change` event system
- [ ] add test coverage
- [ ] manage mobile delivery via `<sp-tray>`
