### ISSUE TITLE
[Color Area] Extend set color method to use HSV values from input object

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1470]
### Expected Behaviour
Extend `set color` method to parse and use hsv values directly from input - if `color` input is an HSV/HSVA object like `{h: hueValue, s: sValue, v: vValue}`

This will prevent TinyColor's `toHsv()` method to override any given hue values with `0` if s-value is set to `0`

### Actual Behaviour
If I provide an input color object with s (saturation) = 0, TinyColor's `toHsv()` method will also set the hue value to `0` regardless of the provided input hue value.
This leads to resetting the hue value. Currently this can be temporary fixed if `hue` , `x` and `y` values are provided directly but still a color value needs to be set for default background color rendering of ColorHandle. 

#### Steps to Reproduce
- set start color value to `#00ff00`
- move color handle to left border of color area to select grey value or provide a grey value to color area , like `#c1c1c1` 
- this will set the hue part to `0` resulting in a pure red color area

#### Platform and Version
color-area: 0.1.4 on Chrome

**Comment by Westbrook** [comment]
We can use this as a recreation to review options for moving forward here: https://webcomponents.dev/edit/Bv35bBB1gfphaS83UsOQ/src/index.stories.js

We documented this as a reality of the element, but it can/should be addressed to prevent these sorts of issue from occurring. In `sp-color-slider` and `sp-color-wheel` we extract the `hue` entry as `value` internally, and we could definitely do similarly in `sp-color-area`. I think the extra work needed here would include grafting that `hue` value back into the `get color` value returned when `format === 'hsl'` or `format === 'hsv'`. The main complexity of that would be inserting the value into the string results.

@spdev3000 would you be interested in structuring a PR to support inputs in this way?

Conversely, we could raise this to https://github.com/scttcper/tinycolor and discuss/submit a PR that would allow for managing colors inside of the TinyColor object in the format that they were originally supplied. Thoughts?

**Comment by spdev3000** [comment]
I have checked the current source code of TinyColor - and they use internally RGBA data completely. That means they convert everything to RGBA on input and then handle a back conversation to each respective output format when requested. see: [toHsv()](https://github.com/scttcper/tinycolor/blob/e0a400a35d202d25e017bbb83e61cbc100703774/src/index.ts#L167 )
I doubt that they will restructure the complete core of importing/exporting color data for this use case so I would prefer to start with the first option you suggested. Let me check if I can open a PR on color-area.
