### ISSUE TITLE
[Tabs] Disabled attribute of tabs should also disable tab elements

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1471]
### Expected Behaviour
If I set `<sp-tabs disabled></sp-tabs>` I would expect all children `<sp-tab>` elements to be disabled. Also selecting different tabs shouldn't be possible anymore.

Would also be nice to have a readme section about disabled version available.

### Actual Behaviour
Parent `sp-tabs` element is greyed out but children tabs elements aren't - and the tab items are still selectable

#### Platform and Version
tabs: v0.5.6 on Chrome

**Comment by Westbrook** [comment]
🙈 This was definitely something that "came for free" with the base functionality this element, as well as the `sp-tab` element, is based on and was never really taken into account. 

Now that we will also be shipping `sp-tab-panel` my initial instinct is to _not_ do anything to those elements and rely on the consuming developer to make decisions there. The theory is that this would allow for a `disabled` `sp-tabs` to continue to feature in a screen readable manner the last selected `sp-tab-panel` before its controls became disables while still allowing for the application to do things like `aria-hidden="true"`, etc. as needed locally. @spdev3000 How do you see this sort of capability coming into play in the context you're working in?

**Comment by spdev3000** [comment]
The use case is: I don't want to let the user switch tabs until all tab content for all tabs has been loaded. But it's maybe better to let the client decide which tabs are when disabled.
