### ISSUE TITLE
Arrow Up/Down Key Event produce Error in Textfield

### ISSUE THREAD

**Issue by chris22763** [adobe/spectrum-web-components#1472]
### Expected Behaviour
I want to use a textfield and press Arrow Up/Down to increment/decremt a number Value.

### Actual Behaviour
Error gets thrown
`Accordion.ts:107 Uncaught TypeError: Cannot read property 'disabled' of undefined
    at HTMLElement.focusItemByOffset (Accordion.ts:107)
    at HTMLElement.handleKeydown (Accordion.ts:98)`

#### Platform and Version
MacOS
Chrome Developer Version

**Comment by Westbrook** [comment]
`sp-textfield` will not have this functionality added to it. Hopefully, you'll be pleased by the progress we've made toward `sp-number-field` in #1468 which does have that capability.

Separately, the error you've encountered here seems strange, could you share a repro of that so we can help get down to the bottom of it? We looked to address a somewhat similar issue in the most recent version of `sp-accordion`, so if you're not on version 0.4.7, you might check that out first.

**Comment by Westbrook** [comment]
@chris22763 have you been able to repro this?

**Comment by Westbrook** [comment]
For now, I'll close this as not reproducible. Please feel free to reopen with more information as needed in the future.
