### ISSUE TITLE
[Menu] scrollIntoView on connect can cause issues.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1473]
### Expected Behaviour
Connecting a Menu to the DOM does not scroll the page in a surprising way.

### Actual Behaviour
While connecting a Menu to the DOM can usually benefit from scrolling to its currently selected element, doing so while `opacity: 0` or similar can cause the page to act in a surprising way.

### Reproduce Scenario (including but not limited to)
https://webcomponents.dev/edit/S3CWjt2ob4nmyKmPbXid/src/index.ts

CC @joekukish

**Comment by Westbrook** [comment]
One possible path here could be to scope the scrollIntoView call to _only_ when the element owns focus?

**Comment by joekukish** [comment]
@Westbrook actually it would be an accessibility violation to steal focus.

**Comment by Westbrook** [comment]
This wouldn't be moving the focus, this would leverage the presence of focus to activate the scroll position update (or not) at connect time, so no effect on the accessibility tree or tab/screen reader cursor.
