### ISSUE TITLE
[RFC] Support slotted label content for `sp-sidenav-item`

### ISSUE THREAD

**Issue by simshanith** [adobe/spectrum-web-components#1485]
### Expected Behaviour

Support slotted content similar to `MenuItem`:

```html
<sp-sidenav-item>Item Content</sp-sidenav-item>
```

...would render appropriately with `Item Content` visible in the light DOM

### Actual Behaviour

Currently the only API to specify content is the `label` property. It expects a `string`, but you can provide a `TemplateResult` and it will render in the shadow root. Styles must also be applied in the shadow root which adds additional complications.

### Reproduce Scenario (including but not limited to)

I'm implementing a side nav where one item "expands" and reveals sub-navigation items. To indicate expanded state, I display a chevron, rotated via css class manipulation. Additionally, I use an `<sp-avatar>` for a rich label for the "parent" sidenav item.

```ts
html`
<sp-sidenav>
  <sp-sidenav-item
    .label=${html`
      <style>
        sp-avatar {
          height: 20px;
          width: 20px;
          margin-right: 8px;
        }
        .indicator {
          transition: transform 0.4s ease;
          margin-left: 5px;
        }
        .indicator.open {
          transform: rotate(180deg);
        }
      </style>
      <sp-avatar
        label="${this.avatarLabel}"
        src="${this.avatarSrc}"
      ></sp-avatar>
      <sp-icon
        size="s"
        class="indicator ${this.expanded
          ? 'open'
          : 'closed'}"
      >
        ${ChevronDownIcon()}
      </sp-icon>
    ` as any}
    @click=${this.handleToggleExpanded}
  ></sp-sidenav-item>
  ${this.expanded
    ? html`<sp-sidenav-item label="Subnav Item"></sp-sidenav-item>` // additional sidenav items displayed when expanded
    : null}
</sp-sidenav>
`
```

I'd much prefer to pass slotted content and style light DOM without having to deliver to the component directly:

```ts
html`
<sp-sidenav>
  <sp-sidenav-item  @click=${this.handleToggleExpanded}>
    <sp-avatar
      label="${this.avatarLabel}"
      src="${this.avatarSrc}"
      slot="label"
    ></sp-avatar>
    <sp-icon
      slot="label"
      size="s"
      class="indicator ${this.expanded
        ? 'open'
        : 'closed'}"
    >
      ${ChevronDownIcon()}
    </sp-icon>
 </sp-sidenav-item>
  ${this.expanded
    ? html`<sp-sidenav-item label="Subnav Item"></sp-sidenav-item>` // additional sidenav items displayed when expanded
    : null}
</sp-sidenav>
`
```

#### Steps to Reproduce

Provide content to an `<sp-sidenav-item>` element

#### Platform and Version

 `"spectrum-web-components/sidenav@0.10.1"`

#### Sample Code that illustrates the problem

See above.

#### Logs taken while reproducing problem

n/a

**Comment by simshanith** [comment]
Added `slot="label"` naming to example desired API to avoid conflict with existing use of default slot for `multilevel` sidenav.

**Comment by Westbrook** [comment]
I think it's a great idea to move in this direction! Some initial thoughts...

The use of a `slot="label"` API would prevent the ability to do:
```
<sp-sidenav-item>Item Content</sp-sidenav-item>
```
This seems like the "default use case" that we should likely be attempting to support with this change. 🤔 

Positioning this path forward at the highest level of current complexity, we're looking for a way to support something like:
```
<sp-sidenav variant="multilevel" defaultValue="Layout">
    <sp-sidenav-item value="Guidelines">Guidelines</sp-sidenav-item>
    <sp-sidenav-item value="Styles" expanded>
        Styles
        <sp-sidenav-item value="Color">Color</sp-sidenav-item>
        <sp-sidenav-item value="Grid" expanded>
             Grid
            <sp-sidenav-item value="Section Title 1" label="Section Title 1">
                <sp-icon-star slot="icon"></sp-icon-star>
            </sp-sidenav-item>
            <sp-sidenav-item value="Section Title 2" label="Section Title 2">
                <sp-icon-star slot="icon"></sp-icon-star>
            </sp-sidenav-item>
        </sp-sidenav-item>
        <sp-sidenav-item value="Typography">Typography</sp-sidenav-item>
    </sp-sidenav-item>
    <sp-sidenav-heading>
        Category 2
        <sp-sidenav-item value="Section 5" label="Section 5"></sp-sidenav-item>
        <sp-sidenav-item value="Section 6" label="Section 6"></sp-sidenav-item>
    </sp-sidenav-heading>
</sp-sidenav>
```
The above combination of headings, icons, labels or various application, etc. needs to be supported by whatever we come up with here.

Non-breaking changes are definitely going to be preferred here, but in that we are pre-1.0 we should be open to what is "right" as much as to what is easy for current consumers. In that way, we might want to take the recently released `sp-tab-panel` element which actually sprouts its own `slot` attribute, in hopes of somewhat aligning with the imperative slotting API that is slowly being implemented x-browser. In this way, all of the elements that are currently slotted in the default slot could also sprout a `slot` attribute freeing the default slot for label centric content. This could mean that a user applies the above HTML, but the final delivery of it is more like the following, without requiring developer intervention.
```
<sp-sidenav variant="multilevel" defaultValue="Layout">
    <sp-sidenav-item value="Guidelines" slot=""descendant">Guidelines</sp-sidenav-item>
    <sp-sidenav-item value="Styles" expanded slot=""descendant">
        Styles
        <sp-sidenav-item value="Color" slot=""descendant">Color</sp-sidenav-item>
        <sp-sidenav-item value="Grid" expanded slot=""descendant">
             Grid
            <sp-sidenav-item value="Section Title 1" label="Section Title 1" slot=""descendant">
                <sp-icon-star slot="icon"></sp-icon-star>
            </sp-sidenav-item>
            <sp-sidenav-item value="Section Title 2" label="Section Title 2" slot=""descendant">
                <sp-icon-star slot="icon"></sp-icon-star>
            </sp-sidenav-item>
        </sp-sidenav-item>
        <sp-sidenav-item value="Typography" slot=""descendant">Typography</sp-sidenav-item>
    </sp-sidenav-item>
    <sp-sidenav-heading slot=""descendant">
        Category 2
        <sp-sidenav-item value="Section 5" label="Section 5" slot=""descendant"></sp-sidenav-item>
        <sp-sidenav-item value="Section 6" label="Section 6" slot=""descendant"></sp-sidenav-item>
    </sp-sidenav-heading>
</sp-sidenav>
```

**Comment by Westbrook** [comment]
Here's a demo based on the conceptual outline above: https://westbrook-sidenav-label-slot--spectrum-web-components.netlify.app/components/sidenav You can review this in the `westbrook/sidenav-label-slot` branch if you want to take a closer look.
