### ISSUE TITLE
[Documentation] Enhance sidenav item docs

### ISSUE THREAD

**Issue by simshanith** [adobe/spectrum-web-components#1486]
- https://opensource.adobe.com/spectrum-web-components
- https://opensource.adobe.com/spectrum-web-components/components/sidenav
- https://opensource.adobe.com/spectrum-web-components/components/sidenav-item
- https://opensource.adobe.com/spectrum-web-components/components/sidenav-item/api

### Expected Behaviour

- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) should appear as a component in the sidenav
- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) should be linked from the [Sidenav](https://opensource.adobe.com/spectrum-web-components/components/sidenav) component documentation
- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) should have an overview page demonstrating usage

### Actual Behaviour

- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) does not appear as a component in the sidenav
- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) is not linked from the [Sidenav](https://opensource.adobe.com/spectrum-web-components/components/sidenav) component documentation
- [Sidenav Item](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item) overview page is the same content as the [API](https://opensource.adobe.com/spectrum-web-components/components/sidenav-item/api), with no usage overview.

**Comment by Westbrook** [comment]
First, ugly, draft: https://westbrook-sidenav-item--spectrum-web-components.netlify.app/components/sidenav-item

Should this update also include a page for `sp-sidenav-heading`?
