### ISSUE TITLE
[Documentation] Enhance accordion item docs

### ISSUE THREAD

**Issue by simshanith** [adobe/spectrum-web-components#1487]
- https://opensource.adobe.com/spectrum-web-components
- https://opensource.adobe.com/spectrum-web-components/components/accordion
- https://opensource.adobe.com/spectrum-web-components/components/accordion-item
- https://opensource.adobe.com/spectrum-web-components/components/accordion-item/api

### Expected Behaviour

- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) should appear as a component in the sidenav
- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) should be linked from the [Accordion](https://opensource.adobe.com/spectrum-web-components/components/Accordion) component documentation
- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) should have an overview page demonstrating usage

### Actual Behaviour

- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) does not appear as a component in the Accordion
- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) is not linked from the [Accordion](https://opensource.adobe.com/spectrum-web-components/components/Accordion) component documentation
- [Accordion Item](https://opensource.adobe.com/spectrum-web-components/components/accordion-item) overview page is the same content as the [API](https://opensource.adobe.com/spectrum-web-components/components/accordion-item/api), with no usage overview.

**Comment by Westbrook** [comment]
First draft: https://westbrook-accordion-item--spectrum-web-components.netlify.app/components/accordion-item
