### ISSUE TITLE
Typo on documentation for Tabs

### ISSUE THREAD

**Issue by taylorcenters** [adobe/spectrum-web-components#1490]
### Expected Behaviour

Documentation shows correct import value for sp-tab-panel
import '@spectrum-web-components/tabs/sp-tab-panel.js';

### Actual Behaviour

Documentation shows incorrect import value
import '@spectrum-web-components/tabs/sp-panel.js';

### Reproduce Scenario (including but not limited to)

Navigate to https://github.com/adobe/spectrum-web-components/tree/main/packages/tabs and read the README

**Comment by Westbrook** [comment]
Fixed by #1491
