### ISSUE TITLE
[Number Field] No value formatting feature

### ISSUE THREAD

**Issue by stanvladut** [adobe/spectrum-web-components#1497]
### Expected Behaviour
The expected behavior would be to have the option to prevent Number Field from formatting the value. There are cases where only the numeric value is needed to be displayed, without any formatting.

This way, we can still benefit from increasing the value by pressing ArrowUp/ArrowDown and other such functionalities, but for just a numeric value, not a formatted one.

### Actual Behaviour
The Number Field component formats the field's value as standard, not allowing customisation for it.

**Comment by Westbrook** [comment]
Merging with #1495, as while they're not exactly duplicates, I think they'll leverage roughly the same solution.

**Comment by Westbrook** [comment]
Reopening as there are some things specific to this that I'd like to understand.

In cases where there was "no formatting" would you ever need to support numbers with decimals? E.G. https://webcomponents.dev/edit/HeaAQQov30igs7sg0kuT/src/index.ts

If there were cases of this, would you expect always for the "decimal" to be written in "English" as a `.`? Generally, French would write this as a `,` instead. In this way are we removing formatting: something that would display as `3,000.1` should be forced to `3000.1` regardless of the locale or are we removing grouping, as outlined in the above example (requires : here `3,000.1` would be updated _some times_ to `3000,1` as locally appropriate?

**Comment by stanvladut** [comment]
First, it seems like we moved away from this idea lately and we'll continue using the standard formatted NumberField component. I guess this can be closed if you don't see any value for the future usage of the component.

Second, just to answer your questions: I would expect to only have the decimal written in _English_ as `.` (which is also the `JS` standard for decimals), so `3,000.1` or `3000,1` should be always forced to `3000.1` regardless of the locale selected. So, not only the group separator should be removed, but the formatting should be done in _English_ too.

**Comment by Westbrook** [comment]
Reviewing this further, if the goal ends up being that an `sp-number-field` element should display:
1. In English
2. Without separators

Then the path to doing so would be to resolve the display language to "English" via https://github.com/adobe/spectrum-web-components/pull/1550 or similar and leverage `useGrouping: false` in the `formatOptions` to achieve this delivery.

If this usage becomes a requirement again and you feel this doesn't server the desired delivery, feel free to reopen with extended use case information. Close for now.
