### ISSUE TITLE
sp-menu-group is overkill

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1505]
### Expected Behaviour
Our code and API structure is as simple as possible.

### Actual Behaviour
`sp-menu-group` really only serves the purpose of adding a header item above menu items. We should be able to move this pattern into `sp-menu` directly.

Because `sp-menu-group` is adding an `sp-menu` in it's Shadow DOM, it's also creating some timing complexities around managing menu items. 

### Proposal
Deprecate `sp-menu-group` and just add the `header` slot it supports directly to `sp-menu`.

**Comment by Westbrook** [comment]
While not impossible, there is a couple of cascade realities that this opens:
- the layout of `sp-menu-group` is based off of the the styled "menu" being separate from the heading, so we'd likely need to introduce a new container `div` to the tree
- this means we also need to update the processing of Spectrum CSS to both pass these styles to the new element and ensure block styling on the `sp-menu` by default
- review of the current relationship between the heading and the `sp-menu` outlines a dropped label relationship between the two
  - we _could_ hand new attributes off of slotted content (when available), that is a risky proposition.
  - it's likely required that we move the `role`, the `tabindex`, and the label relationship onto this new `div` element, which both makes this task, and adopting this work into #1475 more change than initially expected
    - this likely benefits from mixing in `Focusable` to manage some of this...

So roughly:
```
${this.slotContentIsPresent
  ? html`
    <span class="header" id="header" aria-hidden="true">
      <slot name="header"></slot>
    </span>
  ` : html``
}
<div
  class="menu"
  role=${this.menuRole}
  aria-labelledby=${ifDefined(this.slotContentIsPresent ? 'header' : undefined}
  aria-label=${ifDefined(this.label && !this.slotContentIsPresent ? this.label : undefined}
>
    <slot></slot>
</div>
```

There's some associations in there for a screen reader that I've not reviewed for other patterns that we'd need to confirm first, however.

The new approach seems easier for label appropriately, as well as to leverage appropriately in your selection work, so it might be required, whether we want it or not.

In other news, there will be no sweater left once you finish pull all these threads.

**Comment by adixon-adobe** [comment]
I'm also not sure things *really* get easier for the menu item management once we really integrate it with PickerBase, which also renders `sp-menu` in the Shadow DOM, but with more complexity due to the re-parenting. Though the re-parenting timing might actually help us there.

For now I'll avoid this with the work in #1475, but this does seem worth doing while we're being disruptive to the menu API.
