### ISSUE TITLE
Eliminate need for overlay-root

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#151]
### Expected Behaviour

We should be able to use overlays (e.g. dropdown menus and popovers) without having to create a `overlay-root`

### Actual Behaviour

Right now, we have to manually create an `overlay-root` element to host our popovers

### Reproduce Scenario (including but not limited to)

Any use of `overlay-trigger` or any component that uses it.

#### Steps to Reproduce

Run the `overlay-trigger` samples in Storybook

**Comment by Westbrook** [comment]
I've gotten into some early research as far as removing `overlay-root` from the system here: https://github.com/adobe/spectrum-web-components/tree/westbrook/overlay-root. Here we're eschewing the need for an explicit `overlay-root` element and hanging all of the functionality expected therein on the `<body>` element. I could see a worthwhile extension that allowed for this to be configured, but wanted to get something "working" to discuss first.

It does generally suffer from the CSS Custom Property maintenance outlined in earlier comments. I've not followed up on whether we can extract these from the `overlay-trigger` context or not. It is likely, however, that we need to resolve en mass if we really want to do this in a performant manner. To that end, this might align with https://github.com/adobe/spectrum-web-components/issues/154 to necessitate a sort of "registration" system, that whether it happens in an `<sp-theme>` element or as a mixin allowed an element to respond to "do I have styles?" events with the style sheet that outlines its theme. There are likely a number of gotchas to this, but if we gather the styles from `OverlayTrigger.getRootNode()` and this "registration" point, we might be able to cover enough cases to make it worth moving forward with this?

**Comment by cuberoot** [comment]
@Westbrook I am currently chewing on #154. I was looking at the option where we change the `:host` to `:host[color="light"]` for example. Would that facilitate this work?  Could we then use that to import the correct variables into some sort of container at the root?

**Comment by Westbrook** [comment]
I think for the "theme" specific properties, yes.

If you have a style root, we're using `<sp-theme>` for now, and it knows what themes it is displaying (e.g. `lightest`, `medium`, etc.) then when a child `overlay-trigger` tries to open an overlay, it can first resolve the themes with a DOM event, and then pass that to the `active-overlay` which can act as or compose an `<sp-theme>` element manages the Custom Properties for the overlay content.
