### ISSUE TITLE
[Menu Item] Justified right side slot for sp-menu-item

### ISSUE THREAD

**Issue by stanvladut** [adobe/spectrum-web-components#1515]
### Expected Behaviour
The expected behaviour would be to have a slot on the `sp-menu-item` component that allows inserting justified content on the right side. A good example would be having a `<kbd>` on the the menu item's right side. 

![Screenshot 2021-06-08 at 14 49 43](https://user-images.githubusercontent.com/8905546/121179778-c5770e00-c868-11eb-8af6-22dd873be3a4.png)

### Actual Behaviour
The actual behaviour consist in sp-menu-item only having a slot for icons on the left side of the text.

**Comment by Westbrook** [comment]
Did some initial thinking on this, and wonder how you feel about this approach: 
https://westbrook-menu-item--spectrum-web-components.netlify.app/storybook/index.html?path=/story/menu-item--end-slot
```
        <sp-menu style="width: 150px;" selectable>
            <sp-menu-item>
                Save
                <kbd slot="end">⌘S</kbd>
            </sp-menu-item>
            <sp-menu-item selected>
                Save As...
                <kbd slot="end">⇧⌘S</kbd>
            </sp-menu-item>
            <sp-menu-item disabled>
                Save All
                <kbd slot="end">⌥⌘S</kbd>
            </sp-menu-item>
        </sp-menu>
```
`slot="after"` takes into better account the idea that in RTL context it will no longer be "to the right", while making it clear where the content will land visually in the Menu Item.

Spectrum is revisiting the "item" design right now, so I'll need to confirm this naming aligns with any other changes they've got coming together here, but this feels like it goes in the right direction.

**Comment by stanvladut** [comment]
It looks great!
I totally agree the RTL/LTR part, where we should specify that the slot is at the `end`, or `after`, to properly describe its position. Good point on this.

If everything is all right on the Spectrum's side, then I think we can proceed further with this as it's exactly what we've been looking for.

**Comment by Westbrook** [comment]
I'll convert this to a PR then and confirm the naming with the Spectrum team this afternoon and hopefully have this merged out to you, soon!
