### ISSUE TITLE
active-overlay is defined twice in bundle when importing Overlay

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1537]
### Expected Behaviour
When including full `@spectrum-web-components/bundle/elements.js` and later somewhere using `import {Overlay} from '@spectrum-web-components/overlay';` there should be no error about `active-overlay` being already defined.

### Actual Behaviour
Error is thrown.

#### Steps to Reproduce
1. Install `@spectrum-web-components/bundle`
2. Include `@spectrum-web-components/bundle/elements.js`
3. Use `import {Overlay} from '@spectrum-web-components/overlay';`

#### Platform and Version
* Windows 10
* Chrome 91.0.4472.101
* Webpack 5.38.1
* @spectrum-web-components/bundle 0.22.0

#### Logs taken while reproducing problem
```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "active-overlay" has already been used with this registry
```

*First call stack:*
* `./node_modules/@spectrum-web-components/overlay/active-overlay.js`

*Second call stack:*
* `./node_modules/@spectrum-web-components/overlay/src/overlay.js`
* `./node_modules/@spectrum-web-components/overlay/src/overlay-stack.js`
* `./node_modules/@spectrum-web-components/overlay/active-overlay.js`

---

It works if I take the content of `elements.js` file, use that instead and comment out `import '@spectrum-web-components/overlay/active-overlay.js';`

**Comment by Westbrook** [comment]
As outlined in the documentation for the Bundle package, it is not meant for production development. You've run into one of the reason that this is stated, package managers and bundlers do a poor job on managing deduplication of files when doing so in transitive dependencies. They're already bad enough in direct dependencies 🙈 

On first look, it is peculiar that this webpack build context wouldn't follow standard ES Module realities and deduplicate the request to `./node_modules/@spectrum-web-components/overlay/active-overlay.js` here. It could be that there is something stange in your config that is preventing that.

It is possible that you can assist the bundler in it's work by doing some specific duplication settings possibly found here: https://webpack.js.org/guides/code-splitting/ or by leveraging plugins like https://www.npmjs.com/package/webpack-deduplication-plugin but in general such requirements would be second order side effects of not importing _only_ what you need from the Spectrum Web Components library.

If you absolutely 100% (knowing all the reason not to) want to use the bundle package in your work, it is also possible that you could delay running into issues in this area by importing `Overlay` through the bundle as well.
```
import { Overlay } from '@spectrum-web-components/bundle';
```
_Everything_ that is available in the entire SWC library is available in bundle in some way. Importing JS through the bundle can support NPM and Webpack in not making bas decisions about duplicating code. HOWEVER, it further invests you in an approach to building your application that CAN NOT be optimized for production. In that way, we highly suggest when `@spectrum-web-components/bundle` begins to run into issues like this that you could your self as no longer "prototyping" and start refactoring for longer term work.

For now, I'm going to close this issue as out team does not plan to address work in this area. If you happened to discover something in your config that might be causing this, I'd love to hear about it so we can add information about it to our documentation. OR, if you think of a path by which we could not change the functionality currently found in `bundle` package (which occurs when you take element definitions out of `element.js`) but still opens this use case to consumers of the library, we'd be happy to discuss whether it made sense to adopt that into the library. At that point feel free to reopen or open a new issue with what you've discovered.
