### ISSUE TITLE
Can't import typography.css with Webpack

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1551]
### Expected Behaviour
Including `@spectrum-web-components/styles/typography.css` (from docs) should work in Webpack without errors.

### Actual Behaviour
Webpack fails to compile.

#### Platform and Version
* Webpack 5.38.1
* We're using a Webpack loader that automatically transforms all `*.css` files to `CSSStyleSheet` so we can easily use them in our components.

#### Sample Code that illustrates the problem

Using in app:

```
import spectrumTypographyStyles from '@spectrum-web-components/styles/typography.css';

export class MyComponent extends LitElement
{
	public static styles: CSSResultGroup = [
		spectrumTypographyStyles,
	];
}
```

Using in styles:

```
@import "~@spectrum-web-components/styles/typography.css";
```

#### Logs taken while reproducing problem

In app:

```
Module not found: Error: Package path ./typography.css is not exported from package C:\***\node_modules\@spectrum-web-components\styles (see exports field in C:\***\node
_modules\@spectrum-web-components\styles\package.json)
```

In styles:

```
ERROR in ./Styles/index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[3].use[2]!./node_modules/sass-loader/dist/cjs.js!./Styles/index.scss)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~@spectrum-web-components/styles/typography.css' in 'C:\***\Styles'
```

---

I can see that the `package.json` contains `exports` rule for `./*.css` but that probably does not work with Webpack. I don't know much about `exports` so I'm not sure if the problem is with spectrum or with Webpack.

**Comment by Westbrook** [comment]
Thanks for the report @davidkudera!

Can you confirm whether the in app version you've share can import the `typography.js` file instead? See this example: https://webcomponents.dev/edit/EL5hQTlzbPaYX0JzlYVX/src/index.ts

Another confirmation could be to see whether `@spectrum-web-components/styles/all-large-dark.css` is importable via the patterns you've outlined above? We're a little imprecise with the files we publish here, but `all-large-dark.css` (and similar) are meant to be imported into CSS while `typograpy.css` (and others with matching `*.js` files) are not. These files have been explicitly escaped and processed for use with `lit-html` as outlined in the documentation page for this package. It _could_ be that the processing on those files makes them incompatible with more "normal" CSS workflows and that publishing them only serves to spread confusion. In the case that you actually want to import them as CSS their source is available as follows: https://unpkg.com/browse/@spectrum-css/typography@3.0.2/dist/index-vars.css

If that doesn't work for you, it would be really helpful if I could get a minimal repro in the for the a repo to hunt down what settings is tripping this up. While we can attempt to recreate this in our Webpack Example project, there a numerous misalignments between versions  of loaders, plugins, tools, etc. that could lead to this and it would be great to be able to check this out in your context immediately as opposed to going back and forth with non-matching set ups.

**Comment by davidkudera** [comment]
@Westbrook thanks for your reply and sorry, I probably should have waited before creating another related issue... https://github.com/adobe/spectrum-web-components/issues/1552

Anyway importing the `*.js` files instead of `*.css` files in Lit works as they should. I tried to import `all-large-dark.css` in both our `index.scss` file and in `my-component.ts` but in both cases, I see the same errors as posted above.

For a while, we were using `index-vars.css` from the `@spectrum-css/typography` package and that worked also fine, but later we found about the `.js` "style" files so we switched to them.

**Comment by Westbrook** [comment]
Great! The fact that you can import `all-large-dark.css` in Webpack means this remains an issue, but the fact that you're able to move forward may leave this issue with a pretty low priority. Please let us know if your situation changes or if you are able to share a focused repro to get investigations here started.

**Comment by davidkudera** [comment]
I'm sorry, I meant that I was not able to import `all-large-dark.css`. Importing it resulted in the same errors. (I need to work more on my English...)

But yes, using `*.js` files works perfectly fine for us.

If you're interested I prepared a small repro project with a really simple Webpack config. I used just standard css & js compilation - https://github.com/davidkudera/webpack-spectrum-typography-repro

**Comment by Westbrook** [comment]
Awesome. This will definitely help clarify what's going on when we're able to get deeper into this!

**Comment by Westbrook** [comment]
@davidkudera I've updated https://webcomponents.dev/edit/EL5hQTlzbPaYX0JzlYVX/src/index.ts with an `alpha` channel release of `@spectrum-web-components/styles` that _might_ correct the issues you're seeing here.

I've also tested it in your repo (thanks again for that), and it seems to build with no issues, now: https://github.com/davidkudera/webpack-spectrum-typography-repro/pull/1

**Comment by davidkudera** [comment]
@Westbrook That's awesome, I tried it on the project I'm working on and it works just as expected (after I included `@spectrum-web-components/styles/all-medium-light.css` too).

Thank you 🍻

**Comment by davidkudera** [comment]
@Westbrook Oh, and to answer your question in the PR - I tried all examples from Spectrum CSS typography pages and they all work. So it looks good to me.
