### ISSUE TITLE
Typescript "cannot find module" errors in IDE

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1555]
### Expected Behaviour
After running all three steps from "Getting Started", there should be no errors in IDEs.

### Actual Behaviour
WebStorm is highlighting all `@spectrum-web-components/*` imports. I tried VS Code with the same result.

### Reproduce Scenario (including but not limited to)
Local development on Windows with WSL2

### Steps to Reproduce
```bash
git clone https://github.com/adobe/spectrum-web-components.git
cd spectrum-web-components
yarn
```

And open for example `action-button/src/ActionButton.ts`.

### Platform and Version
* Windows 10 (using WSL2)
* WebStorm 2021.1.2
* VS Code 1.57.1

### Logs taken while reproducing problem
Taken from `action-button/src/ActionButton.ts`:

![image](https://user-images.githubusercontent.com/1174072/122670195-fd634700-d1c0-11eb-9c71-b46bf0689802.png)

```
TS2307: Cannot find module '@spectrum-web-components/base' or its corresponding type declarations.
```

---

The build commands (including `build:ts`) work fine and there are no errors. So it seems that only the Typescript language server is confused. Maybe all of this is related to the fact that I'm running `yarn` commands in WSL because of the other issue I'm having - #1554.

**Comment by Westbrook** [comment]
@davidkudera can you revisit this with #1554 fixed? I think it's just the location/ownership of the created TS assets that you were causing this issue for you.

**Comment by davidkudera** [comment]
@Westbrook that's exactly my thoughts. WebStorm is now happy and both issues are gone, thank you 🍻
