### ISSUE TITLE
[Overlay] Close Active-Overlay on right mouse click or contextmenu event

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1559]
### Expected Behaviour
When an active overlay is open the user can (left) click outside the popover content to close it while a right mouse click (or contextmenu event) would not close the overlay.

### Actual Behaviour
Right mouse click outside popover content doesn't trigger the active overlay to close.

#### Platform and Version
MacOS, Chrome V91

**Comment by Westbrook** [comment]
Steps:
1. User activates an overlay.
2. User right clicks somewhere.
3. You expect that to close the overlay?

Can you share some expanded use cases here? I'm not sure that's a _default_ functionality that we want to add. It may be that this needs to be a configuration option, or we need to outline how to do this easily in user space, but I can't quite tell from the information currently available.

**Comment by spdev3000** [comment]
Yes, our use case is a @contextmenu event triggers a contextmenu to render via an VirtualTrigger:
```
    const fragment = document.createDocumentFragment()
    fragment.appendChild(contextMenuContent)

    openOverlay(event.target as HTMLElement, 'modal', contextMenuContent, {
      receivesFocus: 'auto',
      virtualTrigger: new VirtualTrigger(event.clientX, event.clientY),
    })
```
If we then right click outside the menu this overlay should be closed and another menu should be triggered.
Yes, maybe there is some configuration option that enables closing also via right mouse click or @contextmenu event from the active-overlay.

**Comment by Westbrook** [comment]
Looking into this a bit closer, and want some information on step 3 above. Is closing an Overlay enough? As I build up some test contexts to develop against, it seems like the desire in the context of a `contextmenu` + `VirtualTrigger` would be to not just _close_ the Overlay but also to throw a subsequent context menu. See this experience when you right click on the right side of this comment to open a context menu and then while it is open you click on the left side of the comment to open a _new_ context menu in a that location closing the first.

Closing on right click, and only when it's not in the Overlay content, is relatively straight forward, but there's a good bit more infrastructure to get subsequent context menus to open...
