### ISSUE TITLE
grow attribute on sp-textfield multiline has strange rendering

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#1568]
### Expected Behaviour
A single text field should be rendered

### Actual Behaviour
2 textfields are rendered.

### Reproduce Scenario (including but not limited to)
Run storybook and look at the textarea story

#### Platform and Version
All platforms - component version 0.8.9

**Comment by Westbrook** [comment]
Oh, fun! Looks like we missed one of the Spectrum token updates there...

We'll add a VRT to watch for this in the future, too!

**Comment by jnurthen** [comment]
Unless I'm missing something 
`:host([grows]) #input` just needs changing to `:host([grows]) .input {` as you are using `class="input"` not `id="input"` on the textarea.
I'd create a PR but a test is failing on the picker on FF for some reason (nothing to do with this PR though)
