### ISSUE TITLE
[Picker] Icon only Picker

### ISSUE THREAD

**Issue by stanvladut** [adobe/spectrum-web-components#1569]
### Expected Behaviour
We would need an icon-only version of the current `Picker` implementation. The `Picker` would have icon-only items with assigned values and each time an icon is selected from the menu, it should propagade to the trigger (current selection).

### Actual Behaviour
Right now only items with text are propagated to the `Picker's` trigger when selected.

![Screenshot 2021-06-23 at 15 30 57](https://user-images.githubusercontent.com/8905546/123096688-06118280-d438-11eb-86ed-75f0fcdf0ae4.png)

_* screenshot extracted from Apple's Keynote app_

**Comment by Westbrook** [comment]
Prototype: https://webcomponents.dev/edit/RItZJb9EtTseDHsNRGd4/src/index.stories.js however, we should look at a more thorough support for the Spectrum contribution version of this design, which would likely include an updated approach to `public get itemText()` as well as an `icon-only` sort of variant/attribute to alter the visual delivery here.

**Comment by Westbrook** [comment]
Further prototyping on this: https://westbrook-icon-picker--spectrum-web-components.netlify.app/storybook/index.html?path=/story/picker--icons-only

**Comment by stanvladut** [comment]
It actually looks pretty good! 👍 
One quick question though: for the `icon-only` version, we would have the option of not adding text at all in the dropdown, right? I assume yes, but wanted to double check.

**Comment by Westbrook** [comment]
Yep. I've extended the Icons Only story to show a Control for managing the presence of this content.

Couple of things this bring up:
- when no slotted content is available, should the Picker adopt `label` and/or `aria-label` content from the Menu Item when building the accessibility tree entry of the Picker "button"?
- could documentation to include accessible content in the Icon element be enough?
- the inheritance tree gives `div#label` a `hidden` attribute when no slotted label text is present causing the horizontal layout to collapse.
  - do we need to inherit functionality here differently?
  - can we get away with just added some extra CSS? If so, we should share a solution here up to the Spectrum CSS team.
