### ISSUE TITLE
Investigating tying `sp-dropdown` and `sp-action-menu` into overlay system

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#157]
### Expected Behaviour
Content should be available on top of everything!

### Actual Behaviour
Some content can flow over the dropdown/action-menu content.

### Reproduce Scenario (including but not limited to)
Put content after the dropdown or action-menu with a very high z-index...

### Possibilities
This may be manageable by adding a fallback to the `overlay` system that hoists overlay content to the `<body/>` when and `overlay-root` is not available. Further research should go into whether `popover`, which powers these elements, should deliver this feature by default.

**Comment by Westbrook** [comment]
Right now, the element API for this looks like:
```
            <sp-dropdown>
                Select a Country with a very long label, too long in fact
                <sp-menu slot="options" role="listbox">
                    <sp-menu-item>
                        Deselect
                    </sp-menu-item>
                    <sp-menu-item>
                        Select Inverse
                    </sp-menu-item>
                    <sp-menu-item>
                        Feather...
                    </sp-menu-item>
                    <sp-menu-item>
                        Select and Mask...
                    </sp-menu-item>
                    <sp-menu-divider></sp-menu-divider>
                    <sp-menu-item>
                        Save Selection
                    </sp-menu-item>
                    <sp-menu-item disabled>
                        Make Work Path
                    </sp-menu-item>
                </sp-menu>
            </sp-dropdown>
```
In that way, we're not requiring a `items` property at the `<sp-dropdown>` level, because we are slotting the `<sp-menu>` content into that part of the interface. Working with `overlay-trigger` prevents the ability for this to continue as it does not support forwarding content from inside of a slot to `overlay-root` element. 

## Options:

1. Extend `overlay-trigger` to flatten slotted content when forwarding content to `overlay-root`. In this was we'd need to not just grad the root element of the overlay and pass it along, but we'd need to walk the entire tree looking for `<slot>` elements, then query their `assignedNodes()` (note the newest version of Safari has some issues with `assignedElements()`) and send those elements into the overlay recursively until the entire overlay is populated. I think where this creates the most issue is when you close the overlay, as you will need to have noted what content came from where all along the process of opening the overlay so that you can replace it all as part of the `close` process. This could be really interesting and expressive, but likely fairly buggy and possibly really slow. It also opens us to extended issues around CSS Custom Property application that are featured https://github.com/adobe/spectrum-web-components/issues/151#issuecomment-523295170.

2. Use the elements API to populate data. This is more like what we see in the native `<select>` element. Whether through a simple `slotchange` listener, but likely via the more dynamic `MutationObserver()`, we could use the HTML elements to populate a data object that could be used to create an alternate, flattened, DOM structure to represent the desired overlay UI. The main side effects of this change are that it invalidates almost all of the internals of `<sp-dropdown>` as implemented today as the functionality would need to be applied to the alternate DOM structure. Hopefully that wouldn't be too much work, but it's unclear to me the best way to keep reference to the overlay, and manage passing focus into it. This would be my suggestion and is something I've done some early research around via https://github.com/adobe/spectrum-web-components/tree/westbrook/157/dropdown-overlay

3. Using an `items` property that we expect to be set by the implementor would allow for creating the DOM to represent the overlay dynamically inside of the `<sp-dropdown>` element relatively easy. This is essentially option 2 without the slot interaction. It's the easiest of the three options, and as such can likely be surfaced as part of option 2, so we have more flexibility with this component going forward.

**Comment by cuberoot** [comment]
We can probably learn a bit from this project: https://github.com/adobe/react-webcomponent

1. There is [some code in the above project](https://github.com/adobe/react-webcomponent/blob/master/lib/dom-model/DOMNode.js) that steals DOM nodes and then replaces them later. The trick uses is to insert a placeholder comment node where you steal from so you can swap it for the stolen node later. This is fairly robust, simple and efficient.
2. The above project also has [code for extracting a data model from DOM node structure](https://github.com/adobe/react-webcomponent/blob/master/lib/dom-model/DOMNode.js).
3. This is easier, but isn't very web-component-esque.

Anyway, that's some prior art to chew on...

**Comment by cuberoot** [comment]
One thing to note about approach 1 above is that React components do not like being moved around in the DOM. So, that approach would not work well with React.

**Comment by benjamind** [comment]
@Westbrook can you elaborate more on option 1 here? I'm not sure I quite understand the need to do slot flattening.

Surely if the slotted content in the dropdown element (i.e. the sp-menu) is attached as content payload to the `sp-overlay:open` event then there's no need to do any additional walking of the dom to gather slotted nodes? You're just taking the top level content that was slotted into the dropdown.
