### ISSUE TITLE
[Slider] Add editable input for Slider component

### ISSUE THREAD

**Issue by stanvladut** [adobe/spectrum-web-components#1572]
### Expected Behaviour
We would like to have an editable input for the current `Slider` implementation that would not only reflect the current `Slider's` value, but would also allow us to edit the current value.

### Actual Behaviour
The current `Slider` implementation only allows changing the value via dragging the bullet on in horizontal axis.

![Screenshot 2021-06-23 at 17 04 51](https://user-images.githubusercontent.com/8905546/123111833-e4b79300-d445-11eb-9cab-9d9acd574bc9.png)

**Comment by Westbrook** [comment]
A possible implementation here could build from https://webcomponents.dev/edit/cKxlTH1P65jtulpARr7j/src/index.ts.

Points of concern/question:
- value is currently calculated in reference to the _entire_ width of the element, not the width of the track
- this adds a _second_ tab stop, it is possible that we'd want to remove one, and if so how would a keyboard navigator get to both (if needed)
- there isn't currently a label associated with the Number Field, can it _just_ be the main `Slider Label` text, or is something more needed?
- should the recently added `formatOptions` property be passed down to the Number Field?
- do we need to manage `hide-stepper` transitively through the `sp-slider` element, or can we assume that it is always on?
- likely we need to add `--spectrum-stepper-width: 48px;` to accurately deliver the designs, but what do we expect here when the number is larger than that space?
- this version theorizes an `sp-slider-editable` element, this _could_ be a good way to prevent standard slider users from paying the cost of the Number Field element all the time. If this is added to `sp-slider` what would we want to gate the loading/inclusion of `sp-number-field` on?

**Comment by Westbrook** [comment]
Here's a nicer demo: https://westbrook-slider-editable--spectrum-web-components.netlify.app/storybook/index.html?path=/story/slider--editable

**Comment by stanvladut** [comment]
Wow, it is amazing to see the progress on this! 💯 
Regarding the points of concern, I do have some answers for some of them, but I want to double check with the Design and Product team on both known and unknown items. I will get back as soon as I have the answers.

**Comment by stanvladut** [comment]
Regarding the points of concern:

1. I'm not really sure how the navigation should be done having in mind that both the slider and the input should be able to be editable using keyboard. But assuming a second `tab` stop is not feasible and the Number Field is enabled, I would prioritize the input for focus instead of slider; I will double check on that.
2. There's no need for having a separate label associated with the Number Field alone. We would want only one label per the entire Slider (Slider + Input);
3. Yes, I think we sould pass the `formatOptions` to the Number Field to assure consistency with the other fields in the app.
4. It would be great if we can have the stepper in the Number Field displayed only when it is focused and not having it always on.
5. I would not make these properties customizable in the first place. I'm not sure whether or not we should allow users to customize the width of the Number Field at all or, at least, not with absolute values. If we are to allow custom values, the design team suggested to have a maximum width value set for the Number Field of 50%.
6. We are totally fine of having separate components withing the Slider package to not make the standard users pay the cost of the Number Field too, as you suggested. However, if we would want to have all the logic under the same umbrela, I would make it dependend on a property like `editable`, `numberField` or `hasInput`.
7. We don't want to associate an input with a `range` slider, so let's make `range` and `editable` incompatible. If a slider is `range`, it should not have any Number Fields at that point.

**Comment by Westbrook** [comment]
4. Let's track the design conversation around this. It doesn't seem like Spectrum is going to go with a _hover only_ approach on the stand along Number Field, so I'm not sure we can do that here either.
5. The native width is pretty small, I think we need to clarify access to this. Maxing it out at 50% makes sense!
6. It's working now with lazy loading of the Number Field code only when requested, but I do want to do a quick test of slotting the element instead. That way it's more clear when you load the supporting element definition. 

Hopefully with these decisions/ideas we can have a PR ready for this work sometime this coming week.

**Comment by Westbrook** [comment]
#1670 is coming along! Please check it out. I'm particularly happy to see very little perf effect in this addition: https://github.com/adobe/spectrum-web-components/pull/1670#user-content-slider

@stanvladut could you take [the preview therein](https://slider-editable--spectrum-web-components.netlify.app/storybook/?path=/story/slider--editable) for a spin and let me know if this seems to cover the use cases you have right now.

@adixon-adobe this is positioning the choice to use `editable` behind a dynamic import. Do you see this as another good place to leverage an optional "sync" import?

I've got some documentation and tests to write and then hopefully this is good to go!

**Comment by stanvladut** [comment]
Sorry for delay!

4. Sure, let's see what Spectrum thinks about it. However, if the _hover only_ functionality is not compliant, then let's consider it always on and customizable via a `hide-stepper` property as you proposed.

I will take a look as soon as possible.
