### ISSUE TITLE
Missing scroll bar in dialog with long content until viewport is resized

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1577]
### Expected Behaviour
There should be a scroll bar in a dialog when content is too long after opening it.

### Actual Behaviour
After opening a dialog with long content, there is no scroll bar present. Dialog content is scrollable only after the viewport is resized.

### Reproduce Scenario (including but not limited to)
Opening dialog

#### Platform and Version
* Windows 10
* Chrome 91.0.4472.114

#### Sample Code that illustrates the problem
I prepared an example - https://webcomponents.dev/edit/CJRAMGrFhxa7st7lHy4U/src/index.ts

**Comment by Westbrook** [comment]
Here's our current working approach to this: https://westbrook-dialog-scroll-management--spectrum-web-components.netlify.app/storybook/index.html?path=/story/dialog-wrapped--long-content Going in the PR shortly.
