### ISSUE TITLE
Add "part" attribute to "sp-theme" in "active-overlay"

### ISSUE THREAD

**Issue by ejez** [adobe/spectrum-web-components#1586]
The principle way for css customization is through the css custom properties provided by "sp-theme". When we create an "sp-theme" component, we can control it and modify the css custom properties. However when it is created automatically, for example through the overlay component, we don't have control on its css.

Adding a part attribute will allow us to control the css:
https://github.com/adobe/spectrum-web-components/blob/947e81061fb9db8a3f7cb6603cf0ff9b4107f4ae/packages/overlay/src/ActiveOverlay.ts#L479
```diff
    public renderTheme(content: TemplateResult): TemplateResult {
        const { color, scale, lang } = this.theme;
        return html`
            <sp-theme
                color=${ifDefined(color)}
                scale=${ifDefined(scale)}
                lang=${ifDefined(lang)}
+               part="theme"
            >
                ${content}
            </sp-theme>
        `;
    }
```

Now we can use something like:
```css
active-overlay::part(theme) {
  --spectrum-global-font-family-base: "myFont";
}
```

The issues of losing styles due to reparenting performed by the overlay can be mitigated in a much easier way with the above rather than the tedious way of adding inline styles to each individual sub-component:
```html
      <sp-picker
        id="theme-color-picker"
        quiet
        value=${DEFAULT_COLOR}
        @change=${handleChange}
      >
        <sp-menu-item style="font-family: myFont" value="lightest">${tc('lightest')}</sp-menu-item>
        <sp-menu-item style="font-family: myFont" value="light">${tc('light')}</sp-menu-item>
        <sp-menu-item style="font-family: myFont" value="dark">${tc('dark')}</sp-menu-item>
        <sp-menu-item style="font-family: myFont" value="darkest">${tc('darkest')}</sp-menu-item>
      </sp-picker>
```

See:

https://developer.mozilla.org/en-US/docs/Web/CSS/::part
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-part

(The developer should be aware of the [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/::part#browser_compatibility))

**Comment by Westbrook** [comment]
Oooh, I rather like this. Having an HTML/CSS first corollary to #1496 will be quite nice.

Would love to accept a PR for this. What were the issues you had previously signing the CLA?
