### ISSUE TITLE
Missing body slot in card component

### ISSUE THREAD

**Issue by ejez** [adobe/spectrum-web-components#1587]
As per https://spectrum.adobe.com/page/cards/#Anatomy , the card component might have a body section.
![Screenshot 2021-06-27 at 19-20-20 Spectrum, Adobe’s design system](https://user-images.githubusercontent.com/48388358/123552165-8d832c80-d77d-11eb-8682-1bf764ab9521.png)

Is it possible to add a slot for it:
https://github.com/adobe/spectrum-web-components/blob/947e81061fb9db8a3f7cb6603cf0ff9b4107f4ae/packages/card/src/Card.ts#L248
```diff
                ${this.variant !== 'gallery'
                    ? html`
                          <div class="content">
                              ${this.renderSubtitleAndDescription}
                          </div>
                      `
                    : html``}
+                <slot name="body"></slot>
            </div>
            ${this.variant === 'standard'
                ? html`
                      <slot name="footer"></slot>
                  `
                : html``}
```

**Comment by Westbrook** [comment]
Generally, we try not to ship things on the delivery of which we do not have styling direction . In this way, being the `body` content is not currently included in [Spectrum CSS](https://opensource.adobe.com/spectrum-css/card.html) I'm not sure that we'll be shipping this in the near future. 

There are active conversations at the Spectrum level around updating the Card content delivery guidelines in a way that may open a path towards offering something like this in the future. In the interim, you might find success in registering a local extension of the element that features this interface.

**Comment by ejez** [comment]
Thanks for the explanation!
