### ISSUE TITLE
Website has no favicon

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1601]
### Expected Behaviour
The website should have a favicon

### Actual Behaviour
There is no favicon on the website

### Reproduce Scenario (including but not limited to)
Looking at the docs

#### Steps to Reproduce
1. Go to https://opensource.adobe.com/spectrum-web-components/
2. Look at the tab

#### Platform and Version
Windows 10
Chrome, Edge, Firefox...

#### Sample Code that illustrates the problem
Not code, but here is a screenshot comparing some other adobe projects

![image](https://user-images.githubusercontent.com/1174072/124018626-5795b080-d9e8-11eb-9267-704d5bced748.png)

**Comment by Westbrook** [comment]
fixed in https://github.com/adobe/spectrum-web-components/commit/1e37070a4db68ed844f92c93bf0b2f34061a85cf
