### ISSUE TITLE
[Split view] primarySize can't be updated

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1610]
### Expected Behaviour
Changing the `primary-size` attribute in `<sp-split-view>` should update the size of primary and secondary views.

### Actual Behaviour
Changing it does nothing. I tried numbers, percentages, and pixels too.

### Reproduce Scenario (including but not limited to)
Using the Split view component with provided size

#### Steps to Reproduce
Here is an example with a toggle button that is changing the value from `20%` to `80%` and back: https://webcomponents.dev/edit/13P6vLAg4Fb6SGvVYtIm/src/index.ts

#### Platform and Version
* Spectrum web components ^0.22.2
* Edge 91.0.864.64

**Comment by Westbrook** [comment]
First thought... updated:
```
    protected firstUpdated(changed: PropertyValues): void {
        super.firstUpdated(changed);
        this.checkResize();
    }

    protected updated(changed: PropertyValues): void {
        super.updated(changed);
        if (
            changed.has('splitterPos') &&
            this.splitterPos !== undefined &&
            this.enoughChildren
        ) {
            this.firstPaneSize = `${Math.round(this.splitterPos)}px`;
        }
    }
```
to be
```
    protected updated(changed: PropertyValues): void {
        super.updated(changed);
        if (changed.has('primarySize') {
             this.checkResize();
        }
        if (
            changed.has('splitterPos') &&
            this.splitterPos !== undefined &&
            this.enoughChildren
        ) {
            this.firstPaneSize = `${Math.round(this.splitterPos)}px`;
        }
    }
```
And you'd be good to go...in that case that you're interested in submitting a PR. @spdev3000 does that sound right-ish?

Otherwise, we've got a number of people of holiday, so it'll be another couple of weeks before we'd be able to actively take a look at this.

**Comment by davidkudera** [comment]
@Westbrook I was going to try to create a PR and you just made it much easier for me. Thank you
