### ISSUE TITLE
sp-tabs element doesn't have size in layout.

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1612]
### Expected Behaviour
You should be able to style `sp-tabs` with margin/padding and have it affect the layout.

### Actual Behaviour
It looks like something broke, and now `sp-tabs` doesn't affect the layout of its underlying tabs. You can see this pretty easily in the docs by inspecting the `sp-tabs` examples in the debugger. It doesn't show as having the width/height of its children, and if you add margin/padding, it also doesn't affect its children.

**Comment by adixon-adobe** [comment]
Note: this was working in @spectrum-web-components/tabs version 0.5.5

**Comment by adixon-adobe** [comment]
Also, it's pretty easy to just override the `display` property to fix, but that doesn't seem like it should be necessary.

**Comment by Westbrook** [comment]
Nice catch! Looks like it came with an uncaught regression for elements that are sized as well: https://westbrook-tabs--spectrum-web-components.netlify.app/storybook/index.html?path=/story/tabs--vertical-sized
