### ISSUE TITLE
Minimal demo not working as expected

### ISSUE THREAD

**Issue by martinerko** [adobe/spectrum-web-components#1633]
### Expected Behaviour
nicely styled components

### Actual Behaviour
styling does not work

#### Sample Code that illustrates the problem
https://codesandbox.io/s/relaxed-cookies-c636m?file=/src/index.js

**Comment by Westbrook** [comment]
Hi @martinerko thanks for your interest in the library! It looks like you're just missing an import here. I've forked your repro: https://codesandbox.io/s/beautiful-ishizaka-1sysi?file=/src/index.js

The `<sp-theme>` element needs both color stops `import "@spectrum-web-components/theme/theme-darkest.js";` AND sizing information `import "@spectrum-web-components/theme/scale-medium.js";` to display the components correctly.

You can see this _roughly_ in the docs under the "Advanced usage" section on this page: https://opensource.adobe.com/spectrum-web-components/components/theme We're looking to get some more intro content between "hacking" https://opensource.adobe.com/spectrum-web-components/getting-started and "advanced" soon, and we'll make sure to include this sort of minimal demo context for clarity.

**Comment by martinerko** [comment]
Hi @Westbrook , thanks for quick response. I got confused by "Quick start" section on the same page.
