### ISSUE TITLE
Issues when using a CDN is generating errors

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#1640]
### Expected Behaviour
Spectrum components work by importing the Spectrum library through a CDN 

### Actual Behaviour
Error is generated in the browser that prevents the library from working. The library did not load and two errors appeared in the web developer console. 

### Reproduce Scenario (including but not limited to)
Create an HTML page locally with the following code and then load that page in Firefox using the file:// protocol

#### Steps to Reproduce
1. create page with contents below
2. open page in browser before Firefox Developer 91.0b6
3. open console to see error messages

#### Platform and Version
OSX 10.15.7 and probably Windows and all browsers

#### Sample Code that illustrates the problem
Included in example

#### Logs taken while reproducing problem
Shown below. 

**Update**:   
Well the errors now appear to be resolved in the latest Firefox and do not show. So I did not have a chance to save the error messages. I'll post them if they appear again. 

They mentioned CORS related issue and they mentioned a mime type not compatible issue. 
I was able to save the page that it opened when I clicked on the error in the console:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

I have a suggestion though in case this appears again: 

Is there a way to get the folder or zip with Spectrum Component library so that a user can have it locally on their computer or server in case the CDN goes down? It would be rather fragile to have a page break if the user is not online. Without this offline single page applications will also break. 

Note: I do not want to use the command line service to retrieve the library for the same reason as in the present issue. If the CDN is down or an upgrade changes things then the page breaks.

**Comment by Westbrook** [comment]
The CDNs that we can suggest today are all publicly accessible with their own SLA and uptime rules, and any guarantees, etc. would need to be reviewed on their end. While we do not currently offer an official CDN for the SWC library, it's certainly possible that we do some at some point in the future and we'd want to give fail overs the level of respect that'd require at that time.

Both [JSPM](https://jspm.org/docs/cdn#urls) and [Skypack](https://docs.skypack.dev/skypack-cdn/api-reference/pinned-urls-optimized) (popular CDNs) outline the benefits of pointing to fixed versions of packages available therein. However, to ensure that out "Getting started" always has the most up-to-date packages we do not do that. As such, there is some time across updates where the CDN might not have a version fully built, which can lead to errors. If you're using CDN URLs in your project, you should 100% follow the instructions linked above to have the most stable access to SWC and all of your dependencies possible. This will also prevent your adopting possibly breaking changes before you are ready to do so.

As for alternate options, as an open source project, you are welcome to download our library from Github, build and store the distributed assets as you'd like. In that way you can leverage the tip of the development path from `main` or a slice of the project at any release point throughout our history: https://github.com/adobe/spectrum-web-components/tags. We do not, however, have any plans of offerings ZIP files of the built project as there are a number of issues that can arise from this that we'd not be able to fully support.

I'm quite sorry if that's not what you were looking to hear on this subject, but I'm going to close this issue as I don't see us being able to take on any work to support this workflow at this time. We're very happy that you're finding some success working with out library and if you find some other path via which we might be able to support you in this way, please feel free to reopen this issue.
