### ISSUE TITLE
action-menu & split-button should have sync import options like picker

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1642]
### Expected Behaviour
Following up on the resolution to #801 Clients should have the option to do a sync import of action-menu & split-button, so that the menus don't open with a delay because of the async overlay import.

### Actual Behaviour
This is only available in picker now.

**Comment by charlessuh** [comment]
What about `<sp-action-menu>`?

**Comment by Westbrook** [comment]
https://github.com/adobe/spectrum-web-components/tree/main/packages/action-menu/sync
