### ISSUE TITLE
Add Badge pattern

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1643]
Currently, there is no badge component.

Spectrum: https://spectrum.adobe.com/page/badge/
Spectrum CSS: https://opensource.adobe.com/spectrum-css/label.html

---

I'm not sure if the Spectrum CSS Label is compatible with the Spectrum Badge or if it even matters... I can see two possible ways of how to implement this:

1. Wait with this issue until https://github.com/adobe/spectrum-css/issues/598 is done
2. Implement it based on the current Label component and change it later to use the new Badge component

The name should be (I think) in both cases `<sp-badge>`. I could also probably help by preparing a PR with an initial implementation.

**Comment by Westbrook** [comment]
Agreed, this will be a good add. We're working through the a pending release of Spectrum CSS output, and then if you interested in taking a swing at this, we'd love to see it. If not, I could see someone getting into it in the next couple of months. Thoughts?

**Comment by davidkudera** [comment]
@Westbrook Cool, I'll send a PR. Is there some issue in Spectrum CSS I can subscribe to, to be notified when your work is done? Or is the issue I send above?

**Comment by Westbrook** [comment]
I believe that is happening in https://github.com/adobe/spectrum-css/pull/1138 but I’ll double check with their team!

**Comment by hunterloftis** [comment]
For visibility - we have a branch with a first draft here: https://hunterloftis-add-badge--spectrum-web-components.netlify.app/storybook/?path=/story/badge--default

The Badge design spec is going through some revisions right now; I'll integrate any changes into the above component and open a PR once the spec is stable.

**Comment by castastrophe** [comment]
I was hoping to follow-up on this component - it's used in the Account Menu designs and I would rather pull it from SWC than create a UEC element for it.

**Comment by hunterloftis** [comment]
@castastrophe sorry for the delay getting back to you; I'm catching up on GH notifications today.

As long as @westbrook and @najikahalsema are 👍 , I can update this branch and ship a web component that matches the current CSS implementation.

The spec question is basically: should (can) a badge be interactive? Or is it purely informational? The hover-state visual cue suggests interactivity, and the spec mentions interactivity, but it's not currently an accessibly interactive component (the CSS implementation is a [span](https://opensource.adobe.com/spectrum-css/badge.html)).

Along those same lines: if a badge can be interactive, is it sufficiently different from an action button?

action-button:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/364501/168344519-a293ea97-33c5-4031-94b6-6f3c875fcecf.png">

badge:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/364501/168344675-709cbfdf-d91e-4cd2-b7fc-9ddc371a4f2a.png">

If a badge _can_ be interactive, then I'd like to add an `interactive` attr that wraps them in `<button>`s with `cursor: pointer`. But I could ship the current version in the short term and change the implementation later if necessary.

@castastrophe, how is badge used in the designs you're working on? Are they interactive, or are they informational?

**Comment by castastrophe** [comment]
@hunterloftis They are informational at the moment though I imagine that could evolve over time.

<img width="520" alt="Screen Shot 2022-05-17 at 10 33 47 AM" src="https://user-images.githubusercontent.com/1840295/168837015-c2ff3fba-ff8e-4b04-9974-81e788448f63.png">

```
Admin badge

The admin badge is visible to both contract owners (primary admins) or secondary admins, and serves as a reminder of their special role.
```

**Comment by Westbrook** [comment]
This shipped in https://github.com/adobe/spectrum-web-components/pull/2305, thanks @hunterloftis!
