### ISSUE TITLE
Slider: label-visibility doesn't work

### ISSUE THREAD

**Issue by mahdiridho** [adobe/spectrum-web-components#1695]
How do I can hide the slider value?

### Expected Behaviour
`label-visibility="text"` hides the value

### Actual Behaviour
`label-visibility="text"` doesn't hide the value

#### Sample Code that illustrates the problem
```
<sp-slider label="slider label" label-visibility="text" step=1 min="0" max="10"></sp-slider>
<sp-slider label="slider label" labelVisibility="text" step=1 min="0" max="10"></sp-slider>
```

**Comment by Westbrook** [comment]
Hi, @mahdiridho, thanks for reaching out! Our documentation site runs against `main` not against production, see #1305. We have this featured schedule for release later this week, sorry for the delay.
