### ISSUE TITLE
Visual focus indicator disappears in Color Areas

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1698]
### Expected Behaviour
Whenever a handle has focus, it is rendered magnified to visually indicate focus.

### Actual Behaviour
Keyboard interactions work as expected. Mouse interactions grant focus, but disable visual magnification.

### Reproduce Scenario (including but not limited to)
This is best demonstrated in https://github.com/adobe/spectrum-web-components/pull/1696, where keyboard behavior is fixed:
https://color-tab-index--spectrum-web-components.netlify.app/storybook/?path=/story/color-area--joint

#### Steps to Reproduce
1. use the mouse to drag a color handle
2. verify that the handle has focus by pressing keyboard arrows and seeing the handle move around the color area
3. see that despite being focused, the handle has no visual focus indicator

https://user-images.githubusercontent.com/364501/129067088-97ee114f-c833-44d8-99d5-ca5ce163578f.mov

#### Platform and Version
Commit 1321f16c086887156f8fe1f27a20a5e11ff84415
Chrome Version 92.0.4515.131 (Official Build) (arm64)
OSX 11.4

#### Other notes
Other Spectrum components exhibit similar behavior, like [the slider](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--default), which decouples focus visuals/behavior unlike [this w3 example](https://www.w3.org/TR/wai-aria-practices-1.2/examples/slider/slider-1.html). Is this intentional or should it also be considered a bug?

**Comment by Westbrook** [comment]
There's an important distinction between these various experiences you are seeing here and that is the difference between `:focus` and `:focus-visible`: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible. In all of these cases we are attempting to synthesize the experience you will see in the `:focus-visible only` _button_ when visiting the above page in Chrome.

When doing so, you'll notice that the dashed border becomes available when using `Tab` to focus the element, but not when clicking the element (the main difference between `:focus` and `:focus-visible`). When clicking the element to apply focus, any subsequent keyboard interactions would then trigger the `:focus-visible` display. 

In this way, while tabbing into the various elements listed above should trigger the `:focus-visible` display, when moving the Color Handle with a pointing device the handle should not be enlarged while the pointing device is "up", even after having enlarged while the pointer was "down". After the pointer has moved to the "up" position, if the focus has not moved from the Color element then subsequent keyboard interactions should trigger the `:focus-visible` display enlarging the Color Handle.

**Comment by hunterloftis** [comment]
Thanks, that clarification helps - let me make sure I grok the behavior we're targeting:

1. At 0:05, the control is behaving correctly, because so far it has only been focused via the mouse.
2. At 0:18, the control is behaving incorrectly, because it was first focused by the keyboard and then interacted with via the mouse, which should not have made it lose its visible focus.

Similarly to how in the [mdn example](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible), tabbing into the `:focus-visible only` button shows the dashed border, and that dashed border doesn't disappear from subsequent clicks on the same element.

**Comment by Westbrook** [comment]
It can get complicated, and is something we would want to confirm with the design team, as well as some product groups that have "personal opinions" in this area, but it seems that:

1. At 0:03 when the pointer goes up, the handle gets small, correctly.
2. At 0:05 when the `ArrowLeft` key is pressed, the handle _should_ get large, this is currently not happening.
3. Yes, at 0:18, the control is behaving incorrectly, because it was first focused by the keyboard and then interacted with via the mouse, which should not have removed its visible focus.

#3 is likely the trickiest part of that as it is tracking over multiple types of interactions, and while we _might_ be able to reference browser state for this context, we may need to carry our own to ensure that is delivered correctly.
