### ISSUE TITLE
sp-textfield[multiline] always features resize handles

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1700]
### Expected Behaviour
There should be an API for directly preventing resize handles on the `<textarea>` internal to the `sp-textfield[multiline]` element.

### Actual Behaviour
You need to work around the current API with something like: https://webcomponents.dev/edit/TMoZiDE5EnHi2OLfoeBA/

### Possible solutions...
- Can we add `resize: inherit` to that element so that users can place `resize: none` on the `sp-textfield` like a normal `textarea`?
- Should we surface an attribute `<sp-textfield multiline resize="none">`?
- Extend an SWC specific CSS Custom Property `--spectrum-textarea-resize` or similar?

#### Steps to Reproduce
`<sp-textfield multiline>`... see resize handle in bottom right corner:
![image](https://user-images.githubusercontent.com/1156657/129100519-16a89afb-5a95-4606-bb55-b4c8dda9fc6e.png)

#### Platform and Version
All the things.

**Comment by hunterloftis** [comment]
> Can we add resize: inherit to that element so that users can place resize: none on the sp-textfield like a normal textarea

I like this idea, but since [resize is not an inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/resize#formal_definition), I don't think it will work in practice.

> Should we surface an attribute <sp-textfield multiline resize="none">?

We could do this, but...

> Extend an SWC specific CSS Custom Property --spectrum-textarea-resize or similar?

I think this is the cleanest option. It's more powerful and flexible than adding an attribute, and it leverages the browser's CSS engine instead of reimplementing stuff in JS. @Westbrook thoughts?

**Comment by Westbrook** [comment]
If `inherit` doesn't actually work, then I agree with your assessment here.

Can you confirm whether using the following styles for empowering the `inherit` approach doesn't work in this context first?
```
:host([multiline]) {
   resize: both;
}

textarea {
  resize: inherit;
}
```

**Comment by hunterloftis** [comment]
@Westbrook thanks for having me try that - I missed that it doesn't inherit _by default_, but explicitly inheriting works! That has all the pros of option 3 without more properties for users to learn.
