### ISSUE TITLE
TextfieldBase [Textfield,NumberField] : optional hide validation icon for invalid state

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1708]
### Expected Behaviour
As we currently use a set of smaller input fields (Textfield or NumberFields) and like to use the `invalid` state - it would be good to have an option to hide the validation icon (`sp-icon-alert`) and to remove the padding in the input field - in order to have the full space available in the input field and also signalize the user the invalid input by only rendering the red border.

This is especially important for smaller input fields where the icon would take a majority of space compared to the whole input field.
 
Would be good to have some optional attribute like `hide-icon` to disable the icon rendering and padding.
  
### Actual Behaviour
Red border and alert-icon is always rendered, taking  a lot of space especially in small input fields. 

#### Platform and Version
MacOs, chrome version 92

#### Furter comment
I am not sure, if this would make sense for the `valid` state as well - as there is no such colored (green) border like for invalid state. Would be good to ask Spectrum team if such a combination makes sense. (No validation icon but green border).

**Comment by Westbrook** [comment]
Upon design review, we've found that the combination of the red outline and the alert icons is _required_ for appropriately delivering the state of the input in an accessible manner.

An alternate approach in this case is to more tightly manage the value inserted the field and move that value back to a valid state as needed. You can see this with the `min`, `max`, `step`, etc. attribute in `sp-number-field` that allow for immediate management of the values that a user inserts into that interface.

With this in mind, we'll be closing this issue.
