### ISSUE TITLE
Switches do not render properly on Edge

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#174]
### Expected Behaviour

Switches should look the same in Edge as in other browsers

### Actual Behaviour

The switches will animate from right to left, but seem to get stuck in the left position.

![ezgif-1-99c6eceafa85](https://user-images.githubusercontent.com/154097/64213328-b2e7dc00-cf00-11e9-864c-851c6a9d1602.gif)

#### Steps to Reproduce

Build Spectrum web components into an app that has polyfills for Edge, such as our documentation app. View the switches page in Edge.

#### Platform and Version

Windows 10 + Edge (not Chromium version)

**Comment by Westbrook** [comment]
I'm no longer seeing any issue with this in Edge 18. If this persists in some way that isn't apparent, please feel free to add additional recreation information and reopen!
