### ISSUE TITLE
[Bug]: sp-slider label takes up space even when hidden

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1744]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Slider content is vertically centered if `label-visibility="none"` is specified

### Actual behavior

It's not centered because the label is still taking up space.

### Screenshots

<img width="261" alt="Screen Shot 2021-08-26 at 3 49 49 PM" src="https://user-images.githubusercontent.com/48841507/131034593-53526132-d0cd-46e1-aa31-90c0c2ed2cbf.png">

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/slider
2. Inspect the slider with `label-visibility="none"` in the debugger and inspect

**Comment by Westbrook** [comment]
Fixed https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--no-visible-labels&args=variant:!undefined;tickStep:0.1;labelVisibility:none
