### ISSUE TITLE
[Feat]: support containerized development

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1761]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

N/A

### Description of the requested feature

We could reduce setup -> contribution time to nearly zero by [developing within containers](https://code.visualstudio.com/docs/remote/containers). I've pushed [a branch](https://github.com/adobe/spectrum-web-components/tree/add-devcontainer) adding vscode devcontainer configuration.

However, `yarn test` depends on playwright, which currently [lacks support for m1 (arm) architectures](https://github.com/microsoft/playwright/issues/7723). Until that's resolved, I'm unable to containerize SWC's full development workflow.

### Implementation notes or ideas

- This should be shippable once [playwright ships containers for linux/arm64](https://github.com/microsoft/playwright/issues/7723)
- It may be simplest to extend the devcontainer Dockerfile from [playwright](https://playwright.dev/docs/docker/), then add the [node devcontainer](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node/.devcontainer/base.Dockerfile) functionality inline.

**Comment by najikahalsema** [comment]
@hunterloftis Do you still want to work on this?
