### ISSUE TITLE
[Docs] Missing components request

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#1763]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

A call-to-action near the components documentation for what to do if you don't see what you're looking for.

- Q1: Is it in Spectrum CSS yet?
  - **Y** Find the issue for the missing component and add a note of your needs and what your timeline is.
  - **N** Q2: Is it part of the Spectrum project?
    -  **Y** Link to who to contact with the Spectrum CSS team
    - **N** Link to who to contact with the Spectrum design team

**Comment by najikahalsema** [comment]
closed via #1199
