### ISSUE TITLE
[Docs] Playground for app examples and demos

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#1764]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

Really cool interactive example: https://lit.dev/tutorial/

Could make use of the playground components: https://github.com/PolymerLabs/playground-elements

**Comment by Westbrook** [comment]
Combination of the playground-elements with MD for reference: https://github.com/apollo-elements/apollo-elements/blob/main/docs/index.md

**Comment by Westbrook** [comment]
These designs might be an interesting inclusion as "demo apps" when made interactive: https://spectrum.corp.adobe.com/page/tutorials/ While also being useful learning content, generally.
