### ISSUE TITLE
[Bug]: Color Area "keypress" test is flappy

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1772]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Color Area

### Expected behavior

Tests are deterministic

### Actual behavior

The check `expect(el.x, 'x').to.equal(0.67);` is sometimes off by 0.01, leading to flappy test failures.

### How can we reproduce this issue?

Run `yarn test` repeatedly and notice that sometimes all tests pass, and sometimes this test fails. For example:

https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/9063/workflows/b5076bff-7557-4d76-b914-fdb3cbe38a02/jobs/111639

**Comment by Westbrook** [comment]
fixed by #1773
