### ISSUE TITLE
[Bug]:  (Editable) Slider: Numberfield value update normalization  

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1782]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider, SliderHandle

### Expected behavior

When using an editable slider AND providing normalization functions via sp-slider-handle the display value in the NumberField isn't reflecting the real (de-normalized/fromNormalized) value. 
Also if the user inputs values they should be processed using `toNormalized` function (if provided).

### Actual behavior

Display value isn't reflecting/updated with real value

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

https://webcomponents.dev/edit/cvpm95Z7Xz6RV70jKXZ5/src/index.ts - Editable with normalization

### Sample code that illustrates the problem

https://webcomponents.dev/edit/cvpm95Z7Xz6RV70jKXZ5/src/index.ts

**Comment by spdev3000** [comment]
from slack:

Westbrook Johnson  6:14 PM
I think we just missed it... seems like there's a relatively straight forward PR to use normalizedValue as opposed to value in https://github.com/adobe/spectrum-web-components/blob/main/packages/slider/src/Slider.ts#L184

**Comment by Westbrook** [comment]
Merging with #1781 as a duplicate. We should have someone picking up this issue today or tomorrow. Thanks!
