### ISSUE TITLE
[color-area]: remove deprecated `label` at 1.0

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1802]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

`label-x` and `label-y` have replaced `label` via https://github.com/adobe/spectrum-web-components/pull/1801, but we kept `label` around to avoid a breaking change.

When we ship 1.0, we should take that opportunity to remove the deprecated `label` attribute.

**Comment by najikahalsema** [comment]
Let's do a release with devmode deprecating these values, then follow up with a general release that removes them.

**Comment by Westbrook** [comment]
@blunteshwar could I interest you in completing the deprecation for this property?

**Comment by blunteshwar** [comment]
Sure I can help!

**Comment by Rajdeepc** [comment]
Will be merged to `main` on SWC 1.0.0 release. Holding the merge for now!
