### ISSUE TITLE
[Bug]: Range slider throws an error when trying to drag the handles

### ISSUE THREAD

**Issue by hkh12** [adobe/spectrum-web-components#1803]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider, sp-slider-handle

### Expected behavior

It just should work.

### Actual behavior

One of the handles doesn't show up, and when I try to drag the handles I get this error:
```
Uncaught TypeError: Cannot destructure property 'input' of 'this.getHandleElements(...)' as it is undefined.
    at HandleController.handlePointermove (HandleController.ts:321)
    at HTMLElement.fn (HandleController.ts:437)
    at HTMLDivElement.handleStream (streaming-listener.ts:72)
```

### Screenshots

![Slider](https://user-images.githubusercontent.com/24871883/133917546-00e02dc2-e723-4d2e-bd25-0c8ac4473bad.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Add an `sp-slider[variant=range]`
2. Try to drag the handles
4. Check console
3. See error

### Sample code that illustrates the problem

Copied from [the docs](https://opensource.adobe.com/spectrum-web-components/components/slider-handle/examples)
```html
<sp-slider variant="range" step="1" min="0" max="255">
    Output Levels
    <sp-slider-handle
        slot="handle"
        name="min"
        label="Minimum"
        value="5"
    ></sp-slider-handle>
    <sp-slider-handle
        slot="handle"
        name="max"
        label="Maximum"
        value="250"
    ></sp-slider-handle>
</sp-slider>
```

### Logs taken while reproducing problem

I'm using `@spectrum-web-components/bundle@0.22.7` and I'm testing on Chrome 93

**Comment by hunterloftis** [comment]
Ok, I'm able to repro by loading the bundle via `<script>` in HTML:

https://webcomponents.dev/edit/T2jOTTTBmRDtrh4RYod5/www/index.html

re: @Westbrook this may be due to `<sp-slider>` trying to load state, on upgrade, from `<sp-slider-handle>` before the handle elements are registered.
