### ISSUE TITLE
[Feat]: `sp-action-menu` should support customizing the internal `sp-menu`

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-web-components#1831]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Description of the requested feature

When using `sp-action-menu`, there is no way to customize the internal `sp-menu` that is opened. Potential use cases could be specifying a `max-width`, or overriding a supported CSS variable.

For example, perhaps `sp-action-menu` could support a `menu` slot:

```jsx
<sp-action-menu size="m">
    <span slot="label">More Actions</span>
    <sp-menu slot="menu" style="max-width: 400px; --spectrum-listitem-m-height: 50px;">
        <sp-menu-item />
    </sp-menu>
</sp-action-menu>
```

**Comment by najikahalsema** [comment]
Will be addressed by #2086
