### ISSUE TITLE
[Feat]: Swap "self-managed" for "managed" with opposite effect

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#1885]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tooltip

### Description of the requested feature

Swap `<sp-tooltip></sp-tooltip>` for `<sp-tooltip managed></sp-tooltip>` and `<sp-tooltip self-managed></sp-tooltip>` for `<sp-tooltip></sp-tooltip>` for easier consumption in the preferred shape.

**Comment by najikahalsema** [comment]
Figure out how to deprecate this behaviour since it's a breaking change
