### ISSUE TITLE
[Feature]: Update package exports to include "Overlay Timer" in default import 

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#1897]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Expected behavior

A minor issue, but I came across some of our code that uses the overlay timer directly and it isn't [exported from the project](https://github.com/adobe/spectrum-web-components/blob/next/packages/overlay/src/index.ts#L12-L17).

I would expect to be able to do:

```js
import { OverlayTimer } from '@spectrum-web-components/overlay'
```

### Actual behavior

Right now we are referencing it via `src` 

```js
import { OverlayTimer } from '@spectrum-web-components/overlay/src/overlay-timer.js'
```

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
Closing as not needed. We may surface timing functions in a different way in future Overlay API iterations.
