### ISSUE TITLE
[Bug]: Picker menu is very slow to open

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#1910]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Picker

### Expected behavior

When you click on a picker button, the menu opens pretty immediately.

### Actual behavior

With the latest release it's taking around a second to open.

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/picker/
2. Click on a picker button (and observer the time it takes)
3. Repeat step 2 and notice that it's not faster on subsequent attempts.

**Comment by adixon-adobe** [comment]
What's interesting is that action menu is opening almost immediately, and split button seems like it might have a short delay, but the other issue there is making it harder to compare.

**Comment by adixon-adobe** [comment]
We're also a new delay after the menu closes until the page is interactive again, which is possibly related.

**Comment by Westbrook** [comment]
I see no degradation when opening the Picker in this way, do you have any extra information to share about this use case?

This is the [last build before](https://picker-late-item--spectrum-web-components.netlify.app/) the change (using `modal` as overlay type) that _may_ have caused what you're seeing, but I see no degradation between the two experiences either. This goes even further back to before `v0.7.5` of Picker and still feels the same: https://fix-overlay-open-close-symmetry--spectrum-web-components.netlify.app/ What version were you on previously so we could compare one vs the other in the documentation site?

While closing, we currently do not restore interactions until `sp-closed`, which could certainly adjusted if you felt that was unexpected, but seems unrelated to anything you might experience on an initial open event.

**Comment by adixon-adobe** [comment]
I restarted Chrome, and I'm seeing much less of a difference than before, but I still do see a slight difference. The scrollbar in the sidebar popping up seems like a clue -- perhaps the modal change is triggering a more expensive re-render. I'm also seeing some focus differences between the 2 which you can see in the screen recording.

Screen recording (right tab is the last build before the modal change): https://user-images.githubusercontent.com/48841507/140574425-6b0d8cd8-0d61-4519-9490-d8b99cf52b9a.mov
