### ISSUE TITLE
[Bug]: Size of ProgressCircle can not be changed with size attribute

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#1941]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ProgressCircle

### Expected behavior

`size=small` or `size=large` should change the size of `sp-progress-circle` element acording to [doc](https://opensource.adobe.com/spectrum-web-components/components/progress-circle/#size).

### Actual behavior

The size is always the same (`medium`).

### Screenshots

![image](https://user-images.githubusercontent.com/1174072/142415999-afef8409-f79c-4ebb-aafa-59bb95b44779.png)

### What browsers are you seeing the problem in?

Firefox, Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Go to [progress-circle doc](https://opensource.adobe.com/spectrum-web-components/components/progress-circle/#default)
2. See that all examples have the same size

### Sample code that illustrates the problem

```html
<sp-progress-circle size="small"></sp-progress-circle>
<sp-progress-circle size="large"></sp-progress-circle>
```

**Comment by Westbrook** [comment]
Thanks for catching this. The usage of the `size` attribute here has changed to better align with the rest of the library. See https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/progress-circle--default If you had a minute to submit a PR to normalize this, we’d be much obliged, otherwise we’ll get to this as soon as we can!

**Comment by davidkudera** [comment]
@Westbrook thanks, here is a PR - https://github.com/adobe/spectrum-web-components/pull/1942

There is still the example at webcomponents.dev that should be updated:

![image](https://user-images.githubusercontent.com/1174072/142421715-22aa0cf5-7647-460c-9c66-f6c4e4666f72.png)

**Comment by Westbrook** [comment]
Great! I just bumped https://webcomponents.dev/edit/LfliuY0UocICDCBr21uy/src/index.ts too, so we should be all set here. Thanks again.
