### ISSUE TITLE
[Feat]: Support downward reactivity for `.selected` in `<sp-action-group>`

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#1955]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-group

### Description of the requested feature

Allow action groups to be used as controlled components with one-way data flow by setting their `selected` state, eg:

```
<sp-action-group .selected=${[someValue]}>
```

- if `.selected` exists on an action-group, it should be used for initial selection state
- subsequent changes to `.selected` should be reflected in the action group's selection state
- an `<sp-action-group>` with a constant `.selected` value should not change its selection state, even via user interaction with child action buttons, if `preventDefault` is called on its `change` event.

### Mockups or screenshots

Once complete, [this example](https://webcomponents.dev/edit/ielfeh4FXIP1kmZWVjz3/src/index.ts?p=stories) should work.

**Comment by Westbrook** [comment]
Also make sure the `change` event from the `<sp-action-group>` element is correctly documented.

**Comment by hunterloftis** [comment]
@asthapasta is working on this; assigning so nobody else picks it up concurrently

**Comment by hunterloftis** [comment]
A more-complete specification:

- `selected` is the current selected state of the group
  - setting it at any time updates the state
- `selects` specifies how the component handles user interaction
  - "single" sets `selected` in the way a radio-button group would (positively selecting one at a time)
  - "multiple" sets `selected` in the way that a checkbox group would (toggling selection of any button within it)
  - unspecified doesn't respond to user interactions
  - whenever the group is about to set `selected` in response to a user interaction, it emits a `change` event with the upcoming `selected` value. If the `change` event is canceled, the group does not update `selected`

With some example cases:

- `<sp-action-group selects="multiple" .selected=${controlledSelected} @change=${preventDefaultAndSetControlledSelected}>` would try to toggle button selections on click, but would ultimately select whatever `controlledSelected` specifies.
- `<sp-action-group selects="single" .selected=${controlledSelected} @change=${preventDefaultAndSetControlledSelected}>` would try to move selection to the clicked button, but would ultimately select whatever `controlledSelected` specifies.
- `<sp-action-group selects="single" .selected=${["d"]}>` would initially select "d" and afterwards act as a radio group
- `<sp-action-group selects="multiple" .selected=${["d", "e"]}>` would initially select "d" and "e" and afterwards act as a checkbox group
- `<sp-action-group selects="single" .selected=${["b, "d"]}>` would initially show multiple selections, but subsequent user interaction would force it back to a single selection
- `<sp-action-group .selected=${["d"]}>` would apply an initial selection, but not respond to subsequent user input
