### ISSUE TITLE
[Feat]: (Editable) Slider: provide maxlength to restrict user input

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#1996]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Description of the requested feature

While the maxlength attribute is provided in NumberField and TextField via TextfieldBase, it would be good to somehow expose this attribute as well to Slider. 
It should restrict the available user input In the case of an editable slider.

### Implementation notes or ideas

It can be discussed if the maxlength should include any appended unit formatting, but I would argue to restrict only to the user input-able values.

**Comment by sorinsarca** [comment]
What would be the difference between `maxlength=3` and `max=999`?

**Comment by Westbrook** [comment]
@spdev3000 does the validation of large number fix from #1995 and the presence of the `max` attribute cover the functionality you were looking for here? Would love to close this as "won't fix" if so!

**Comment by spdev3000** [comment]
yes this seems reasonable to close this as the fix has been applied and max can be utilized.
