### ISSUE TITLE
[Bug]: Picker doesn't work in content area of documentation site

### ISSUE THREAD

**Issue by SavoInfostream** [adobe/spectrum-web-components#2016]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

Picker's menu should open when picker is clicked on.

### Actual behavior

Picker's menu doesn't open.

### What browsers are you seeing the problem in?

Firefox

### How can we reproduce this issue?

1. Go to '[sp-picker page](https://opensource.adobe.com/spectrum-web-components/components/picker/)'
2. Click on 'Selection Type picker'
5. See error

**Comment by Westbrook** [comment]
Thanks for the issue. For clarity, this situation does not effect Firefox _generally_ as you should be able to see by leveraging the themeing pickers in the top right corner of every page, but only the documentation content in our site. We've seen this before and have not be able to track down a source, as yet. It is possible that #1988 might help as it moves us to a more transparent overlay calculation process, but I'm unsure when we'll be able to get to that work. 

In the interim, you can further experience our Picker element in the "wild" by visiting: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/picker--default If along your development process you're able to sequester this issue into a more reproducible manner, we'd love to check it out and see whether it helps finding the source of this issue. Thanks!

**Comment by SavoInfostream** [comment]
I know my colleague had issues with the picker in Firefox, I will post an update tomorrow.

**Comment by SavoInfostream** [comment]
Hey, 
here's a small screenrecording of the issue on firefox
https://www.awesomescreenshot.com/video/6716039?key=850403422201592584ef30cd69ce2af5
