### ISSUE TITLE
[Bug]: Only the rightmost sp-slider-handle child is active in an sp-slider[variant=range]

### ISSUE THREAD

**Issue by peterjanes** [adobe/spectrum-web-components#2032]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider, sp-slider-handle

### Expected behavior

It should be possible to move all handles inside an sp-slider.

### Actual behavior

Only the rightmost sp-slider handle is active.

### What browsers are you seeing the problem in?

Firefox, Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/slider-handle/
2. Try to adjust the minimum value of the slider inside each example, either by dragging it or clicking on the slider line.
3. Observe that the maximum value/rightmost handle is the only one that moves.

**Comment by Westbrook** [comment]
Have you tried the latest release of this element? It includes #2030, which should address this.

**Comment by peterjanes** [comment]
I actually just left a comment on #2035 that says it does. :)

**Comment by peterjanes** [comment]
It looks like 0.12.2 does solve it. (I hadn't shift+reloaded the demo page.)

**Comment by Westbrook** [comment]
Thanks for confirming! Closing.
