### ISSUE TITLE
[Bug]: sp-slider doesn't allow touch-dragging

### ISSUE THREAD

**Issue by lrymarz** [adobe/spectrum-web-components#2034]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider, sp-color-slider

### Expected behavior

On a touch device, I should be able to tap-hold the slider handle and drag it to a new position.

### Actual behavior

On Android devices and when simulating touch using Chrome desktop, the slider does not track your finger as you drag.  iOS appears to work, at least in the iOS 14 simulator.

In our code, we've fixed this by extending sp-slider with following CSS:

```
:host {
	touch-action: none;
}
```

### Screenshots

![spsliderScrub mov](https://user-images.githubusercontent.com/2146888/148475071-23017066-36bb-4788-8528-b4be0f7682b0.gif)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/slider/
2. Open the Chrome debugger and toggle the mobile devide simulator on (top right of the debugging window)
2. Scroll down to a slider example
3. click-hold and drag the slider handle
4. Observe that the slider does not track your pointer as you move.  It's just stuck.

**Comment by Westbrook** [comment]
@lrymarz for confirmation, you've listed `<sp-color-slider>` in your description, but I am unable to duplicate the situation that I see in `<sp-slider>`, both in you screen capture and in local testing, with that element. If you're indeed seeing this issue there can you share some more information around how you've encountered it? If not, hopefully #2030 will be enough to get this issue out of your hair.

Thanks again for posting!

**Comment by lrymarz** [comment]
@Westbrook Oh sorry, I listed `<sp-color-slider>` only because I want the behavior to be consistent. I'm not using that component right now and haven't encountered any issues with it.
