### ISSUE TITLE
[Feat]: Default-values for slider / sider-handle

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2065]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider, SliderHandle

### Description of the requested feature

We'd like to have a feature implemented in Slider or SliderHandle to provide a `default-value`. If the user would then double click on the slider or the handle the value would reset to the provided default-value.

### Implementation notes or ideas

I tested also detecting a double click on the slider track. This might be possible to let the user even reset a slider when not double clicking on the slider handle.
We need to consider resetting values also for keyboard-users. Maybe we can use Escape key when the handle has focus to reset to default value (if given).

**Comment by jnurthen** [comment]
Please also consider touch users, screen reader users and voice recognition users when thinking about how this should work.

**Comment by hunterloftis** [comment]
@jnurthen do you have concerns about accessibility with the core [spec](https://spectrum.adobe.com/page/slider/#Double-click-to-reset)?

If so, is there an alternative input to a double-click that you would recommend replacing the Spectrum behavior with?

**Comment by jnurthen** [comment]
I have concerns - it doesn't appear to take account of any input mechanisms other than pointers

**Comment by jnurthen** [comment]
I filed https://jira.corp.adobe.com/browse/SDS-12156

**Comment by hunterloftis** [comment]
Thanks @jnurthen!

**Comment by najikahalsema** [comment]
related to #586

**Comment by Westbrook** [comment]
Erroneously closed.

**Comment by Rajdeepc** [comment]
Needs some testing on touch users, screen reader users and voice recognition
