### ISSUE TITLE
[Feat]: ActionMenu - PickerBase - make TriggerInteraction customizable

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2067]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu, PickerBase

### Description of the requested feature

As we’re restructuring our Headerbar/Navbar menu system I’d like to use ActionMenus for most of the menu components, but would also like to open them not in `modal` mode (preferable `inline` as before) to enable users to hover and click other menu triggers with the current menu open. As it definitively makes sense for a single picker to open in modal mode, we’d like to use an optional parameter to adjust the TriggerInteractions of the[ openOverlay call of PickerBase](https://github.com/adobe/spectrum-web-components/blob/be29bf6679a92ff56f40c9833f462944a490cf4d/packages/picker/src/Picker.ts#L333). Can be set to `modal` as default.

### Implementation notes or ideas

add an optional param to ActionMenu to provide the desired TriggerInteraction to PickerBase.
default should be `modal`.

**Comment by najikahalsema** [comment]
related to #2086
