### ISSUE TITLE
[Feat]: ActionMenu/Picker - add identifier to internal sp-menu for css customization

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2068]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu, Picker

### Description of the requested feature

We have seen quite difficulties to adapt and style underlying `sp-menu` without any additional id or class of that element. The problem is - if you’d add css styles for an `sp-menu` of an `ActionMenu` and the user opens another (not-styled) `ActionMenu`, those sp-menu css styles will get also applied to the new menu, as there is a short time, when both menus are both opened.
Would it be possible to add an optional parameter (`data-menu-id` or menuClass) to the newly created internal [sp-menu](https://github.com/adobe/spectrum-web-components/blob/be29bf6679a92ff56f40c9833f462944a490cf4d/packages/picker/src/Picker.ts#L457) in PickerBase to be used for styling or for e2e tests as css reference? 

Styling use cases could include:
- subtitles / subtext in an sp-menu-item
- different colors
- extended alignment of icons for multiline items

**Comment by Westbrook** [comment]
Leaking these implementation details could be prevented by moving to a `<dialog>`/`[popup]` structured API.

**Comment by najikahalsema** [comment]
Will be addressed by #2086
