### ISSUE TITLE
Add ability to select/preview fonts in docs

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#208]
### Expected Behaviour
The docs should allow you to select between loading no additional fonts, Adobe Clean, or Adobe Clean UX (which will soon be the preferred option). Non-Adobe consumers of this library won't have access to Adobe Clean so having a way to preview without it will be good. When this change is made, we should also change Adobe Clean UX to be the default.

### Actual Behaviour
There's no ability to select the font right now outside of development.

**Comment by Westbrook** [comment]
@adixon-adobe will we be moving away from Adobe Clean UX at this point? I find it difficult to keep up with the broader unification goals there.

**Comment by adixon-adobe** [comment]
We're hoping to keep it working for a bit, but the long term goals are in flux so I'll close this. Still might be nice to have a preview that uses the fallback font.
