### ISSUE TITLE
[Bug]: Multi-level sideNav does not convey structure

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#2119]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-sidenav

### Expected behavior

Mutli-level sidenav should convey the level to AT. The easiest way to do this is nested lists

### Actual behavior

No level information is conveyed to AT

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/sidenav/#multi-level
2. Look at structure - no level information is conveyed. 
3. Confirm using NVDA or VO. The structure is not conveyed

### Sample code that illustrates the problem

https://opensource.adobe.com/spectrum-web-components/components/sidenav/#multi-level

**Comment by Westbrook** [comment]
#3348 has extended fix outlined, closing in favor of that duplicate.
