### ISSUE TITLE
[Bug in Documentation]: sp-tray component documentation page is blocked by overlay

### ISSUE THREAD

**Issue by pinkhominid** [adobe/spectrum-web-components#2120]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tray documentation

### Expected behavior

The sp-tray component documentation page is interactive.

### Actual behavior

The page is blocked by an overlay and you can't interact or navigate to other documentation pages.

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/tray/
2. Try clicking Toggle tray or navigating to another page
3. See issue

**Comment by Westbrook** [comment]
Indeed. The "tray", being predominately a visual element, needs a bit more management here. The correct path is likely to wrap all the usage in `<overlay-trigger>` elements to manage the availability of the `<sp-tray>` in the _physical_ layout of the page.

@pinkhominid, would you be interested in submitting a PR with this update?

**Comment by pinkhominid** [comment]
@Westbrook , sure!
