### ISSUE TITLE
[Feat]: Provide a CSS Custom Property to manage `user-select` on interactive elements

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#2136]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

many: switch, button, icon, radio...

### Description of the requested feature

Selecting text in interactive, non-textual components can provide a sub-par user experience when compared to native applications. Users don't typically expect that native:

switches, buttons, menu items, icons, radio buttons, ...etc

...will be highlighted as text nodes during drag-and-drop operations or other normal pointer usage. This is a frequent source of accidental selection:

![image](https://user-images.githubusercontent.com/364501/155566862-9d98b00d-5a21-43e9-ab2b-f29a533a8cba.png)

While keeping traditional browser-like `user-select` behavior of inputs by default, we should allow consumers to override this choice in a single place via a CSS custom property (eg, `spectrum-form-user-select: none`, or similar)

**Comment by Westbrook** [comment]
https://mobile.twitter.com/rick_viscomi/status/1507464774015016963

**Comment by hunterloftis** [comment]
IMO the harm described in that tweet comes from the `html { ... }` part rather than the `user-select: none` part.

A control like a toggle switch, for instance, becomes _more_ accessible when a user can rely on toggling it (its purpose) instead of selecting text nodes in it via an imperfect (>0px movement) click.

**Comment by Westbrook** [comment]
Consumption hasn't lead to a more holsitic need for this.
