### ISSUE TITLE
[Bug]: Possible incorrect usage of @element in jsdoc

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#2141]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

All

### Expected behavior

When using `lit-analyzer` at the CLI or as a plugin for VSCode + TS we would expect the import of a type from a component to still cause a `no-missing-imports` warning/error if the components defining entrypoint was not also included.

The following import should not satisfy the `no-missing-imports` check:

```ts
import { Textfield } from '@spectrum-web-components/textfield';
```

### Actual behavior

Currently however this import appears to be evaluated as importing the `sp-textfield` component. I believe this is due to the use of the `@element` JSDoc Tag in our comments as [seen here](https://github.com/adobe/spectrum-web-components/blob/main/packages/textfield/src/Textfield.ts#L324). 

According to the `web-component-analyzer` [docs](https://github.com/runem/web-component-analyzer#overview-of-supported-jsdoc-tags) the `@element` tag:

> Gives your component a tag name. This JSDoc tag is useful if your 'customElements.define` is called dynamically eg. using a custom function.

So I think we may need to remove this comment from these class definitions since our element tag name is defined on our [sp-textfield.ts](https://github.com/adobe/spectrum-web-components/blob/main/packages/textfield/sp-textfield.ts#L14) file instead which is perhaps where this comment should be?

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by benjamind** [comment]
I tested this theory by removing the `@element` JSDoc tag from the `Textfield.d.ts` in the built package and lit-analzyer then correctly identifies the missing import. I'm not sure however if removing this doctag from the JSDoc would cause the actual output of `web-component-analyzer` to change?

**Comment by Westbrook** [comment]
No longer occurring with `v1.4.3` of `lit-plugin`.
