### ISSUE TITLE
[Bug]: When sp-menu-item changes its label while selected, picker label does not update

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#2158]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

When the label of an item changes while selected, the picker should reflect that label

### Actual behavior

The old label remains

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://webcomponents.dev/edit/msStOl89omAAl2v2k3VR/src/index.ts?p=stories

In the above demo, select "Soon" from the picker (ensure "Soon shows as the label in the picker)

Next click the button - this button changes the label "Soon" to "My Item Changed"

Note that the picker label field does not get updated.

### Logs taken while reproducing problem

My workaround currently is to target the selected sp-menu-item and do `.breakItemChildrenCache();` on it

**Comment by bengfarrell** [comment]
Oops, should probably mention that it seems like a regression of this: https://github.com/adobe/spectrum-web-components/issues/1893

**Comment by Westbrook** [comment]
Starting the conversation on this here: https://github.com/lit/lit/issues/2629

See the dirty hack of this here: https://webcomponents.dev/edit/CudbvARZhYNbJazbrOrx/src/index.ts?p=stories

Likely need to add a Mutation Observer to support both paths to changing the value here, but want to confirm that `lit-html` is performing as expected.

**Comment by Westbrook** [comment]
Lit team reports that they'll not be able to amend this functionality within the library, so we'll need to move to a Mutation Observer for this responsivity.
