### ISSUE TITLE
[Bug]: action-menu missing popover dependency

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#2170]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

action-menu

### Expected behavior

During an upgrade to yarn 3.x with Plug n Play turned on, it highlighted that the popover dependency was missing from the action-menu tree.

### Actual behavior

Add the popover dependency and run `yarn workspace uec-preview run start` in UEC, validate that this error no longer occurs:

```
(node:67254) [MODULE_NOT_FOUND] Error: @spectrum-web-components/action-menu tried to access @spectrum-web-components/popover, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

### Logs taken while reproducing problem

(node:67254) [MODULE_NOT_FOUND] Error: @spectrum-web-components/action-menu tried to access @spectrum-web-components/popover, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

**Comment by Westbrook** [comment]
Take a look at whether or not this can go the other way and remove the import all together. I'm not sure that it's used in Action Menu outside of the usage extended from Picker which includes this import, too.
