### ISSUE TITLE
scale/themes package is very large due to many variables

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#2173]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

The `spectrum-scale-medium.css` and `spectrum-scale-large.css` files are very large due to a high number of spectrum varable definitions that map component specific names to global/alias variables.

These are largely unused by component implementations at this time.

Suggest we filter these out so we only include the variables actually used by components in the theme.

**Comment by beeduul** [comment]
impacts https://jira.corp.adobe.com/browse/VEN-2726

**Comment by Westbrook** [comment]
Related to https://github.com/adobe/spectrum-css/pull/1429 and https://github.com/adobe/spectrum-css/pull/1430
