### ISSUE TITLE
[Feat]: Ability to prevent keyboard driven interaction events on elements which are not focus-visible

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#2206]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Possibly all

### Description of the requested feature

In some applications, particularly those focused around design tools, we have often have a global keyboard shortcut for the 'Pan tool' to activate when holding down the `Space` key. This creates a problem from an a11y point of view since `Space` also commonly is used to 'activate' a control, e.g. a button, or a dropdown.

Currently when a button is focused via a mouse/pointer input modality it receives focus, but does not get granted focus-visible matching. This is desirable so that focus indication does not clutter the UI for a mouse driven experience. Our design system gives no other indication of focused element state, unless the user uses a keyboard input modality to focus the button.

Pressing `Space` however when a button is has focus, will result in the button both getting `focus-visible` matching AND activating. So there's a bit of an unexpected UX here, where the user has no idea what will happen when they press the `Space` key because there is no focus-visibility on the button, although this is what happens in native HTML controls if they do not have focus styling.

This also introduces the problem for our design tools, `keydown` events happen after `focus-visible` matching is applied (even in capturing phase), this means we can't detect if a `keydown` capturing phase event at the high level in the DOM is destined for a control that is `focus`/`focus-visible`, so we can't determine if we should intercept the `Space` key or not to handle our pan tool shortcut, i.e. we have no way of knowing if the event should be handled by the button or our global shortcut handler.

In discussion with our a11y team and @hunterloftis we came to the conclusion that a better approach would be for all our activatable controls to only activate on `Space` if they are already `focus-visible` matching. The keydown event will cause `focus-visible` to apply to the control, so the first press of `Space` with a button focused should make it `focus-visible` but not activate it, then the second press would activate it as normal and because it handled the event it should call `stopPropagation()` on the event. The simple rubric here is that keyboard activation events should not be enacted unless the control has visible focus indication, i.e. you know where your focus is as a user. This obviously runs counter to the native HTML elements which activate on `Space` if they have `focus` regardless of their `focus-visible` state, these controls also do not prevent propagation of the `keydown` event (since otherwise they would be useless as primitives).

### Implementation notes or ideas

To implement this behavior I propose the following:
* Modify `FocusVisiblePolyfillMixin` to implement tracking of `focus-visible` state on `focus`
* Add a new function `shouldAllowKeyboardActivation` to the mixin that will:
  * Test if the element had `focus-visible` state before this interaction, if it did, then return `true`
  * If it did not, fire a `keyboard-activation` event and return the boolean returned by the `dispatchEvent` function, i.e. if the event was cancelled return `false`.
  * Update the state of the interanl `focus-visible` tracking (so subsequent calls will work from the new state, as any key driven event will add focus-visibility to the control).
* Update components which support `Space` as an activation to check this function before executing the action, and also call `stopPropagation()` on their keyboard events if they do execute the action (because the key has been handled).

This approach then allows a design tool to listen for these `keyboard-activation` events and call `preventDefault()` on them if it would prefer to use its own event handler for this interaction. The flow is that a button that is 'focus' mode only, i.e. its been clicked upon, will emit the `keyboard-activation` event the first time a key is pressed while it retains focus. If nothing prevents the `keyboard-activation` event, behavior continues as normal and the event stops propagating since this control is handling it. This means the design tool can simply listen for a bubbling phase `keydown` event for the `Space` key to handle the pan tool behavior.

**Comment by Westbrook** [comment]
Fixed as an application concern.
