### ISSUE TITLE
Support having more than one copyright year.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#2212]
New files have old copyright
```suggestion
Copyright 2022 Adobe. All rights reserved.
```

_Originally posted by @pinkhominid in https://github.com/adobe/spectrum-web-components/pull/1905#discussion_r845714065_

**Comment by castastrophe** [comment]
Ah I might have some code for this in UEC I can share. I'll take a look later this week!

**Comment by Westbrook** [comment]
That would be awesome! 🙏🏼  I'm hoping it's nothing too crazy, but it only coming up once in two years has kept it lower on the priority list.
