### ISSUE TITLE
[Feat]: Textfield / Number Field: Select input value on click into input field

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2255]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Number Field, Textfield

### Description of the requested feature

Clicking the input field select all of the values, allowing users to quickly enter a whole number instead of adjusting the caret for input, or having to click again to select.

### Implementation notes or ideas

If not setup as default behavior this might be switch on by an optional property/attribute, like `click-to-select` or similar.

**Comment by Westbrook** [comment]
As a class extension of Textfield this element has access to https://github.com/adobe/spectrum-web-components/blob/main/packages/textfield/src/Textfield.ts#L159 which would allow you to work this out from above the component. We’ll discuss this internally and get back to you about whether this will make it into the library when taking into consideration that the exact opposite workflow you’ve outlined having roughly the same precedence.

**Comment by Westbrook** [comment]
As per the above comment, this can be managed locally to another surface with the following code:

```html
<sp-number-field
    value="18"
    @focus=${(e) => e.target.select()}
></sp-number-field
```

Or in a more global manner that would end up taking less specific care that a `click-to-select` attribute:

```html
<div 
    @focusin=${(e) => e.target.select()}
>
    <sp-number-field
        value="18"
    ></sp-number-field>
    <sp-number-field
        value="18"
    ></sp-number-field>
    <sp-number-field
        value="18"
    ></sp-number-field>
    <sp-number-field
        value="18"
    ></sp-number-field>
</div>
```

See it in action here: https://webcomponents.dev/edit/TXlwVZIWMyzDa0XPl4tq/src/index.ts?branch=auto-select%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories

With this in mind, we will not be adding this as an element internal feature at this time.
