### ISSUE TITLE
[Bug]: sp-slider disable while in use behaviour

### ISSUE THREAD

**Issue by liviunst** [adobe/spectrum-web-components#2268]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Once the disabled property is set on the slider the user should not be able to use it anymore.

### Actual behavior

If the user is actively using the sp-slider , dragging the track handler, once the disabled attribute is set the user can continue to use the sp-slider until he releases the track handler.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://webcomponents.dev/edit/1MMWGFoQRTixNrxknzi7/src/index.ts?pm=1&p=stories
2. Drag the slider handler
3. After 3 seconds the slider is disabled  
4. You can continue to drag the handler after the slider was disabled

### Sample code that illustrates the problem

https://webcomponents.dev/edit/1MMWGFoQRTixNrxknzi7/src/index.ts?pm=1&p=stories

**Comment by Westbrook** [comment]
Related to #2103
