### ISSUE TITLE
[Bug]: Accordions are navigable by Up/Down keys instead of Tab key

### ISSUE THREAD

**Issue by mjawili** [adobe/spectrum-web-components#2273]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-accordion

### Expected behavior

Accordion items are navigable only by pressing Tab or Shift-Tab.

### Actual behavior

Accordion items are navigable only by pressing Up or Down.

### Screenshots

![Screen Shot 2022-05-05 at 1 43 28 PM](https://user-images.githubusercontent.com/698736/167022297-41319e25-5820-45f3-bc54-5859ca01c07d.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/accordion/
2. Tab to the accordion.
3. Press Tab to go to the next accordion item.
4. See that focus has actually exited the accordion instead of moving to the next accordion item.

Looks like this was caused by https://github.com/adobe/spectrum-web-components/pull/2017

**Comment by Westbrook** [comment]
Interesting, we've always tracked this as a "composite component" within which we moved focus around as per https://www.w3.org/TR/wai-aria-practices-1.2/#kbd_general_within but you're right it doesn't seem to be leveraging this pattern in the Accordion example: https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html

Thanks for the issue!

**Comment by mjawili** [comment]
@Westbrook thanks for your quirk work on this. When would I be able to see the change on https://opensource.adobe.com/spectrum-web-components/components/accordion/ ?

**Comment by Westbrook** [comment]
We’re looking to have a release later today or so that will include this update publicly on the docs and in installable packages.
