### ISSUE TITLE
[Bug]: dialog and aria-modal are on different elements

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#2282]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

dialog / dialog wrapper

### Expected behavior

aria-modal and role=dialog are on different elements.
These have to be on the same element per the aria spec https://w3c.github.io/aria/#aria-modal

### Actual behavior

When rendering a dialog using dialog wrapper the role=dialog gets rendered on the sp-dialog element but aria-modal=true gets rendered on the active-overlay element.

### How can we reproduce this issue?

1. Go to dialog wrapper https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper/
2. Click on toggle dialog
3. inspect the DOM

**Comment by Westbrook** [comment]
We're moving to the `<dialog>` element in https://overlay-mixins--spectrum-web-components.netlify.app/components/dialog-wrapper/, which should resolve this.
