### ISSUE TITLE
[Bug]: Express-themed Sliders are not styled correctly

### ISSUE THREAD

**Issue by andrewhatran** [adobe/spectrum-web-components#2301]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

The **express themed** Spectrum wc slider with a **large scale** should have a handle with a width of 22px and a border radius of at least 11px to maintain the circular look. 

### Actual behavior

The **express themed** Spectrum wc slider with a **large scale** has a handle with a width of 22px and a border-radius of 10px, which is giving it a squircle look.

Digging into spectrum-wc, looks like the border-radius is set to **--spectrum-slider-m-handle-border-radius** here in the [Spectrum-wc slider css](https://github.com/adobe/spectrum-web-components/blob/32e049a0da090ffc1a54cfe3234be4d5efc73339/packages/slider/src/spectrum-slider.css#L51), regardless of the size of the theme.

Digging into [spectrum-css](https://github.com/adobe/spectrum-css/blob/89c4f233abcaf74c69fd166a77a1cc1c0f03e947/components/expressvars/css/components/spectrum-slider.css#L2024), it looks like -**-spectrum-slider-m-handle-border-radius** has has a value of --spectrum-global-dimension-size-100, which is equal to 10px for a large theme size, causing the squircle look

### Screenshots

![image](https://user-images.githubusercontent.com/8894489/169384270-8770c3fe-1bd2-45a8-ba9d-75ba43b0f3fa.png)

### What browsers are you seeing the problem in?

Firefox, Chrome

### How can we reproduce this issue?

1. Add an `sp-theme` component with a theme of **express** and a scale of **large**
2. Add an sp-slider inside of the theme
3. Notice that the handle of the slider is not a perfect circle

### Sample code that illustrates the problem

<sp-theme theme="express" scale="large">
    <sp-slider></sp-slider>
</sp-theme>

**Comment by Westbrook** [comment]
Can you confirm that you are still seeing this in https://opensource.adobe.com/spectrum-web-components/components/slider/? I can't seem to recreate it there, which makes me think maybe it's just been fixed in intervening versions.

**Comment by andrewhatran** [comment]
@Westbrook it looks like you're right here, I'm unable to reproduce the issue on https://opensource.adobe.com/spectrum-web-components/components/slider/

There was a [corner roundness fix ](https://github.com/adobe/spectrum-css/pull/1395) to the spectrum-css express slider a few months ago: The slider used in project X is not the latest version, so chances are this issue is fixed. Good catch and sorry for the noise.

**Comment by Westbrook** [comment]
Always happy to hear from you Andrew! Keep us in the loop if you run into any issues upgrading when it comes time.
