### ISSUE TITLE
Size of css files renders  Chrome DevTools unusable

### ISSUE THREAD

**Issue by Illusive7Man** [adobe/spectrum-web-components#2315]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

For my project I use `core-global.css`, `theme-light.css` and `scale-large.css`, whose combined size is over 10,000 lines which causes a massive responsiveness issues in Chrome DevTools. There's around 5 seconds delay between selection of a DOM element and when its styles load.

10,000 lines is a bit much, is there a possibility of a lighter version in the future?

**Comment by Westbrook** [comment]
Thanks for the issue! we are chasing this down in #2173. There’s a related PR, but we’re giving upstream dependencies some time to address this situation before moving forward with it on our own.

I’ll be closing this as a duplicate, please keep track of the situation in that issue going forward.

**Comment by Illusive7Man** [comment]
Great news!
