### ISSUE TITLE
[Bug]: sp-slider incompatible types for numberFormat property

### ISSUE THREAD

**Issue by sorinsarca** [adobe/spectrum-web-components#2322]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Definition of `numberFormat` property from `Slider` should be removed or should match the
definition from `SliderHandle`.

https://github.com/adobe/spectrum-web-components/blob/9ffefee25538527b020ac9bf812c4152acb8f18f/packages/slider/src/Slider.ts#L164-L166

https://github.com/adobe/spectrum-web-components/blob/9ffefee25538527b020ac9bf812c4152acb8f18f/packages/slider/src/SliderHandle.ts#L208-L211

### Actual behavior

Typescript error

```sh

node_modules/@spectrum-web-components/slider/src/Slider.d.ts:48:9 - 
error TS2416: Property 'numberFormat' in type 'Slider' is not assignable to the same property in 
base type 'SliderHandle & SlotTextObservingInterface'.
  Type 'NumberFormat' is not assignable to type 'NumberFormatter'.
    The types returned by 'formatRangeToParts(...)' are incompatible between these types.
      Type 'NumberFormatPart[]' is not assignable to type 'NumberRangeFormatPart[]'.
        Property 'source' is missing in type 'NumberFormatPart' but required in type 'NumberRangeFormatPart'.

48     get numberFormat(): Intl.NumberFormat;
           ~~~~~~~~~~~~

  node_modules/@internationalized/number/dist/types.d.ts:6:5
    6     source: 'startRange' | 'endRange' | 'shared';
          ~~~~~~
    'source' is declared here.


Found 1 error in node_modules/@spectrum-web-components/slider/src/Slider.d.ts:48

```

**Comment by Westbrook** [comment]
What version of TS do you run into this issue with? Want to make sure I can fully recreate to be sure any fix both works and removes the error.

**Comment by sorinsarca** [comment]
This happens in both 4.6 and 4.7.

Suggestion: can we enable [noImplicitOverride](https://www.typescriptlang.org/tsconfig#noImplicitOverride)? In this way we won't accidentally override a method or property when extending a class or when using a mixin.

**Comment by Westbrook** [comment]
We've got a fix for the types submitted and we'll take a look at `noImplicitOverride` at the library scale to see if that's a good idea for us going forward. Thanks!

**Comment by Illusive7Man** [comment]
I have got the same error. Waiting for the PR merge.
![Screenshot 2022-05-31 194727](https://user-images.githubusercontent.com/8900151/171251991-8a28f4a5-5991-48a2-8414-baacd82efd9c.png)
