### ISSUE TITLE
[Number Field] Warning about non-passive scroll handler

### ISSUE THREAD

**Issue by moisadoru** [adobe/spectrum-web-components#2323]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

When focusing on a number field instance, Chrome shows a warning about the `wheel` event handler not being passive.

![image](https://user-images.githubusercontent.com/109328/170740056-3baa762b-fb00-48a2-b722-0c712078ea8e.png)

**Comment by sorinsarca** [comment]
This is normal since wheel is used to increment/decrement input value, not to scroll (which must be prevented).

**Comment by Westbrook** [comment]
fixed in #2377
