### ISSUE TITLE
[Feat]: Performance of the picker

### ISSUE THREAD

**Issue by Illusive7Man** [adobe/spectrum-web-components#2360]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Description of the requested feature

It opens soooo slowly. You can see it on demo page.
https://opensource.adobe.com/spectrum-web-components/components/picker/
Any reason for this delay?

**Comment by Westbrook** [comment]
I don't currently experience this issue. Would you happen to have Dev Tools open while measuring your experience?

**Comment by Westbrook** [comment]
Do you experience that past the initial opening of a Picker? That is to say, is it just as slow when you open the Picker a second time?

**Comment by Illusive7Man** [comment]
It doesn't matter if it's a first or a second+ time, always this speed.

**Comment by Illusive7Man** [comment]
How does it look in your browser? The gif above is for a 2+ opening.
Is it an artificial delay?

**Comment by najikahalsema** [comment]
will be addressed by #2086
