### ISSUE TITLE
[Switch]: Spectrum CSS source places "input" on new z-index.

### ISSUE THREAD

**Issue by ayugupta11** [adobe/spectrum-web-components#2405]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus (Illustrator on Web)

### Expected behavior

Spectrum UI components should not take gestures/events from a UI view(context menu) over the spectrum component
Refer bug id: https://jira.corp.adobe.com/browse/VEN-3548

### Actual behavior

Spectrum component registers event, even if the event is meant for the context menu above

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

Refere bug https://jira.corp.adobe.com/browse/VEN-3548

**Comment by Westbrook** [comment]
There have been updates to the applied CSS here. Please feel free to open a new issue if you experience an updated version of this situation.
