### ISSUE TITLE
[Feat]: Name attribute for input components

### ISSUE THREAD

**Issue by Illusive7Man** [adobe/spectrum-web-components#2406]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield, sp-picker, sp-checkbox, sp-switch

### Description of the requested feature

Without name attribute there is no browser autocomplete.
For example a login form made using `<sp-textfield>` components will never be auto-filled by Chrome.

**Comment by blunteshwar** [comment]
@Illusive7Man sp-textfield, sp-checkbox, sp-switch are doable but i think sp-picker is not an input component how can it have a name attribute for autocomplete

**Comment by Westbrook** [comment]
@blunteshwar we should spend some time looking into how [this feature](https://html.spec.whatwg.org/multipage/custom-elements.html#form-associated-custom-elements:face-state-6) supports doing just that or not.

**Comment by blunteshwar** [comment]
Sure!
We can discuss this in our tuesday session
