### ISSUE TITLE
[DOCS]: investigate grouping of related components on docs site

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#2411]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

Some components, like menu and table, have multiple sub-components that require documentation. It would be nice to be able to group them under a sub-folder or something. We should explore this and see what we can do.

**Comment by Westbrook** [comment]
First draft of this: https://docs-groups--spectrum-web-components.netlify.app/components/accordion/

It would benefit of a pairing with https://docs-nav-scroll--spectrum-web-components.netlify.app/components/overlay-trigger/ or slightly nicer version of the idea, IMO.

**Comment by Westbrook** [comment]
Another alternative on this concept: https://docs-groups-autofocus--spectrum-web-components.netlify.app/components/tabs/

**Comment by Westbrook** [comment]
Does it feel like either of these are enough of a qualitative benefit to users to ship on this?
- [current item nav scrolling](https://docs-nav-scroll--spectrum-web-components.netlify.app/components/tab-panel/)
- [nav grouping and autofocus](https://docs-groups-autofocus--spectrum-web-components.netlify.app/components/tab-panel/)

**Comment by najikahalsema** [comment]
I like the nav grouping and autofocus. Looks great.
