### ISSUE TITLE
Manage console interactions at test time

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#2464]
Build a utility function to make setting up dev mode tests more standardized.

_Originally posted by @castastrophe in https://github.com/adobe/spectrum-web-components/pull/2257#discussion_r932298002_

-- 

Consume lit dev mode comments
Consume swc dev mode comments
Normalise testing console interactions

**Comment by najikahalsema** [comment]
Console logs should not throw an error in dev mode, which happens currently.
