### ISSUE TITLE
[Bug]: the sp-grid renderItem callback sometimes passes undefined

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#2465]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-grid

### Expected behavior

If sp-grid `items` are all defined, `renderItem` is never called with an `undefined` value.

### Actual behavior

Received a bug report that, with an Array of `items` where every item is defined, the `renderItem` callback is sometimes passed an `undefined` value.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

This needs a minimal reproduction in order for us to write a regression test that verifies the fix moving forward.

**Comment by Westbrook** [comment]
This seems like it may have been addressed upstream. Please open a new issue with expanded reproduction steps if you continue to experience this situation.
