### ISSUE TITLE
[Bug]: Tooltips hosted in Dialogs interfere with focus

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#2483]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

tooltip, dialog, overlay, overlay-trigger

### Expected behavior

Tooltips open and close without changing focus, in all contexts.

### Actual behavior

Tooltips initiated in dialogs change the focused element.

### How can we reproduce this issue?

https://studio.webcomponents.dev/edit/HHcNNv46jQ0fluF3x2B9/src/index.ts?p=stories

**Comment by Westbrook** [comment]
@joekukish does this feel more like what you'd want to see here? https://returns-focus--spectrum-web-components.netlify.app/storybook/?path=/story/dialog-wrapped--tooltips
