### ISSUE TITLE
[Bug]: Focus state management for sp-menu

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-web-components#2490]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-menu

### Expected behavior

Focus state should move smoothly through items in the menu with only 1 item receiving focus at a time.

### Actual behavior

Focus state management seems to be altered when a submenu is present and can lead to duplicate focused menu items.

### Screenshots

https://user-images.githubusercontent.com/1840295/183101382-d8ecd183-9926-4e16-97d5-5d08a062a89c.mov

### How can we reproduce this issue?

TODO

### Sample code that illustrates the problem

```html
<sp-menu>
  <sp-menu-item>Item 1</sp-menu-item>
  <section>
    <sp-textfield value="url"></sp-textfield>
    <sp-action-button>Text</sp-action-button>
  </section>
  <sp-divider size="s"></sp-divider>
  <sp-menu-item>Item 2</sp-menu-item>
  <sp-divider size="s"></sp-divider>
  <sp-menu-item>
    Item 3
    <sp-menu slot="submenu">
      <sp-menu-item> Options 3a </sp-menu-item>
      <sp-menu-item> Options 3b </sp-menu-item>
      <sp-menu-item> Options 3c </sp-menu-item>
    </sp-menu>
  </sp-menu-item>
  <sp-menu-item> Item 4 </sp-menu-item>
  <sp-menu-item> Item 5 </sp-menu-item>
</sp-menu>
```

**Comment by castastrophe** [comment]
```
<sp-menu>
  <sp-menu-item>Item 1</sp-menu-item>
  <section>
    <sp-textfield value="url"></sp-textfield>
    <sp-action-button>Text</sp-action-button>
  </section>
  <sp-divider size="s"></sp-divider>
  <sp-menu-item>Item 2</sp-menu-item>
  <sp-divider size="s"></sp-divider>
  <sp-menu-item>
    Item 3
    <sp-menu slot="submenu">
      <sp-menu-item> Options 3a </sp-menu-item>
      <sp-menu-item> Options 3b </sp-menu-item>
      <sp-menu-item> Options 3c </sp-menu-item>
    </sp-menu>
  </sp-menu-item>
  <sp-menu-item> Item 4 </sp-menu-item>
  <sp-menu-item> Item 5 </sp-menu-item>
</sp-menu>
```

**Comment by Westbrook** [comment]
Menu and likely Focus Group/Roving Tab Index are not updating `focusInIndex` to take into account `lastFocusedIndex` as they should. This would allow implied focus return to go to the triggering element here rather than the first element in the Menu.

**Comment by Westbrook** [comment]
The focus now is passed back to the owner of the submenu, rather than the first item in the parent menu, as expected.

Visible focus is passed to the owner of the submenu as long as the `:focus-visible` heuristic is true for the browser. At the same time, the hover state will still follow the mouse. This is an expected outcome.
