### ISSUE TITLE
[Feat]: Option to configure overlay-trigger parent element

### ISSUE THREAD

**Issue by Illusive7Man** [adobe/spectrum-web-components#2502]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay-trigger, sp-popover

### Description of the requested feature

When `overlay-trigger` is placed inside an element that has scrolling, its `click-content` doesn't stay attached to the trigger element. See the screenshot. This is because `active-overlay` is appended to the body and the offset is calculated relative to the body, and instead it should be using the scrollable ancestor.

### Mockups or screenshots

![Screenshot 2022-08-11 111620](https://user-images.githubusercontent.com/8900151/184102060-ea9c8090-2c18-4221-b335-c9df92f0db0b.png)

**Comment by najikahalsema** [comment]
This issue can be abstracted to talk about what kind of behaviour we would like to see in this scenario. Should the overlay follow the trigger, close itself automatically, block scrolling...? Much to think about.
