### ISSUE TITLE
[Bug]: In Safari, grid view is showing a noticable delay on loading more than 60 or 70 cards.

### ISSUE THREAD

**Issue by preethialuru** [adobe/spectrum-web-components#2505]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-grid

### Expected behavior

Ideally, the grid view in safari should work same as chrome.

### Actual behavior

In safari, when we load more than 70 cards using sp-grid, we see a noticeable delay in all the operations on the page. I see the same delay occurring in the grid view [story book](https://grid--spectrum-web-components.netlify.app/storybook/?path=/story/grid--default) (when loaded in safari) when I try to select the cards or do operations on the action bar.

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to 'https://grid--spectrum-web-components.netlify.app/storybook/?path=/story/grid--default' in Safari.
2. Select any card and notice the delay.
3. Try to select multiple cards. You can see the delay in selection.
4. Try to click on any icon in the action bar. You can notice the delay in these operations well.

**Comment by Westbrook** [comment]
Across many intervening changes in the dependencies leveraged herein, I'm no longer seeing a difference between Safari and Chrome in this example.

@preethialuru if you continue to experience a difference here, please feel free to reopen with expanded reproduction steps.
