### ISSUE TITLE
[Bug]: sp-tabs doesn't support vertical quiet version

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2552]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Expected behavior

sp-tabs should support vertical quiet version 
see: https://opensource.adobe.com/spectrum-css/tabs.html#quiet
and https://opensource.adobe.com/spectrum-css/tabs.html#compactverticaltabs

### Actual behavior

vertical sp-tabs doesn't support quiet version

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/CYn9d6TeRbWaK8STmfjE

**Comment by Westbrook** [comment]
Do you feel like these cover the use case you're looking at here? https://e93dca4d63ac5d66d3f4dc69365e2fc5--spectrum-web-components.netlify.app/review/#TabsStories/verticalQuietCompact.png
