### ISSUE TITLE
[Bug]: Tooltip not open on slow pointer enter from the direction it opens towards

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2573]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionButton, ToolTip

### Expected behavior

(Self-managed) tooltip should open (and stay open) when user enters mouse/pointer slowly into/over icon-only action-button.

### Actual behavior

There seems some area after the border of the action-button (icon-only) that triggers pointer-out or pointer-leave event to dismiss the tooltip.
This happens when the user slowly moves the mouse/pointer over the action-button.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/XrdomH5iKve4qnoNo8Vz/src/index.ts
use last row with action-button below "Self managed ToolTip"

**Comment by Westbrook** [comment]
A quick review of this repro page points to this being the Tooltip itself preventing the `pointerover` by being itself _over_ the parent. This can be recreated on other buttons in the page by slowing `pointerenter`ing the buttons from middle top. Tooltips might deserve `pointer-events: none`, at least on the `:not([open])` side with some transition delay to prevent this.

**Comment by spdev3000** [comment]
yes, it only happens from the side where the tooltips is starting to render, for the repro page "bottom"

**Comment by spdev3000** [comment]
@Westbrook Shouldn't that demo be automatically be fixed as it's pulling in latest sp-tooltip package? Seems, that it's still broken at: https://studio.webcomponents.dev/edit/XrdomH5iKve4qnoNo8Vz/src/index.ts

**Comment by Westbrook** [comment]
I'm not currently seeing it broken locally. The versioning with in a demo depends a lot on the current state of caching in your browser. If you hop to a new browser, does it still show the same error for you?
