### ISSUE TITLE
[Bug]: long search terms overlap the "clear text" x button

### ISSUE THREAD

**Issue by chrispaterson** [adobe/spectrum-web-components#2574]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-search

### Expected behavior

When typing a long search query, the text should not overlap the inset "clear text" x button.

### Actual behavior

Opposite of expected behavior (it does)

### Screenshots

![image](https://user-images.githubusercontent.com/1268493/189726255-970435ff-fda5-4c5f-8538-d39bc3275735.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. click into sp-search text box
2. type long term with no breaks

**Comment by Westbrook** [comment]
@pfulton do you think this might be something that will "just work" post Core Tokens, or is this something we should get a specific ticket for on the CSS side?
