### ISSUE TITLE
[Bug]: No tray behavior with sp-action-menu on Android

### ISSUE THREAD

**Issue by HenryPing** [adobe/spectrum-web-components#2575]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ProjectX

### Expected behavior

On Mobile, sp-action-menu is supposed to display its menu items within in tray from the bottom of the screen.

### Actual behavior

No tray, instead, sp-action-menu display its menu items within in popover style on Android as it does on desktop. This happens in both ProjectX shell app on Android and Chrome browser on Android.

More details/discussion can be seen at this Slack thread:
https://cclight.slack.com/archives/CESK60MQD/p1662762810680189

### Screenshots

<img width="398" alt="Screen Shot 2022-09-12 at 3 28 58 PM" src="https://user-images.githubusercontent.com/1392203/189769784-07d3e66b-7b2b-40ad-b00e-fc28ec8c3b51.png">
<img width="495" alt="Screen Shot 2022-09-12 at 3 29 55 PM" src="https://user-images.githubusercontent.com/1392203/189769878-7ac20a0a-fe82-4f1c-a02a-17d33f650d53.png">
![Uploading Screen Shot 2022-09-12 at 3.29.55 PM.png…]()

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

There are 2 ways:

1. ProjectX on Android
   - Install and launch ProjectX shell app on Android device
   - open an existing document
   - tap the page adornment("... Page 1") at the top of the page
   - The page adornment menu items are shown as popover instead of tray, attached image 1

2. Chrome on Android:
   - Open sp-action-menu example( https://opensource.adobe.com/spectrum-web-components/components/action-menu/ ) in Chrome
   - Tap the "... More Action" 
   - The menu items are shown as popover instead of tray, attached image 2

**Comment by Westbrook** [comment]
@HenryPing have you been able to confirm this state in the context of an actual device? I'd be interested in knowing if this is failing on `pointer: coarse` as it seems you're on an emulator, which would mean it could read you mouse as `pointer: fine`... 🤔 A quick test would be to be whether the docs site loads in `medium` or `large` scale by default in this context, as it also uses roughly the same media query.

**Comment by HenryPing** [comment]
Yes, it is on the actual device. I used Vysor to mirror the device screen to my  desktop to make it easier to take image & video.

My android device info:
Samsung S21
Android version: 12
Chrome version: 105.0.5195.79

**Comment by Westbrook** [comment]
Shared this info to https://bugs.chromium.org/p/chromium/issues/detail?id=1384181

**Comment by najikahalsema** [comment]
It seems like the bug was addressed per [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1384181#c23) on Friday. Perhaps we can test the latest version of Chromium on Android and see if this is still reproducible? @HenryPing

**Comment by Westbrook** [comment]
Chromium/Android has since shipped updates that should normalize this delivery context.
