### ISSUE TITLE
docs: Remove light.css file from documentation folder

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#2622]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

There's a file called `light.css` that is empty and should be removed from the documentation folder.

**Comment by mgueyraud** [comment]
Hi @najikahalsema , are you talking about this file: https://github.com/adobe/spectrum-web-components/blob/main/projects/documentation/src/components/light.css ?

**Comment by najikahalsema** [comment]
@mgueyraud Yes, I am. I haven't gotten around to it, though.

**Comment by mgueyraud** [comment]
I can delete it if you want, you can assign it to me.
