### ISSUE TITLE
[Bug]: sp-popover dismisses unexpectedly

### ISSUE THREAD

**Issue by hooplapunta** [adobe/spectrum-web-components#2625]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-popover

### Expected behavior

Include `sp-popover` with `overlay-trigger` and a `<div><sp-icon></sp-icon></div>` as the trigger.
Hover over the icon
`sp-popover` should remain visible on hover

### Actual behavior

Depending on angle of approach (e.g from the top or outside the icon content), `sp-popover` renders briefly then immediately dismisses

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

See sample code
Hover over icon from different approaches, especially from the top.

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/fbq8OMs9JW82nZ1YBVpP/
https://studio.webcomponents.dev/edit/KVdD0QHXejirkE1YNbi2/

**Comment by hooplapunta** [comment]
Have been told this is a tip/margin issue for the positioning of the popover

**Comment by najikahalsema** [comment]
When the overlay appears, part of its rect is going over the trigger then and then basically saying you're not hovering the trigger anymore, and then it disappears.

**Comment by hunterloftis** [comment]
I'm afraid the linked samples don't seem to work (load), unless this is a temporary issue:

![image](https://github.com/adobe/spectrum-web-components/assets/364501/bf3c0691-5c5d-4ecb-89e9-ac2054d5c5cd)

**Comment by Westbrook** [comment]
I'm getting these pages to load again, and the situation therein _should_ be addressed by the [new Overlay API](https://github.com/adobe/spectrum-web-components/discussions/2764). We're currently on track for a July 2023 release of this update.
