### ISSUE TITLE
[Bug]: sp-tabs indicator location is unpredictable on Safari

### ISSUE THREAD

**Issue by nickschaap** [adobe/spectrum-web-components#2629]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tabs

### Expected behavior

The current tab indicator should be directly under the current active tab and take up no more width that the tab button itself.

### Actual behavior

The tab indicator is really unpredictable and does not seem to align with the active tab.

### Screenshots

![image](https://user-images.githubusercontent.com/4684894/193290892-588360cc-6181-4a92-942f-1e85aab08a7c.png)

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to the Spectrum Web Components docs site on Safari
2. Click on Tabs
3. See indicator for tabs

**Comment by monkeyjabs** [comment]
It seems like on Safari and Firefox, the left margin of the containing parent is affecting the calculation. I have a simple example here to show the issue:
https://grjxcb.csb.app/

The larger the left margin, the farther the indicator gets pushed
![PixelSnap 2022-10-10 at 22 15 17](https://user-images.githubusercontent.com/4380525/195002692-dc2e7a25-f1f1-4d45-bf34-d0d691ac6079.png)

**Comment by nickschaap** [comment]
@chrisbank Identified a workaround for clients by explicitly setting the CSS position of the sp-tabs element as relative.
