### ISSUE TITLE
[Feat]: Slider with variant filled get a new starting point

### ISSUE THREAD

**Issue by MutuTeodor** [adobe/spectrum-web-components#2640]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Description of the requested feature

We need to implement a Slider that can have the fill start from a different origin. Currently, the fill to start from the left side of the slider.

### Mockups or screenshots

<img width="574" alt="image" src="https://user-images.githubusercontent.com/115152237/194293925-dcd10fdf-f27e-4679-b7b8-bbcd6b55d0f1.png">

**Comment by Westbrook** [comment]
This is a duplicate of #586
