### ISSUE TITLE
[Bug]: dismissing an overlay twice, quickly, breaks the overlay in question

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-web-components#2646]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay,dialog

### Expected behavior

Pressing escape N times, or clicking on an underlay N times, no matter how fast, does not impact the future behavior of overlays.

### Actual behavior

Pressing escape twice or clicking on an underlay twice, quickly, can prevent future overlays from opening.

### Screenshots

https://user-images.githubusercontent.com/364501/194432655-23f81f5f-b8a4-457a-a716-554c877a4849.mov

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/dialog-wrapper/
2. Click "toggle dialog"
3. Double-click on its underlay quickly
4. Click "toggle dialog"
5. Notice that no dialog opens

**Comment by Westbrook** [comment]
Seems like there should be a pretty direct way to gate this duplication on state under the covers.

**Comment by najikahalsema** [comment]
The overlay may not be prepared to accept a close event while it's awaiting a promise or some other async event... Should investigate the underlying cause and if this relates to the lifecycle of the component.
