### ISSUE TITLE
[Bug]: Button with self-managed tooltip doesn't trigger overlay close on first click

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2647]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tooltip, Button

### Expected behavior

When I have a button with self-managed tooltip and another open overlay - clicking that button should close that overlay. 

### Actual behavior

Clicking the button just closes the tooltip but not the opened (other) overlay

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/agr8E5xHIqmrd6P82trn
2. Click on first button to open overlay
3. Hover over 2nd button, click button 
4. Overlay won't be closed
5. Try 3rd button without self-managed tooltip: click closes the overlay

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/agr8E5xHIqmrd6P82trn

**Comment by spdev3000** [comment]
@najikahalsema I haven't updated in our project yet, but can confirm, the webcomponents.dev test project works fine.

**Comment by najikahalsema** [comment]
Great. Thank you for the update! @spdev3000
