### ISSUE TITLE
[Bug]: missing the decimal point on iOS keyboard if enter the editable <sp-slider>

### ISSUE THREAD

**Issue by wyanghz1** [adobe/spectrum-web-components#2674]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

<sp-slider>

### Expected behavior

the iOS keyboard should have "." (the decimal point)

### Actual behavior

no decimal point on iOS keyboard

### Screenshots

![image](https://user-images.githubusercontent.com/116198819/197063896-802a8c87-bd65-4ac0-bea6-05b9fb3e24f6.png)

### How can we reproduce this issue?

missing the decimal point on iOS keyboard if enter the editable <sp-slider>.

I tried with my iPhone to open the spectrum component website https://opensource.adobe.com/spectrum-web-components/components/slider/ , and found the keyboard doesn’t show the point there even the numeric input box is for floating number. see screenshot.
Steps:
1. with iPhone, 
2. open spectrum component website https://opensource.adobe.com/spectrum-web-components/components/slider/
2. tap on the numeric input of the slider
4. Check the keyboard
5. Missing decimal point

**Comment by MutuTeodor** [comment]
@Westbrook a possible solution wouldn't be to always trigger the numeric keyboard for iOS devices? This can be achieved by changing the input type of the element to `number` and applying the following attribute `pattern="-?[0-9]+\.?[0-9]*"`. This approach will also offer an unified experience for iOS users. 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/115152237/199245948-6178f387-b7b4-45e6-a9f6-a968e44d49f7.png">

**Comment by Westbrook** [comment]
As per https://github.com/adobe/spectrum-web-components/pull/2694 I think the number pad with decimal, or language specific separator, is most appropriate here. This will support users in finding the best possible input in the shortest possible time.
