### ISSUE TITLE
[Bug]: Overlayed popover with action buttons with self-managed tool-tips closes when button is clicked

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2693]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay // OverlayTrigger

### Expected behavior

Opened popover within overlay-trigger containing action buttons with self-managed tooltips should not close when user clicks on one of those containing action buttons.

### Actual behavior

When a user clicks on an action button with self-managed tooltips the popover containing those buttons will be closed.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/tz9nxXPZYJAZp4XZbZ2a
2. Click on left button to open popover with action buttons
3. Hover over buttons to verify tooltips are displaying
4. Click button
5. Overlaid popover dismisses
6. Compare with overlay triggered by second main button
7. This popover doesn't dismiss on action button clicks

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/tz9nxXPZYJAZp4XZbZ2a

**Comment by Westbrook** [comment]
Can you help confirm that this is the expected behavior in this case: https://overlay-stack-mangement--spectrum-web-components.netlify.app/storybook/?path=/story/overlay--deep

**Comment by spdev3000** [comment]
Yes, this is the expected behavior, thanks @Westbrook
