### ISSUE TITLE
[Bug]: Overlay containers do not expand past the original height from when they were set in Chrome

### ISSUE THREAD

**Issue by nickschaap** [adobe/spectrum-web-components#2772]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Expected behavior

When the browser viewport height increases the overlay container continues to fill up the inner viewport height and any overlaid content such as modal content remains centered.

### Actual behavior

In Chrome open dialogs do not remain centered vertically in the window when the viewport height is increased in Chrome.

### Screenshots

https://user-images.githubusercontent.com/4684894/204649694-26d69e9c-3da2-4efc-bef9-a60ac8e98093.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

See screenshare

**Comment by Westbrook** [comment]
Need to work through some more tests to confirm, but I'm looking at this being the right update here: https://overlay-container--spectrum-web-components.netlify.app/components/dialog-wrapper/
