### ISSUE TITLE
[Bug]: Picker component is failing to open in Vite project

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#2775]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Picker

### Expected behavior

Picker component should open with menu

### Actual behavior

The picker throws an error and fails to open.

The error occurs at [this line of code](https://github.com/adobe/spectrum-web-components/blob/main/packages/picker/src/Picker.ts#L298). 

```Typescript
        this.popover = this.popoverFragment.children[0] as Popover;
        this.optionsMenu = this.popover.children[1] as Menu;
```

After executing this line of code, the value of `this.popover` should be a Popover. I have confirmed that `this.popoverFragment.children[0]` is a valid Popover. However, after executing the line, the value of `this.popover` is the string `"manual"`.

I'm am currently stumped as to why that is.

### Screenshots

<img width="583" alt="Screenshot 2022-12-01 at 4 17 35 PM" src="https://user-images.githubusercontent.com/154097/204957868-095cf276-d7f8-4eee-8b10-ed2aa9567831.png">

### How can we reproduce this issue?

1. Download the sample code project and untar it
2. `cd picker-test`
3. `yarn install`
4. `yarn dev`
5. click on the link from the console
6. in your browser, verify that the picker looks ok (code was taken from docs page)
7. click on the picker to open the menu and watch the page get mangled
8. see the error in the console

### Sample code that illustrates the problem

[picker-test.tgz](https://github.com/adobe/spectrum-web-components/files/10128973/picker-test.tgz)

### Logs taken while reproducing problem

```
@spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1860 Found a 'popover' attribute with an invalid value.
generatePopover @ @spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1860
openMenu @ @spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1866
update @ @spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1988
performUpdate @ chunk-YPMMEVVJ.js?v=27adc4e7:455
scheduleUpdate @ chunk-YPMMEVVJ.js?v=27adc4e7:419
__enqueueUpdate @ chunk-YPMMEVVJ.js?v=27adc4e7:412
await in __enqueueUpdate (async)
requestUpdate @ chunk-YPMMEVVJ.js?v=27adc4e7:401
set @ chunk-YPMMEVVJ.js?v=27adc4e7:232
toggle @ @spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1847
onButtonClick @ @spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1778
handleEvent @ chunk-YPMMEVVJ.js?v=27adc4e7:1323
@spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1861 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
    at Picker.generatePopover (@spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1861:45)
    at Picker.openMenu (@spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1866:16)
    at Picker.update (@spectrum-web-components_picker_sp-picker__js.js?v=75c2e3c5:1988:14)
    at Picker.performUpdate (chunk-YPMMEVVJ.js?v=27adc4e7:455:14)
    at Picker.scheduleUpdate (chunk-YPMMEVVJ.js?v=27adc4e7:419:17)
    at Picker.__enqueueUpdate (chunk-YPMMEVVJ.js?v=27adc4e7:412:25)
```

**Comment by cuberoot** [comment]
I'm closing this. It looks like it is a problem with the nightly Chrome Canary build. I cannot reproduce it in the released version of Chrome.

**Comment by Westbrook** [comment]
Relates to https://github.com/adobe/spectrum-web-components/pull/2757

**Comment by cuberoot** [comment]
This is now logged with Google [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1395159).

**Comment by Westbrook** [comment]
I listed that PR because it's a known issue of upcoming browser specs taking over that property name. I don't believe it to be a browser bug, and with the next SWC release you will no longer need to worry about it at all.

**Comment by cuberoot** [comment]
Ah, cool! Thanks
