### ISSUE TITLE
[Bug]: Slider inside popover doesn't get cancel event on Esc

### ISSUE THREAD

**Issue by bianca-mihaela-stan** [adobe/spectrum-web-components#2783]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider, sp-popover

### Actual behavior

We have an `sp-slider` inside an `sp-popover`. If you press Esc while sliding the slider, the popover closes, but the `sp-slider` doesn’t get a cancel event. So if you open the popover again, you will be able to move the popover just by hovering on the slider, without starting a new action with a click.

### Screenshots

https://user-images.githubusercontent.com/55094172/205979542-7e3dfe24-c206-4f36-99af-f572656f8e93.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Add an sp-slider inside an sp-popover
2. Click and start moving the slider
3. While moving the slider, press Escape
4. The popover will close, open it again
5. Hover over the slider and observe how the slider moves without having to click it.

**Comment by Westbrook** [comment]
This should corrected in https://github.com/adobe/spectrum-web-components/pull/3113 which was released as of version [0.15.11](https://github.com/adobe/spectrum-web-components/blob/main/packages/slider/CHANGELOG.md#01511-2023-04-24). If you continue to experience this situation, please feel free to reopen issue with further information.
