### ISSUE TITLE
[Bug]: Documentation has wrong code samples styles in Firefox

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#2793]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

documentation

### Expected behavior

Styles should be same as in chrome.

### Actual behavior

They are different and because of that, the code is hard to read.

### Screenshots

![image](https://user-images.githubusercontent.com/1174072/207043401-6fa5ea0f-1cc3-4ba9-a3df-b13c8c9f9236.png)

### What browsers are you seeing the problem in?

Firefox

### How can we reproduce this issue?

1. Go to any code example

**Comment by nickschaap** [comment]
I'm seeing this issue in Chrome and Safari as well

**Comment by Westbrook** [comment]
Certainly hate when code stops working and then you can't track how it ever did in the first place! 😳 Putting a fix in now.
