### ISSUE TITLE
[Bug][Swatch Group]: `selects="single"` doesn't clear selection upon deselecting

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#2812]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-swatch-group

### Actual behavior

`<sp-swatch-group selects="single">` doesn't remove the selection (clear the array) if a `selected` swatch is clicked to be deselected. This behaviour occurs in `selects="multiple"` though.

### How can we reproduce this issue?

1. Go to [this story](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/swatch-group--selects-single)
2. Click on one of the swatches to populate the `selected` array at the bottom
3. Click that same swatch to deselect it
4. Notice the swatch selection continues to maintain the single selection

For comparison:
1. Go to [this story](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/swatch-group--selects-multiple)
2. Click the swatches to deselect them, watching the array as you do so
3. Notice the swatch selection empties once all the swatches are deselected

**Comment by Westbrook** [comment]
Generally the functionality that we ship in a `selects="single"` context and it specifically parallels the relationship between "[radio buttons](https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/radio)" (`selects="single"`) and "[checkboxes](https://developer.mozilla.org/ja/docs/Web/HTML/Element/input/checkbox)" (`selects="multiple"`). In that way, I'd say that _by default_ the Color Swatch allowing itself to be deselected in this case is the bug. I could see expanding the Color Swatch Group element to support something like a `toggles` attribute that would allow for the selection array to be emptied, but for a first path normalizing to the other elements in the library seems like the better path forward.
