### ISSUE TITLE
Named export 'IconsetRegistry' not found when used in Svelte

### ISSUE THREAD

**Issue by omar2205** [adobe/spectrum-web-components#2820]
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

ALL

### Actual behavior

I'm trying to use this library with Sveltekit. When building the project and running it I get Named export 'IconsetRegistry' not found.

The full error:
```
SyntaxError: Named export 'IconsetRegistry' not found. The requested module '@spectrum-web-components/iconset/src/iconset-registry.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@spectrum-web-components/iconset/src/iconset-registry.js';
const {for(var i=t>1?void 0:t?l(r,e):r,n=s.length-1,a;n>=0;n--)(a=s[n])&&(i=(t?a(r,e,i):a(i))||i);return t&&i&&p(r,e,i),i};import{html: c}from"@spectrum-web-components/base";import{property: d,query: m}from"@spectrum-web-components/base/src/decorators.js";import{ifDefined: u}from"@spectrum-web-components/base/src/directives.js";import{IconsetRegistry: h}from"@spectrum-web-components/iconset/src/iconset-registry.js";import{IconBase: v}from"./IconBase.js";export class Icon extends v{constructor(){super(...arguments);this.iconsetListener=e=>{if(!this.name)return;const t=this.parseIcon(this.name);e.detail.name===t.iconset&&(this.updateIconPromise=this.updateIcon())}}connectedCallback(){super.connectedCallback(),window.addEventListener("sp-iconset-added",this.iconsetListener)}disconnectedCallback(){super.disconnectedCallback(),window.removeEventListener("sp-iconset-added",this.iconsetListener)}firstUpdated(){this.updateIconPromise=this.updateIcon()}attributeChangedCallback(e,t,i){super.attributeChangedCallback(e,t,i),this.updateIconPromise=this.updateIcon()} = pkg;
```

**Comment by Westbrook** [comment]
There is no default export from the file in question. That means that the following code will fail, always:

```
import pkg from '@spectrum-web-components/iconset/src/iconset-registry.js';
```

The expected usage is more like:

```
import { IconsetRegistry } from '@spectrum-web-components/iconset/src/iconset-registry.js';
```

Would you be able to share more of what you are attempting to accomplish with this code so that we can support you in finding a path to consuming the package successfully?

**Comment by omar2205** [comment]
Sorry if I didn't provide the full code. I just created a Sveltekit project and tried to use the `bundle/elements.js`. When I build the project, I get the above error.

You can try it here https://stackblitz.com/edit/sveltejs-kit-test-spectrum-web-components 

Try to build the project with `yarn build`

**Comment by Westbrook** [comment]
I can't really speak to how SvelteKit builds its code. I can assure you that the package in question is not a CommonJS module, and as such there has to be something about the way that SvelteKit is interacting with the package that is at fault. It would be good to discuss with their community what the tooling therein might be doing to cause this issue.

**Comment by szundel** [comment]
I have the same error when I use astro.

**Comment by omar2205** [comment]
I think it might be an issue with _Vite_

**Comment by Westbrook** [comment]
@omar2205 I'm not seeing this is a Vite project focused on consuming web components: https://stackblitz.com/edit/vitejs-vite-udhvmc?file=package.json,src%2Fmy-element.ts,vite.config.ts&terminal=dev built from https://stackblitz.com/edit/vitejs-vite-crnylq?file=index.html&terminal=dev As mentioned before, I'm not a Vite pro, but maybe from this project you could divine the config delta that is causing this issue.

**Comment by omar2205** [comment]
Maybe Sveltekit and Astro are doing something extra that causes this issue.

**Comment by szundel** [comment]
I think it has something to do with the vite ssr because Astro and Sveltekit are likely both Server Side Rendering. I thought it could be related to this open bug for hoisting in Vite:
https://github.com/vitejs/vite/issues/10444

**Comment by szundel** [comment]
I'm still investigating my issue with this in astrojs, but I don't seem to see the issue now that I switched from yarn to npm. 

I thought this was somehow related to Vite's SSR dyanamic imports, but I don't run into this issue anymore using npm (before I was using Yarn). Before npm I also tried pnpm but with pnpm I saw another error with a different module that I was trying to import.

**Comment by najikahalsema** [comment]
not planned
