### ISSUE TITLE
Getting Spectrum components to work inside UXP panels

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#2821]
How do I get spectrum components to work in UXP panels. I am getting some component support, invisible components and when I try to import I'm getting errors. 

Without importing anything the SP-Switch component sort of works. The Tabs component and related shows nothing. The Action Menu shows some parts of the component. 

More details here: 
https://forums.creativeclouddeveloper.com/t/how-to-use-spectrum-components-in-uxp-plugin/5625

**Comment by beeduul** [comment]
Please reach out to UXP support via https://forums.creativeclouddeveloper.com/ to discuss SWC support in UXP.

**Comment by velara3** [comment]
Related discussion: 

https://forums.creativeclouddeveloper.com/t/how-to-use-spectrum-components-in-uxp-plugin/5625/10

Quote

> To add, I’d like to clarify a few things. 

>Spectrum Web Components and Spectrum support in UXP are fundamentally different, in that, native Spectrum Widgets are in-built in UXP and don’t require any external imports. 

>UXP only supports the ones listed here under [Typography 1](https://developer.adobe.com/xd/uxp/uxp/reference-spectrum/Typography/) and [User Interface 1](https://developer.adobe.com/xd/uxp/uxp/reference-spectrum/User%20Interface/). 

>These native Spectrum Widgets are implementations of Spectrum guidelines and expose a subset of the functionality of the corresponding Spectrum Web Components but are not built atop web components. 

>UXP has added initial support for Web Components commencing with v6.5 and should be rolling out support for the usage of a limited set of Spectrum Web Components (the ones listed [here 4](https://opensource.adobe.com/spectrum-web-components/)) with v7.0.
