### ISSUE TITLE
[Bug]: Slider with editable is not accessible using tab key

### ISSUE THREAD

**Issue by Eliza-developer** [adobe/spectrum-web-components#2837]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Slider with editable should be accessed using tab key

### Actual behavior

Slider with editable is not accessible using tab key.

### Screenshots

Slider with editable is not accessible:
https://user-images.githubusercontent.com/110098771/211282856-c07e3de1-35a5-4782-a6c4-60ef598ae99a.mov

Other sliders are accessible:

https://user-images.githubusercontent.com/110098771/211283009-eee9cc93-dfa0-4ac8-b8d2-ff527da98541.mov

Code snippet where tabindex value is assigned as -1 for which the issue is caused:
<img width="1270" alt="Code snippet" src="https://user-images.githubusercontent.com/110098771/211283121-87e5e88d-c41a-44df-a137-8ad9ada6ed54.png">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

<img width="1270" alt="Code snippet" src="https://user-images.githubusercontent.com/110098771/211283240-5bea141f-08b2-4429-9386-0d8b1a3ebb77.png">

**Comment by najikahalsema** [comment]
Duplicate issue
