### ISSUE TITLE
[Bug]: KB "Enter" event does not work correctly with Japanese IM

### ISSUE THREAD

**Issue by iooi** [adobe/spectrum-web-components#2857]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

TextInput

### Actual behavior

Button should not receive "click" event when pressing Enter, while Japanese IME is on.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Change keyboard layout to JP keyboard and input some characters to the input field
2. While IME window is displayed , clicking on Enter

### Sample code that illustrates the problem

https://github.com/adobe/spectrum-web-components/blob/main/packages/button/src/ButtonBase.ts#L167

**Comment by Westbrook** [comment]
Curious how you are able to keep IME open while focusing on a button in order for it to receive the keyboard event in this case. Could you share some more information on a reproduction?

**Comment by iooi** [comment]
The issue is not for WC after more debug.
