### ISSUE TITLE
[Bug]: sp-textfield grows option causes a very squashed textfield

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-web-components#2862]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Textfield

### Expected behavior

I thought `<sp-textfield grows>` would grow horizontally when the user types just like `<sp-textfield multiline grows>` grows vertically as line breaks are added.

### Actual behavior

It gets squished!

### Screenshots

<img width="246" alt="image" src="https://user-images.githubusercontent.com/201344/213530737-01b43235-963b-4ba1-8dbc-07e2ca3dc129.png">

### How can we reproduce this issue?

1. Create a textfield with `<sp-textfield grows></sp-textfield>`
2. Observe the squishiness

### Sample code that illustrates the problem

```html
<sp-textfield grows></sp-textfield>
```

**Comment by Westbrook** [comment]
`grows` should not apply without `multiline`. We'll clamp down the logic on those values to ensure quality visual delivery in these cases.
