### ISSUE TITLE
Docs: convert API Table to use <sp-table>

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#2863]
On the docs site, the current API table is built with Spectrum CSS. We should update this to use the `<sp-table>` component, since we have it now.

**Comment by Westbrook** [comment]
An old draft of this is available [here](https://github.com/adobe/spectrum-web-components/tree/api-docs-table) for reference. It currently supports a very fixed layout, which is very different than what the `<table>` approach gave up.

`<table>`
<img width="975" alt="image" src="https://user-images.githubusercontent.com/1156657/213540994-a0883f9f-bfe7-4a8b-9913-fe593a6eccb6.png">

`<sp-table>`
<img width="977" alt="image" src="https://user-images.githubusercontent.com/1156657/213541112-49b78248-7c99-43b8-b8fe-0cb4a475ed40.png">

Notice the forced overflow scrolling, even when the content could "collapse" while still looking correct.

This may be a hard requirement for `<sp-table>` while `subgrid` is not available x-browser, but it would be good to have a solid perspective on delivering `<sp-table>` in responsive contexts for our consumers.

**Comment by Westbrook** [comment]
This went in some while back and didn't get closed at merge time. Shipped!
