### ISSUE TITLE
Implement `sp-table` component

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#290]
### Expected Behaviour
We shouldn't have to rely on Spectrum CSS directly for our documentation site. We're pointing to the `table` sheet, we should have a component or a pattern that supports including that in a page easily.

### Actual Behaviour
https://opensource.adobe.com/spectrum-css/table.html

**Comment by hunterloftis** [comment]
Review pre-1.0.

**Comment by Westbrook** [comment]
@lastmjs there should be no trouble implementing something in Spectrum CSS inline with things shipped via SWC. You would benefit from ensuring that the version of the Spectrum CSS package you are leveraging depends on the same Spectrum CSS Vars package that is leveraged in `<sp-theme>`, assuming you use that, in order to make sure there are no subtle rendering bugs, but other than that, you should be good to go.

We are just beginning work with a team that intends to consumer the `sp-table` pattern, so hopefully we'll also have an update on SWC native support for this pattern, soon.

Cheers!

**Comment by lastmjs** [comment]
I'm super excited for `sp-table`! Once that is implemented we might make a full switch over. Thanks!
