### ISSUE TITLE
[Bug]: Spectrum Web Components - Bundle incorrect copy

### ISSUE THREAD

**Issue by bangank36** [adobe/spectrum-web-components#2902]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

All

### Expected behavior

I found some spelling issues when reading this page: https://opensource.adobe.com/spectrum-web-components/tools/bundle/
Below is the correct words in **bold**

> @spectrum-web-components/bundle is a master **dependency** that allows a project to import any and all of **the** Spectrum Web Components. While it is a great approach to prototyping, the fact that is versions all of the Spectrum Web Components packages collectively means that depending on it can leave you with a lot of package **updates** to manage at any one version change. For a more **predictable** upgrade process we suggest that you depend upon individual packages directly, but hope you find this bundle productive when initially trying to get into the act of developing with Spectrum Web Components!

### Actual behavior

@spectrum-web-components/bundle is a master **dependancy** that allows a project to import any and all of **the the** Spectrum Web Components. While it is a great approach to prototyping, the fact that is versions all of the Spectrum Web Components packages collectively means that depending on it can leave you with a lot of package **udpates** to manage at any one version change. For a more **predicatable** upgrade process we suggest that you depend upon individual packages directly, but hope you find this bundle productive when initially trying to get into the act of developing with Spectrum Web Components!

### How can we reproduce this issue?

1. Go to [this link](https://opensource.adobe.com/spectrum-web-components/tools/bundle/)
2. View the document
3. The document is defined in this .md file [README.md](https://github.com/adobe/spectrum-web-components/blob/729adb1b84bcb1f66bfa21229784b89454ffd7c4/tools/bundle/README.md)

**Comment by Westbrook** [comment]
closed by  #2903
