### ISSUE TITLE
bug(sp-picker):  Picker doesn't close on scroll and is switching placement because of that

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#2904]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker, overlay

### Expected behavior

Placement should maintain its location. 

### Actual behavior

The overlay isn't closing upon scrolling, which causes the overlay to shift from bottom placement to the top. 

### Screenshots

https://user-images.githubusercontent.com/44980010/217058444-a119eb41-31a8-44c5-ac78-f3bb76d70114.mov

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by najikahalsema** [comment]
cc @pwong09

**Comment by pwong09** [comment]
The other issue with `sp-picker` is the way the overlay's height increases (presumably forever) while the user scrolls down the main webpage due to its height set to 100%. I had expected the overlay's height to stay static while I scroll outside of it.

**Comment by Westbrook** [comment]
As of #3456 the `<sp-picker>` and related elements close on scroll.
