### ISSUE TITLE
[Bug]: action-menu doesn't support nested <sp-action-group selects="single">

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#2913]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Expected behavior

Action menu should support both a nested menu group that's selectable and one that isn't in the same menu (in our use case, we have a sort menu that has a non-selectable "reverse order" option):

```
<sp-action-menu selects="none">
  <sp-menu-group selects="single">
     <sp-menu-item>Selectable 1</sp-menu-item>
     <sp-menu-item>Selectable 2</sp-menu-item>
  </sp-menu-group>
  <sp-menu-group>
    <sp-menu-item>Not selectable</sp-menu-item>
  </sp-menu-group>
</sp-menu-menu>
```

### Actual behavior

It seems like the menu groups inherit the `sp-action-menu` selects setting and doesn't allow overriding (unlike doing the same in `sp-menu`, which works).

**Comment by Westbrook** [comment]
`selects="none"` isn't a valid attribute/value pari for Action Menu. Can you take a look at https://studio.webcomponents.dev/edit/EYQn9T6wOnieZbv4xnPj?branch=multi-group%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories and see if either of those options behaves as you'd like here?

**Comment by najikahalsema** [comment]
Revisit issue once overlay v2 is implemented

**Comment by hunterloftis** [comment]
Closing as stale after confirming that a two sibling groups can have two different selects values, eg:

```html
      <sp-action-menu>
        <sp-menu-group selects="single">
          <sp-menu-item>Selectable 1</sp-menu-item>
          <sp-menu-item value="two">Selectable 2</sp-menu-item>
        </sp-menu-group>
        <sp-menu-group selects="inherit">
          <sp-menu-item>Not selectable</sp-menu-item>
        </sp-menu-group>
      </sp-action-menu>
```
