### ISSUE TITLE
[Feat]: tooltip for action-menu

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2916]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu

### Description of the requested feature

We'd like to use sp-tooltip in combination with an ActionMenu, in theory this works with extra `<overlay-wrapper>` where `<sp-action-menu>` triggers the hover-content with `<sp-tooltip>` in it.
However that leads to flickering issues when the action-menu was open and after it has been closed.
Ideally ActionMenu would provide a `slot=tooltip` (or similar) to provide such an tooltip when hovering over the trigger item of that ActionMenu.

**Comment by Westbrook** [comment]
@anishAdobe the `slot="tooltip"` approach here seems like it would be a better idea than taking attributes for this content. It would afford full API support for the Tooltip (`placement`, `delay`, etc.) while also allowing full HTML content (keyboard shortcuts, or similar) within the Tooltip.

**Comment by anishAdobe** [comment]
Updated the PR with required changes.

**Comment by Westbrook** [comment]
Fixed by #3488
