### ISSUE TITLE
[Feat]: SliderHandle animation onPointerdown

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#2917]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

SilderHandle

### Description of the requested feature

We'd like to have a little SliderHandle animation like in Lightroom Web (see screencast), it can be also seen in Spectrum, see: https://spectrum.adobe.com/page/slider/#Double-click-to-reset

Lr Web seems to have a
```
transition: border-width 100ms ease-out;
```
with border-width from 2px to 6px - which seems good to me.

### Mockups or screenshots

https://user-images.githubusercontent.com/29090947/217575912-c9256bd5-73be-4fc9-97ca-c29356b6867d.mov

**Comment by Westbrook** [comment]
@pfulton this seems to track back to https://github.com/adobe/spectrum-css/blob/main/components/slider/index.css#L276, do you think we could get this addressed in the Core Tokens work for this pattern?

**Comment by Westbrook** [comment]
Oh, it looks like it might be fixed in the WIP branch, already: https://slider-core-tokens--spectrum-web-components.netlify.app/components/slider/ ❗❗❗

**Comment by pfulton** [comment]
@Westbrook you're correct. This should be in with the migrated component work. There was an issue filed for it a few weeks ago: https://github.com/adobe/spectrum-css/issues/1583
