### ISSUE TITLE
[Feat]: Provide an API to be able to identify the overlay that opened or closed

### ISSUE THREAD

**Issue by joekukish** [adobe/spectrum-web-components#2939]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Description of the requested feature

Currently {{sp-closed}} and {{sp-opened}} are called on the owner of the overlay, the problem is that there is no way, from the event to identify which component triggered the event.

Ideally `event.relatedTarget` or `event.detail.target` would refer to the component that triggered the event.

**Comment by Westbrook** [comment]
If we were to expand `OverlayOpenCloseDetail` to include an `overlayEl` property (or similar), could you share via some examples which element you'd expect this to point to? In the context of the [new Overlay API](https://github.com/adobe/spectrum-web-components/discussions/2764) all Overlays will be managed via an `<sp-overlay>` element, which would be the easiest element to reference here. However, I'm not sure that actually resolves the situation in which you find yourself.

Resolving some other element may be difficult to do 100% of the time, so your thoughts here will be invaluable in finding whether there's a path to include additional information to event consumers here or not.

**Comment by joekukish** [comment]
@Westbrook ideally it would reflect `event.target` (basically triggered by the component that just opened / closed). `overlayEl` would definitely worked as well, although to me `event.target` (basically part of the event and not part of the detail) is more natural in HTML.

**Comment by joekukish** [comment]
in my case `event.target` points to `af-fontpicker` for both use cases, so I cannot use it to differentiate it. Also some HTML events have `relatedTarget` but if you are triggering a CustomEvent (and you don't want to create your own class), then adding a detail does make sense.

**Comment by spdev3000** [comment]
@Westbrook @najikahalsema is there any plan to continue work on that issue? Would be good to know as we'd like to have such an attribute (or API) that contain a reference to the <sp-overlay> that is actually opening/closing for certain use cases. Thanks!

**Comment by Westbrook** [comment]
@spdev3000 yes, we do plan on working on this. It's not come clear which data is most useful here. You're proposing that the added property hold a reference to the `sp-overlay` element itself that is open/closing? Does that play appropriately in that case that this element is within an `sp-picker` or other composed interface? @joekukish thoughts?

If there were additional use cases that could be shared, we can better ensure that this change to the API surface is in support of all consumers.
