### ISSUE TITLE
[Bug]: lit warning with slider in overlay

### ISSUE THREAD

**Issue by mighdoll** [adobe/spectrum-web-components#2941]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

slider, overlay

### Expected behavior

Lit gives a warning if you click on the button:
```html
      <overlay-trigger>
        <sp-action-button slot="trigger"> </sp-action-button>
        <sp-popover slot="click-content" placement="right" dialog>
          <sp-slider label="histogram bins"> </sp-slider>
        </sp-popover>
      </overlay-trigger>
```

### Actual behavior

in the browser console, see:

```
active-element.ts:76 Element sp-slider scheduled an update (generally because a property was set) after an update completed, causing a new update to be scheduled. This is inefficient and should be avoided unless the next update can only be scheduled as a side effect of the previous update. See https://lit.dev/msg/change-in-update for more information.
```

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

git clone https://github.com/mighdoll/spectrum-experiments
cd spectrum-experiments 
git checkout 164313
pnpm install
pnpm vite

**Comment by Westbrook** [comment]
Not currently seeing this dev mode warning.
