### ISSUE TITLE
[Bug]: sp-tabs-overflow next and previous buttons position is not align then sp-tabs is in compact mode

### ISSUE THREAD

**Issue by monkeyjabs** [adobe/spectrum-web-components#2961]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs-overflow

### Expected behavior

The next/previous scroll button should auto align when sp-tabs is in compact mode

### Actual behavior

The next/previous buttons are lower than the tab label

### Screenshots

![PixelSnap 2023-02-26 at 10 48 26](https://user-images.githubusercontent.com/4380525/221430468-a0b8c5dc-ad4a-4070-a6a2-8965223fe66f.png)

### How can we reproduce this issue?

1. Go to: https://studio.webcomponents.dev/edit/OmrIqazVRHvZAJAvJn4D/src/index.ts?p=stories
2. Observe the Next/Previous button

**Comment by Westbrook** [comment]
closed by #3012
