### ISSUE TITLE
[Bug]: Button text is aligned too high

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#2975]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-button

### Expected behavior

https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/button-primary-fill--default matches https://opensource.adobe.com/spectrum-css/button-primary.html and doesn't look obviously off

### Actual behavior

It looks obviously wrong (Chrome/Mac)

### Screenshots

![Screen Shot 2023-02-28 at 7 51 54 PM](https://user-images.githubusercontent.com/48841507/222024292-ce396ca6-835c-4619-981e-394d7bba7ff9.png)

**Comment by Westbrook** [comment]
Tacking in https://github.com/adobe/spectrum-css/pull/1614
