### ISSUE TITLE
[Bug]: sp-radio label-below no longer supported

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#2976]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-radio

### Expected behavior

Storybook shouldn't include an example of something that's not supported. It should either work or be removed.

### Actual behavior

The label-below variant is documented here, but doesn't work: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/radio--horizontal-label-below-group

**Comment by adixon-adobe** [comment]
We're not actually using this (we just have an example of it on a test page). Noticed it though so filed the issue.

**Comment by Westbrook** [comment]
fixed in #3217
