### ISSUE TITLE
[Feat]: For menu-items, we have the option of specifying a shortcut by using the "value" slot. the gap between the menu-item text and the value slot is very less.

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2984]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Description of the requested feature

For menu-items, we have the option of specifying a shortcut by using the "value" slot. the gap between the menu-item text and the value slot is very less.
It would be good to have a configuration where we can specify the minimum gap between text and shortcut label in menu-item. 

### Mockups or screenshots

<img width="944" alt="image" src="https://user-images.githubusercontent.com/127212746/223432161-4166fc13-8dae-4ed6-acf0-e7a0f353fb23.png">

**Comment by Westbrook** [comment]
Over the course of Q2, a release will be made that surfaces the `--mod-menu-item-label-to-value-area-min-spacing` CSS Custom Property for managing this part of the layout.
