### ISSUE TITLE
[Feat]: Option to show icon to the right of label in Action Menu

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2986]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Description of the requested feature

We need an option to display icon to the right side of the label.
<img width="178" alt="Screenshot 2023-03-07 at 6 48 39 PM" src="https://user-images.githubusercontent.com/127212746/223433596-e1394163-f030-4300-977d-60b5144639d7.png">

**Comment by najikahalsema** [comment]
We brought up with.the design team that this pattern shown is not currently supported by Spectrum, so it's not an issue. If they decide in the future that they'll support this delivery, we'll let you know.
