### ISSUE TITLE
[Feat]: Option to have a custom view as submenu in Menu/Action Menu

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2987]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Description of the requested feature

Option to have a custom view as submenu in Menu/Action Menu
Please see attached for the requirement.
<img width="770" alt="Screenshot 2023-03-07 at 6 50 36 PM" src="https://user-images.githubusercontent.com/127212746/223434114-96a8fa07-15b1-4be9-8a59-bf883093ba61.png">

**Comment by najikahalsema** [comment]
See above example for the conclusion of this issue. We will address this in a uec component in the future (for Document Menu), but closing this for now.
