### ISSUE TITLE
[Bug]: In Spectrum Number field Number format not getting updated as per the resolved language

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2988]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Expected behavior

In German, instead of decimal (.), comma (,) should be used to represent fractional digits.

### Actual behavior

Number format not getting updated as per the resolved language. The doc for spectrum number mentions that the locale would be picked from this.resolvedLanguage. In our case, it is coming correctly, for e.g. as Deutsch but the formatting still happens as per En. 

### Screenshots

<img width="452" alt="image" src="https://user-images.githubusercontent.com/127212746/223434865-e8a8a4fc-5761-417f-b84c-2f3a2dbaabdc.png">

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by bmandal2** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/127212746/223434764-e8d52fcd-985e-4a90-b6fb-b3c6564a7b4f.png">

**Comment by Westbrook** [comment]
The latest version of Number Field does not include a `resolvedLanguage` property: https://github.com/adobe/spectrum-web-components/commit/b7781db820620688f97a40225fb17a10e7881178#diff-bbe60f2ecb5ae23472a9f446b13eaf5000919b731d68bee594c13a930d9b9933L107 Please be sure you're using the latest release.

**Comment by Westbrook** [comment]
You don't need to manage the language at the `sp-number-field` level, but you do need to change it at the `<html>` tag level. However, the versions of `sp-number-field` after `0.5.3` DO NOT have a `resolvedLanguage` property. That means that the code in your screenshot is not representing the usage of version `0.5.10`. Can you confirm that you are leveraging the newest version, which would features a `languageResolver` property instead, and retest? If you continue to experience this issue, we will need a life reproduction of your the situation to ensure the full page implementation of language values is appropriately set. Here's an example with it set appropriately and the `,` used as expected: https://studio.webcomponents.dev/edit/NkWAAWzKWcPu5Kf6wBc8/www/index.html?p=website
