### ISSUE TITLE
[Bug]: In Spectrum Number Field box shadow goes outside the boundary

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#2989]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Expected behavior

No styling should be needed and box shadow shouldn't overflow.

### Actual behavior

Spectrum numberfield issue where box shadow goes outside boundary of numberfield in large scale. As a workaround, we are setting the following fields: 
textField.style.setProperty('overflow', 'hidden'); 
textField.style.setProperty('border-radius', 'var(--spectrum-textfield-m-border-radius,  4px)'); 

### Screenshots

<img width="146" alt="image" src="https://user-images.githubusercontent.com/127212746/223435407-5ba06dbb-64b8-4302-a48c-06c95324b5aa.png">

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
All of the Spectrum designs leverage focus visible states that go outside of their bounding rectangle. In order to faithfully deliver them, it is important not to wrap them in `overflow: ...` containers that cling to their edge. For example, see Button:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/1156657/223441306-ebd32a43-cede-4f96-8144-94018c1d8694.png">

**Comment by bmandal2** [comment]
We are setting the overflow property because without it, the UI at the corners look bad. The box shadow goes outside the boundary. Hence, we are using this workaround.

**Comment by Westbrook** [comment]
For layouts like the one you've provided, the expected delivery is as follows:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/1156657/224061870-36c2dd75-7fbc-417e-abca-2eb6c3ef5f2c.png">
I do not believe that Spectrum or Spectrum CSS have any plans to alter this delivery or the way the it is delivered anytime soon, but maybe @pfulton could speak to this?

If not, we'll be closing this as "works as expected".

**Comment by Westbrook** [comment]
Be aware that this means that if the situation you've listed comes from a parent that leveraged `overflow: hidden` that you will likely no longer see any focus outline, which will negatively effect the accessibility of your application.

**Comment by Westbrook** [comment]
Closing as "works as expected".
