### ISSUE TITLE
[Bug]: Slider handle not aligning with tick values

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#2990]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

slider

### Expected behavior

The slider center-aligns with all the tick values when it's over them.

### Actual behavior

If you look at https://opensource.adobe.com/spectrum-web-components/components/slider/ at the tick with labels example, and move the slider to one of the edges like 5 or 95, the tick alignment is noticeably off (looks fine in the middle)

### Screenshots

<img width="993" alt="Screen Shot 2023-03-07 at 10 02 34 AM" src="https://user-images.githubusercontent.com/48841507/223477966-326e1731-ae4f-4544-8b77-34f509598504.png">

**Comment by castastrophe** [comment]
This will be fixed in Spectrum CSS when https://github.com/adobe/spectrum-css/pull/1547 is merged. We'll make sure to add a backlog item to bring those changes into SWC. cc @pfulton
