### ISSUE TITLE
[Bug]: sp-number-field doesn't always limit to max value upon return

### ISSUE THREAD

**Issue by celeryclub** [adobe/spectrum-web-components#3000]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

If you type in a number larger than the `max` attribute and press "return", it should change the number to the max.

### Actual behavior

If you type in a number larger than the `max` attribute and press "return", it doesn't always change the number. However, the number is always changed when the input is blurred. In addition, the number is never changed when `format-options` is used, and the number is only changed the first time you press "return" even without `format-options`.

### Screenshots

<img width="302" alt="Screenshot 2023-03-08 at 4 33 48 PM" src="https://user-images.githubusercontent.com/750809/223884511-d75b5203-1184-40e1-be29-060470347d77.png">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

It's on an unreleased app so I can't share a link here.

### Sample code that illustrates the problem

```
<sp-slider
    variant="filled"
    hide-stepper
    editable
    format-options='{"style": "unit", "unit": "percent"}'
    min="0"
    max="100"
    step="1"
>
    <sp-field-label size="l">Opacity</sp-field-label>
</sp-slider>
```

**Comment by TarunAdobe** [comment]
https://github.com/adobe/spectrum-web-components/assets/137032355/c6a68d65-308b-4dfe-9ebb-370d560e4249

**Comment by TarunAdobe** [comment]
@celeryclub  Please checkout the attached video... I wanna know your thoughts on this pattern
