### ISSUE TITLE
[Bug]: Slider thumb move on hovering over sp-slider.

### ISSUE THREAD

**Issue by manassinghadobe** [adobe/spectrum-web-components#3002]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

On mousedown on slider thumb and sliding thumb all the way to end, but releasing the mouse away from slider. and now after bringing it back on over slider, the sliding thumb move along with mouse hover event.

### Actual behavior

Slider thumb should not move on mouse hover after the mouse up is done.

### Screenshots

https://user-images.githubusercontent.com/108454313/224026513-3de810c6-9803-4803-8122-1b70869026e2.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
I'm having trouble being able to recreate this situation on our end, e.g. in our [Storybook](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--editable). Without that, any attempted fix could not be guaranteed. Would you please provide a live repro of this situation to test against.
