### ISSUE TITLE
[Bug]: sp-radio invalid state not visibly different

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#3005]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-radio

### Expected behavior

The invalid state here looks different from the other states: https://opensource.adobe.com/spectrum-web-components/components/radio/

Or, if this attribute is deprecated that should be made clear in the docs.

### Actual behavior

It looks the same as a valid state. Looks like this affects spectrum-css too: https://opensource.adobe.com/spectrum-css/radio.html

**Comment by adixon-adobe** [comment]
This isn't actually affecting us - just something I noticed in an upgrade demo today.

**Comment by Westbrook** [comment]
Yeah, weird, but see https://opensource.adobe.com/spectrum-css/radio.html#usage

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1156657/224419250-7a48c63e-cba9-4989-97ac-fe3c2a7afd21.png">

Which we support via: https://opensource.adobe.com/spectrum-web-components/components/radio/#help-text
 
And https://opensource.adobe.com/spectrum-css/radio.html#standard
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/1156657/224419376-a89dd19d-ce29-4d2a-89ad-0fc34bf49c36.png">

😱 

@pfulton does Spectrum CSS intend to keep the "invalid" states displayed in the docs, even though they are the same now? If not, a joint effort to remove those columns would make sense.

**Comment by pfulton** [comment]
Yes, this could be much clearer on our end. I think we should remove the Invalid example shown among default, disabled, and read-only, and instead show it on its own with the proper usage (HelpText + Icon).

**Comment by Rajdeepc** [comment]
Closed by #3558
