### ISSUE TITLE
[Feat]: Support of tooltip for sp-color-slider

### ISSUE THREAD

**Issue by prabhjodh** [adobe/spectrum-web-components#3008]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-color-slider

### Description of the requested feature

Need to add a tooltip on the top of the color slider component to show the actual values while dragging the color handle.

### Mockups or screenshots

<img width="201" alt="Screenshot 2023-03-13 at 11 03 44 AM" src="https://user-images.githubusercontent.com/20225072/224616237-53133ebd-793b-4ed3-9d0f-2b865456f6e4.png">

**Comment by Westbrook** [comment]
This is outside of the [Spectrum specification for this pattern](https://spectrum.adobe.com/page/color-slider/) and is not likely to be added to the library. Related, you'll notice that the spec also prescribes the use of a visible label: https://spectrum.adobe.com/page/color-slider/#Include-labels, be sure to share this info with your designer.

The majority of product patterns address this with a textfield at the end of the slider, which also offers precision input to your application visitors: https://spectrum-patterns.corp.adobe.com/page/cc-color-picker/ This not only solves the need for such a Tooltip but also served to make inputs in contexts such as this accessible to those with varying motor control abilities.

**Comment by Westbrook** [comment]
After discussing this with design, this is not something that we will be adding at this time.
