### ISSUE TITLE
API tab in documentation for components is broken

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#301]
### Expected Behaviour

When I click on the "API" tab in the docs for a component I should see the API for the component

### Actual Behaviour

I see `[Object object]`

### Reproduce Scenario (including but not limited to)

Click on any component in the docs and then click on "API"

**Comment by Westbrook** [comment]
This looks good on my end, are you seeing similar now @cuberoot?

**Comment by Westbrook** [comment]
No longer an issue.
