### ISSUE TITLE
[Bug]: required textfield fails on minimum text length

### ISSUE THREAD

**Issue by MircoSteyer** [adobe/spectrum-web-components#3013]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield

### Expected behavior

When I set the sp-textfield as required with a minlength of 3, the input should be valid with 3 characters.

### Actual behavior

When I set the sp-textfield as required with a minlength of 3, the input is only valid from the fourth character onwards.

### Screenshots

![spectrum-textfield-bug](https://user-images.githubusercontent.com/57771199/225005348-8490fffe-1a57-47ba-95c1-10f933e89f7c.gif)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Create a sp-textfield component
2. Make the component required with a minlength of 3
3. Type "abc"
4. See that displayed icon is the alert icon instead of the checkmark.

### Sample code that illustrates the problem

` <sp-textfield required minlength="3"></sp-textfield>`

The issue probably lies here:
https://github.com/adobe/spectrum-web-components/blob/d45dffddd23c16611cb9c0fa645e2a2cb020bb95/packages/textfield/src/Textfield.ts#L317

"abc".toString().length evaluates to 3. As does the minlength of 3.
The operator should therefor be `>=`, meaning the string is of minlength or longer.

The behaviour would then mirror non-required text-fields, where the minlength works properly. Probably, because that line of code is not executed, unless "required" or "pattern" is set.

**Comment by Westbrook** [comment]
Nice find. Thanks for the deep research of this. We'd love to accept a PR correcting this, if you. were interested... 😄

**Comment by MircoSteyer** [comment]
How do I create a branch for PRs? I get the following issue:
` git push --set-upstream origin required-textfield-minlength
ERROR: Permission to adobe/spectrum-web-components.git denied to MircoSteyer.
fatal: Could not read from remote repository.
`

This is my first time commiting to something on Github that is not my own repository. Do I need to be added as a collaborator or something?

**Comment by Westbrook** [comment]
Start with a fork:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/1156657/225090829-fdf3baf4-08e4-43bb-bb0f-f64b2f6ec08c.png">

Then make the changes local to there, and open a cross repo PR from that.

See [more info on that process](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by Westbrook** [comment]
Fixed in #3021
