### ISSUE TITLE
Add DialogBase component to swc-react wrapper library

### ISSUE THREAD

**Issue by sasaber** [adobe/spectrum-web-components#3026]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

Currently `<DialogBase/>` is missing from `@swc-react` wrapper library. Only `<Dialog/>` and `<DialogWrapper/>` are available. 

```import { DialogBase } from "@swc-react/dialog";``` results in following error: ```Module '"@swc-react/dialog"' has no exported member 'DialogBase'```

**Comment by jianliao** [comment]
Verified. The `DialogBase` wrapper was generated and exported.
https://unpkg.com/browse/@swc-react/dialog@0.11.14/index.dev.js

Thanks
