### ISSUE TITLE
[Bug]: selfManaged tooltip are not working properly on sp-button and sp-field-label elements after hovering multiple times 

### ISSUE THREAD

**Issue by ananpal** [adobe/spectrum-web-components#3044]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

the tooltip view should should be stable and should be visible on hover

### Actual behavior

the tooltip view should should is not stable and after some hover tooltip view is losing its parent and not displaying properly

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
Without a repro of this situation we will be closing this issue as part of the release of the [new Overlay API](https://github.com/adobe/spectrum-web-components/discussions/2764).
