### ISSUE TITLE
tool: move copy to clipboard out of docs and into `shared`

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#3047]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

In `projects/documentation/src/components/copy-to-clipboard.ts`, we should abstract this to move into the `shared` package for abstraction. This will benefit the ue-share-menu down the line, as well as other components in the future that may require something similar.

**Comment by Westbrook** [comment]
The code for this now look like `navigator.clipboard.writeText(textToCopy);` natively. No need to export this anymore...
