### ISSUE TITLE
[NEW]: Support of ColorField (same as React Spectrum's ColorField component)

### ISSUE THREAD

**Issue by prabhjodh** [adobe/spectrum-web-components#3070]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Name of component

sp-color-field

### Link to the Spectrum assets

https://react-spectrum.adobe.com/react-spectrum/ColorField.html

### Design specification

Add the support for ColorField component which can be used to get color string as an input (in formats such as HEX and RGB) and also provide with the support to format and validate the color strings according to the color mode (same as React Spectrum's ColorField component).

### API requirements

Same as React Spectrum's ColorField

**Comment by Westbrook** [comment]
There is no Color Field in the [Spectrum Design system](https://spectrum.adobe.com/) at current, so I'm not sure there would be any form of specification against which to build this pattern.

**Comment by najikahalsema** [comment]
Hi, I spoke with the design team about this, and while they are aware of it, developing a design spec for this is not prioritised for them at the moment. This would be its own component. If this component were to exist, it would be used in conjunction with other colour elements, as seen below: 
![image](https://github.com/adobe/spectrum-web-components/assets/44980010/d3aa4e5a-bbd5-4790-a87d-8d034e6f1ddc)
