### ISSUE TITLE
[Bug]: sp-dialog content is not scrollable when starting with a small window

### ISSUE THREAD

**Issue by mariusgrafu** [adobe/spectrum-web-components#3073]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dialog

### Expected behavior

I expect to be able to scroll the content section when it's too large to fit.

### Actual behavior

The content section is only scrollable after a window resize - if I start with a small enough window and I don't resize I won't be able to scroll.

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

In the `studio.webcomponents.dev` example attached:
1. Try to scroll the content section - where the red text appears
2. The content won't scroll 

If you resize the window and try again - it will work

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/TXMr394dST4OmsWaAibj/src/index.ts?p=stories

**Comment by najikahalsema** [comment]
Hi, thanks for filing this issue and creating a reproduction on webcomponents.dev. I'm not seeing the same issue on my end. 

https://user-images.githubusercontent.com/44980010/230143564-a0e54168-f563-4c51-858e-111d0d5eba41.mov

What version of dialog are you using at the moment?

**Comment by mariusgrafu** [comment]
Hello! Thanks for checking out this issue! I'm only seeing this issue when I start with a small window. I am able to scroll after I resize the window. Try to start without the demo window resizing - I sometimes have to reload the webcomponents.dev demo to be able to repro.

https://user-images.githubusercontent.com/16462007/230323790-8eea0ae6-6d81-4c5b-9792-43f899f9db98.mov

**Comment by najikahalsema** [comment]
I see. I did try this, and though the scroll bar wasn't visible initially, I was still able to scroll. 

https://user-images.githubusercontent.com/44980010/230424116-62c3ad25-13bc-4b7d-a66d-690c729ea591.mov
