### ISSUE TITLE
[Bug]: RadioGroup component's 'selected' property not working correctly with React wrapper

### ISSUE THREAD

**Issue by jianliao** [adobe/spectrum-web-components#3074]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

RadioGroup

### Expected behavior

The RadioGroup component should display the default selected radio button as defined by the 'selected' property when used with a React wrapper in a React application.

### Actual behavior

The RadioGroup component does not display the default selected radio button as defined by the 'selected' property when used with a React wrapper in a React application.

### Screenshots

[Sandbox](https://codesandbox.io/p/github/jianliao/react-swc-ts/main?file=%2Fsrc%2FApp.tsx&workspace=%257B%2522activeFileId%2522%253A%2522clfx0hjuz0008g5fi0zt19116%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfx0nrnx00113b6mpxkli0tf%2522%253A%257B%2522key%2522%253A%2522clfx0nrnx00113b6mpxkli0tf%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfx0nrnx00133b6mygpu5cl0%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfx0nrnx00113b6mpxkli0tf%2522%252C%2522spacesOrder%2522%253A%255B%2522clfx0nrnx00113b6mpxkli0tf%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D) to reproduce the issue. Here is more [context](https://adobedesign.slack.com/archives/CESK60MQD/p1666709545018059).

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Set up a React application and integrate the Spectrum Web Components library.
2. Create a RadioGroup component with multiple radio buttons.
3. Use a React wrapper for the RadioGroup component.
4. Set the 'selected' property of the RadioGroup component to define a default selected radio button.
5. Render the RadioGroup component in the React application.

### Sample code that illustrates the problem

1. React code:
```jsx
<RadioGroup selected="first" name="example">
    <Radio value="first">Option 1</Radio>
    <Radio value="second">Option 2</Radio>
    <Radio value="third">Option 3</Radio>
    <Radio value="fourth">Option 4</Radio>
</RadioGroup>
```

**Comment by Westbrook** [comment]
fixes by #3075
