### ISSUE TITLE
[Bug]: sp-tabs not working as expected. The line below the heading is misaligned

### ISSUE THREAD

**Issue by atakiyar** [adobe/spectrum-web-components#3078]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Actual behavior

Misaligned underline for tab.
 In the attached video, the tab line is misaligned initially. But after multiple switches between the tab, the tab line automatically gets aligned as expected. Not in all cases this issue is getting reproduced.
This issue does not exist if the parent does not have a margin/padding.

### Screenshots

https://user-images.githubusercontent.com/124043092/229502685-c87f688a-6820-42ae-b807-b7984fee6a82.mov

<img width="921" alt="Screenshot 2023-03-29 at 4 24 23 PM" src="https://user-images.githubusercontent.com/124043092/229502973-aeae819c-a1df-4224-93ac-8c55f8e93b2b.png">

### How can we reproduce this issue?

Add margin/padding to the sp-tabs or its parent element.

**Comment by Rajdeepc** [comment]
@atakiyar Do you have a working repro of this issue. If not, you can start from here: https://studio.webcomponents.dev/edit/2JFFTBPXfCZpePD0wk58/src/index.ts?p=stories

**Comment by Rajdeepc** [comment]
@Westbrook Can you please check this issue whether it can be closed or not. I don't see this is an issue from the library itself, mostly it is coming from the user specific usage of the sp-tabs

**Comment by Westbrook** [comment]
This _was_ occurring when there was `margin` on the body and the content was centered, like [this](https://studio.webcomponents.dev/edit/2JFFTBPXfCZpePD0wk58/src/index.stories.js?branch=centered%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories). However, that no longer seems to exhibit the issue, so I'm happy to close this is @atakiyar is no longer participating here.
