### ISSUE TITLE
Some files in the styles package need to be manually kept in sync with SpectrumCSS

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#308]
### Expected Behaviour
We have an automated process to update variable changes from SpectrumCSS

### Actual Behaviour
At least some files need to be updated, like https://github.com/adobe/spectrum-web-components/blob/master/packages/styles/fonts.css (which is currently out of date).

**Comment by adixon-adobe** [comment]
@Westbrook it'd be good to know if this is just a matter of making some small updates to `scripts/process-spectrum-css.js` or if there's still some larger work to do to properly integrate the SpectrumCSS lerna changes.

**Comment by Westbrook** [comment]
Looks like it’s here https://github.com/adobe/spectrum-css/blob/master/components/typography/font.css so I’d say, yes.

**Comment by adixon-adobe** [comment]
Hmmm... I thought it was here: https://github.com/adobe/spectrum-css/blob/master/components/commons/fonts.css (but now I'm wondering if both need to be reconciled)

**Comment by Westbrook** [comment]
I just linked the first one I could find. If it’s available in an individual package and not a bundle, I’m not too concerned where we pull from.

**Comment by adixon-adobe** [comment]
Right, but the 2 files we linked are different. I'm guessing we want to variable one I linked, but I'm still not totally up to speed on the conversion script (will try to take a look next week though).
