### ISSUE TITLE
Can't use adobe-clean-ux

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#309]
### Expected Behaviour
Since this is supported in SpectrumCSS, it should work here. I'll also note that this is now a deprecated font (but we're hoping to keep using it for some time).

### Actual Behaviour
It's not included here: https://github.com/adobe/spectrum-web-components/blob/master/packages/styles/fonts.css (where-as it is defined in https://github.com/adobe/spectrum-css/blob/master/components/commons/fonts.css)

**Comment by adixon-adobe** [comment]
Added this issue so I can make a more targeted fix.

**Comment by Westbrook** [comment]
Hopefully if you fix #308 then this one will come for free.

**Comment by adixon-adobe** [comment]
Unfortunately there are still bugs in spectrum-css around this (e.g. some of the auto-generated TextField styles don't include this). Since clean-ux is really a dead end at this point, we'll switch our focus to reverting our site back to adobe clean.

I'm gonna close this out.
