### ISSUE TITLE
[Bug]: Text Field type default error text cannot be configured

### ISSUE THREAD

**Issue by TheMcMurder** [adobe/spectrum-web-components#3099]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield

### Expected behavior

Textfield accepts a `type` attribute, as well as a `pattern` attribute, that cascades to the native HTML element. Those attributes provide helpers for on-screen keyboards and some native validation functionality. One aspect of the native validation is that it silently creates a mouseover effect when the input doesn't match the native validation. One way to configure that mouseover text to something custom (or translated) is to use the `title` attribute. When the title attribute is set the mouseover text will match the value specified in the `title` attribute.

### Actual behavior

The `title` attribute does not cascade to the native `input` and so any specified text is ignored and the mouseover always matches the default text. I believe the default text matches your OS language settings but even when the browser settings are changed it ignores the setting and shows the text in English.

### Screenshots

<img width="448" alt="Screenshot 2023-04-11 at 10 45 43 AM" src="https://user-images.githubusercontent.com/3059715/231232654-f8a03b3d-889a-44af-91e6-686ab8e44f3a.png">

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

#### option 1

1. Go to the storybook for textfield
2. Hover over the invalid input in the default stories area
3. Observe system level `mouseover` reading: "Please match the requested format."

#### Option 2

1. Go to https://opensource.adobe.com/spectrum-web-components/components/textfield/
1. Edit the invalid field and add a `type` attribute. I'd recommend using `url`
1. Enter an invalid url `sdfsadfs` will work.
1. Hover over the alert icon
1. Observe the system level text reading: "Please enter a URL."

### Sample code that illustrates the problem

```ts
... 
return html`
  <sp-textfield
    type="url"
    title="My translated error"
  >
  </sp-textfield>
`

```

**Comment by TheMcMurder** [comment]
## Solutions

### Potential Solution 1

Modify `TextField` to cascade the `title` attribute

### Potential Solution 2

Create a custom attribute that can be used to set the title when the existing `invalid` attribute is `true`

### Potential Solution 3

If `negative-help-text` slot is being used then reuse that text as the `title` attribute.

**Comment by Westbrook** [comment]
I'm not sure this is a good path to go down.
- `title` often has unexpected (sometimes negative) effects on the accessibility tree, especially when the same value is shared across multiple elements in the same subtree.
- I've not seen this used in the validation API for the web, would you happen to have any documentation that you could point to regarding `title` being used in the validation API?

I think you want something more like what you get in this screen shot when applying [the APIs available here](https://developer.mozilla.org/en-US/docs/Web/HTML/Constraint_validation).

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1156657/231262272-b0ed0b85-5cf7-4f7d-8e16-ea5866b4daa1.png">

This [demo](https://codepen.io/calebdwilliams/pen/PodZKVd?editors=1010) uses [@open-wc/form-control](https://www.npmjs.com/package/@open-wc/form-control) and [@open-wc/form-helpers](https://www.npmjs.com/package/@open-wc/form-helpers), which are likely going to be helpful in this area, either directly or as examples.

**Comment by Westbrook** [comment]
I've done some more research here, and it's quite an annoying situation.

First, the message you are trying to remove is an OS translation. If you restart your OS with a new primary language it will be translated for you without developer input. It in no cases responds to browser or page settings. 😞 

An `<sp-textfield title="Some title" disabled>` will construct an unexpected accessibility tree, and while the specific usage you have outlined might default to `title=""` which doesn't seem to cause trouble, opening a door by which consuming developers can easily make mistakes in content delivery doesn't feel like the best option, though it is an option.

Options:
1. Cascade `title`
   - Pro:
      - full control to remove or upgrade this content
   - Con:
      - opens the door for erroneous accessibility trees
      - always cascading title means the parent app needs to manage the value of that attribute based on the state of the textfield
2. Apply blank `title` to `<input>` when `invalid`
   - Pro:
      - requires no developer input to leverage
      - doesn't pollute the attribute API before delivering full form associated validation support
   - Con:
      - is not customizable, everyone gets _nothing_
3. Leverage `custom-validity` attribute, or similar
   - Pro:
      - full control to remove or upgrade this content
      - would/could only apply when "invalid" `<input>`
   - Cons:
      - pollutes the attribute API in advance of full form associated validation support
      - requires extra documentation

For how it aligns with future plans and ease of consumption _today_ I'm leaning towards option 2, but let me review this with my team later today and I'll get back to you with our recommendation, whether it's ones of these or something I haven't thought of...
