### ISSUE TITLE
[Bug]: sp-picker title is updated with label on pressing space and click continuously

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#3111]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

spectrum-picker

### Expected behavior

picker should not be updated with label value

### Actual behavior

picker title is changing to label value

### Screenshots

https://user-images.githubusercontent.com/125646446/231656372-6a6258ec-d4fa-4ff7-9012-78547642ab63.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. open picker in the storybook.
2. click on picker menu along with pressing space repeatedly.
3. observe the issue.

**Comment by venkateshjo** [comment]
yeah @Westbrook, I'm unable to reproduce the issue here (https://overlay-mixins--spectrum-web-components.netlify.app/storybook/?path=/story/picker--default)

Please let us know once this fix is released.

Thank you.

**Comment by Westbrook** [comment]
You can track the work here in #3009. We've started to test Canary releases, but it will still be at least 4 weeks before this change becomes publicly vailable.

**Comment by Westbrook** [comment]
I'm no longer experiencing this issue after #3456.
