### ISSUE TITLE
[Bug]: sometimes sp-closed event is not received from sp-action-menu after closing the popover

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#3117]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

action-menu

### Expected behavior

Need to receive sp-closed event once the action menu is closed

### Actual behavior

sometimes sp-closed event is not received

### Screenshots

https://user-images.githubusercontent.com/125646446/231974411-1fe6b9f4-aacf-463a-9dea-c5ec3f23e460.mov

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Create an action menu.
2. Register the below listeners for sp-opened and sp-closed.
3. click on the action menu button  rigorously.
4. After sometime the action button will be disabled

### Sample code that illustrates the problem

static enableDisableActionMenuButton (actionMenuView) {
        const enableButton = () => actionMenuView.shadowRoot?.querySelector('sp-action-button').removeAttribute('disabled');
        const disableButton = () => actionMenuView.shadowRoot?.querySelector('sp-action-button').setAttribute('disabled', '');
        
        actionMenuView.addEventListener('sp-opened', ({ detail }) => {
            if (detail.interaction === 'modal') {
                disableButton();
                let actionButton = triggerView.shadowRoot?.querySelector('sp-action-button');
                actionButton.style.setProperty('background-color', 'var(--spectrum-actionbutton-background-color-default)');
                actionButton.style.setProperty('color', 'var(--spectrum-actionbutton-content-color-default)');
            }
        });
    
        actionMenuView.addEventListener('sp-closed', ({ detail }) => {
            if (detail.interaction === 'modal') {
                enableButton();
            }
        });
    }

**Comment by Westbrook** [comment]
This will hopefully be addressed by #3009. We've started to test Canary releases, but it will still be at least 4 weeks before this change becomes publicly available.

**Comment by hunterloftis** [comment]
@Westbrook once subsequent-click toggling is ready, we can test this (started at https://codesandbox.io/s/3199-forked-pb3moz?file=/src/my-component.ts but won't be able to toggle quickly via mouse)

**Comment by venkateshjo** [comment]
Hi @Westbrook, May I know when this bug fix will be released?

**Comment by Westbrook** [comment]
Release progress for this is being tracked [here](https://github.com/adobe/spectrum-web-components/discussions/2764#discussioncomment-6450198).

**Comment by Westbrook** [comment]
Please retest with the code in #3456, and feel free to reopen this issue with expanded reproduction steps if this issue persists.
