### ISSUE TITLE
[Bug]: slider without label has broken styles on initialization

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-web-components#3118]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Using `<sp-slider></sp-slider>` should render the slider component as usual, without a label.

### Actual behavior

On initialization, it does not look as it should. It fixes itself when I click in the area where the slider should be.

### Screenshots

Initialization:
![image](https://user-images.githubusercontent.com/1174072/232050352-24357b36-1c81-483d-99d4-ae71b06bf551.png)

After clicking in the slider area:
![image](https://user-images.githubusercontent.com/1174072/232050462-16a70123-f296-4423-b67a-404b2bcce58d.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Add `<sp-slider></sp-slider>`
2. Observe the result

### Sample code that illustrates the problem

```html
<sp-theme theme="spectrum" color="light" scale="medium">
	<sp-slider></sp-slider>
</sp-theme>
```

https://studio.webcomponents.dev/edit/0xuMPEiO0hRoAVnM7kbw/src/index.ts?p=stories

**Comment by Westbrook** [comment]
Isn't that quite peculiar! Thanks for the report. This seems like it relates closely to #2940 and our desire to do some refactoring in the element so we can expand into some new features.

In the interim, an `<sp-slider>` element really _shouldn't_ be deployed without a `label` for accessibility purposes. In that case that you are looking to supress that label visibly, you can leverage the `label-visibility` attribute and one of it's values: `'text' | 'value' | 'none'`.

https://studio.webcomponents.dev/edit/Kv87Ng869ueX1qGxatbb/src/index.ts?p=stories

**Comment by Westbrook** [comment]
The accessibility above information would be a good addition to the docs and development mode.

**Comment by davidkudera** [comment]
I definitely agree with your accessibility comment. The only reason I found about this problem is, that I'm trying all spectrum form elements (or elements with value) without any attributes or settings.
