### ISSUE TITLE
Clearing search field does not generate event or clear value

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#313]
### Expected Behaviour

When you click on the 'x' the search field should send out some sort of event, either `input` or `change` to notify that it has happened. And, accessing the `.value` property on the search field should give you and empty string.

### Actual Behaviour

No event is generated and the `.value` remains as it was before the field was cleared.

#### Steps to Reproduce

- Run the documentation site from pull #312
- Type in a search such as "but"
- click the 'x'

#### Sample Code that illustrates the problem

Documentation site from #312

**Comment by Westbrook** [comment]
@cuberoot recent updates have this clearing the `value` appropriately. Do you have any thoughts on whether the event here needs to be anything in specific? Possibly just:
```
this.dispatchEvent(
    new Event('clear', {
        bubbles: true,
    })
);
```
This would match the `submit` event that also `bubbles` without being `composed`.
