### ISSUE TITLE
We should be able to turn off autocomplete for fields

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#314]
### Expected Behaviour

We should be able to pass the [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attribute to text fields to control completion.

### Actual Behaviour

We cannot create a custom completion because the browser's default autocompletion kicks in

<img width="230" alt="Screen Shot 2019-11-26 at 2 57 28 PM" src="https://user-images.githubusercontent.com/154097/69593151-35de8580-105d-11ea-9a85-0d2cbfd9dbd1.png">

#### Steps to Reproduce

Run the documentation site from #312 and run various searches in Chrome.

**Comment by Westbrook** [comment]
@cuberoot if there were other additions you wanted to make here, feel free to reopen, but it looks like we're getting what we were looking for here in the docs site, at least.
