### ISSUE TITLE
[Bug]: OverlayTriggers sometimes don't work

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#3144]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay-trigger

### Expected behavior

Should always function when slotted content is available in them.

### Actual behavior

Due to timing issues its possible for slotted content to be present upon first render and are immediately slotted into the slots but before the `slotchange` event listeners are registered.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
Seems like it was a weird flake in Chrome, closing for now.
