### ISSUE TITLE
[Bug]: Need callback on hover for spectrum picker list items

### ISSUE THREAD

**Issue by cdprashanth** [adobe/spectrum-web-components#3147]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

SP-Picker

### Expected behavior

Need callback on hover for spectrum picker list items

This is required for https://jira.corp.adobe.com/browse/VEN-6024

### Actual behavior

Hover callback for spectrum picker list items is not available

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
This can be done today with default browser events like `pointerenter` and `pointerleave`, see this demo: https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/guTpKeAjgecibF150Qbg/src/index.ts?branch=hover%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories

We're tracking a more concise API for a similar context in #2700, however it's not likely to get actively on our roadmap for a while, yet. If the above doesn't work for you use case and you'd be interested in contributing to the development of that feature, we'd be happy to get you up to speed with out plans there. Please append further conversation on this feature to that issue.

Thanks!
