### ISSUE TITLE
[Bug]: Swatch Group select single is not working if swatch is wrapped inside overlay-trigger

### ISSUE THREAD

**Issue by pkashyap29** [adobe/spectrum-web-components#3153]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-swatch

### Expected behavior

sp-swatch selection should work even it's wrap inside the overlay-trigger

### Actual behavior

Selectin is not working.
When I use multiple sp-swatch inside sp-swatch-group having selects attribute as single. This works fine, with only one swatch getting selected at a time. But this is not the case when we wrap sp-swatch inside overlay-trigger, here multiple swatches are getting selected.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Logs taken while reproducing problem

https://studio.webcomponents.dev/edit/xLErLY8rU8m1nhdRFKQa/src/index.ts?p=stories

**Comment by Westbrook** [comment]
Going forward (as of `v0.37.0`), you should bind Tooltip content to Swatch elements as seen in https://studio.webcomponents.dev/edit/piqJixyRD3Kamwjx19H6/src/index.ts?p=stories

```html
    <sp-swatch-group density="spacious" selects="single">
      <sp-swatch id="color-1" color="var(--spectrum-global-color-blue-500)" draggable="true">
      </sp-swatch>
      <sp-overlay trigger="color-1@hover" placement="bottom">
        <sp-tooltip>
          If you click this, you'll see a popover!
        </sp-tooltip>
      </sp-overlay>
      <sp-swatch id="color-2" color="var(--spectrum-global-color-magenta-500)">
        Hello
      </sp-swatch>
      <sp-overlay trigger="color-2@hover" placement="bottom">
        <sp-tooltip>
          If you click this, you'll see a popover!
        </sp-tooltip>
      </sp-overlay>
    </sp-swatch-group>
```
