### ISSUE TITLE
Fixing versions for ccac-spectrum

### ISSUE THREAD

**Issue by TrojanRocks** [adobe/spectrum-web-components#3154]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

SWC component imports it's peer dependency that might be already part of ccac-spectrum's dependencies but a different version and because of that yarn.lock has multiple entries and custom Element registry will throw an error(that the given web component have already been registered)

For ccac-spectrum integration if fixed versions are provided or bypassing custom Element registry even if dependencies versions are different

PFA the screenshot of the issue for select
<img width="1724" alt="Screenshot 2023-03-23 at 9 24 12 PM" src="https://user-images.githubusercontent.com/8644325/234638926-4e315e14-a12f-4d18-ab6e-171cd2f15193.png">

**Comment by sarahszhou** [comment]
![Screenshot 2023-04-18 at 1 48 04 PM](https://user-images.githubusercontent.com/55859693/234650969-63d2201b-52bc-4547-ae69-a1c78973e27a.png)

I ran into this issue as well with Toasts, while it is possible to work with yarn and resolve these issues, every time there is a spectrum upgrade all client teams will need to put in the time to de-duplicate dependencies. Additionally, many clients are using a hack: https://git.corp.adobe.com/CCX/cloud-shared-components/pull/1268/files#diff-7509ab6d2522d36980417ef2d5a23642dd52d671735e89d5d7b8ff6af7971372R50

Like the one I linked above which is not a sustainable fix.
I would suggest opening this back up and perhaps looking for a long term fix that makes using SWC easier to maintain.
