### ISSUE TITLE
[Bug]:  sp-table's header is unusable if max-width style property cuts off table head row

### ISSUE THREAD

**Issue by lschierer** [adobe/spectrum-web-components#3156]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Table

### Expected behavior

1. when I set max-width on the sp-table, I expected sp-table-head and sp-table-body to respect that and stay constrainted by the sp-table.  

2. when that didn't happen, I set the max-width style property on the sp-table-head and sp-table-body directly in addition to the sp-table.  I expected this to constrain the two such that they staid inside the sp-table and used a common scroll bar. 

### Actual behavior

The sp-table-body and sp-table-header create independent scroll bars.  They scroll independently of each other, such that headings and the columns they are headings for are not aligned.  The scroll bar covers the column headings, such that you cannot see them anyway, so you functionally have a table with no headings.  

### Screenshots

![Screenshot 2023-04-26 at 6 50 19 PM](https://user-images.githubusercontent.com/2224044/234719401-6d173125-cf9a-4ace-bb73-cb67e3e6d5d7.png)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. clone https://github.com/lschierer/EvonyTKRTips.sst/tree/613b8f603a2d86b2b1e6a62b63e98ddee4081107 at commit 613b8f603a
2. run ```pnpm install```
3. navigate into packages/web
4. run ```pnpm run start:mpa```
5. see the error on localhost:8000

### Sample code that illustrates the problem

see steps to reproduce.  The code is in the lib/components/mayor_table.ts file

**Comment by najikahalsema** [comment]
Table has been updated to leverage core tokens. Could you test this on 0.39 and see how the issue changes?

**Comment by lschierer** [comment]
Yes, this appears to be solved, thanks :-)
