### ISSUE TITLE
[Bug]: Using JP keyboard in Safari enables IME UI and yields incorrect results for number fields

### ISSUE THREAD

**Issue by isabella-minca** [adobe/spectrum-web-components#3158]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Number field

### Actual behavior

IME UI shows up for number fields in Safari when using Japanese keyboard. When writing 1 and 2 the result is 112 rather than 12.

### Screenshots

<img width="1320" alt="Screenshot 2023-04-27 at 12 31 57" src="https://user-images.githubusercontent.com/120386026/234822916-8803fbe2-3ab2-4ba9-a063-8e15bd749fd0.png">

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Enable JP keyboard
2. Enter 1 and 2 in a number field
3. Result is 112

**Comment by Westbrook** [comment]
Fixed by #3610
