### ISSUE TITLE
[Bug]: VO on MacOS is inconsistent in moving focus to dialogs

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#3161]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dialog sp-overlay-trigger

### Expected behavior

When a modal dialog is opened focus should always shift to the dialog. 

### Actual behavior

Focus sometimes stays on the button which opens the dialog.

### Screenshots

https://user-images.githubusercontent.com/1724479/235007678-00d02b69-529f-4fc2-b1e9-fe9671570a3b.mov

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/0QAwcRuCoUg7vd5qgdhr/src/index.ts?p=stories
2. Start VO
3. Scroll to Tab to the Magnify Glass icon (each of them are same)
4. Press Return or Control+Option+Space to activate the button
5. Note that focus stays on the button

This reproduces about 10% of the time and never reproduces on the same button instance once it works the first time

**Comment by Westbrook** [comment]
Your demo links seems to have been updated, but it appears that we're doing something closer to what is expected here? https://studio.webcomponents.dev/edit/0QAwcRuCoUg7vd5qgdhr/src/index.ts?p=stories&branch=singleButton%407fBWg9Y3wmUwOKofZzrLDd2SRAr2

**Comment by Westbrook** [comment]
I am not currently experiencing this issue with the following usage: https://studio.webcomponents.dev/edit/54MG2BlDAtiw3KwptE3U/src/index.ts?p=stories

If you feel there is an alternative reproduction case, feel free to open an new issue with that workflow.
