### ISSUE TITLE
[Feat]: Support 'pending' button states

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#3162]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

button

### Description of the requested feature

We should implement the 'pending' button state as described here: https://spectrum.adobe.com/page/button/#Pending

**Comment by Rajdeepc** [comment]
WIP PR: https://github.com/adobe/spectrum-web-components/pull/3163

**Comment by Rajdeepc** [comment]
@benjamind I see a PR opened by you on this. Would you like to take this forward from you or do you have some plans to land this. Let me know what works best for you so that we can add this to our upcoming sprint.

**Comment by benjamind** [comment]
By all means please take this forward, I don't think I'll have time to land it any time soon! Thanks!
