### ISSUE TITLE
[Bug]: Memory Leak in Menu

### ISSUE THREAD

**Issue by joekukish** [adobe/spectrum-web-components#3164]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Menu

### Actual behavior

MenuItemRemovedEvent keeps an instance to an object, which is never cleared. This introduces a leak since the object cannot be garbage collected.

https://studio.webcomponents.dev/edit/C5gyfKCjjMMv14UmjQzr/src/index.ts?p=stories

### Screenshots
<img width="1049" alt="Screenshot 2023-04-28 at 16 38 02" src="https://user-images.githubusercontent.com/1413153/235177422-1f6e4e9e-21b5-4cc0-ac8d-b409b481d70f.png">

_No response_

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/C5gyfKCjjMMv14UmjQzr/src/index.ts?p=stories
2. Open Chrome DevTools and go to the Memory tab.
3. Click on Profiles > Head snapshot > Take snapshot
4. Click the Show / Hide button (10-20 times)
5. Go to Performance Tab in DevTools, and click on the Trash Icon (garbage collection).
6. Go to Memory Tab, and take another snapshot
7. Next to the search field, "All Objects", select Objects allocated between Snapshot 1 and Snapshot 2.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/1413153/235186117-acbbf57e-e108-495d-b8d0-51828ac6ae32.png">
8. Search for Detached
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1413153/235186039-5099513d-0df6-4304-9df2-20a0d850bc84.png">

`_item` is the MenuItem held inside the event

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1413153/235186362-1635acce-3f39-4204-b0cb-5665a4a81af8.png">

**Comment by Westbrook** [comment]
Would be great to have a slice for slice test scenario for this to compare fixed against. You wouldn't happen to have set something like that up in order to track this down?

**Comment by joekukish** [comment]
@Westbrook I've added a playground where it can be reproduced and steps of how to find the leak.

**Comment by nawazmobusss** [comment]
Hi @Westbrook , Can I kindly ask for an update on this ticket?  One of our components is using Menu and we see memory leaks leading to memory crashes in mobile app & safari browser. It would be highly appreciated if this could be addressed soon as we are looking for a public release in 2 weeks.

**Comment by najikahalsema** [comment]
@nawazmobusss We will have this ready to go for you in a release this week.
