### ISSUE TITLE
[Bug]:  some of the spectrum theme values are missing from spectrum styles

### ISSUE THREAD

**Issue by lschierer** [adobe/spectrum-web-components#3168]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

@spectrum-web-components/styles

### Expected behavior

per the documentation, it sounds like @spectrum-web-components/styles should contain all of the values documented in @spectrum-web-components/theme should you need to use them via CSS rather than via a javascript include.  

### Actual behavior

A grep on the word cyan shows that it the cyan color variables are in @spectrum-web-components/theme but not in @spectrum-web-components/styles 

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. add npm modules  "@spectrum-web-components/styles": "^0.24.0",
    "@spectrum-web-components/theme": "^0.15.0", to a project and attempt to use var(--spectrum-global-color-cyan-600) as a color for a component via CSS instead of via a javascript include. 

* import the global stylesheets */
@import '@spectrum-web-components/styles/typography.css';
@import '@spectrum-web-components/styles/all-medium-light.css';
@import '@spectrum-web-components/styles/scale-medium.css';
@import '@spectrum-web-components/styles/theme-light.css';

### Sample code that illustrates the problem
```
//use this as a component in an astro project, including the appropriate CSS files. 
import {html, LitElement} from 'lit';
import {customElement} from 'lit/decorators.js';
import {styleMap} from 'lit/directives/style-map.js';


import '@spectrum-web-components/top-nav/sp-top-nav.js';
import '@spectrum-web-components/top-nav/sp-top-nav-item.js';
import { TopNav } from '@spectrum-web-components/top-nav';

const tagName = 'top-nav';

@customElement('top-nav')
export class myTopNav extends LitElement {

  override render(){
    const styles = {
      backgroundColor: 'var(--spectrum-global-color-cyan-600)',
    }
    return html`
            <sp-top-nav size="xl" client:load style=${styleMap(styles)}>
                <sp-top-nav-item></sp-top-nav-item>
                <sp-top-nav-item href="/"><strong>Evony TKR Tips</strong></sp-top-nav-item>
                <sp-top-nav-item href="/generals/" style="margin-inline-start: auto;">Generals</sp-top-nav-item>
                <sp-top-nav-item href="/monsters/">Monsters</sp-top-nav-item>
                <sp-top-nav-item href="/svs/">SvS</sp-top-nav-item>
                <sp-top-nav-item href="/reference/">Reference</sp-top-nav-item>
                <sp-top-nav-item></sp-top-nav-item>
            </sp-top-nav>
        `
  }
}
```

**Comment by Westbrook** [comment]
Where do you specifically see `--spectrum-global-color-cyan-600` documented? I'm not seeing anything about it in our repo right now.

**Comment by lschierer** [comment]
https://spectrum.adobe.com/page/color-palette/  has it,  
![Screenshot 2023-05-02 at 9 43 39 PM](https://user-images.githubusercontent.com/2224044/235818919-4a42d42c-21bf-4bce-b41d-550a69b4a4e4.png)

**Comment by lschierer** [comment]
but on closer look, it appears that is only for the react implementation?  That's *really* confusing.  Why does react have colors that the web components doesn't have?  I guess it was just an assumption on my part that when I'd grepped on the word "cyan" that all of the cyans would be there, and not just a subset of them.  I see grepping more extensively that only 59 of the --spectrum-global-colors are included?  Should I close this and re-submit as a feature request to include the full set of color?

**Comment by lschierer** [comment]
However, the command
```
grep cyan node_modules/@spectrum-web-components/theme/src/theme-light.css.js | tr ';' '\n' | grep -v var
```
does show it present in the theme, it is just that I haven't figured out how to use the theme version of the CSS with Astro yet because those are css.js files.  I'm sure there is a way, I just haven't figured it out yet.

**Comment by Westbrook** [comment]
There is only ONE Spectrum System. The React Spectrum project doesn't not leverage it and as such gets further and further out of date through time. Out team does not work with that project, so we wouldn't be able to support reducing the delta there.
