### ISSUE TITLE
Focusable components gets tab selection focus if you click in the right spot

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#318]
### Expected Behaviour
Clicking on a checkbox (or other focusable component) selects it, but doesn't show as having tab focus

### Actual Behaviour
You can get a blue selected outline if you click in the right place.

#### Steps to Reproduce
You can repro pretty easily by clicking in the upper-right corner of the checkbox on the docs. You might need to click a few times to get it to happen.

#### Screenshot

<img width="384" alt="selected-focus" src="https://user-images.githubusercontent.com/48841507/69671619-0da25700-105c-11ea-94d0-965d47f614bd.png">

**Comment by cdvu1** [comment]
The outline appears around `<sp-button>` as well. 
![image](https://user-images.githubusercontent.com/32367695/69672312-b21c9d00-104c-11ea-9d47-b2abffc6be69.png)

**Comment by Westbrook** [comment]
Interesting. This focus is actually on the `<sp-checkbox>` element itself, rather than on the `input` that should receive focus when needed. I can more consistantly cause it to occur by clicking on the space that makes up the `margin-right` styling for the `label` element internal to the shadow DOM.

That means that while the real fix here is something like:
```
:host(:focus) {
    outline: none;
}
```
Whatever is actually happening under the covers could happen to any element that extends `Focusable` (so it should maybe added there rather than on a specific element, and included in the extensions), and is showing a case where it isn't passing `focus()` as it should, which is troublesome. It almost like we need to add:

```
this.addEventListener('click', e => {
    const path = e.composedPath();
    if (path[0] === this) {
        this.focus(); // or maybe blur(), which seems a little weird, but supports the "in the margin context"
    }
});
```
or similar...

**Comment by adixon-adobe** [comment]
updated the issue title to make it clearer this affects multiple components.

**Comment by Westbrook** [comment]
### Alternate, less invasive, fix idea!

```
:host {
    pointer-events: none;
}

:host(:not([disabled])) > * {
    pointer-events: all;
}
```

That's it.

If we add this to the `focusable.css`, and ensure that all extensions leverage it, then mouse interaction should never allow us to get into this context.

I'm somewhat worried that it isn't striking at the root problem, but I can't see a root problem... 🤔

**Comment by cdvu1** [comment]
The issue is still occurring in Firefox and Safari. The issue does not occur in Chrome. 

![image](https://user-images.githubusercontent.com/32367695/70950111-773ad300-2014-11ea-9192-ff21480742ad.png)

**Comment by adixon-adobe** [comment]
This is a little tricky to debug, but from what I can tell for checkbox the `<label id="root">` element is getting focus. Hard to validate that in the debugger though.

**Comment by Westbrook** [comment]
I'd be interested in comparing notes with you on this @adixon-adobe. The debug is indeed tricky here, and I'm not sure I'm getting a better/worse/errant read on it with what I'm seeing.

I _think_ I'm seeing, in the browsers in question, when you click on them they initially give you a `focusin` event, which we handle via:

```
        this.addEventListener('focusin', (event) => {
            console.log('focusin', event.composedPath()[0])
            if (event.composedPath()[0] === this) {
                this.handleFocus();
            }
        });
```

This appropriately forwards the focus to the `focusElement` on the first interaction. However, subsequent clicks on the element silently (no `focus` or `focusin` events triggered) move the focus up to the root, which causes the outline we're seeing. We can do the work to prevent that outline on focus via (if want to hide it):

```
:host(:focus) {
    outline: none;
}
```

But, luckily, in this case, it's telling us something important, our focus isn't being managed as we expect. 😱 

I think on these `click` events we might want to be re-forwarding the focus, a la:

```
this.addEventListener('click', (event) => {
        this.focus();
});
```

This becomes a question of whether we always want to be refocusing, as there are a larger number of elements relying on this base class now than ever. It may be that we only want to refocus on "input" elements or some other specific species of elements that we are extended from `Focusabled`, which might mean local listeners (a lot of duplicated effort) or an intermediary base class (lack of clarity as to whether it's the right abstraction).

**Comment by adixon-adobe** [comment]
@Westbrook you're way further than me here so thanks for the writeup! I was really just looking in the chrome debugger to see if I could find something obvious in the docs page (the pre-code debugging triage step).

Another pattern we could use is have a default behavior, but also give derived classes an easy way to override the behavior (e.g. with a `protected get forwardFocus(): boolean` method). I find that's a nice stopgap to creating a separate intermediate base class (but obviously if you have more than 2 of these in a class that's a pretty clear sign you're overloading it).

**Comment by Westbrook** [comment]
I really like that as a possible path forward! Below is a list of the implementations of `Focusable` at current. It looks like _might_ be able to get away with just adding this and then confirming code order work in `sp-dropdown` and `sp-tab-list`?

| File | Focus and click elements should always be the same? |
| --- | --- |
| button-base.ts | ✅|
| checkbox-base.ts | ✅|
| dropdown.ts | 🚫 maybe, when you click an option it technically focuses the `focusElement` |
| link.ts | ✅|
| radio.ts | ✅|
| sidenav-item.ts | ✅|
| slider.ts | ✅|
| tab-list.ts | 🚫 maybe, when you click a tab, it technically becomes the `focusElement` |
| textfield.ts | ✅|
| focusable.test.ts | test... |

**Comment by adixon-adobe** [comment]
I'd expect dropdown to have some subtleties since expectations between keyboard & mouse behavior are different (you should be able to arrow down in dropdown elements and focus those individually, but clicking a menu item has the effect of closing the menu, so maybe the close is actually what changes the focus to the `focusElement`).

For tab-list, I think having the tab clicked get focus makes sense (It looks like scrolling in the docs is busted so I can't see it, but I'm assuming this is the same thing as the "Tabs" control in spectrum/spectrum-css).
