### ISSUE TITLE
[Bug]: tooltip tail is incorrectly placed when using 'top-start' placement

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#3180]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tooltip

### Expected behavior

Tooltip tail should be correctly placed not too close to the edge of the tooltip to look visually correct in all cases.

### Actual behavior

Tip tail is sometimes placed at the very edge, creating an artifact at the rounded border.

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
This was updated in #3456, feel free to open a new issue wth updated reproduction steps if you continue to experience issues in this area.
