### ISSUE TITLE
[Feat]: Submenu of menu item should be open-able via `open` attribute

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3184]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

MenuItem

### Description of the requested feature

We have a use case to control the opening of a submenu of a `sp-menu-item`. Currently it seems it's been only use to reflect the current submenu "open" state. 
We'd like to set that attribute by the outer logic to let the menu-item open it's submenu, when `open` attribute is preset.

**Comment by Westbrook** [comment]
Available and confirmed via the [new Overlay API](https://github.com/adobe/spectrum-web-components/discussions/2764).
