### ISSUE TITLE
[Bug]: Slider performance issues on mobile, low-end devices or complex apps.

### ISSUE THREAD

**Issue by moisadoru** [adobe/spectrum-web-components#3186]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider

### Expected behavior

Dragging the slider should be smooth, even on low-end devices.

### Actual behavior

When using the slider on mobile devices or low-end laptops, dragging the handle lags, as seen in the attached video. Setting the slider handle's absolute position via left/right CSS seems to cause style recalculations and layout changes.

### Screenshots

https://user-images.githubusercontent.com/109328/237030810-945f160d-f946-439f-8f34-a579e25b0ea7.mp4

### What browsers are you seeing the problem in?

Chrome, Microsoft Edge

### How can we reproduce this issue?

1. If using a powerful machine (eg. M1), configure hardware concurrency to 4 and 4x CPU throttling to simulate a low-end/mobile device, or use a real consumer device (phone, non-pro laptop)
2. Go to any page that renders an SWC slider, eg. https://opensource.adobe.com/spectrum-web-components/components/slider
3. Drag the slider
4. Observe the slider handle lagging behind the cursor

### Logs taken while reproducing problem

[Trace-20230509T101433.json.zip](https://github.com/adobe/spectrum-web-components/files/11428706/Trace-20230509T101433.json.zip)

**Comment by Westbrook** [comment]
If you continue to see issues with this post #3243 please open a new issue with updated reproduction information.
