### ISSUE TITLE
[Bug]: Multiple active overlays are opened when using action menu

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#3199]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Expected behavior

only one action menu should be opened at a single time

### Actual behavior

Multiple action menu items are opened

### Screenshots

<img width="1728" alt="Screenshot 2023-05-11 at 3 26 19 PM" src="https://github.com/adobe/spectrum-web-components/assets/125646446/1b6525f6-abf5-47d6-a482-4b115c4ddd30">

### How can we reproduce this issue?

1. use the following code to create two action menu elements.
2. click on the first action menu element.
3. Navigate to the second action menu item using the tab.
4. Press the down arrow.
5. Observe that both the action menu items are opened at the same time.

### Sample code that illustrates the problem

// By Westbrook Johnson @westbrook

import { LitElement, html, customElement, TemplateResult } from "lit-element";
import "@spectrum-web-components/action-menu/sp-action-menu.js";
import "@spectrum-web-components/menu/sp-menu.js";
import "@spectrum-web-components/menu/sp-menu-item.js";
import "@spectrum-web-components/menu/sp-menu-divider.js";
import "@spectrum-web-components/menu/sp-menu-group.js";

@customElement("my-counter")
export default class MyCounter extends LitElement {
  protected render(): TemplateResult {
    return html`
      <sp-action-menu>
        <span slot="label">More Actions</span>
        <sp-menu-group>
          <span slot="header">These actions</span>
          <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
      <sp-action-menu>
        <span slot="label">More Actions</span>
        <sp-menu-group>
           <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
    `;
  }
}

**Comment by westbrookj** [comment]
@venkateshjo Think you tagged the wrong user 😉

**Comment by Westbrook** [comment]
@venkateshjo this doesn't seem to be occurring in https://studio.webcomponents.dev/edit/EYQn9T6wOnieZbv4xnPj?branch=multiple-menus%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories It's difficult to fully tell via screen shot, but it appears that you have unmatched HTML tags in the demo where you ran into this situation.

**Comment by venkateshjo** [comment]
Hi @Westbrook, I mentioned the steps for reproducing the issue.
We need to use keyboard keys to reproduce the issue.
Attaching the video.

https://github.com/adobe/spectrum-web-components/assets/125646446/fcfd59e7-2851-48d6-8cce-7561da84ef2c

**Comment by Westbrook** [comment]
The `<sp-menu-group>` in your demo does not close correctly. You currently use an `</sp-menu-item>` to do so. These unmatched HTML tags will break the functional contract of the elements. If you could share the URL for the demo you've recorded, I could address it directly, but it'll will end up being roughly what I shared before.

**Comment by venkateshjo** [comment]
Thank you @Westbrook, tried without the menu group tag. But still observed the same behaviour.

// By Westbrook Johnson @westbrookj

import { LitElement, html, customElement, TemplateResult } from "lit-element";
import "@spectrum-web-components/action-menu/sp-action-menu.js";
import "@spectrum-web-components/menu/sp-menu.js";
import "@spectrum-web-components/menu/sp-menu-item.js";
import "@spectrum-web-components/menu/sp-menu-divider.js";
import "@spectrum-web-components/menu/sp-menu-group.js";

@customElement("my-counter")
export default class MyCounter extends LitElement {
  protected render(): TemplateResult {
    return html`
      <sp-action-menu>
        <span slot="label">More Actions</span>
          <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
      <sp-action-menu>
        <span slot="label">More Actions</span>
           <sp-menu-item disabled>
          Make work path
        </sp-menu-item>
      </sp-action-menu>
    `;
  }
}

**Comment by venkateshjo** [comment]
sharing the demo url: https://studio.webcomponents.dev/edit/vPQlEPmQzfp8Q72XQwQy/src/index.ts?p=stories

**Comment by venkateshjo** [comment]
In our use case, if the artboard is empty most of the menus are disabled by default.
Because of this issue, the application is crashing at times.

**Comment by Westbrook** [comment]
If you are disabling all of the Menu Items, why not disable the `sp-action-menu` itself? https://studio.webcomponents.dev/edit/6UMBTxrIjrSZkxyytwZp/src/index.ts?p=stories

**Comment by venkateshjo** [comment]
This will impact user experience as menus will be not available when no arts are selected.

**Comment by venkateshjo** [comment]
Currently few bugs are created because of this issue on AI WEB

https://jira.corp.adobe.com/browse/VEN-7137
https://jira.corp.adobe.com/browse/VEN-7140

**Comment by hunterloftis** [comment]
@venkateshjo can you confirm that this issue is resolved with the in-testing [overlay update](https://github.com/adobe/spectrum-web-components/discussions/2764)?

https://codesandbox.io/s/3199-13t9yj?file=/src/my-component.ts

**Comment by venkateshjo** [comment]
Hi @hunterloftis, @Westbrook,

I'm unable to open multiple overlays in the sandbox. Looks like the issue is fixed in the codesandbox.
Please let me know once this update is released.
