### ISSUE TITLE
Feature Request: A way to manually control overlays

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#321]
### Expected Behaviour

We should have a way to manually open or control overlays.

### Actual Behaviour

Right now the only easy way to open an overlay is to use an `overlay-trigger`. However, not all use cases of overlays are triggered by `click` or `hover` events. 

#### Sample Code that illustrates the problem

Right now you have to write code like this to manually open an overlay: https://github.com/adobe/spectrum-web-components/blob/83e4151dc7d1be7617c48ec08fa39e4acbf0f9a1/documentation/src/components/side-nav-search.ts#L74-L115

**Comment by Westbrook** [comment]
This gets dangerously close to pairing #402 with a "Remove the need for `overlay-trigger`" issue/PR pair. Should we push in that direction and make the overlay functionality some sort of mixin or module? The alternative would be to actually use an `overlay-trigger` element in this context and surface a manual API for `OverlayOpen`, possibly an attribute/method pair. Which do you think would solve this issue specifically, while also preparing the library for the most success long term?

**Comment by cuberoot** [comment]
My gut feeling is that the first option is the way to go. I don't know if we want to eliminate the `overlay-trigger` as it is a way to use our overlay system without having to write JS code. You can open overlays from vanilla HTML.

However, if we want to use overlays in our own code and allow programatic control, a mixin might be the thing. We could make `overlay-trigger` use the mixin...
