### ISSUE TITLE
[Bug][a11y]: AccordionItem should not have role="listitem"

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-web-components#3212]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Accordion, AccordionItem

### Expected behavior

`sp-accordion-item` should not expresses its WAI-ARIA `role` as a `listitem`.

### Actual behavior

`sp-accordion-item` expresses its WAI-ARIA `role` as a `listitem` but the containing `sp-accordion` is not a `list`.

This seems to come from Spectrum-CSS, with: 

https://github.com/adobe/spectrum-web-components/blob/cd8c99f3451ad8cde4d561c14d911b4060c2bca9/packages/accordion/src/spectrum-accordion-item.css#L45

Coming from `.spectrum-Accordion-item`: 

https://github.com/adobe/spectrum-css/blob/e9c58caecfcfa8dd71a25d582c2394ed120e6b5e/components/accordion/index.css#L53

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

1. Go to [https://opensource.adobe.com/spectrum-web-components/components/accordion/](https://opensource.adobe.com/spectrum-web-components/components/accordion/)
2. Using Web Inspector tool, inspect the Accessibility properties for the first `<sp-accordion-item>` element in the first Accordion example.
3. Notice that in the Accessibility tree, the `<sp-accordion-item>` is identified as having `role="listitem"`
4. Using Web Inspector tool, inspect the Accessibility properties for the `<sp-accordion>` element that contains the `<sp-accordion-item>` in the first Accordion example.
5. Notice that in the Accessibility tree, the `<sp-accordion>` has no role defined.

Related issue: [Spectrum CSS Issue #1884](https://github.com/adobe/spectrum-css/issues/1884)

**Comment by Rajdeepc** [comment]
Adding WIP PR: https://github.com/adobe/spectrum-css/pull/1789

**Comment by Rajdeepc** [comment]
The above PR is merged. waiting for the issue to be tested.

**Comment by venkateshjo** [comment]
This issue is fixed in the latest swc.
we can close this issue.

**Comment by Rajdeepc** [comment]
Thanks @venkateshjo
