### ISSUE TITLE
[Bug]: Number field is taking -0 as input

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#3214]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Expected behavior

On entering -0, it should appear as 0.

### Actual behavior

-0 is being displayed

### Screenshots

<img width="855" alt="Screenshot 2023-05-19 at 4 03 17 PM" src="https://github.com/adobe/spectrum-web-components/assets/127212746/2108620c-0b10-4a71-9708-f76ebbc6de4c">

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to First example in https://opensource.adobe.com/spectrum-web-components/components/number-field/
2. Click on number field in 1st Example
3. Input -0 and press enter or click outside
4. -0 is displayed on the field.

**Comment by AbhinandanKainth** [comment]
Hi @najikahalsema @Westbrook, 
Should I look into it? 
-0 does not have any value from the user's point of view. 
Is it technically feasible to try to achieve the expected behaviour mentioned above?

**Comment by Westbrook** [comment]
Some extra finders on the keyboard here would be great. Seems like it dates back to proper use of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#signdisplay. Let us know what you find!

**Comment by Westbrook** [comment]
Despite the somewhat odd default behavior in the browser. It seems the use of `signDisplay: 'negative'` in the link above would achieve the end goals of the OP. Closing for now.
