### ISSUE TITLE
[Bug]: Text label of the sp-button is not aligned to center

### ISSUE THREAD

**Issue by cdprashanth** [adobe/spectrum-web-components#3215]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-button

### Expected behavior

Text label of the sp-button should be  aligned to center vertically

### Actual behavior

Text label of the sp-button is not aligned to center vertically 

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

1)Go to the doc page of  sp-button:
https://opensource.adobe.com/spectrum-web-components/components/button/
2) click on "Try it on webcomponents.dev"
3) For the primary, outline button, change the element as below, to have bigger height nad width to see issue clearly:
<sp-button quiet="" variant="primary" dir="ltr" size="m" treatment="outline" focusable="" tabindex="NaN" role="button" style="height:120px; width:300px">Primary</sp-button>
4) Observe that text string "Priamry" of the button is not centrally aligned.
5) This is because  'label' span in shadow-root of sp-button has  align-self: start; 
i.e 
 #label  style has " align-self: start" . 
Either it needs to be removed or we should have align-self: center

**Comment by Westbrook** [comment]
This is delivered as desired by the design team.

**Comment by cdprashanth** [comment]
<img width="359" alt="Screenshot 2023-05-19 at 7 08 15 PM" src="https://github.com/adobe/spectrum-web-components/assets/4542371/85138064-79ef-4e9c-a51b-f1bf3d7cffe5">
if you see the "CTA" is not aligned to center of the button vertically

**Comment by cdprashanth** [comment]
<img width="500" alt="export dialog showing button text mis alignment" src="https://github.com/adobe/spectrum-web-components/assets/4542371/845a1fc5-c878-48c3-82b5-011864d4c068">
we can see the Ok and Cancel text in above dialog do not look to be aligned to center of button.
This is in Venus, export screen
