### ISSUE TITLE
[Feat]: Dropzone filled+dragged state

### ISSUE THREAD

**Issue by mlogsdon18** [adobe/spectrum-web-components#3232]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Dropzone

### Description of the requested feature

There is a new state of the dropzone component for when it is filled and dragged. The design for this can be seen in Spectrum CSS docs and I've attached the design mock-up. 

### Mockups or screenshots

![Screenshot 2023-05-23 at 3 21 17 PM](https://github.com/adobe/spectrum-web-components/assets/99203545/2e12b0b6-f2eb-41f6-9738-3523e2aaaa0c)

### Implementation notes or ideas

There is already a "dragged" state so that state would just need to be updated whenever the component is also filled, meaning some type of attribute to identify the component as filled would need to be added as well.

**Comment by najikahalsema** [comment]
completed via https://github.com/adobe/spectrum-web-components/pull/4617
