### ISSUE TITLE
[Bug]: Progress Circle filled despite progress being 0 on Safari intermittently 

### ISSUE THREAD

**Issue by hlmitchell** [adobe/spectrum-web-components#3239]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Progress Circle

### Expected behavior

I expect the Progress Circle to not be filled when progress is 0. The circle should fill as the progress is increased. 

### Actual behavior

The progress circle is filled when progress is 0 and does not change as progress is updated. 

### Screenshots

https://github.com/adobe/spectrum-web-components/assets/20149192/8ccf101d-ecb3-4fd5-82b9-1fbc6c8a6609

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Open a progress circle in Safari browser that will update progress over time
2. See error but only intermittently 

### Sample code that illustrates the problem

`
class Spinner extends LitElement {

    @state()
    private _currentProgress = 0;

    firstUpdated(): void {
        setInterval(() => {
            this._currentProgress = this._currentProgress + 1;
        }, 1000);
    }

    render() {
        return html`
            <sp-progress-circle
                size="m"
                progress=${this._currentProgress}
            >
            </sp-progress-circle>
        `;
    }
}
`

**Comment by nawazmobusss** [comment]
Hello Spectrum team, do we have any updates on this bug?

**Comment by nawazmobusss** [comment]
Hello @najikahalsema, Can you help us with this issue before the Mobile release? It's important for the user experience.

cc: @hlmitchell @Westbrook

**Comment by Rajdeepc** [comment]
@nawazmobusss I have tried this on safari. It works fine.
Please check here: https://studio.webcomponents.dev/edit/UiCmaTOcTA4YFPeXe7YH/src/index.ts?p=stories

Note: open this in Safari

**Comment by Rajdeepc** [comment]
Closing this as this is not reproducible in the latest versions. Feel free to reopen if this is re orccuring.
