### ISSUE TITLE
[Bug][a11y]: Disabled button is showing incorrect font color in High Contrast Mode for some variants

### ISSUE THREAD

**Issue by dineshy87** [adobe/spectrum-web-components#3244]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Button (primary, negative, secondary, quiet)

### Expected behavior

All quiet, primary, secondary, negative buttons must use GrayText as font color when they're disabled.

### Actual behavior

Some variants like primary, secondary, negative and quiet buttons are showing in ButtonText color instead of GrayText when they're disabled.

### Screenshots

<img width="825" alt="Disabled buttons of some variants showing wrong color in hcm" src="https://github.com/adobe/spectrum-web-components/assets/16927765/d4642468-1694-4718-9828-5ea160d17093">

### How can we reproduce this issue?

1. Go to 'https://studio.webcomponents.dev/preview/sNQ3ZM8hLebINbXzl9Vt/src?p=stories&busid=7f405180-fd86-11ed-ab77-e1c7fb078b46'
2. Open the Chrome browser and navigate to the website you want to test.
3. Open the Chrome DevTools by pressing Ctrl+Shift+I (Windows) or Cmd+Option+I (Mac).
4. Click on the "Rendering" tab.
5. In the Rendering tab, scroll down and find the "Emulate CSS media feature forced-colors" option.
6. Select the "active" option from the drop-down menu.

The website should now be displayed in forced-colors mode.

**Comment by Westbrook** [comment]
This delivery has been corrected by updated CSS dependencies along the way, as seen in the OP demo:

<img width="960" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/1156657/cc3ab3a1-6e6e-45af-83e4-797ee8c92fec">
