### ISSUE TITLE
[Bug]: sp-color-area does not bubble up unhandled keyboard events 

### ISSUE THREAD

**Issue by cdprashanth** [adobe/spectrum-web-components#3246]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-color-area

### Actual behavior

sp-color-area listens to keyboard events and processes it. This is causing Venus app's keyboard shortcut to stop working , for eg when color picker is open ,and sp-color-area is in focus, key 'i' press is not activating eye dropper tool. https://jira.corp.adobe.com/browse/VEN-7053
Can sp-color-area be modified to bubble up non-handled keyboard events , so that this issue is fixed ?

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by cdprashanth** [comment]
Potential fix that works:

```
pdhotre@Prashantkumrs-MacBook-Pro src %  diff -aurN  /Users/pdhotre/src/venus/uec/ProteusWeb/source/Proteus/Resources/web/node_modules/@spectrum-web-components/color-area/src/ColorArea.dev.js ColorArea.dev.js
--- /Users/pdhotre/src/venus/uec/ProteusWeb/source/Proteus/Resources/web/node_modules/@spectrum-web-components/color-area/src/ColorArea.dev.js	2023-02-15 16:00:38.000000000 +0530
+++ ColorArea.dev.js	2023-05-30 15:31:56.000000000 +0530
@@ -133,7 +133,9 @@
       event.preventDefault();
       this.activeKeys.add(code);
       this.handleKeypress();
-    }
+    } else {
+		window.document.dispatchEvent(new event.constructor(event.type, event));
+	}
   }
   handleKeypress() {
     let deltaX = 0;
pdhotre@Prashantkumrs-MacBook-Pro src %
```

**Comment by Westbrook** [comment]
While SWC does consume this event in its `sp-story-decorator` demo helper, `sp-color-area` does not augment, consume, or prevent the event in question in any way. You can test this in https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/crxLSSCXLFPpmUsM6GJQ/src/index.ts?branch=keyboard-events%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories where the `sp-story-decorator` has been removed, while both `keydown` and `keyup` listeners have been added to the `window.document`, inline with your proposed fix above.

At this time, without evidence to point to `sp-color-area` having any effect on keyboard events, we plan to close this issue in the near future. Feel free to share a more focused reproduction of your issue if you feel there is are still changes to be address as part of this situation.

**Comment by cdprashanth** [comment]
Venus jira is https://jira.corp.adobe.com/browse/VEN-7053?filter=505677 .
This was issue in Venus code and I dont see any issue in sp-color-area.
So closing this
