### ISSUE TITLE
[Feat][Menu]: Add support for menu item description

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#3258]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-menu, sp-menu-item

### Description of the requested feature

Menu items should support a description to match what currently exists in core tokens work. 

### Mockups or screenshots

![image](https://github.com/adobe/spectrum-web-components/assets/44980010/4edaf680-ce0f-411d-9113-ddc9a430141a)

### Implementation notes or ideas

Add a div with `id="description"` that mimics the behaviour of the existing `label` attribute (which uses an id to style it and has a slot within in order for it to be accessed by the user). If this isn't the right approach, a regular slot element will do.

**Comment by TarunAdobe** [comment]
created a pr for this - #3559
