### ISSUE TITLE
[Bug][a11y]: ActionMenu accessibility implementation includes irrelevant or incorrect aria-* attributes

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-web-components#3259]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu, ActionButton, Picker

### Actual behavior

There are several small issues with ActionMenu accessibility implementation that require changes to ActionButton and Picker as well.

1. `sp-action-button` within shadowDOM for  `sp-action-menu` includes `aria-pressed` in addition to `aria-expanded` state, which is overkill.

Possible solution would be to change:
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/action-button/src/ActionButton.ts#L213

to 

```ts
        const canBePressed = 
            isButton && 
            (this.selected || this.toggles) && 
            !(this.hasAttribute('aria-haspopup') && this.hasAttribute('aria-expanded'));
```

So that we don't add `aria-pressed` to popup buttons that have `aria-expanded` state.

2. `sp-action-button` within shadowDOM for  `sp-action-menu` should only include `aria-controls` conditionally when the menu is `open`, and `aria-controls` should control the `menu` rather than the `popover`.

Possible solution would be to change:
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/action-menu/src/ActionMenu.ts#L68

to

```ts
                aria-controls=${ifDefined(this.open ? 'menu' : undefined)}
```

2a. Similarly within `sp-picker` add the following to the button within the shadowDOM at 
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/picker/src/Picker.ts#L420

```ts
               aria-controls=${ifDefined(this.open ? 'menu' : undefined)}
               aria-expanded=${this.open ? 'true' : 'false'} 
```

You'll need to `import {ifDefined} from '@spectrum-web-components/base/src/directives.js'`;

3. Remove `role="dialog"` from the `sp-tray` and `sp-popover` within `sp-picker` by changing 
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/picker/src/Picker.ts#L501
to
```ts
                    role="presentation"
```
and
https://github.com/adobe/spectrum-web-components/blob/c820757885bf4b000cacd84b54a0df618df72bd4/packages/picker/src/Picker.ts#L513
to
```ts
                    role="presentation"
```

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Rajdeepc** [comment]
@majornista I see you have already started working on this. May I assign this to you?
