### ISSUE TITLE
[Bug]: Using arrow keys to toggle buttons in an Radio Group does not trigger change event

### ISSUE THREAD

**Issue by yflores814** [adobe/spectrum-web-components#3262]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Radio Group

### Expected behavior

Using keyboard arrows to select radio buttons in a radio group should trigger change event.

### Actual behavior

We see radio buttons selected when using arrow keys but on change event attached to radio group is not triggered.

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

1. create radio group with a change event and radio buttons
2. use arrow keys to alternate between radio buttons
3. see change event is not called

**Comment by najikahalsema** [comment]
Have you tried listening for a change event on `<sp-radio-group>`?

**Comment by majornista** [comment]
Fix by changing this:
https://github.com/adobe/spectrum-web-components/blob/c5f67662ac54d0e37debaf7cbd7c2df60e8b294e/packages/radio/src/RadioGroup.ts#L54-L56
to this:
```ts
        elementEnterAction: (el: Radio) => {
            this._setSelected(el.value);
        },
```
