### ISSUE TITLE
[Bug]: sp-number-field pressing increment/decrement buttons using NVDA moves focus to the text field

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#3272]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

When I press the increment or decrement buttons focus should stay on the button. I can't press it more than once if focus moves

### Actual behavior

Focus currently moves to the text field

### What browsers are you seeing the problem in?

Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/number-field/
2. Turn on NVDA 
3. arrow through the page (down arrow) until you get to a number field
4. Press down arrow one more time to get to the increment button
5. press space or enter 
Note focus moves to the text field and forms mode gets enabled

**Comment by najikahalsema** [comment]
Related to #3274 #3271
