### ISSUE TITLE
[Bug]:  In Venus, overlay-trigger is eating the trackpad event to zoom and pan 

### ISSUE THREAD

**Issue by cdprashanth** [adobe/spectrum-web-components#3280]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay-trigger

### Actual behavior

In Venus, we are getting an issue where overlay-trigger is eating the trackpad event to zoom and pan with two finger drag on canvas.
(Logging on behalf of prasyada@adobe.com)
Venus Jira : https://jira.corp.adobe.com/browse/VEN-7278

'aria-modal = true ' by default for overlay-trigger (ie active-overlay element) I guess this could be the root cause of issue.
If we have flexibility to set aria-modal explicitly during init  , then we can solve this issue

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
These Overlays are intended to be "modal" which prevents interaction with the rest of the page. Some of these will change as part of the new version of the Overlay API, but without an abstract reproduction it is difficult to outside with certainty whether this situation will change for you in the future.
