### ISSUE TITLE
keyboard focus issues on website

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#329]
### Expected Behaviour
Keyboard focus should move to all actionable components and be visible when it gets there

### Actual Behaviour
Focus jumps directly from the "spectrum web components" link at top left to the first interactive item in the page. It skips the sidenav and the tabs completely

### Reproduce Scenario (including but not limited to)
Go to https://opensource.adobe.com/spectrum-web-components/ and press tab a few times

#### Steps to Reproduce
Go to https://opensource.adobe.com/spectrum-web-components/ and press tab a few times

#### Platform and Version
Chrome  78.0.3904.97
Mac 10.15.1

**Comment by Westbrook** [comment]
Thanks for the issue @jnurthen!

We're tracking the update to the `sp-tabs-list` in the following PR as driven by your notes in #292: https://github.com/adobe/spectrum-web-components/pull/296 Once it merges then we should be in a more stable place with that component.

For the `sp-sidenav` pattern, we're not quite to the PR stage, but work is in progress on that in https://github.com/adobe/spectrum-web-components/tree/westbrook/side-nav. It's good to have a ticket to track it with.
