### ISSUE TITLE
[Bug]: Asynchronous open and close calls on sp-action-menu is resulting in uncaught error

### ISSUE THREAD

**Issue by nija1993** [adobe/spectrum-web-components#3343]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action menu

### Expected behavior

No error should be thrown

### Actual behavior

Following error is thrown:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at HTMLElement.generatePopover (Picker.js:290:43)
    at HTMLElement.openMenu (Picker.js:298:20)
    at HTMLElement.update (Picker.js:452:22)
    at HTMLElement.update (observe-slot-text.js:109:19)
    at HTMLElement.update (ActionMenu.js:88:15)
    at HTMLElement.performUpdate (reactive-element.js:1331:14)
    at HTMLElement.scheduleUpdate (reactive-element.js:1263:17)
    at HTMLElement._$Ej (reactive-element.js:1235:25)
```

### Screenshots

<img width="1518" alt="Screenshot 2023-06-21 at 17 50 53" src="https://github.com/adobe/spectrum-web-components/assets/6003419/c14525f0-f040-42aa-8d9d-3e087f81b29d">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/action-menu/
2. Open developer tools and inspect the sp-action-menu element present in the "Sizes" section
3. Ensure that in the elements tab the sp-action-menu is selected
4. Go to console tab
5. Execute the following commands
```
const elem = $0;
window.setInterval(() => elem.open = false, 100);
window.setInterval(() => elem.open = true, 100);
```

**Comment by Westbrook** [comment]
My mistake, the "persistent issues" come from the repro leveraging `setInterval` with the later interval always being `open = true`. The actual issue in the OP seems to be fixed by #3456
