### ISSUE TITLE
[Bug]: Dropzone prevents pointer events to underlying buttons and links

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3357]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dropzone

### Expected behavior

Underlying components (buttons, links, etc.) within dropzone should receive pointer events and be clickable.

### Actual behavior

After last update with core tokens to v0.32 the dropzone :after element blocks all underlying elements from receiving pointer events. Patching this by adding `pointer-events:none` to :after element css style fixes this.

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to [dropzone storybook](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/dropzone--default)
2. Try to click on any link within the dropzone component

**Comment by Westbrook** [comment]
@pfulton this appears to exist in the CSS implementation, as well: https://opensource.adobe.com/spectrum-css/dropzone.html#dropzonedefault. Can you help get this issue into a location where the team can investigate this?

**Comment by dineshy87** [comment]
Lack of href on the 'select a file' link also makes it unreachable for keyboard users.
