### ISSUE TITLE
[Bug][a11y]: focus ring for sp-tag is not using Highlight color in high contrast mode

### ISSUE THREAD

**Issue by dineshy87** [adobe/spectrum-web-components#3365]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tag

### Expected behavior

In High Contrast mode, both the border color and the focus ring should use 'Highlight' color

### Actual behavior

Currently, it seems to show the regular focus ring color

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/preview/XRv5ItW8FrOoplbA6Sf5/src?busid=e7b218e0-1472-11ee-a208-cf38356c398b
2.Simulate forced-colors active on browser using Developer Tools

**Comment by Westbrook** [comment]
@pfulton this appears to be based on the CSS source, would yall be able to track down a fix for this?

**Comment by pfulton** [comment]
Verified on our end. I'll get a ticket in our backlog to address the issue.

Thanks for reporting this @dineshy87

**Comment by Westbrook** [comment]
Looks good to go in the current released version: https://opensource.adobe.com/spectrum-web-components/components/tags/#deletable

Please feel free to open a new issue with updated workflow if you feel there is something as yet uncovered here.
