### ISSUE TITLE
[Bug][a11y]: Tooltip content is not consistently accessible for screenreader users

### ISSUE THREAD

**Issue by dineshy87** [adobe/spectrum-web-components#3367]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tooltip

### Expected behavior

When an element that triggers a tooltip receives keyboard focus, the tooltip content appears and is read to screenreader users. THis can be made possible by having aria-describedby on the triggering element refer to the tooltip content.  

### Actual behavior

With the current implementation, The above expected behavior works fine on safari with VoiceOver. But doesn't seem to work while using VoiceOver with any other browser or with JAWS and NVDA screenreaders.

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/tooltip--overlaid-top
2. Turn Screenreader on
3. Using keyboard, focus on the triggering element that triggers a Tooltip.
4.Check if the tooltip content is read.

Try the above steps for Voiceover+Safari, VoiceOver+chrome, JAWS+Edge, NVDA+Edge

If you need access to [AssistivLabs](https://assistivlabs.com/dashboard) with which you can test on windows based screenreaders, please reach out to our team for access.

**Comment by Westbrook** [comment]
Closing in favor of #3596 which already has some notes on the current state and possible paths forward.
