### ISSUE TITLE
[Feat][a11y]: sp-dialog: use HTMLDialogElement with show() or showModal() method

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-web-components#3374]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Dialog,  DialogBase, DialogWrapper, Overlay

### Description of the requested feature

Dialog component should use modern HTML5 `<dialog>` component, which automatically traps keyboard focus, handles z-index positioning, and makes underlying content `inert`.

**Comment by Westbrook** [comment]
Closing as a duplicate of #2086 and the work going on in #3009
