### ISSUE TITLE
[Bug][a11y]: Update resizable examples in documentation using the label prop available in the api

### ISSUE THREAD

**Issue by dineshy87** [adobe/spectrum-web-components#3383]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Split-view

### Expected behavior

Not a big deal, but I think it's better to have the resizable examples in [documentation](https://opensource.adobe.com/spectrum-web-components/components/split-view/) use label prop. It also helps the devs using it understand that the separator is generally labelled after the primary pane. 

[ "The splitter also has an accessible name that matches the name of the primary pane."](https://www.w3.org/WAI/ARIA/apg/patterns/windowsplitter/#aboutthispattern)

### Actual behavior

None of the examples are labelled.

**Comment by castastrophe** [comment]
@Rajdeepc @dineshy87 Would this be a case where [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) might be more appropriate?

> separator is generally labelled after the primary pane.

Since the separator is labelled for the primary pane, we add an ID to it and point our splitter to that id:

```html
<sp-split-view resizable aria-labelledby="left-panel">
    <div>
        <h1 id="left-panel">Left panel</h1>
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry.
        </p>
    </div>
    <div>
        <h2>Right panel</h2>
        <p>
            It is a long established fact that a reader will be distracted by
            the readable content of a page when looking at its layout.
        </p>
    </div>
</sp-split-view>
```

**Comment by castastrophe** [comment]
I'll add we could also get a little smart with this if the split view has any awareness of which panel is _more_ visible. If one exceeds 60% of the available space for example, we could swap the labelledby to point to the more dominant panel. Just an idea. I'm not sure how helpful that would be necessarily to a screen-reader experience without testing it in action.

**Comment by Rajdeepc** [comment]
Definitely this sounds intuitive but we need to test it out in action to get a broader perspective of how it will read out in screen reader.
