### ISSUE TITLE
[Bug][a11y]: QuickActions needs support for focus management

### ISSUE THREAD

**Issue by dineshy87** [adobe/spectrum-web-components#3404]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Quick Actions

### Expected behavior

As it is written today, there doesn't seem to be any in built support managing focus between quick actions and what triggers quick actions. Similar to components such as tooltip, popover, etc or any other components using overlay that move focus back to triggering element, quick actions must also allow focus management. Once done, the examples in documentation need to be updated.

### Actual behavior

No support for focus management.

**Comment by najikahalsema** [comment]
Quick actions is being deprecated (currently only at the design level).

**Comment by Westbrook** [comment]
Closing as won't fix being this package has been deprecated and will be removed as part of the move to 1.0.
