### ISSUE TITLE
[Bug]: Sp-textfield when in disabled state showing truncated text for long texts even on scrolling.

### ISSUE THREAD

**Issue by manomitam** [adobe/spectrum-web-components#3411]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield

### Expected behavior

Sp-textfield when in disabled state should show full text when the text is too long and the user scrolls like it shows when the textfield is enabled.

### Actual behavior

Sp-textfield when in disabled state showing truncated text for long texts even on scrolling.

### Screenshots

<img width="339" alt="Screenshot 2023-07-04 at 2 53 48 PM" src="https://github.com/adobe/spectrum-web-components/assets/138574838/45816e44-4129-4a07-8883-84044b9f026a">
<img width="1155" alt="Screenshot 2023-07-04 at 2 53 43 PM" src="https://github.com/adobe/spectrum-web-components/assets/138574838/8a785b32-5694-43f6-92f1-a31312696850">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

import {
  LitElement,
  html,
  css,
  customElement,
  TemplateResult,
} from "lit-element";
import "@spectrum-web-components/textfield/sp-textfield.js";

@customElement("my-textfield")
export default class MyTextfield extends LitElement {
  static styles = [ css`
    :host {
      display: block;
    }
  `];
  protected render(): TemplateResult {
    return html`
      <h4>Example</h4>
      <sp-textfield placeholder="Ya like jazz?" password>
      </sp-textfield>

      <h4>Valid</h4>
      <sp-textfield 
        placeholder="Enter an artist name" 
        value="this text is toooooooooooooooo long"
        disabled
        valid 
      >
      </sp-textfield>
      <h4>Invalid</h4>
      <sp-textfield 
        placeholder="Enter a song title" 
        invalid 
      >
      </sp-textfield>
      <h4>Quiet</h4>
      <sp-textfield 
        placeholder="Whisper your jazz opinions" 
        quiet 
      >
      </sp-textfield>
    `;
  }
}

**Comment by Westbrook** [comment]
@pfulton thoughts?

**Comment by Westbrook** [comment]
In both cases, it seems this activates when the `sp-textfield` is focused. In neither case when focus is not given to the host can you see the full text. Closing as working as expected.
