### ISSUE TITLE
[Bug]: Closing tooltip causes complete overlay chain to close too

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3418]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Tooltip

### Expected behavior

When we have chained overlays (example: overlay in an overlay) with an action-button in the inner overlay, that has an self-managed tooltip - clicking this action-button should close the tooltip BUT should not close the complete overlay chain.

### Actual behavior

Closing the tooltip causes closing the whole overlay chain.

### How can we reproduce this issue?

1. Go to webcomponents example
2. Click on button to trigger first level overlay
3. Click on button inside that first level overlay to trigger second level
4. Hover over 1st action-button to reveal tooltip
5. Click action-button
6. See tooltip dimissing, AND all overlays too

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/KJk8hzeTyHX3yVtDCkQP/src/index.ts?p=stories

**Comment by Westbrook** [comment]
This is looking good with the [new Overlay API](https://github.com/adobe/spectrum-web-components/discussions/2764). I'll look into adding specific support for this interaction to our test suite to ensure we don't regress in the future.
