### ISSUE TITLE
[Spike] Investigate migration of Meter component to Spectrum Tokens

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#3424]
This Spike is to document the steps taken to migrate the meter component to Spectrum Web Components.
We need to create a step by step guide to simplify the process of migration of other components. This issue is to track the documentation as well findings and solutions taken.

**Comment by Rajdeepc** [comment]
WIP: https://paper.dropbox.com/doc/CreatingMigrating-Meter-component-to-Spectrum-Tokens-WIP--B77cWK5a83~0LiYz9UcrcHfCAQ-WR3NuCLQNe41v1VernDEX

**Comment by Westbrook** [comment]
From a documentation standpoint, Meter is tricky because it doesn't come from "meter" in CSS is comes from "progressbar", which could cause confusion. Is there specific benefit from documenting a less "normal" pattern here?

**Comment by Rajdeepc** [comment]
I am planning to create few of these to help the newcomers onboarded to the codebase.but I am more focussed on a step by step guide to create/migrate spectrum components on a holistic approach and not component specific which would also align with the architecture of the existing codebase.

**Comment by Rajdeepc** [comment]
Closing. Moving the follow up on a generic approach [here](https://paper.dropbox.com/doc/Step-by-step-guide-on-creating-SWC-component-from-CSS-component--B78ExKMmgySlierAAv8_qrqzAQ-luUI6wTtblnZZoTCM4WJW)
