### ISSUE TITLE
[Bug]: Textarea with quiet and grows does not correctly indicate focused

### ISSUE THREAD

**Issue by joekukish** [adobe/spectrum-web-components#3432]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Textfield

### Expected behavior

Focused state of a textfield with multiple, quiet and grows would be correctly shown.

### Actual behavior

A big blue box appears on top of the textarea.

### Screenshots

<img width="813" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/1413153/625c822d-0d87-476a-a462-e0b3cb681899">

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/textarea/#grows
2. Click on the textfield with "Background (quietly)"
3. Notice how the focused style seems broken

### Sample code that illustrates the problem

NA

### Logs taken while reproducing problem

NA

**Comment by Rajdeepc** [comment]
@blunteshwar Please link your PR in this ticket.

**Comment by blunteshwar** [comment]
its already linked


![Image](https://github.com/adobe/spectrum-web-components/assets/32033946/94b9328b-1da1-4623-9baa-c4c94d68f229)
