### ISSUE TITLE
[Feat]: Add sanity checking of released package contents

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#3443]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

we've had issues with sp-icons-workflow

### Description of the requested feature

When we pick up a new release, we can be reasonably sure there aren't obvious missing package contents.

In particular, we've run into issues like this in 0.33.2 where the custom-elements.json file is blank in some projects: https://unpkg.com/browse/@spectrum-web-components/icons-workflow@0.33.2/custom-elements.json (fixed in 0.34.0)

When these files aren't present, it breaks linting we have in place, as those files are used for defining component to import mappings.

### Implementation notes or ideas

I could see just using a simple minimum file size check for these.

**Comment by Westbrook** [comment]
@adixon-adobe In particular, you team leverages the presence of `tagName` properties in this file, right?
