### ISSUE TITLE
<sp-action-button> doesn't center it's slotted content

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#346]
### Expected Behaviour
If I add an icon to an sp-action-button it should be vertically centered, e.g:

```
<sp-action-button>
    <sp-icon size="s" name="ui:Magnifier" />
</sp-action-button>
```

### Actual Behaviour
Icon is top-aligned.

**Comment by adixon-adobe** [comment]
The div#label element looks like it's causing some problems (it's inheriting line-height & padding, but could also maybe be fixed with an `display: inline-flex` style).

**Comment by Westbrook** [comment]
Does this perform as expected when using `slot=“icon”`? The default slot doesn’t manage anything but text styling as per Spectrum CSS.

**Comment by adixon-adobe** [comment]
Yes -- missed that. Thanks!
