### ISSUE TITLE
[Bug]: Focusing component (for eg Button) through Tab key in Express theme shows blue border color instead of purple.

### ISSUE THREAD

**Issue by sonirajan** [adobe/spectrum-web-components#3481]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

All

### Expected behavior

Focusing each component through keyboard tab key in Express theme should highlight component in purple color (indigo-1000) instead of blue color.

### Actual behavior

Focusing each component through keyboard tab key in Express theme highlight component in blue color.

### Screenshots

![image](https://github.com/adobe/spectrum-web-components/assets/6495820/d936bf57-19fb-407e-9924-c2e519184888)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/button-group-sizes--m
2. Select Express theme from drop down. 
3. Open Button Group buttons from left side bar. 
4. Use tab key to focus various Button.
5. Check focus highlight color. It is blue for Express theme. Instead, it should be purple.

**Comment by Westbrook** [comment]
There is no purple focus loupe.
