### ISSUE TITLE
[Bug]: Overlay Trigger has a delay to open

### ISSUE THREAD

**Issue by atakiyar** [adobe/spectrum-web-components#3484]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay-trigger, sp-popover

### Expected behavior

The pop-up should open as soon as the trigger is clicked.

### Actual behavior

The pop-up is opening with a slight delay.

**Comment by Westbrook** [comment]
First, we're currently testing a Release Candidate of a new version of this API, it would be great if you could test it out and share your thoughts: https://github.com/adobe/spectrum-web-components/discussions/2764#discussioncomment-6450198

Then, if you're still having an issue, please share an abstract reproduction with your experience so we could give you more appropriate steps to resolving the situation. These starter projects can sometimes be a useful place to extend from when looking to create that: https://studio.webcomponents.dev/workspace/adobe

**Comment by Westbrook** [comment]
With no additional repro steps, we're gonna close this for now. Please feel free to reopen or create a new issue with addition reproduction steps in the future.
