### ISSUE TITLE
[Bug]: white space at the bottom when an item is deleted from the bottom of sp-grid

### ISSUE THREAD

**Issue by kalyanrevuru** [adobe/spectrum-web-components#3498]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-grid

### Expected behavior

There should not be white space at the bottom when an item is deleted starting from last. The height should get adjusted accordingly

https://github.com/adobe/spectrum-web-components/assets/65059915/8dbcf93b-a777-4827-b8bf-d237a9a3bae9

https://github.com/adobe/spectrum-web-components/assets/65059915/48504553-be65-4004-916a-fdb428942794

### Actual behavior

There's white space at the bottom when an item is deleted starting from last.

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

1. Launch project-x stage in mobile browser
2. go to your stuff and scroll to bottom( keep enough projects like 10+ )
3. delete 2 projects ( if no.of projects is even ) else 1 
4. you'll see white space after the items got deleted
5. If you delete 2 projects to see the white space, after seeing the white space, delete one more project, the height get adjusted automatically which is expected to get adjusted at first.

**Comment by Rajdeepc** [comment]
@kalyanrevuru Please provide the project-x URL for triaging. Thanks

**Comment by kalyanrevuru** [comment]
@Rajdeepc https://stage.projectx.corp.adobe.com/

**Comment by TarunAdobe** [comment]
We are currently working on the fix for this with the appropriate team.

**Comment by TarunAdobe** [comment]
@kalyanrevuru update the @lit-labs/virtualizer to latest version(2.0.6) and this issue should go away. Let me know if this works on your end too or not

**Comment by kalyanrevuru** [comment]
Hi @TarunAdobe, I've updated to the latest version and tried. It didn't worked on my end.

https://github.com/adobe/spectrum-web-components/assets/65059915/367bbb7c-38e8-4418-90a8-c46ab622216d

**Comment by kalyanrevuru** [comment]
@TarunAdobe , I've updated the version and tried, it didn't worked. Since sp-grid internally uses virtualizer, the version should be upgraded on SWC side.

**Comment by TarunAdobe** [comment]
Hey @kalyanrevuru  I have created a repro fix that you can try out [here](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyJztcbmltcG9ydCB7IExpdFZpcnR1YWxpemVyIH0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL0xpdFZpcnR1YWxpemVyLmpzJztcbmltcG9ydCB7Z3JpZH0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL2xheW91dHMvZ3JpZC5qcyc7XG5cbmludGVyZmFjZSBJdGVtIGV4dGVuZHMgUmVjb3JkPHN0cmluZywgdW5rbm93bj4ge1xuICAgIGlkOiBudW1iZXI7XG59XG5cbmZ1bmN0aW9uIGdlbmVyYXRlSXRlbXMoY291bnQ6IG51bWJlcik6IEl0ZW1bXSB7XG4gICAgY29uc3QgaXRlbXM6IEl0ZW1bXSA9IFtdO1xuICAgIHdoaWxlIChjb3VudCkge1xuICAgICAgICBjb3VudCAtPSAxO1xuICAgICAgICBpdGVtcy51bnNoaWZ0KHsgaWQ6IGNvdW50IH0pO1xuICAgIH1cbiAgICByZXR1cm4gaXRlbXM7XG59XG5cbmNvbnN0IHJlbmRlckl0ZW0gPSAoKTogVGVtcGxhdGVSZXN1bHQgPT4ge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8ZGl2IHN0eWxlPVwiYm9yZGVyOiAycHggeWVsbG93IHNvbGlkOyBtYXJnaW46IDVweFwiPlxuICAgICAgICAgPGgzPmhlbGxvPC9oMz5cbiAgICAgICAgPC9kaXY-XG4gICAgYDtcbn07XG5cbkBjdXN0b21FbGVtZW50KCdzcC1ncmlkJylcbmV4cG9ydCBjbGFzcyBHcmlkIGV4dGVuZHMgTGl0VmlydHVhbGl6ZXIgeyBcbiAgXG4gIHByb3RlY3RlZCBvdmVycmlkZSB1cGRhdGUoY2hhbmdlczogYW55KTogdm9pZCB7XG4gICAgIGNvbnNvbGUubG9nKCdjaGFuZ2VzIGluIHRoZSB1cGRhdGUgRnVuY3Rpb246ICcsIGNoYW5nZXMpO1xuICAgICBzdXBlci51cGRhdGUoY2hhbmdlcyk7XG4gIH1cbiAgXG4gIHB1YmxpYyBvdmVycmlkZSByZW5kZXIoKTogYW55PDE-IHtcbiAgICAgICAgcmV0dXJuIGh0bWxgXG4gICAgICAgICAgICA8c2xvdD48L3Nsb3Q-XG4gICAgICAgIGBcbiAgIH07ICBcbn1cblxuY29uc3QgZ3JpZGQgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdzcC1ncmlkJykgYXMgR3JpZDtcbmxldCBpdGVtcyA9IGdlbmVyYXRlSXRlbXMoMTApO1xuZ3JpZGQuaXRlbXMgPSBpdGVtcztcbmdyaWRkLnJlbmRlckl0ZW0gPSByZW5kZXJJdGVtO1xuZ3JpZGQubGF5b3V0ID0gZ3JpZCgpO1xuXG52YXIgYnV0dG9uID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudChcImJ1dHRvblwiKTtcbmJ1dHRvbi5pbm5lckhUTUwgPSBcIkRlbGV0ZVwiO1xuLy8gYnV0dG9uLm9uQ2xpY2sgPSBoYW5kbGVDbGljaztcbmJ1dHRvbi5hZGRFdmVudExpc3RlbmVyIChcImNsaWNrXCIsIGZ1bmN0aW9uKCkge1xuICBpdGVtcyA9IGl0ZW1zLnNsaWNlKDAsIGl0ZW1zLmxlbmd0aC0xKTtcbiAgZ3JpZGQuaXRlbXMgPSBpdGVtcztcbn0pO1xuXG52YXIgYm9keSA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKFwiYm9keVwiKVswXTtcbmJvZHkuYXBwZW5kQ2hpbGQoYnV0dG9uKTtcblxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzcC1ncmlkIHN0eWxlPVwiYm9yZGVyOiAzcHggc29saWQgcmVkXCI-PC9zcC1ncmlkPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ). Also We'll be doing a release from SWC side soon to adopt this fix

**Comment by kalyanrevuru** [comment]
Thanks @TarunAdobe, I tried your code, it looks fixed 👍 . Waiting for SWC update.

**Comment by Westbrook** [comment]
fixed in #3578
