### ISSUE TITLE
[Bug]: NumberField does not reflect the correct value in the UI when value is a negative floating number and step is a floating number

### ISSUE THREAD

**Issue by ckrac** [adobe/spectrum-web-components#3508]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

The value passed to the [value](https://opensource.adobe.com/spectrum-web-components/components/number-field/api/#attributes%20and%20properties_value) property should be reflected in the UI without any rounding.

### Actual behavior

When the `value` is a negative floating number (eg. -2.4) and [step](https://opensource.adobe.com/spectrum-web-components/components/number-field/api/#attributes%20and%20properties_step) is set to a float number, the value in the UI is rounded.

### Screenshots

![Screen Shot 2023-08-03 at 12 52 50 PM](https://github.com/adobe/spectrum-web-components/assets/32920549/a397e26e-0a33-480e-b425-5ccd8c320ef1)

### What browsers are you seeing the problem in?

all browsers

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/number-field--default
2. Update the `step` property value to `0.001` under storybook controls
3. Update the `value` property value to `-2.4` or any negative floating number
4. The value shown in the UI is different than the actual `value` entered

**Comment by najikahalsema** [comment]
While JS does not have floating point numbers and has issues with precision, but usually not to this low of a decimal place. We should check to see how we're rounding these numbers, because the output seems like it's using the `ceil()` function.

**Comment by hunterloftis** [comment]
This section has a few places that may not account for negatives:

https://github.com/adobe/spectrum-web-components/blob/main/packages/number-field/src/NumberField.ts#L474-L491

`moduloStep` is built with JS's remainder operator, which isn't quite a modulo operator and has different behavior with negatives:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder#description

`overUnder` is only checking for positive `1`:
- https://github.com/adobe/spectrum-web-components/blob/main/packages/number-field/src/NumberField.ts#L480

I'd recommend writing a few tests to check different combinations of steps and values to make sure they all fall out appropriately.
