### ISSUE TITLE
[Bug]: Double-right click for context menu locks browser in infinite loop

### ISSUE THREAD

**Issue by senocular** [adobe/spectrum-web-components#3509]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Context Menu

### Expected behavior

Context menu appears

### Actual behavior

No context menu, browser locks up becoming unresponsive

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/menu-submenu--context-menu
2. Double right-click on the empty area of the screen (may need multiple attempts)

### Sample code that illustrates the problem

Whatever https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/menu-submenu--context-menu uses

**Comment by Westbrook** [comment]
Can you attempt to recreate this situation with https://overlay-mixins--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--context-menu?

**Comment by senocular** [comment]
@Westbrook I was unable to reproduce on https://overlay-mixins--spectrum-web-components.netlify.app/storybook/?path=/story/menu-submenu--context-menu

**Comment by Westbrook** [comment]
Seems to be corrected by #3456
