### ISSUE TITLE
[Bug]: Toast does not open in the correct position when used with overlay-trigger

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#3510]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

toast

### Expected behavior

`sp-toast` used in an overlay trigger should open in the correct position.

### Actual behavior

toast always appears centered on the trigger

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Create an `sp-toast` inside an overlay trigger with a specified placement.
2. Trigger the overlay

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/lzXQXJSMsytEpRIwIft3/src/index.ts?p=stories

**Comment by Westbrook** [comment]
Closed by https://github.com/adobe/spectrum-web-components/pull/3511
