### ISSUE TITLE
Migrate Meter Component to Core Tokens

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#3513]
## Acceptance Criteria

Meter components depends on progressbar component in Spectrum CSS
Currently progressbar is on 3.0.54 in SWC but in CSS it is being migrated to 3.0.57

1. Update Progressbar to its new version, do yarn install to update its newer version and see the changes in generated spectrum css file under src folder in SWC
2. Make sure if there are any properties added to the core token migration, if so talk to the CSS dev and understand the properties added in CSS
3. If new properties are added update the storybook to support those properties

## What needs to be built?

Update Meter component to new token system

## What effects it'll have?

Sizes S and L are includes M and XL are excluded in the new core token migration.
Needs to have a clear direction with the design team before this gets merged since this is inherited from the progress bar component.

**Comment by Rajdeepc** [comment]
We are keeping this ticket on hold since waiting for the css team to update on the decision to support sizes S, L only or we keep the size variants as it is.

**Comment by jnjosh** [comment]
Looks like we now have the CSS available using the actual meter token values. https://github.com/adobe/spectrum-css/commit/da88b3c4cd01c2b1069c4d1a9996c1148aadbd9e
