### ISSUE TITLE
[Bug]:  sp-grid size is not updating while delete items from grid

### ISSUE THREAD

**Issue by Vishesh-G** [adobe/spectrum-web-components#3519]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-grid

### Expected behavior

grid size should get updated to avoid extra white space

### Actual behavior

grid size is not changing

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/uuHG3QXoFpFImuCo0xUB/src/index.ts?p=stories

Click on items to delete them. Delete 2 items. Now you can see grid size is still same although items are now coming in 2 lines instead of 3

**Comment by Westbrook** [comment]
If this is materially different that #3498 please provide an abstract reproduction. If not, please close this issue as a duplicate.

**Comment by Vishesh-G** [comment]
Closing this issue, this is a duplicate bug
