### ISSUE TITLE
[Feat]: add `static` attribute support to Action Menu

### ISSUE THREAD

**Issue by l3vi-7** [adobe/spectrum-web-components#3530]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action Menu

### Description of the requested feature

Adding `static` attribute support to the Action Menu would allow the clients to use a fixed color (black or white) in the same way as `static` support in Action Buttons.

**Comment by Westbrook** [comment]
This should hopefully be just adding a `static` attribute/property (much like `quiet`) and binding it through tot he child `sp-action-button` (similar to `quiet`, but a value binding, not a boolean).
