### ISSUE TITLE
Fix tooltip hover issue on Action Menu

### ISSUE THREAD

**Issue by blunteshwar** [adobe/spectrum-web-components#3533]
## Acceptance Criteria:

There were two approaches discussed.
1. A coupled solution (Contributor can help): abstract the <slot name="tooltip> from the sp-button-menu or whatever is your parent element and keep it outside inside `<sp-overlay> like <sp-overlay triggerElement="#button@hover"><slot name="tooltip" style="display:contents"></sp-tooltip></sp-overlay>`
This will fix the issue for the Action Menu.

3. 2. Global fix - Update the Overlay V2 api tooltip to target the triggerElement to have `this.assignedSlot.parentElement` which will look for any slotted parentElement instead of a direct this.parentElement
You can create a branch from `overlay-mixins` branch and work on this fix.

## Issue
https://users-anishr-overlay-mixing--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--tooltip-description-and-placement

PR: https://github.com/adobe/spectrum-web-components/pull/3500

**Comment by blunteshwar** [comment]
[this](https://users-anishr-overlay-mixing--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--tooltip-description-and-placement)  PR  has many conflicts with the main. @Rajdeepc can you help me to replicate the issue

**Comment by blunteshwar** [comment]
@Westbrook the bug is not present in the latest version of main branch.
Please do let us know what needs to be done!

**Comment by Rajdeepc** [comment]
@jnjosh This bug can be closed as this is fixed in the new overlay API

**Comment by Westbrook** [comment]
Fixed by #3456
