### ISSUE TITLE
[Bug]: Slider's `*-handle-border-color-*` CSS variables are not taken into account

### ISSUE THREAD

**Issue by didnotwant** [adobe/spectrum-web-components#3536]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-slider, sp-handle

### Expected behavior

After setting:
```
  --spectrum-slider-handle-border-color-hover: red;
  --spectrum-slider-handle-border-color-down: red;
  --spectrum-slider-handle-border-color-key-focus: red;
```
I expect to see the handle's border colors changed accordingly to the settled values.

### Actual behavior

When setting:
```
  --spectrum-slider-handle-border-color-hover: red;
  --spectrum-slider-handle-border-color-down: red;
  --spectrum-slider-handle-border-color-key-focus: red;
```
the `style` attribute overrides the styles for the specific `.handle` class stylings and states, so the borders aren't red.

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Import theme and slider as described in docs:
```ts
import '@spectrum-web-components/theme/sp-theme.js';
import '@spectrum-web-components/theme/src/themes.js';
import '@spectrum-web-components/slider/sp-slider.js';
```
2. In the `LitElement`'s `render` method add:
```html
        <sp-theme
          scale="large"
          color="light"
        >
          <sp-slider
            variant="filled"
            label-visibility="none"
            ?disabled=${this.isPlaceholder}
            value=${this.initialAmount}
            min=${this.amountConstraints.min}
            max=${this.amountConstraints.max}
            step="100"
            @change=${this.onSliderChange}
            @input=${this.onSliderInput}
            @sp-slider-handle-ready=${this.onSliderHandleReady}
          ></sp-slider>
        </sp-theme>
```
3. In the CSS styles add:
```css
  --spectrum-slider-handle-border-color-hover: red;
  --spectrum-slider-handle-border-color-down: red;
  --spectrum-slider-handle-border-color-key-focus: red;
```
4. Go to the rendered component in your browser, inspect the handle element
5. Force e.g. the `:hover` state on the `.handle` element and see that the specific hover `border-color` styles are overriden by the `border-color` in the `style` attribute:
<img width="628" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/13979371/22419646-f466-4b90-b255-e11b87d50d9f">

**Comment by didnotwant** [comment]
I spotted the potential problematic line of code: https://github.com/adobe/spectrum-web-components/blob/v0.35.0/packages/slider/src/HandleController.ts#L502

Do you guys have some ideas on at least a work-around for this behaviour so I can live with it until the problem is resolved in this package?

**Comment by Rajdeepc** [comment]
@didnotwant According to the latest code we have added a check for background-color and border-color in the style object to only appear for multiHandle sliders.
```
const style = {
            [this.host.isLTR ? 'left' : 'right']: `${
                model.normalizedValue * 100
            }%`,
            right: 'auto',
            'z-index': zIndex.toString(),
            ...(isMultiHandle && {
                'background-color': `var(--spectrum-slider-handle-background-color-${index}, var(--spectrum-slider-handle-background-color))`,
                'border-color': `var(--spectrum-slider-handle-border-color-${index}, var(--spectrum-slider-handle-border-color))`,
            }),
        };
 ```
 
 So now you can overwrite your single `<sp-slider>` like this
 ```
     --mod-slider-handle-border-color-hover: red;
    --mod-slider-handle-border-color-down: red;
    --mod-slider-handle-border-color-key-focus: red;
 ```
<img width="993" alt="Screenshot 2023-12-12 at 11 50 22 AM" src="https://github.com/adobe/spectrum-web-components/assets/8790510/5dccf143-f9e3-475e-a043-e9b2c90fa257">
