### ISSUE TITLE
Ability to customize themes?

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/spectrum-web-components#3541]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

Is it possible to create custom, or customize existing themes with SWC?

An example would be changing the colors, such as the blue primary color to red. 

Ideally i'm interested if this can happen outside the build process, and by including a ancillary set of CSS/JS that adds/overrides specific vars.

**Comment by najikahalsema** [comment]
The Spectrum CSS is currently having conversations about how to support Express and potential other themes right now, but in the meantime, there are the `--mod` variables that you can use to override certain CSS vars as you like. @pfulton or @jnjosh can provide updates and documentation for how to use these variables.
