### ISSUE TITLE
[Bug]: New Overlay.open cause Illegal constructor at lit/reactive-element/development/reactive-element.js:102:5

### ISSUE THREAD

**Issue by jianliao** [adobe/spectrum-web-components#3563]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

@spectrum-web-components/overlay

### Expected behavior

[Overlay.open](https://opensource.adobe.com/spectrum-web-components/components/overlay/) api should work. Here is the function signature of `open`:
```
Overlay.open(
    (owner: HTMLElement), // the element to open the overlay in reference to, "trigger"
    (interaction: TriggerInteractions), // the type of interaction type that opened the overlay
    (overlayElement: HTMLElement), // the element that will be projected into the overlay, "content"
    (options: OverlayOptions) // options to customize the overlay
);
```

### Actual behavior

```
TypeError
Illegal constructor
    at new ReactiveElement (https://nccx6g.csb.app/node_modules/
lit/reactive-element/development/reactive-element.js:102:5
new LitElement
https://nccx6g.csb.app/node_modules/lit-element/development/lit-element.js:27:5
    at new AbstractOverlay (https://nccx6g.csb.app/node_modules/
spectrum-web-components/overlay/src/AbstractOverlay.dev.js:101:5
    at new _Overlay (https://nccx6g.csb.app/node_modules/
spectrum-web-components/overlay/src/Overlay.dev.js:47:5
    at _Overlay.open (https://nccx6g.csb.app/node_modules/
spectrum-web-components/overlay/src/AbstractOverlay.dev.js:152:21
handleButtonClick
/src/App.tsx:10:18
   7 | const handleButtonClick = async () => {
   8 |   const overlayTriggerElement = document.getElementById("overlay-trigger");
   9 |   const overlayContentElement = document.getElementById("popover-content");
> 10 |   await Overlay.open(
     |                ^
  11 |     overlayTriggerElement!,
  12 |     "click",
  13 |     overlayContentElement!,

HTMLUnknownElement.callCallback
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4164:14
Object.invokeGuardedCallbackDev
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4213:16
invokeGuardedCallback
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4277:31
invokeGuardedCallbackAndCatchFirstError
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4291:25
executeDispatch
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9041:3
processDispatchQueueItemsInOrder
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9073:7
processDispatchQueue
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9086:5
dispatchEventsForPlugins
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9097:3
eval
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9288:12
batchedUpdates$1
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26140:12
batchedUpdates
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3991:12
dispatchEventForPluginEventSystem
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:9287:3
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6465:5
dispatchEvent
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6457:5
dispatchDiscreteEvent
https://nccx6g.csb.app/node_modules/react-dom/cjs/react-dom.development.js:6430:5
```

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Open this sandbox - https://codesandbox.io/s/overlay-open-api-nccx6g
2. Click `Hello CodeSandbox` button
3. Observe the screen or browser console

**Comment by jianliao** [comment]
Hi @Westbrook,

I've managed to reproduce this issue in a project that uses the @swc-react wrapper. However, I'm finding it challenging to pinpoint how the error relates to the React wrapper and react.js itself. From my perspective, it seems more like an issue with lit-element and JavaScript.

**Comment by jianliao** [comment]
I found this https://jonas.arnklint.com/illegal-constructor-web-component-custom-element

```
The Illegal constructor error is thrown when a class extends HTMLElement, but is instantiated like a regular class.
```

If it is correct, then the issue maybe cause by https://github.com/adobe/spectrum-web-components/blob/d771f62f0d8063070af43283bb0fd5e3400bad06/packages/overlay/src/AbstractOverlay.ts#L224

**Comment by Westbrook** [comment]
I'm thinking it's a question of how the code is transpiled to lower level JS. Particularly in that it doesn't not occur in https://studio.webcomponents.dev/edit/bu0sOBIfyW7wnHkXtGzL/src/index.stories.js?branch=imperative-api%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories 🤔 

There's lots of room to alter the structure of the code, but if it's going to be side effects from the build context then we'd need to reproduction context that was portable and could easily consume dev time code for us to confirm that it's fixed.

Would you be able to abstract this Codesandbox link into a repo for us to better test against?

**Comment by jianliao** [comment]
Here is the extracted [repo](https://github.com/jianliao/swc-overlay-bug). This issue does not exist on Overlay RC release - `swc@0.34.1-rc.0`.

**Comment by jnjosh** [comment]
While this doesn't specifically solve the problem, I did notice that using a different construction of the Overlay does work in your repo project.

<img width="922" alt="Screenshot 2023-09-01 at 10 36 00 AM" src="https://github.com/adobe/spectrum-web-components/assets/66142/8655ffc6-7ff4-4599-aa94-b6a64441a6b8">

**Comment by jianliao** [comment]
Hi @Westbrook,

I've been investigating the issue with Overlay.open and believe I've found the root cause. The Overlay is a custom element class that extends HTMLElement. In order to successfully create an instance of it using the new operator, it seems that I need to define the custom element first.

I added the following line of code before calling Overlay.open(...), and everything started working as expected:

```
!customElements.get("sp-overlay") && customElements.define("sp-overlay", Overlay);
```

**Comment by jianliao** [comment]
> I found this https://jonas.arnklint.com/illegal-constructor-web-component-custom-element
> The Illegal constructor error is thrown when a class extends HTMLElement, but is instantiated like a regular class.

It appears the information is outdated. In modern implementations, as long as the custom element has been defined using customElements.define(), it can be instantiated using the new operator just like any other class. I've tested this successfully, so it seems that defining the custom element first is key to resolving the issue.

**Comment by jianliao** [comment]
Hi @Westbrook,

While digging further into the Overlay.open() issue, I realized that in my implementation, I never declaratively use the <sp-overlay> element in my codebase. It got me thinking—perhaps we could streamline this process for users like myself.

Would it make sense to incorporate the `...customElements.define("sp-overlay", Overlay);` line within the Overlay.open() function itself? This would alleviate the need for consumers of the library to add what might be considered an unconventional line of code just to make things work.

If this is a change you'd consider beneficial, I'd be more than happy to contribute a PR to implement it.

Let me know your thoughts!
