### ISSUE TITLE
[Bug]: sp-dialog-wrapper doesn't scroll content after large hero image has been loaded

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3613]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-dialog-wrapper

### Expected behavior

When user has a small screen normally rendering large content in a sp-dialog-wrapper will lead to css property `overflow: auto;` in content class and will show scrollbars to user as dialog height is limited.
User would expect to also have scrollbars of a large hero image is loaded (or replaced) after dialog has been opened to show scrollbars in content section.

### Actual behavior

Replacing hero image with higher version or loading larger images after the dialog has been open doesn't lead to `overscroll: auto;" css and therefore no scrollbar is shown. (Text)content will be truncated and there is no was to scroll down to see the rest of it.
Resizing the window resolves it as it re-triggers overflow-detection.

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/SR85ol2A1eUP0MbsdWq1/src/index.ts?p=stories
2. Shrink browser window to appr. 1000px height
3. Click on "Toggle button"
4. See hero image loaded after dialog is open
5. See that there is no scrollbar to fully see content

**Comment by Westbrook** [comment]
The scroll area here measures itself on content change and window resize, sounds like it need to do so via a Resize Observer instead...
