### ISSUE TITLE
[Bug]: Default Tooltip offset should be 4

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3631]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tooltip

### Expected behavior

Default offset should be 4 or 5 (mobile) regarding to Spectrum doc: https://spectrum.adobe.com/page/tooltip/#Offset

### Actual behavior

default offset is "0"

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
Related: https://github.com/adobe/spectrum-css/issues/2156
