### ISSUE TITLE
Coach-Indicator DIY Migration

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#3634]
Spectrum CSS PR: https://github.com/adobe/spectrum-css/pull/1992
PR includes Migration of CoachMark, moving Coach Indicator into its own component, and the DIY migration of coach indicator.

**Comment by Rajdeepc** [comment]
spectrum-css team will add the ` --spectrum-coachmark-animation-indicator-ring-duration` out from coach-indicator/index.css to  custom tokens.

**Comment by Rajdeepc** [comment]
Awaiting an alpha release of `"@spectrum-css/coachindicator"`
https://github.com/adobe/spectrum-css/pull/2174

**Comment by Westbrook** [comment]
Closing in favor of #3666
