### ISSUE TITLE
[Bug]: Color Area showing incorrect values

### ISSUE THREAD

**Issue by bmandal2** [adobe/spectrum-web-components#3652]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Venus

### Expected behavior

The color change should be linear. Changing the 'v' component should move the color-area uniformly and consistently on the y axis.

### Actual behavior

with the hsv values (0, 0, 1) it goes to top left corner, then on (0, 0, 2) it comes to bottom left

### How can we reproduce this issue?

1. Go to '...' https://studio.webcomponents.dev/edit/ggcvbXkuFiEnLte4wGEp/src/index.ts?p=stories
3. Scroll to '....'
4. Check console
5. See error

**Comment by najikahalsema** [comment]
We are looking at a larger refactor of how we process colour, and this should be addressed through that PR.

**Comment by Westbrook** [comment]
This [comment](https://github.com/adobe/spectrum-web-components/issues/3652#issuecomment-1725863510) seems to address the issue at hand here. https://studio.webcomponents.dev/edit/3cvQ2OVieORjHUSuKHma/src/index.stories.js?p=stories

There is a looming refactor that may more support a broader number of values here, but in the interim, you should be good to go here.
