### ISSUE TITLE
[Feat]: Adding a flag based handling to hide close Icon and selection count in Action bar

### ISSUE THREAD

**Issue by TrojanRocks** [adobe/spectrum-web-components#3671]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action Bar

### Description of the requested feature

Action Bar component right now have close icon and selection count present always, adding a flag based handling to hide the same

### Mockups or screenshots

<img width="196" alt="Screenshot 2023-09-22 at 7 24 51 AM" src="https://github.com/adobe/spectrum-web-components/assets/8644325/beb53428-fb2c-4bfc-89de-e599e87b3a41">

**Comment by Westbrook** [comment]
You can get that like [this](https://studio.webcomponents.dev/edit/omhKPPsfFwPuzf4Lz1Bt/src/index.ts?branch=no-trigger%40wfVpXdsTYhf9mY2slxW4t2Y2SjC3&p=stories).
