### ISSUE TITLE
[Bug]: Keyboard up and down arrow keys are not working on action menu when menugroup is used

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#3686]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

action-menu

### Expected behavior

Arrow keys should work with action menu

### Actual behavior

Unable to navigate the menu with arrow keys

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/YAUfYesctBh2z2QCbNYD/src/index.ts?p=stories

**Comment by najikahalsema** [comment]
What are you referring to when you say "menugroup"?

**Comment by venkateshjo** [comment]
Not working case

<sp-action-menu>
    <sp-menu-group>
        <span slot="header">New York</span>
        <sp-menu-item>
            Central Park
        </sp-menu-item>
      <sp-menu-item>
           Golden Gate Park
      </sp-menu-item>
    </sp-menu-group>
    </sp-action-menu>

repro link: https://studio.webcomponents.dev/edit/YAUfYesctBh2z2QCbNYD/src/index.ts?p=stories
