### ISSUE TITLE
[Bug]: Cannot write to clipboard in Safari from change event of sp-action-menu

### ISSUE THREAD

**Issue by rickharris** [adobe/spectrum-web-components#3687]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Expected behavior

I would like to be able to call `navigator.clipboard.writeText` from inside the `change` event of `sp-action-menu`. Safari only allows this function to be called as the result of a user interaction. Since this is the result of a user interaction it seems like this should work, and I would expect to be able to call `navigator.clipboard.writeText` successfully without an error.

It's not completely surprising or unexpected that this wouldn't work, but what's interesting to me is that it does work in react-spectrum's ActionMenu `onAction` callback, so I'm curious if it could be supported here.

### Actual behavior

When calling `navigator.clipboard.writeText` from the change event in Safari it results in an error:

> NotAllowedError
> The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://codesandbox.io/s/solitary-worker-6f26cf?file=/src/App.js
2. Click on the action menu trigger under the heading "react-spectrum ActionMenu"
3. Observe that the string "rsCopy" is now in your clipboard
4. Click on the action menu trigger under the heading "SWC sp-action-menu"
5. Observe the `NotAllowedError` and "rsCopy" is still in your clipboard when it should be "spCopy"

### Sample code that illustrates the problem

https://codesandbox.io/s/solitary-worker-6f26cf?file=/src/App.js

**Comment by Westbrook** [comment]
@rickharris our current unit testing config allows us to test this everywhere but in Safari... 😬 can you lend a hand and confirm that the selections in [this demo](https://direct-change--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--label-only) are copied appropriately to the Clipboard in that context? I've manually confirmed in Safari 17 for macOS 13.6, but want to make sure this is doing the right thing in the context you encountered this initially.

If it looks good to you, we'll get a PR together and have this in the next release.

**Comment by jeffgint** [comment]
+ @Rick ***@***.***>  in case he’s not on  the DL

From: Westbrook Johnson ***@***.***>
Date: Sunday, October 1, 2023 at 6:16 PM
To: adobe/spectrum-web-components ***@***.***>
Cc: Jeff Guentert ***@***.***>, Manual ***@***.***>
Subject: Re: [adobe/spectrum-web-components] [Bug]: Cannot write to clipboard in Safari from change event of sp-action-menu (Issue #3687)

EXTERNAL: Use caution when clicking on links or opening attachments.



@rickharris<https://github.com/rickharris> our current unit testing config allows us to test this everywhere but in Safari... 😬 can you lend a hand and confirm that the selections in this demo<https://direct-change--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--label-only> are copied appropriately to the Clipboard in that context? I've manually confirmed in Safari 17 for macOS 13.6, but want to make sure this is doing the right thing in the context you encountered this initially.

If it looks good to you, we'll get a PR together and have this in the next release.

**Comment by rickharris** [comment]
@Westbrook yep that demo is working how I'd hoped in Safari. Thanks!

**Comment by rick** [comment]
![blingz](https://github.com/adobe/spectrum-web-components/assets/6259/be77db8c-7a4d-4703-9b00-ca8296f42b94)
