### ISSUE TITLE
[Bug]: Manual overlay dismisses like auto overlay

### ISSUE THREAD

**Issue by timsnadden** [adobe/spectrum-web-components#3702]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Expected behavior

As per the [docs](https://opensource.adobe.com/spectrum-web-components/components/imperative-api/#type) "'manual' Overlays act much like "auto" Overlays, but do not close when losing focus or interacting with other parts of the page"

### Actual behavior

An overlay with `type="manual"` is closed when interacting with other parts of the page. The attribute `popover="manual"` is added but there is some code in [OverlayStack](https://github.com/adobe/spectrum-web-components/blob/main/packages/overlay/src/OverlayStack.ts#L59-L82) that closes the open overlay.

### Screenshots

https://www.loom.com/share/87ac4011b05041568b8c23b949503d46

### What browsers are you seeing the problem in?

All

### How can we reproduce this issue?

1. Create a 'manual' Overlay (`<sp-overlay type="manual">`)
2. Open the Overlay 
3. Click elsewhere in the document
4. Note that the overlay is closed automatically when the expectation is that it remains open until explicitly closed

### Sample code that illustrates the problem

https://codepen.io/karbonhq/pen/XWoxqBm

**Comment by Westbrook** [comment]
That does seem like a thing that happens 🙈

Quick note to triaging, the demo linked above places `type="manual"` on the wrong element, see https://codepen.io/Westbrook/pen/yLGRERg for usage on `<sp-overlay>` not `<sp-popover>`.

Also, naming 😓 ...
