### ISSUE TITLE
[Bug]:  Number Field Min not respected

### ISSUE THREAD

**Issue by SidIcarus** [adobe/spectrum-web-components#3719]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

number field

### Expected behavior

option `min` should prevent value from going below it

### Actual behavior

when `max` is not set and `step` is set, `min` is not respected

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to [example step values](https://opensource.adobe.com/spectrum-web-components/components/number-field/#step-values)
2. Click on the middle example that only has the `min` set to `2`.
3. Approach the value `2` via decrement button clicking - see that it does disable the button
4. click again, see that it goes past the `min` and button is no longer disabled

if you decrement via input scrolling, it will just zoom right past it.
This error does not occur when you also have the `max` set. You can see this via the example right below it.

### Sample code that illustrates the problem

Copy pasted from [here](https://opensource.adobe.com/spectrum-web-components/components/number-field/#step-values)

```javascript
<sp-field-label for="step-min">Step + min</sp-field-label>
<sp-number-field id="step-min" min="2" step="3"></sp-number-field>
```

**Comment by Westbrook** [comment]
I'm having trouble reproducing the situation you've outlined in the documentation site. Could you provide more precise reproduction steps?

**Comment by ebshimizu** [comment]
I accidentally opened a new issue for this same problem. See #3791 for another report, using MS Edge. I was able to reproduce this by just clicking the decrement button past the minimum value with the default values on the documentation site.

**Comment by Westbrook** [comment]
Closing in favor of #3827 which has more precise repro conditions.
