### ISSUE TITLE
(Coachmark): Test performance of anonymous render functions within `when` directive

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-web-components#3723]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

(To be done once the initial component is merged to main)

The `when` [directive](https://lit.dev/docs/templates/directives/#when) takes anonymous functions as arguments. The question is whether there's a performance difference between using anonymous methods as arguments or initialising these render methods as anonymous. We should experiment with the two and test the performance of each to see if there's any noticeable difference. 

For example,

Wrapping these render methods in an anonymous function within the parameters of `when`
```
  method1() {
    return html`
      ${this.name} is my name too   
    `;
  }

// ....

  render() {
    return html`
      ${when(this.name, () => this.method1(), () => this.method2())}
    `;
    }  
```

vs using an anonymous function from the get-go: 

```
  method1 = () => {
    return html`
      ${this.name} is my name too   
    `;
  }

// ... 

  render() {
    return html`
      ${when(this.name, this.method1, this.method2)}
    `;
    }  
```

**Comment by Rajdeepc** [comment]
@najikahalsema  While there is not a significant amount of time difference between the two usage of function expressions, anonymous function takes a little bit more time than regular function declaration.

Tested using the `console.time()` and `console.timeEnd()` methods

```
  method1() {
    return html`
      ${this.name} is my name too   
    `;
  }

// ....

  render() {
    return html`
      ${when(this.name, () => this.method1(), () => this.method2())}
    `;
    }  
```

Performance with `console.time`

![Image](https://github.com/adobe/spectrum-web-components/assets/8790510/191eb5b5-1e75-4cf3-a21e-fc6207bbb645)

using an anonymous function from the get-go:

```
  method1 = () => {
    return html`
      ${this.name} is my name too   
    `;
  }

// ... 

  render() {
    return html`
      ${when(this.name, this.method1, this.method2)}
    `;
    }  
```



![Image](https://github.com/adobe/spectrum-web-components/assets/8790510/342d1b90-81cb-49e7-a226-0de2fa2a865d)

**Comment by najikahalsema** [comment]
Interesting. thank you so much for taking a look! I think the second one is better based on it's nearly half the amount of time needed to render.

**Comment by Rajdeepc** [comment]
Cool Thanks! Feel free to close this issue once Coachmark is merged.
Tagging the PR here: #3639
