### ISSUE TITLE
[Bug]:Scrolling sp-grid fastely, the screen get blank for some moment 

### ISSUE THREAD

**Issue by kumarhimanshu5128409** [adobe/spectrum-web-components#3734]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-grid

### Expected behavior

The screen should either slow down or stop scrolling, if it's not ready, rather than being blank for the moment.

### Actual behavior

Screen is getting blank if its not ready by virtualizer. And after moments virtualizer seems to fill it.

### Screenshots

<img width="300" alt="Screenshot 2023-10-20 at 16 40 46" src="https://github.com/adobe/spectrum-web-components/assets/25195086/a1ffa549-2ccf-4c6b-9cff-8fdf6b33511a">

<img width="300" alt="Screenshot 2023-10-20 at 16 41 04" src="https://github.com/adobe/spectrum-web-components/assets/25195086/dc50fc0a-67a0-4062-9f44-468591efa6c1">

![sp-grid-getting-blinked-for-moment](https://github.com/adobe/spectrum-web-components/assets/25195086/50845103-101e-4e12-9edc-d36a2a3f92cd)

### How can we reproduce this issue?

1. Go to StoryBook.
2. Click on Sp-grid->default
3. Scroll the cards fastly
4. You may observe blank spaces, sometimes.

**Comment by Westbrook** [comment]
This works in accordance with the upstream dependency that we leverage for [virtualization](https://github.com/lit/lit/tree/main/packages/labs/virtualizer) and you're welcome to work with their team for alternative approaches here, but we will not be making alteration to how their tools work in the foreseeable future.
