### ISSUE TITLE
Establish deprecation process

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#3749]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

When patterns are deprecated by Spectrum design, or Spectrum CSS, what is our process for deprecating them from the library?

Outline and enact a process to announce, deprecate, and remove patterns. See:
- [x] Banner
- [x] Quick Actions
- [ ] etc.

**Comment by Rajdeepc** [comment]
Deprecation process has been streamlined in SWC with Banner, Quick Actions and Split-Button being deprecated already. Please let us know what else needs to be added to this ticket for closure!

**Comment by Rajdeepc** [comment]
RFC: https://paper.dropbox.com/doc/RFC-Spectrum-Web-Components-Deprecation-Strategy--CLz6oOt2laW2x~7i1oeicLw9Ag-zwmZHp3pBSCngsrZYp1kP
