### ISSUE TITLE
[Bug]: sp-number-field value doesn't update on ArrowDown/ArrowUp keydowns or on scroll

### ISSUE THREAD

**Issue by mizgaionutalexandru** [adobe/spectrum-web-components#3753]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

When focusing the input field and tapping the ArrowUp/ ArrowDown buttons, the component should display the updated/current value.

### Actual behavior

When focusing the input field and tapping the ArrowUp/ ArrowDown buttons, the component's display value does not change. It updates only when blur happens - clicking outside the component.

### Screenshots

In the first part of the video you can see what currently happens while I'm scrolling with focus on number field, while the last part shows what happens when tapping the ArrowUp/ArrowDown keys.

https://github.com/adobe/spectrum-web-components/assets/67201262/70b1cf9c-3a02-49be-a10f-6c65867aa97d

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Go to [SWC Storybook](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/number-field-sizes--s)
2. Click on the number field to focus it
3. Tap the ArrowUp/ArrowDown key 
4. See that the value doesn't update
5. Click outside the component
6. See that value updates

**Comment by Westbrook** [comment]
Fixed by  #3754
