### ISSUE TITLE
Recent PR broke docs on Edge

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#376]
### Expected Behaviour

Documentation site should load in Edge

### Actual Behaviour

Documentation site throws a console error about `customElement` being missing

#### Steps to Reproduce

Go to https://opensource.adobe.com/spectrum-web-components/ in Edge

#### Platform and Version

Edge (pre-chromium)

**Comment by cuberoot** [comment]
This break was caused by ditching the polyfill in this PR: https://opensource.adobe.com/spectrum-web-components/

Looks like we need to update our OpenWC webpack config.

**Comment by Westbrook** [comment]
That’s likely due to me merging PRs out of “order”. All of the Open WC dependencies are updated in #315, so when that clears it should clean this up as well!

**Comment by cuberoot** [comment]
Ah cool. I approved #315.

**Comment by Westbrook** [comment]
Seems I was wrong about this... 😞 It's possible that we need to roll back the removal I made. @cuberoot do you see anything we're _not_ doing as far as the `webpack.config` that would prevent us from adopting the new OpenWC approach here?

**Comment by cuberoot** [comment]
@Westbrook [These Open-WC docs](https://github.com/open-wc/open-wc/tree/master/packages/building-webpack#config-features) don't make sense to me.

It says that the modern config supports Edge, but then only says that the webcomponentsjs polyfills are included in the legacy build. Seems like they are anticipating Edgium?

**Comment by cuberoot** [comment]
@Westbrook [This fix sort of helps](https://github.com/adobe/spectrum-web-components/compare/cuberoot/edge-polyfill?expand=1). It at least gets the web components rendering. However, the themes don't seem to work. It doesn't look like the CSS custom properties are working.

**Comment by cuberoot** [comment]
Actually, I think the above fix does work. I just hadn't done a full build of the docs.

**Comment by cuberoot** [comment]
Seems to be working now.
