### ISSUE TITLE
[Bug]: DragImage of draggable content with overlaid tooltip shows whole page

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3761]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay, Tooltip

### Expected behavior

When a draggable item contains an sp-overlay (for example sp-tooltip self-managed) then dragging that content should only show that element via `DataTransfer: setDragImage()`

### Actual behavior

If the draggable item contains any sp-overlay it shows the complete page (any previous rendered DOM Elements).

### What browsers are you seeing the problem in?

Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/AErDGkwGZNfUz6fHcQxb/src/index.ts?p=stories
2. Make sure, tooltips are enabled
3. Drag the div element with red border
4. Notice that the DragImage includes the simple button, why it should only show the div (with id='draggableElement')
5. Disable tooltips
6. Drag again, now DragImage renders correctly

**Comment by Westbrook** [comment]
Seems to be based on the way that the Overlaid content is "on the page" but positioned to the extreme top/left. This "extends" the drag element to include the rest of (or almost all of) the page.

Current research into #3596  and #3367 both use `display: none` for not content that does not display visibly, which seems to address this.
