### ISSUE TITLE
[Bug]: Overlay is positioned incorrectly when re-opening after VirtualTrigger position has been adjusted away from window edges

### ISSUE THREAD

**Issue by estollnitz** [adobe/spectrum-web-components#3762]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Expected behavior

When an overlay is opened with a VirtualTrigger, I expect it to be positioned adjacent to the trigger coordinates.

### Actual behavior

After opening once near the edge of the window (so the overlay position is adjusted to fit within the window), the next time the overlay is opened with a VirtualTrigger:

- In Chrome 118.0.5993.88 and Edge 118.0.2088.76, the overlay appears in the old position instead of near the new trigger position.
- In Firefox 119.0, the overlay's height is too big for the content (if it was previously positioned at the bottom of the window).
- In Safari 16.4 (18615.1.26.110.1), everything works fine!

### What browsers are you seeing the problem in?

Firefox, Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Visit simple repro at https://studio.webcomponents.dev/edit/s334t4CsQLZSNCiGFOPE/src/index.ts?p=stories.
2. Right-click near the bottom or right edge of this window to open the context menu.
3. Left-click anywhere else to close the context menu.
4. Right-click again to open the context menu.

Result: The context menu appears again in the same place as in step 1.

Expect: The context menu should appear near the pointer.

### Sample code that illustrates the problem

https://studio.webcomponents.dev/edit/s334t4CsQLZSNCiGFOPE/src/index.ts?p=stories

**Comment by Westbrook** [comment]
We likely should add better management for _changing_ the trigger object over time, you can achieve what you're targeting here by leveraging the rather poorly documented ([see tracking issue for docs](https://github.com/adobe/spectrum-web-components/issues/2657)) `updateBoundingClientRect(x, y)` method on the Virtual Trigger and using a single virtual trigger over the entire lifetime on your experience. [Demo](https://studio.webcomponents.dev/edit/4V8bCcpmaB42mN6DAXhY/src/context-menu.ts?p=stories).

If you have a quality use case for changing the actual object overtime, please feel free to open a new issue with that information so we can prioritize that work as needed.

**Comment by estollnitz** [comment]
Thanks, @Westbrook! That solved the problem for us.
