### ISSUE TITLE
Update lit to v3

### ISSUE THREAD

**Issue by damooo** [adobe/spectrum-web-components#3773]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

All

### Description of the requested feature

Lit is updated to v3. There are not many breaking changes. It will be great if swc update the dependency too. Otherwise bundler seems including both versions, and types are incompatible when used along with new lit versions, and other ecosystem components.

**Comment by Westbrook** [comment]
We are tracking this in #3209, but it will likely still be a little while yet before we are able to release fully `lit@3.0` versions of the library. Depending on install order and package manager configurations, there _should_ be no issue in using our components in a `lit@3.0` application. You _will_ need to have both versions in your build, but in terms of client side libraries is quite a small price to pay. I can say that you _won't_ be able to force the next version (via `resolutions` or `overrides`) without issue today, but maybe there's an interim step that we could do to unlock that in the time being.

**Comment by damooo** [comment]
> I can say that you won't be able to force the next version (via resolutions or overrides) without issue today, but maybe there's an interim step that we could do to unlock that in the time being.

As update being already working upon, it is not an issue to include both versions now, and also no particular other reason to override. swc seems re-exporting lit functionalities.  I would be importing them, as we are anyway using `SpectrumElement` as baseclass.

**Comment by Westbrook** [comment]
It shouldn't be an issue to include both versions.

In face, if you're always importing through SWC then you'll always get v2, which means you wouldn't really be using two versions!
