### ISSUE TITLE
[Bug]: Overlay - triggerElement might be null in doPointerleave

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3795]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay

### Expected behavior

No error should be thrown when pointer leaves trigger element

### Actual behavior

Sometimes it happens, that the triggerElement is null, when function `doPointerleave` is called, leading to an exception when trying to exec 
```
if (this.focusedin && triggerElement.matches(":focus-visible"))
      return;
```
It happens with triggers for both tooltip and overlay in some (more complex) use cases.
It might be fixable by using conditional operator in `triggerElement?.matches(":focus-visible")` 

Exception thrown:
```
TypeError: Cannot read properties of null (reading 'matches')
    at _Overlay2.doPointerleave (Overlay.ts:851:46)
    at Button.handlePointerleave (Overlay.ts:841:14)
    ...
 ```

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
Do you have any context as to why this might be? For `doPointerLeave` to be called you, at least in theory, need a `triggerElement` from which to have left in to begin with. Putting a presence gate on this seems more like addressing a symptom than a cause...

**Comment by Westbrook** [comment]
@spdev3000 any other insight into how you were encountering this?

**Comment by spdev3000** [comment]
It can be reproduced here: https://studio.webcomponents.dev/edit/7KjoJgLNZWuoRqHdKKua/src/index.ts
try clicking the button and when the popover opens, move the pointer out of the button.
