### ISSUE TITLE
[Bug]: Outline offset is presumably incorrect

### ISSUE THREAD

**Issue by SavoInfostream** [adobe/spectrum-web-components#3821]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Textfield, Search

### Expected behavior

Outline to be covering the border line.

### Actual behavior

Outline is offset from the border line.

### Screenshots

Quiet:
![outline 1](https://github.com/adobe/spectrum-web-components/assets/60256229/fd3894cd-a707-4bd0-8f78-04bf1482b18c)

Standard:
![outline2](https://github.com/adobe/spectrum-web-components/assets/60256229/7021034e-9ab7-4446-bc23-6007c967e903)

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Westbrook** [comment]
This works as expected to deliver an accessible interface that is normalized to others in the library, like Button, et al:

<img width="108" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/1156657/aa905c58-87c5-48a7-aa01-981b8c92ea5f">

**Comment by SavoInfostream** [comment]
Thanks for the info. Personally, I will remove the offset.
