### ISSUE TITLE
[Bug]: Overlay Trigger creates an infinite callback loop in Angular (after migrating 0.29.0 -> 0.40.0)

### ISSUE THREAD

**Issue by SavoInfostream** [adobe/spectrum-web-components#3826]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Overlay Trigger

### Expected behavior

For Angular (v15) app to work like it did int v0.29

### Actual behavior

Total freeze of the page.

### Screenshots
![304d0f6f-2306-4c74-9dc8-279acfaadf66](https://github.com/adobe/spectrum-web-components/assets/60256229/47ea6ff8-fd8f-4319-a957-19d0238cda1c)

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Create a new Angular project
2. Add `"@spectrum-web-components/bundle": "0.40.0"` to package.json, and run `npm install`
3. Add `schemas: [CUSTOM_ELEMENTS_SCHEMA],` to app.component.ts declaration
4. Add `
      			<overlay-trigger type="modal">
      				<sp-button slot="trigger" variant="secondary">Toggle menu</sp-button>
      				<sp-tray slot="click-content">
      					<sp-menu style="width: 100%">
      						<sp-menu-item selected>Deselect</sp-menu-item>
      						<sp-menu-item>Select Inverse</sp-menu-item>
      						<sp-menu-item focused>Feather...</sp-menu-item>
      						<sp-menu-item>Select and Mask...</sp-menu-item>
      						<sp-menu-divider></sp-menu-divider>
      						<sp-menu-item>Save Selection</sp-menu-item>
      						<sp-menu-item disabled>Make Work Path</sp-menu-item>
      					</sp-menu>
      				</sp-tray>
      			</overlay-trigger>
`
to component template.
6. Run `npm start` in root directory to start the app.
7. Try to open the page.

### Sample code that illustrates the problem
Angular project:
[untitled.zip](https://github.com/adobe/spectrum-web-components/files/13458971/untitled.zip)

### Logs taken while reproducing problem
[logs.txt](https://github.com/adobe/spectrum-web-components/files/13459204/logs.txt)

**Comment by Westbrook** [comment]
Not sure the timing on spending more focused effort on this, but you might try the following DOM instead:

```
<sp-button id="trigger" variant="secondary">Toggle menu</sp-button>
              <sp-overlay trigger="trigger@click">
                <sp-tray>
                  <sp-menu style="width: 100%">
                    <sp-menu-item selected>Deselect</sp-menu-item>
                    <sp-menu-item>Select Inverse</sp-menu-item>
                    <sp-menu-item focused>Feather...</sp-menu-item>
                    <sp-menu-item>Select and Mask...</sp-menu-item>
                    <sp-menu-divider></sp-menu-divider>
                    <sp-menu-item>Save Selection</sp-menu-item>
                    <sp-menu-item disabled>Make Work Path</sp-menu-item>
                  </sp-menu>
                </sp-tray>
              </sp-overlay>
```

**Comment by SavoInfostream** [comment]
That code works. Thanks :)

**Comment by SavoInfostream** [comment]
Also, there's flickering on animation of the overlay (did two takes in the screenshot because recording fps wasn't big enugh to catch it every time):
![Recording 2023-11-28 103613](https://github.com/adobe/spectrum-web-components/assets/60256229/a2f4f470-c94f-4c79-8646-e28446cd34c6)

**Comment by najikahalsema** [comment]
original issue fixed. Overlay flickering needs a separate issue.
