### ISSUE TITLE
[Bug]: Number Field min-max limits not correctly working

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3827]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Number Field

### Expected behavior

When using Number fields with limit (min/max) it should act like:
- using keyboard arrow keys to modify values should stop at limit
- using mouse wheel to modify values it should stop at limit
- using stepper buttons to modify values it should stop at limit

### Actual behavior

Following wrong behavior can be experienced:
1. Defining a max value:
- if using a max value and click into Number Field a user can successfully step up (using `cursor up` key or mouse wheel) to `max + 1` value as display value, it will be corrected, once it looses the focus
- if using a max value and click into Number Field a user can successfully step up (using SHIFT modifier and `cursor up` key or mouse wheel) to `max + 10` value, it will be corrected, once it looses the focus

2. Defining a min value:
- if using a min value and click into Number Field a user can successfully step down (using `cursor down` key or mouse wheel) to `min - 1` value, it will be corrected, once it looses the focus
- if using a min value and click into Number Field a user can successfully step down (using SHIFT modifier and `cursor down` key or mouse wheel) to `min + 10` value, it will be corrected, once it looses the focus
- if using a min value of `0` - there seems no real min limit set and user can step down to `-1 * max` 
- if using a min value of `0` - user can use the stepper to step to `0` - button seems disabled, but clicking it again re-enables the button and steps further down to `-1 * max` , this won't be corrected

### Screenshots

<img width="224" alt="Screenshot 2023-11-24 at 17 45 16" src="https://github.com/adobe/spectrum-web-components/assets/29090947/40a65e62-4046-44db-99b3-bef077bad4da">

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/JAP5C1EoJO0WvZGrZx4I/src/index.ts?p=stories
2. Try out several use cases with stepper, cursor keys, mouse wheel and SHIFT modifier.

**Comment by nilerudra** [comment]
I want to work on it. Could you please assign this issue to me?
