### ISSUE TITLE
[Bug]: Horizontal card corners not hugging component correctly

### ISSUE THREAD

**Issue by lynnhao** [adobe/spectrum-web-components#3843]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

card, horizontal

### Expected behavior

The border should hug the component, and there should be no gap in the corners.

### Actual behavior

There are gaps in the corners where the white background is showing.

### Screenshots

<img width="560" alt="Screenshot 2023-12-01 at 11 49 38 AM" src="https://github.com/adobe/spectrum-web-components/assets/16598521/1ec777ff-264d-4854-bc55-b4c291302dd9">

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

1. Go to [Storybook](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/card--horizontal)
2. Observe corners of the border

### Sample code that illustrates the problem

N/A

### Logs taken while reproducing problem

N/A

**Comment by Westbrook** [comment]
This looks like it sources from Spectrum CSS, see https://opensource.adobe.com/spectrum-css/card.html#horizontal

<img width="661" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/1156657/c31df569-7f3e-4477-9807-c696a3752fc4">

@pfulton could you help us out here?

**Comment by pfulton** [comment]
Thanks for reporting this! We'll get it scheduled for our next sprint. Tracking it here: https://jira.corp.adobe.com/browse/CSS-677

**Comment by Westbrook** [comment]
Thanks @pfulton this upstream fix is now available in the `latest` release.
