### ISSUE TITLE
[Bug]: Overlays position incorrectly when inside elements with container-type property

### ISSUE THREAD

**Issue by timsnadden** [adobe/spectrum-web-components#3874]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

overlay

### Expected behavior

Overlays are positioned correctly in relation to trigger elements

### Actual behavior

An overlay can be positioned incorrectly if it is a descendant of an element with the `container-type` CSS property applied with a value other than 'normal' (e.g. `container-type: size`). This happens in Chromium browsers but not in Firefox.

This is likely the same issue as this https://github.com/adobe/spectrum-web-components/issues/3718. I created a new issue as the issue is wider than tooltips.

### Screenshots

![image](https://github.com/adobe/spectrum-web-components/assets/221541/f575b47a-7cf4-4873-910d-bc538f7e9cda)

### What browsers are you seeing the problem in?

Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

See https://codepen.io/karbonhq/pen/dyaaLKR?editors=1000

1. Place a component that creates an overlay inside an element with the CSS `container-type: size` or `container-type: inline-size`
2. Click on the trigger element to show the overlay
3. Note that overlay is not positioned in relation to the trigger

### Sample code that illustrates the problem

```html
<sp-theme theme="spectrum" color="light" scale="medium">
  <div style="display: grid; place-content: center">
    <div style="container-type: size">
      <p style="white-space: nowrap">This is inside an element with 'container-type: size'</p>
      <sp-action-menu size="m">
        <span slot="label">More Actions</span>
        <sp-menu-item> Deselect </sp-menu-item>
        <sp-menu-item> Select inverse </sp-menu-item>
        <sp-menu-item> Feather... </sp-menu-item>
        <sp-menu-item> Select and mask... </sp-menu-item>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-item> Save selection </sp-menu-item>
        <sp-menu-item disabled> Make work path </sp-menu-item>
      </sp-action-menu>
    </div>
</sp-theme>

```

**Comment by Westbrook** [comment]
Thank you so much for following [instructions the docs](https://opensource.adobe.com/spectrum-web-components/components/overlay/#top-layer-over-complex-css) and sharing this use case!

If you were interested in getting a head start on making a contribution to address this, you could do so by including some combination of `css.container`, `css.containerName`, and `css.containerType` tests to https://github.com/adobe/spectrum-web-components/blob/8895b0cb671ca95c457ad631a644879dd8226c81/packages/overlay/src/topLayerOverTransforms.ts#L83-L105
