### ISSUE TITLE
[Bug]: typo in checkmark override color

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#3917]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-checkbox

### Expected behavior

--mod-checkbox-checkmark-color should override the checkmark color

### Actual behavior

--mode-checkbox-checkmark-color is used for the checkmark icon, while --mod-checkbox-checkmark-color is used in a few other places.

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/checkbox/
2. Inspect the checkmark in the debugger
3. Look at the styles for sp-icon-checkmark100 -- you'll see `--mode-` instead of `--mod`

**Comment by adixon-adobe** [comment]
This is easy to workaround by just overriding both variables, and is likely a very easy fix.

**Comment by Westbrook** [comment]
@pfulton thought on the tokens at play here?

**Comment by pfulton** [comment]
Thanks for reporting this. Should be a quick fix for us, and I'll get it scheduled for our next sprint. Tracking it here: https://jira.corp.adobe.com/browse/CSS-675

**Comment by Westbrook** [comment]
Thanks @pfulton the upstream fix is now part of the `latest` release.
