### ISSUE TITLE
[Bug]: Action Menu in express theme hover item color is not populating

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#3933]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Action-Menu

### Expected behavior

Hover background should work as per design

### Actual behavior

Hover background doesnt work and `--spectrum-menu-item-background-color-hover` is not getting populated

### Screenshots

<img width="462" alt="Screenshot 2024-01-11 at 5 46 44 PM" src="https://github.com/adobe/spectrum-web-components/assets/8790510/e6766934-e2a0-4593-a4f9-1323218ca2b9">

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/action-menu/
2. Click on any action-menu item and hover

### Sample code that illustrates the problem

`--spectrum-menu-item-background-color-hover` is declared in spectrum > custom-light-vars but not in express > custom-light-vars

**Comment by Westbrook** [comment]
@pfulton do you expect an Express product to be required to have both [Spectrum custom light tokens](https://github.com/adobe/spectrum-web-components/blob/main/tools/styles/tokens/spectrum/custom-light-vars.css) AND the [Express custom light tokens](https://github.com/adobe/spectrum-web-components/blob/main/tools/styles/tokens/express/custom-light-vars.css) which amount to https://unpkg.com/browse/@spectrum-css/tokens@13.0.6/dist/css/spectrum/custom-light-vars.css and https://unpkg.com/browse/@spectrum-css/tokens@13.0.6/dist/css/express/custom-light-vars.css as CSS project output, respectively.

**Comment by Rocss** [comment]
> @pfulton do you expect an Express product to be required to have both [Spectrum custom light tokens](https://github.com/adobe/spectrum-web-components/blob/main/tools/styles/tokens/spectrum/custom-light-vars.css) AND the [Express custom light tokens](https://github.com/adobe/spectrum-web-components/blob/main/tools/styles/tokens/express/custom-light-vars.css) which amount to https://unpkg.com/browse/@spectrum-css/tokens@13.0.6/dist/css/spectrum/custom-light-vars.css and https://unpkg.com/browse/@spectrum-css/tokens@13.0.6/dist/css/express/custom-light-vars.css as CSS project output, respectively.

Was there any decision over this?

**Comment by GarthDB** [comment]
In Spectrum 2, the spectrum and express themes are combined in the token system that populates spectrum css and spectrum web components. Anything that any product needs specific to their product will need to be set using overrides in the individual product.
