### ISSUE TITLE
[Bug]: Dialog: sp-close-button should use sp-icon-cross300 in default size

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3939]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Dialog

### Expected behavior

Refering to the Spectrum css spec - `sp-close-button` in a dismissible dialog should use a 12x12px icon, which should be sp-icon-cross300

### Actual behavior

Current `sp-close-button` of a dismissible dialog uses 8x8px icon (sp-icon-cross100)

### Screenshots

Spectrum css: https://opensource.adobe.com/spectrum-css/dialog.html#dialog-dismissible
<img width="918" alt="Screenshot 2024-01-15 at 12 27 38" src="https://github.com/adobe/spectrum-web-components/assets/29090947/84a1239c-f29c-4f7b-8afe-7f75ac8813c6">

SWC: https://opensource.adobe.com/spectrum-web-components/components/dialog/#dismissable
<img width="717" alt="Screenshot 2024-01-15 at 12 27 21" src="https://github.com/adobe/spectrum-web-components/assets/29090947/d1098ae6-5c3f-4fb1-a61d-aeeee75ba646">

### What browsers are you seeing the problem in?

Firefox, Chrome, Microsoft Edge

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
@pfulton how does the CSS team make the decision between leveraging [Icon Size - Large](https://opensource.adobe.com/spectrum-css/closebutton.html#iconsize-large) and the [Default Icon Sizes](https://opensource.adobe.com/spectrum-css/closebutton.html#migrationguide)?
