### ISSUE TITLE
[Bug]: Card: border-radius of asset from slot="preview" should be correct

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#3940]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Card

### Expected behavior

Border-radius of slotted image as `sp-asset` should be correct align outer border of card. This is correctly set for sp-asset in slot="cover-photo":
```
    border-start-end-radius: calc(var(--mod-card-corner-radius, var(--spectrum-card-corner-radius)) - var(--mod-card-border-width, var(--spectrum-card-border-width)));
    border-start-start-radius: calc(var(--mod-card-corner-radius, var(--spectrum-card-corner-radius)) - var(--mod-card-border-width, var(--spectrum-card-border-width)));
 ``` 
   

### Actual behavior

Its incorrectly set for sp-asset in slot="preview":
 
```
border-start-end-radius: var(--mod-card-corner-radius,var(--spectrum-card-corner-radius) );
border-start-start-radius: var(--mod-card-corner-radius,var(--spectrum-card-corner-radius) );
 ``` 
 
look at top left + top right corner radius of asset: 
<img width="738" alt="Screenshot 2024-01-15 at 13 14 16" src="https://github.com/adobe/spectrum-web-components/assets/29090947/23e79a45-136c-4386-a5ca-f207d380b242">

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
@pfulton FYI: this looks quite closely related to #3843.

Closing as a duplicate.
