### ISSUE TITLE
[Bug]: re-opening an action menu on the right side of the page can open outside window bounds

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#3955]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Expected behavior

If there's space on the page, an action menu should always open within the page bounds.

### Actual behavior

If an action menu is on the right side of the page, you can get the menu to open off the right side of the page after opening it a few times. I was able to repro this in the story book by hacking the menu css to push the action menu to the right.

### Screenshots

<img width="839" alt="action-menu-offscreen" src="https://github.com/adobe/spectrum-web-components/assets/48841507/e2949314-6290-4f5d-a17e-aafd4bfc60ec">

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/action-menu--icon-only
2. Hack the css for the action menu to push it to the right of the page (e.g. by adding `float: right;`)
3. Open and close the menu a few times
4. Eventually you should be able to see the issue.

**Comment by Westbrook** [comment]
Does this branch appear to address the issue for you? https://repeat-placement--spectrum-web-components.netlify.app/storybook/?path=/story/action-menu--icon-only&args=align:end
