### ISSUE TITLE
[Bug]: Migrating from SWC 0.11.11 to 0.40.2 caused <Switch> component onChange event to stop working

### ISSUE THREAD

**Issue by lylynguyen** [adobe/spectrum-web-components#3970]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

@spectrum-web-components/switch

### Expected behavior

Expect Switch component onChange to trigger an event

https://git.corp.adobe.com/neuralfiltersplatform/spl-web-client/blob/13d40cdeffcd85e4f04e2dc30c32f4bb2cd18c4e/packages/clio-playground/src/modules/text-to-image/pages/Text2ImageSidebar.tsx#L1618

### Actual behavior

OnChange does not trigger an event. However, replacing onChange with onClick does trigger an event.

### How can we reproduce this issue?

1. Go to 'https://firefly-stage.corp.adobe.com'
2. Login with stage env credentials
3. Click on 'Text to Image' module
4. Enter any prompt, ei "dog in a park"
5. Auto toggles are in the side panel have all stopped working
![Screen Shot 2024-01-26 at 12 32 17 PM](https://github.com/adobe/spectrum-web-components/assets/12718416/f587fb17-2a52-436d-9ec2-ad7e2f4ba691)
![Screen Shot 2024-01-26 at 12 32 43 PM](https://github.com/adobe/spectrum-web-components/assets/12718416/498a2154-fde7-4479-8379-23db91d9cc82)

**Comment by Westbrook** [comment]
Closed via https://github.com/adobe/spectrum-web-components/pull/3977. This should be available in the release coming later this week or so.
