### ISSUE TITLE
[Feat]: sp-action-menu should have an attribute to modify icon placement from left to right.

### ISSUE THREAD

**Issue by akshitrewari** [adobe/spectrum-web-components#3986]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-menu

### Description of the requested feature

sp-action-menu component has a sp-action-button inside it. The action button has a default placement of icon on left side and there is no way to apply CSS on it until the component has been rendered and that is not the correct way.

sp-action-menu should have an attribute to modify icon placement from left to right.
![Screenshot 2024-01-31 at 12 46 58 PM](https://github.com/adobe/spectrum-web-components/assets/8710412/5b8ee5b7-c520-423a-9d60-f485eddd1d1e)
![Screenshot 2024-01-31 at 12 48 00 PM](https://github.com/adobe/spectrum-web-components/assets/8710412/6810bfa8-f0e5-4cd3-8c36-4c5f74341aef)

**Comment by Westbrook** [comment]
Spectrum design specifically excludes this option from their specification. It's unclear whether this would be something that they would accept as an addition to the specification.

**Comment by Rajdeepc** [comment]
@blunteshwar I think we already had one convo on this but defiantly something we should make sure that it is circled through design first.

**Comment by blunteshwar** [comment]
@akshitrewari  Thank you for your suggestion to add an `icon-placement` attribute to the `sp-action-button`. This feature request has been discussed in the past, particularly with teams like the CCUE (Photoshop/Illustrator). The consensus was to simplify the menu structure and not add the option for icons to be placed on the right side in action buttons.

Our current design philosophy aims to maintain a simplified menu structure, ensuring clear distinctions between different UI elements such as action buttons and picker components. Adding the option to modify icon placement could complicate the user interface and lead to inconsistencies.

Furthermore, adding an attribute like icon-placement to the sp-action-button would involve changes in the component's logic, styling, and possibly its documentation.
For  specific icon placements, we recommend using the picker component directly. This approach will provide you with the flexibility you need while adhering to our design guidelines.

We appreciate your understanding and are here to help with any further questions or suggestions.

**Comment by Rajdeepc** [comment]
Link to the discussion we had previously on this! https://adobedesign.slack.com/archives/C01SXNQL760/p1714148327785369
Closing this for now! If you need further clarifications please reach out to Spectrum Design.
