### ISSUE TITLE
[docs] Include link to Storybook from component pages

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#4008]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

> Would it be possible to get a link/card to the storybook, as well? I think that would be great for our consumers.

_Originally posted by @najikahalsema in https://github.com/adobe/spectrum-web-components/issues/3957#issuecomment-1928090860_

- gather list of this data as json to pass into 11ty
- design a good location for another link
- render the link onto the component page

**Comment by TarunAdobe** [comment]
Help me understand the better one from the two approaches below (or a third one if it exists and is better)...

1. Should we add `storybook` urls in the Readme of the packages and update the `gather-spectrum-urls.js` to add the storybook urls from the readme for the 11ty.
2. Another option is to somehow magically figure out the storybook urls without having to add them in the readme (I'm hoping this shouldn't be as magical as it sounds to me) and then add them for the 11ty
