### ISSUE TITLE
[Bug]: Button text (label) vertical alignment differs at certain font-sizes between Firefox and Chrome

### ISSUE THREAD

**Issue by zbrownell** [adobe/spectrum-web-components#4025]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-button

### Expected behavior

I expect the label text to be vertically centered between browsers at all font-sizes

### Actual behavior

At certain font-sizes (e.g. - 16px, see screenshots; below), the vertical spacing is 1px off between Firefox and Chrome - with Chrome appearing to do the better of job of retaining true center (Firefox appears _slightly_ lower than center)

### Screenshots

![example_chrome](https://github.com/adobe/spectrum-web-components/assets/25671661/a8f42628-510a-4353-9bb0-c146c96adf25)
![example_firefox](https://github.com/adobe/spectrum-web-components/assets/25671661/ec4aee32-4d88-4c99-9f3c-ab72fd5e640f)

### What browsers are you seeing the problem in?

Firefox, Chrome

### How can we reproduce this issue?

1. Go to ['...'](https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/Zjc3o94DWuBkT4ve3dny?p=stories)
2. Select `<sp-button>` element in the inspector (Chrome: dev tools, element selector)
3. Alter `font-size` property on button to be 16px
4. Observe

**Comment by zbrownell** [comment]
I'm not sure if this is something that is going to be easily addressed by the spectrum web components team. It looks like it would require adding some Firefox (moz) specific selectors to the styles to target/adjust (special case) firefox. However, it also seems like it would require a significant matrix to achieve correctness across all possible font-sizes.

Instead, it seems like the font metrics used/applied by each browser are the real culprit behind these discrepancies. Unfortunately, it seems like universal browser support for overrides on these values (e.g. - [ascent-override](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/ascent-override#browser_compatibility)) leave some browsers out of the mix.

Not sure if we can kick this out to the adobe clean team/maintainers or if there's even anything they can do to address these discrepancies using font metadata. Still, the issue exists and it would be nice to have addressed in a perfect world. 😄

**Comment by Westbrook** [comment]
Luckily, the Adobe Clean team is already looking into this. There's nothing that SWC will be able to do until a font with different metrics are available, however.

With all the things that are going on at this time, I'd expect any changes to come sync'd to Spectrum 2, so later this year or next.

Given all that, I'm going to close this issue for now.
