### ISSUE TITLE
[Bug]: Picker SWC cannot be disabled on Chrome

### ISSUE THREAD

**Issue by datle-Adobe** [adobe/spectrum-web-components#4033]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Clients that use Picker component

### Expected behavior

When `disabled` is set to true, it should disable the picker

### Actual behavior

In [here](https://opensource.adobe.com/spectrum-web-components/components/picker/#disabled), when `disabled` is set to true, it only grays out the picker, but user can still select the options from the Picker

### Screenshots

![Screenshot 2024-02-13 at 10 13 20 AM](https://github.com/adobe/spectrum-web-components/assets/159950239/b3d80041-b27f-4671-8617-43a9c88f739d)

### How can we reproduce this issue?

1. On Chrome, go to https://opensource.adobe.com/spectrum-web-components/components/picker/#disabled
2. Click on the disabled picker
3. See error

**Comment by Westbrook** [comment]
If you were able to confirm that the version available [here](https://picker-disabled--spectrum-web-components.netlify.app/components/picker/) no longer exhibited this issue, that would be a great help. Thanks!

**Comment by datle-Adobe** [comment]
@Westbrook Confirmed that [this](https://picker-disabled--spectrum-web-components.netlify.app/components/picker/) is fixed on Chrome and Safari
