### ISSUE TITLE
Abstract find and update/create PR comments workflow.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#4039]
The code available below is used across three different workflows in GitHub Actions:

https://github.com/adobe/spectrum-web-components/blob/73902a374037c846dc93845d6eb20596177b3510/.github/workflows/test.yml#L39-L60

It would be good to abstract it to a single place for reuse. While refactoring, it would be nice to move to `async/await` flavored code, rather than `Promise.then()` favored.

If it were possible to find the right configuration to exclude comment producing Action from dependabot PRs, that would also be amazing.

Many thanks!

**Comment by cbum-dev** [comment]
Can you please tell me what to actually do in this issue?

**Comment by Westbrook** [comment]
The code above is used multiple times. This issue look for a single method file that exports the copy/pasted functionality so it can be called from multiple location in the action.

**Comment by Rajdeepc** [comment]
@cbum-dev create a utils action like this:

```
const { github } = require('@actions/github');

async function updateTachometerResultsComment(body, context) {
  const { owner, repo, issue } = context.repo;
  
  const { data } = await github.rest.issues.listComments({
    owner,
    repo,
    issue_number: issue.number,
  });

  const priorComment = data.find(comment => comment.body.startsWith('## Tachometer results') || comment.body.startsWith('# Tachometer results'));
  if (priorComment) {
    await github.rest.issues.updateComment({
      owner,
      repo,
      comment_id: priorComment.id,
      body,
    });
  } else {
    await github.rest.issues.createComment({
      owner,
      repo,
      issue_number: issue.number,
      body,
    });
  }
}

module.exports = { updateTachometerResultsComment };

```

And use it like this:
```
      const { updateTachometerResultsComment } = await import('${{ github.workspace }}/tasks/githubUtils.js');
      await updateTachometerResultsComment(body, context);
```
