### ISSUE TITLE
Side nav does not scroll when on large screen

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#406]
### Expected Behaviour

The side bar should always scroll when there is more content than fits on the screen.

### Actual Behaviour

The sidebar does not scroll when the browser window is wider than 960px.

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-web-components
2. Make sure your browser is wider than 960px
3. Try to scroll the sidebar

**Comment by Westbrook** [comment]
fixed by #407
