### ISSUE TITLE
[Bug]: ActionMenu closing prematurely on iPad pro device

### ISSUE THREAD

**Issue by godanny86** [adobe/spectrum-web-components#4107]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu

### Expected behavior

The `sp-action-menu` should work on iPad pro and other larger touch devices. Either a mobile tray implementation should be used or the standard overlay should work. 

### Actual behavior

What we are observing with the latest version of SWC is that on a large touch device such as an iPad pro the action menu looks to be using the `sp-overlay` + `sp-popover`. However on touch end it seems to close the Overlay and the  result is the menu just flickers. On smaller devices the mobile tray implementation is triggered as expected and this doesn't happen.

Can be reproduced using the documentation and/or sandbox: https://opensource.adobe.com/spectrum-web-components/components/action-menu/, https://studio.webcomponents.dev/edit/OfeOwrikpHyrhWv6YvUI/package.json?p=stories

### Screenshots

Video below is a screen recording using Safari on an iPad Pro simulator:

https://github.com/adobe/spectrum-web-components/assets/8974514/a49f08a9-2675-4ac0-876b-53bee752217f

Sandbox:  https://studio.webcomponents.dev/edit/OfeOwrikpHyrhWv6YvUI/package.json?p=stories

### What browsers are you seeing the problem in?

Chrome, Safari

### How can we reproduce this issue?

1. Navigate to a site using the ActionMenu on a large touch device such as an iPad Pro
2. Try to open the menu by tapping it
3. Observe that the menu flickers and then closes on the end of the touch 

**note** we started seeing this issue after upgrading to SWC 0.45+

**Comment by Westbrook** [comment]
@TarunAdobe would you have any availability to start investigating this, after we get that Slider PR landed?
