### ISSUE TITLE
[Bug]: TabOverflow API Documentation is broken

### ISSUE THREAD

**Issue by blaabaer** [adobe/spectrum-web-components#4146]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

TabsOverflow

### Expected behavior

Each Component's documentation page should have an API section that is generated via a template. Tabs Overflow should have one too, based on the attributes and properties exposed in its code.

### Actual behavior

`Tabs-Overflow` has a white screen on the API tab instead of a table of attributes and properties. Somehow, the API tab is getting created, therefore it has detected data to be displayed, but something is wrong displaying it. 

### Screenshots

<img width="1663" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/162190334/1835a606-130a-47be-9fba-e23a25f26d2f">

<img width="1663" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/162190334/7dce6e09-6391-459c-8380-aa3a6252e06a">

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Rajdeepc** [comment]
I have confirmed that there is no extra API for `<sp-tab-overflow>` so this issue can be closed. Please check the <sp-tab> [API](https://opensource.adobe.com/spectrum-web-components/components/tab/api/) for your use cases.

**Comment by Westbrook** [comment]
fixed in #4165
