### ISSUE TITLE
S2: `theme` deprecation with `system` in `sp-theme` for S2 delivery

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#4261]
Objective
----------

Renames all usages of the `theme` attribute in `sp-theme` to `system` while maintaining `theme` as a deprecated option. Theme-theme has often been a confusing idea to communicate—especially with the upcoming addition of [Spectrum 2](https://s2.spectrum.adobe.com/). This PR aims to better describe a theme as a collection of values including `system` and `color`.

RFC: https://paper.dropbox.com/doc/RFCdeprecation-theme-with-system-in-SWC--CNe1XGM6UDw7EJzTtW8ZMFEuAg-tZw1OlIvRM5J6pVwad3J7

**Comment by lschierer** [comment]
This is yet another component that is apparently deprecated, at least, I get a warning when it is used, but it 
1) isn't marked as deprecated in the documentation
2) there is no migration guide available per <https://opensource.adobe.com/spectrum-web-components/deprecation/>
