### ISSUE TITLE
[Bug]: Focus-ring does not get shown on sp-action-bar's sp-close-button when keyboard focus is brought on the sp-action-bar

### ISSUE THREAD

**Issue by inasirhussain** [adobe/spectrum-web-components#4279]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-action-bar

### Expected behavior

This is an issue in sp-action-bar component that it does not extends sp-action-bar class properly to leverage focus-visible polyfill for the browser which do not support :focus-visible pseudo-class inherently.

### Actual behavior

Focus-ring does not get shown on sp-action-bar's sp-close-button

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

**Comment by Westbrook** [comment]
As we continue to look at changes specifically for supporting the UXP environment, can you think of any automated testing approaches that we could use to support ensuring continued support of this handicapped context?
