### ISSUE TITLE
sp-textinput cannot be reset through lit-html

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#429]
### Expected Behaviour
Given a non-empty string, sp-textinput should display that string, but then be allowed to re-render via lit-html with an empty string. Placeholder should return, and previous non-empty contents should be cleared

### Actual Behaviour
Subsequently rendering sp-textinput with an empty string via lit-html does not return sp-textinput to initial state with placeholder. Instead the component instance must have its value set with dot property notation in JS (but ONLY in the case of empty strings, everything else seems to work fine)

#### Steps to Reproduce
1. Provide data model object containing an empty string
2. Render property containing empty string via template literal and lit-html (both/either in value and/or slot)
3. sp-textinput correctly displays placeholder fallback
4. User types input inside sp-textinput
5. @input or @change event triggers - custom logic updates data model, replacing empty string with input contents
6. User presses a button to clear the input field, application logic tries to clear text field by setting data model with an empty string ('') and re-rendering
7. sp-textinput is unchanged (no placeholder and displays last entered value)

**Comment by Westbrook** [comment]
@bengfarrell thanks for the issue! I'm trying to recreate what you're running into [here](https://webcomponents.dev/edit/ErJS9r5a9QO1UMWKtrFs) but seem to be missing something. Can you review and let me know what else might need to be true for me to encounter step 7?

**Comment by bengfarrell** [comment]
Hey, I just forked yours (for no real reason other than I haven't used that tool yet) and made this test case, which still fails for me.

https://webcomponents.dev/edit/LENmcfKPzvPfJBFdz1Oi

It's entirely possible its not a bug, but I'm not using it correctly - but I'm really not seeing what I'm doing wrong.

Steps here: first enter text and commit the change to the field. Next you'll see an attempt to change the field to an empty string using lit-html's render. Then 2 seconds later, it will ACTUALLY change the field by directly setting the value on the element through JS, bypassing lit-html (demonstrating what I had to do to work around the issue).

**Comment by Westbrook** [comment]
It looks like you're just missing one more `this.render()` in your vanilla element: https://webcomponents.dev/edit/qELZAvlvBMkzt4gIEJ16 `lit-html` will check whether the data is dirty internal to itself, so you actually have to have a render pass after caching `value` into the `datamodel` representing `this.datamodel.value = 'user input'` even though the UI shouldn't change at that point. Otherwise, you'll be comparing the initial render `this.datamodel.value = ''` to what should be the third render `this.datamodel.value = ''`, in light of which `lit-html` will not alter the element.

I'm going to close this for now, but feel free to reopen if you think I've misrepresented your experience!

**Comment by bengfarrell** [comment]
Doh! You're right. After I wrote that example, I thought the extra setting of this.datamodel.text wasn't needed - but I left it in anyway. But now I recall that lit-html needs to be aware of the value, and its not a simple matter of sp-textinput needing to keep track of its own state.

This has bitten me before, and I've just plain forgotten about it. Looks like more of a non-obvious ecosystem problem. Thanks for checking!
