### ISSUE TITLE
[Bug]: ActionMenu items cannot be navigated or selected via Keyboard when MenuItems are inside a MenuGroup

### ISSUE THREAD

**Issue by godanny86** [adobe/spectrum-web-components#4380]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

ActionMenu, MenuGroup

### Expected behavior

When using `sp-menu-group` to group menu items inside a `sp-action-menu` we expect to be able to navigate to the items via the keyboard, just like a menu without using `sp-menu-group`.

**Without Menu Group: keyboard navigation**:

https://github.com/adobe/spectrum-web-components/assets/8974514/0c9c3b5d-e9f8-4848-b3e7-b3b230ef110a

### Actual behavior

When using `sp-menu-group` to group menu items inside a `sp-action-menu` we are unable to navigate to the items via the keyboard. The menu can be opened with "Tab" > "Enter". However the arrow keys do not allow a user to navigate to any menu items. 

We are using the `selects` property of the menu groups to control the selection behavior. 

**With Menu Groups: keyboard navigation**:

https://github.com/adobe/spectrum-web-components/assets/8974514/64d8a418-e958-48d4-a613-fdf0626b54fa

### Screenshots

See videos above ^

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Navigate to the following sandbox: https://studio.webcomponents.dev/edit/JciavEjTy2VT17fMD1Rp/src/index.ts?p=stories
2. Open the actionMenu with the mouse. Verify ActionMenu items can be selected.
3. Try to "tab" and open the ActionMenu
4. Try to use the keyboard arrows to navigate to individual items
5. Observe that we cannot navigate to menu items and/or select them.

### Sample code that illustrates the problem

```
import { LitElement, html, TemplateResult } from "lit";
import { customElement } from 'lit/decorators.js';
import "@spectrum-web-components/action-menu/sp-action-menu.js";
import "@spectrum-web-components/menu/sp-menu.js";
import "@spectrum-web-components/menu/sp-menu-item.js";
import "@spectrum-web-components/menu/sp-menu-divider.js";
import "@spectrum-web-components/menu/sp-menu-group.js";

@customElement("my-counter")
export default class MyCounter extends LitElement {
  protected render(): TemplateResult {
    return html`
      <sp-action-menu @change=${e => console.log(e.target.value)}>
        <sp-menu-group selects="single">
          <span slot="header">Sort By</span>
          <sp-menu-item>
            Name
          </sp-menu-item>
          <sp-menu-item>
            Created
          </sp-menu-item>
          <sp-menu-item>
            Modified
          </sp-menu-item>
        </sp-menu-group>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-group selects="multiple">
        <sp-menu-item>
          Reverse Order
        </sp-menu-item>
        </sp-menu-group>
      </sp-action-menu>
      
    `;
  }
}
```

**Comment by Westbrook** [comment]
We're looking at [this](https://action-menu-groups--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--groups-with-selects) as the "correct" updated functionality here. Can you take a look at confirm we're moving in a direction that supports your goals here?

**Comment by godanny86** [comment]
Yes keyboard navigation looks good with [this](https://action-menu-groups--spectrum-web-components.netlify.app/storybook/index.html?path=/story/action-menu--groups-with-selects) !
