### ISSUE TITLE
Advertise our size better

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#439]
We should leverage community efforts to better outline the small size of our packages. It's possible that means we should have something like:

[![Spectrum Web Components are Small!](https://badgen.net/bundlephobia/minzip/@spectrum-web-components/bundle)](https://bundlephobia.com/result?p=@spectrum-web-components/bundle)

In the top-level README, or in every read me, or in a chart in the docs site, etc.

| Package | Size | Install |
| --- | --- | --- |
| Action Menu | [![Action Menu is Small!](https://badgen.net/bundlephobia/minzip/@spectrum-web-components/action-menu)](https://bundlephobia.com/result?p=@spectrum-web-components/action-menu) | [![Install Action Menu from NPM](https://badgen.net/npm/v/@spectrum-web-components/action-menu)](https://www.npmjs.com/package/@spectrum-web-components/action-menu) |
| Actionbar | [![Actionbar is Small!](https://badgen.net/bundlephobia/minzip/@spectrum-web-components/actionbar)](https://bundlephobia.com/result?p=@spectrum-web-components/actionbar) | [![Install Actionbar from NPM](https://badgen.net/npm/v/@spectrum-web-components/actionbar)](https://www.npmjs.com/package/@spectrum-web-components/actionbar) |
| Avatar | [![Avatar is Small!](https://badgen.net/bundlephobia/minzip/@spectrum-web-components/avatar)](https://bundlephobia.com/result?p=@spectrum-web-components/avatar) | [![Install Avatar from NPM](https://badgen.net/npm/v/@spectrum-web-components/avatar)](https://www.npmjs.com/package/@spectrum-web-components/avatar) |
| Etc. | Etc. |

But it's possible it means something else.

Open to suggestions.

This also starts to outline some of the costs we're passing on to users via the file organization we're using. See `Action Menu` which depends on `Button` and `Icons` which are both actually a number of components under the covers that aren't all needed in the context of `Action Menu`. Reviewing and addressing that would be separate follow up work.

**Comment by benjamind** [comment]
Now that bundlephobia has exports analysis https://github.com/pastelsky/bundlephobia/releases/tag/v1.2.0 it might be worth adding a `sideEffects` entry to our `package.json` files listing just those files which actually have direct side effects (the `index.js` only?) And seeing what we get?

**Comment by Westbrook** [comment]
💯 I was looking at that a little, but am still ramping up on what `sideEffects` means or does when used. Our whole tree _has_ `sideEffects`, but you can avoid that when not using `index.js`, so good call. Not sure what we get on their end from it, but let's see!

**Comment by benjamind** [comment]
As I understand it the list of files in `sideEffects` property are treated as if they cannot be treeshaken even if no actual exports from them are directly used in the analyzed code bundle. So our `index.js` files all have side effects, since they are the registration calls that use the web component classes, but our other files do not.

I think this should actually reduce the size of the `action-menu` example, since its dependency on the buttons is on files which do not have side effects (the css for instance), which are just exported as values.
