### ISSUE TITLE
[Bug]: Checkbox and Overlay are missing lit dependencies in 0.42.3 release

### ISSUE THREAD

**Issue by jcmitch** [adobe/spectrum-web-components#4407]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Checkbox, Overlay

### Expected behavior

Should be able to install components without error or without needing to include additional dependencies. 

### Actual behavior

Error messages when installing.

```
CheckboxMixin.d.ts:1:33 - error TS2307: Cannot find module 'lit' or its corresponding type declarations.

1 import { ReactiveElement } from 'lit';
                                  ~~~~~

InteractionController.d.ts:1:41 - error TS2307: Cannot find module 'lit' or its corresponding type declarations.

1 import type { ReactiveController } from 'lit';
                                          ~~~~~

slottable-request-directive.d.ts:2:32 - error TS2307: Cannot find module 'lit/async-directive.js' or its corresponding type declarations.

2 import { AsyncDirective } from 'lit/async-directive.js';
```

### How can we reproduce this issue?

1. Attempt to install 0.42.3 outside of an environment which includes lit

**Comment by Westbrook** [comment]
Closed by #4416
