### ISSUE TITLE
[Bug]: Slider values are truncated and divided by 1000 - when using values > 1000

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#4415]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider

### Expected behavior

When an editable slider is used with values > 1000 - those values should be displayed without truncation

```
<sp-slider 
        label="Slider with values > 1000" 
        min=0
        max=5000
        step="1"
        editable
        hide-stepper
      ></sp-slider>
``` 

### Actual behavior

Using an editable slider with values > 1000 those values will be truncated by 1000 and rendered into input field

### Screenshots

![Screenshot 2024-05-08 at 11 06 26](https://github.com/adobe/spectrum-web-components/assets/29090947/0947a4b9-bb63-4e48-b085-207b5102c30d)

https://github.com/adobe/spectrum-web-components/assets/29090947/c970c5ef-9359-4193-8951-9262adfa6ef5

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/MhXptBuyqtzL3DXAK3Cj/src/index.ts?p=stories
2. Click on slider and adjust values to be greater than 999
3. See input field renders values divided by 1000, so 1 instead of 1000 and 2 instead of 2000 are rendered, etc.

**Comment by spdev3000** [comment]
Probably was introduced with: https://github.com/adobe/spectrum-web-components/pull/4263

**Comment by Westbrook** [comment]
@blunteshwar please look at this with priority!

**Comment by spdev3000** [comment]
Thanks!
