### ISSUE TITLE
[Bug]: Firefox: Text in Textfield cannot be selected by mouse

### ISSUE THREAD

**Issue by abdelina** [adobe/spectrum-web-components#4420]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-textfield, sp-popover

### Expected behavior

Double clicking within the textfield will select a word from the text. Right and left cursor keys will navigate through the text

### Actual behavior

On Firefox: Clicking within the textfield does nothing. It changes the focus correctly, but no click or double click goes to the actual text.
This works fine in Chrome.

### Screenshots

<img width="265" alt="image" src="https://github.com/adobe/spectrum-web-components/assets/112932135/8dc21f13-82e6-4e3c-b18a-f344d14da6a8">

### What browsers are you seeing the problem in?

Firefox

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/udD6Tr9Na5gEAqE9Wc0O/src/index.ts?p=stories
2. Click on Button popover 1 (an action button)
3. Try to select text within the textfield by mouse or try double clicking for single word selections

### Sample code that illustrates the problem

See minimal repo case shared above. The crucial part is the draggable="true" attribute. When removing the attribute, it also works fine in Firefox.

**Comment by Westbrook** [comment]
You can't leverage the `draggable` attribute in this way, it's one of the fun bugs in the API cross browser.

If you want that content to be "draggable" you should scope the application of the `draggable` attribute to the `pointerdown` (correct me if I'm wrong here @hunterloftis) of the specific elements in the `sp-popover` that you would like to be draggable. A drag handle can be good for this, or if you 100% want it to be the _entire_ popover, you could do that as well, in cases where the `pointerdown` is not on the `sp-textfield` at first.

**Comment by Westbrook** [comment]
This is a side effect of this unaddressed browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=739071. The fix is to conditionally apply `draggable="true"` _only_ when you know that the element you are interacting with should allow the parent element to be dragged.

Closing as "won't fix".
