### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'selectionRoot') in Menu.handlePointerBasedSelection 

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#4456]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Menu

### Expected behavior

When using non-menu-item components as submenu clicking those components shouldn't trigger TypeError

### Actual behavior

Using arbitrary components as submenu items and clicking them produces the TypeError: 
`Cannot read properties of undefined (reading 'selectionRoot') in Menu.handlePointerBasedSelection` 

### Screenshots

![Screenshot 2024-05-15 at 12 16 48](https://github.com/adobe/spectrum-web-components/assets/29090947/c2b2e82f-6123-42d5-b5ad-ca7d59ca6902)

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Sample code that illustrates the problem

This might be fixed by adding `?` after `menuData`, see:  
```
 target?.menuData?.selectionRoot === this &&
 ```
in https://github.com/adobe/spectrum-web-components/blob/d38bf04fc204ea47c1b60874bd48536d961cb9c1/packages/menu/src/Menu.ts#L391

**Comment by Westbrook** [comment]
I'm surprised that without a Menu Item that [this code](https://github.com/adobe/spectrum-web-components/blob/d38bf04fc204ea47c1b60874bd48536d961cb9c1/packages/menu/src/Menu.ts#L366-L372) is finding a `trigger`. Can you share what the trigger is so we can understand how it is both `el.getAttribute('role') === this.childRole` and `el.menuData === undefined`?

**Comment by spdev3000** [comment]
```
  handlePointerBasedSelection(event) {
    const path = event.composedPath();
    const target = path.find((el) => {
      if (!(el instanceof Element)) {
        return false;
      }
      console.log("MENU SWC: ", el);
      return el.getAttribute("role") === this.childRole;
    });
```

    
prints out:


`<li class="spectrum-Menu-item" tabindex="0" role="menuitem"><span class="spectrum-Menu-itemLabel"><span>Edit version info</span></span></li>`
    
and leads to:


```
    TypeError: Cannot read properties of undefined (reading 'selectionRoot')
    at Menu.handlePointerBasedSelection (chunk-SCU35XXF.js?v=c2a8ef54:347:59)
    at Menu.handlePointerup (chunk-SCU35XXF.js?v=c2a8ef54:321:10)
    at Menu.nrWrapper (chunk-DTJESBZO.js?v=c2a8ef54:71:21)
```

**Comment by najikahalsema** [comment]
We can add this, but we should make sure we add tests for this case.
