### ISSUE TITLE
[Bug]: Slider and Numberfield don't respect different locale with fractional steps

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#4483]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Slider, Numberfield

### Expected behavior

When rendering an editable slider component or Numberfield with step=0.1 it should correctly increase/decrease the value by this step when using stepper buttons or key events (arrow up/down) - in all locales.

### Actual behavior

When rendering an editable slider component or Numberfield with step=0.1 changing values by stepper button or key event works correctly in en-US locale, but doesn't in other locales (such as de-DE) where different characters are used as delimiter (`,` instead of `.`)

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/3kPO18Pv4S4RTLAy6Pia/src/index.ts?p=stories
2. Try adjusting the Numberfields in different locales with stepper or key events
3. See different results for different locales, en-US is working well, de-DE isn't

**Comment by najikahalsema** [comment]
Fix your value formatter !!!!! @blunteshwar
