### ISSUE TITLE
[Bug]: Inconsistent behavior of sp-number-field in Safari on iOS

### ISSUE THREAD

**Issue by mihaiudvuleanu** [adobe/spectrum-web-components#4531]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

The number grouping separator `,` should not be interpreted as a decimal point. For example if i edit a number displayed as "1,000" and I delete the last 0 digit, the result should be "100".

### Actual behavior

While editing a number, the grouping separator is interpreted as a decimal point and, in the above scenario, the result is 1.

### Screenshots

![number-field](https://github.com/adobe/spectrum-web-components/assets/171576787/7ea55bb4-1bef-412e-8bb1-408491d6b623)

### What browsers are you seeing the problem in?

Safari / iOS 17.5.1

### How can we reproduce this issue?

1. Navigate to https://opensource.adobe.com/spectrum-web-components/components/number-field/
2. Edit the first editable box on the page (from Sizes), by deleting the last digit (try to change it from 1024 to 102)
3. Hit Enter, now I'm expecting to see 102 in the text box
4. Instead, it displays 1.02 (the grouping separator was interpreted as a decimal point)

**Comment by rubencarvalho** [comment]
Fixed by https://github.com/adobe/spectrum-web-components/pull/4571
