### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by pauceano** [adobe/spectrum-web-components#4551]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Description of issue

I am having a lot of problems to install the project for development, problems with yarn versions, deprecated packages... things that have nothing to do with the package itself.
Could someone give a docker for development? Something that works.
Thank you very much.

**Comment by Rajdeepc** [comment]
Closing this due to insufficient description. Feel free to let us know in the channel so that team can proactively unblock you if you are still having issues!
