### ISSUE TITLE
[Feat]: Fill-start in slider should respect 0-values as well as normalization function

### ISSUE THREAD

**Issue by spdev3000** [adobe/spectrum-web-components#4559]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Silder

### Description of the requested feature

1. Currently `fill-start` attribute only allows to set values !== 0, but sometimes clients have sliders with min<0 , so for example: `min="-100", max="200"` - so we need a possibility to define `fill-start="0"` to not start from centered track position
2. Also currently the fill-start calculation doesn't respect any provided normalization function, so we'd like to calculate all fill-related values (offset + length) by a given normalization function of model of active handle 

### Mockups or screenshots

![Screenshot 2024-06-12 at 18 05 40](https://github.com/adobe/spectrum-web-components/assets/29090947/9f36c876-300d-4c5a-808b-c7d4abebc6a3)

**Comment by najikahalsema** [comment]
fixed via #4573
