### ISSUE TITLE
[Bug]: sp-tray retracts automatically when opened with less items in iOS simulator

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#4572]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tray. sp-picker

### Expected behavior

The `sp-tray` should not automatically retract when opened in any devices.

### Actual behavior

The `sp-tray` automatically retracts when opened in iOS devices.

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes
2. visit the page, 2.
3. click on Sort: Popularity

**Comment by blunteshwar** [comment]
@Rajdeepc the link in the ticket(https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes) is not opening and thus I am unable to reproduce the bug. Can you look at this?

**Comment by yesil** [comment]
@blunteshwar @Rajdeepc the issue is reproducible at https://main--cc--adobecom.hlx.live/products/catalog?martech=off

**Comment by blunteshwar** [comment]
@yesil Can you please confirm which version of ios and safari you are using,because on my end the bug is not present.

**Comment by Rajdeepc** [comment]
> [@yesil](https://github.com/yesil) Can you please confirm which version of ios and safari you are using,because on my end(ios 17.5) the bug is not present.

@blunteshwar can you add a repro on this issue on simulator and actual device?
