### ISSUE TITLE
[Bug]: Documentation Mobile RTL Settings panel is off-screen

### ISSUE THREAD

**Issue by barryels** [adobe/spectrum-web-components#4615]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Documentation

### Expected behavior

1. Navigate to the documentation site (https://opensource.adobe.com/spectrum-web-components/)
2. Resize the browser to a width of less than 961px
3. Press the Settings menu trigger (gear icon in the top right corner)
4. You should see the "Settings" menu
5. Choose "RTL" in the "Direction" dropdown
6. The "Settings" menu closes
7. Then the layout adjusts to Right-to-Left orientation
8. Press the Settings menu trigger (gear icon now in the top left corner)
9. You should see the "Settings" menu

### Actual behavior

1. Navigate to the documentation site (https://opensource.adobe.com/spectrum-web-components/)
2. Resize the browser to a width of less than 961px
3. Press the Settings menu trigger (gear icon in the top right corner)
4. You should see the "Settings" menu
5. Choose "RTL" in the "Direction" dropdown
6. The "Settings" menu closes
7. Then the layout adjusts to Right-to-Left orientation
8. Press the Settings menu trigger (gear icon now in the top left corner)
9. You should see a dark UI overlay
10. You **will not** see the "Settings" menu

### Screenshots

https://github.com/user-attachments/assets/5d024988-5e96-406c-b4dc-ec4b65233c8a

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Navigate to the documentation site (https://opensource.adobe.com/spectrum-web-components/)
2. Resize the browser to a width of less than 961px
3. Press the Settings menu trigger (gear icon in the top right corner)
4. You should see the "Settings" menu
5. Choose "RTL" in the "Direction" dropdown
6. The "Settings" menu closes
7. Then the layout adjusts to Right-to-Left orientation
8. Press the Settings menu trigger (gear icon now in the top left corner)
9. You should see a dark UI overlay
10. You **will not** see the "Settings" menu

### Sample code that illustrates the problem

Potential fix:

```diff
diff --git a/projects/documentation/src/components/layout.css b/projects/documentation/src/components/layout.css
index 4513eb049..8629ae4fa 100644
--- a/projects/documentation/src/components/layout.css
+++ b/projects/documentation/src/components/layout.css
@@ -297,6 +297,6 @@ sp-underlay:not([open]) + aside {
     right: auto;
 }
 
-:host([dir='rtl']) aside:not(.show) {
+:host([dir='rtl']) sp-underlay:not([open]) + aside {
     transform: translateX(-100%);
 }
```

**Comment by najikahalsema** [comment]
Would you be interested in making a contribution to fix this issue?
