### ISSUE TITLE
Docs for placement attribute are less descriptive

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#462]
### Expected Behaviour

The docs for `sp-tooltip` and `sp-popover` should list all of the options for the `placement` attribute. I tried to use a Typescript type for that which isn't helpful to users reading the docs.

https://opensource.adobe.com/spectrum-web-components/components/tooltip/api

### Actual Behaviour

The docs should describe the actual available options.

**Comment by juju5477** [comment]
@Westbrook trying to make it work

**Comment by Westbrook** [comment]
Thanks @juju5477 looking forward to what you find here! One option might be to leverage JSDocs for this case. Here are some extended options that `web-component-analyzer` offers in this area: https://www.npmjs.com/package/web-component-analyzer#%E2%9E%A4-how-to-document-your-components-using-jsdoc

As you work through this, please let us know if you find any way we could clarify/expand the documentation or generally make the repo easier to use as we greatly appreciate contributions and would like to support contributors as best we can.
