### ISSUE TITLE
[Bug]: When pressing the Enter button in a textbox, the option should be unselected and the corresponding value should be updated.

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#4620]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

slider

### Expected behavior

On Pressing enter on the sliders text box, the value should be applied and the blue highlight should go away.

### Actual behavior

The sliders text box is still focused on pressing enter

### How can we reproduce this issue?

1. Create a slider
2. Change the value in the text box
3. Press enter key on text box
4. Textbox is still in focus

**Comment by najikahalsema** [comment]
Hi, this isn't a bug. Pressing `Enter` key to unfocus a form input element is not standard behaviour. Try it for yourself with the standard HTML `<input type="text" />` element. To unfocus a form element, the standard key to press is `Tab`.
