### ISSUE TITLE
[Bug]: Spectrum Switch Not Toggling on Enter Key Press

### ISSUE THREAD

**Issue by venkateshjo** [adobe/spectrum-web-components#4624]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

spectrum-switch

### Expected behavior

The switch should toggle its state (on/off) when the Enter key is pressed.

### Actual behavior

The switch does not toggle its state when the Enter key is pressed.

### How can we reproduce this issue?

1. Navigate to the Spectrum switch component.
2. Focus on the switch using keyboard navigation.
3. Press the Enter key.

**Comment by najikahalsema** [comment]
Enter key does not toggle a switch. The key that does this is the `space` bar. For more information, view this documentation: https://www.w3.org/WAI/ARIA/apg/patterns/switch/
