### ISSUE TITLE
[Bug]: @spectrum-web-components/contextual-help has no typings

### ISSUE THREAD

**Issue by moisadoru** [adobe/spectrum-web-components#4648]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

contextual-help

### Expected behavior

When importing from `@spectrum-web-components/contextual-help` in a typescript file from a typescript source file, the typescript compiler should properly detect and load the typings for this package.

### Actual behavior

When importing from `@spectrum-web-components/contextual-help` in a typescript file from a typescript source file, the typescript compiler should not throw an error (TS7016) about missing types.

### How can we reproduce this issue?

1. create a typescript project
2. add `@spectrum-web-components/contextual-help` as a dependency
3. use `import { ContextualHelp } from '@spectrum-web-components/contextual-help';` as per the [docs](https://opensource.adobe.com/spectrum-web-components/components/contextual-help/#usage)
4. attempt to compile the project
5. observe the typescript error

**Comment by neehhaa06** [comment]
Hello @moisadoru :)

fix: #4648

Create a `types` folder and add a file `@spectrum-web-components__contextual-help.d.ts` with basic module declarations. Then, update `tsconfig.json` to include the `types` folder.

**Comment by Rocss** [comment]
Available in next release
