### ISSUE TITLE
[Bug]: FocusGroup won't set the tabindex=0 on the item focused using mouse

### ISSUE THREAD

**Issue by TarunAdobe** [adobe/spectrum-web-components#4649]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

action-group, grid, radio

### Expected behavior

A focused item should have a tabindex=0

### Actual behavior

If the item inside of a action-group (or radio) is focused using a mouse click, the tabindex is not set to 0. 

### How can we reproduce this issue?

1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/action-group--default)
2. Open Inspect element and select action-group.
3. Click on an action-button.
5. Check that the focused action-button doesn't have a tabindex = 0

**Comment by neehhaa06** [comment]
Hello @TarunAdobe  :)

> To fix the error where tabindex=0 is not set on mouse click, ensure that your focus event handler sets tabindex correctly:

```
const handleFocus = (event) => event.target.setAttribute('tabindex', '0');
element.addEventListener('click', handleFocus);
```
