### ISSUE TITLE
[Bug]: Can't trigger change event on breadcrumbs via keyboard

### ISSUE THREAD

**Issue by rickharris** [adobe/spectrum-web-components#4733]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-breadcrumbs

### Expected behavior

When focused on a breadcrumb item, I would expect that hitting enter (or possibly spacebar as well, though I'm not sure what the correct behavior for the sp-breadcrumb-item role would be) would trigger the `change` event on the sp-breadcrumbs element.

### Actual behavior

The `change` event is only triggered on the `sp-breadcrumbs` element when a breadcrumb item is clicked, but not when pressing enter or spacebar while a breadcrumb item has focus.

### Screenshots

https://github.com/user-attachments/assets/ac364adf-ee65-4162-aa94-f734836514bf

In this screen recording you can see that the change event is triggered when a breadcrumb item is clicked. After clicking through items, I focus a breadcrumb item and then press both enter and spacebar several times, and the event is not triggered.

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/kmx7QJCb3pDgMh5caVtZ/src/index.ts?p=stories
2. Click on a breadcrumb item to see the event handler working
3. Focus on one of the breadcrumb items and press enter and spacebar
4. No event is triggered for keyboard events

### Sample code or abstract reproduction which illustrates the problem

https://studio.webcomponents.dev/edit/kmx7QJCb3pDgMh5caVtZ/src/index.ts?p=stories

### Severity

SEV 3

I've labeled this as SEV 3, but it could possibly be a SEV 2 depending on accessibility standards. It doesn't seem possible to navigate via the breadcrumb without a mouse.

**Comment by najikahalsema** [comment]
Fixed via #4769
