### ISSUE TITLE
[Bug][Safari]: Tooltip tip is misaligned 

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-web-components#4734]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Tooltip

### Expected behavior

Tooltip tip in placement `top|bottom` should be aligned in all browsers

### Actual behavior

Tooltip tip is misaligned in Safari
Repro in Safari: https://studio.webcomponents.dev/edit/RWWqg6Hk6AZgH7jKIWVR/src/index.ts?p=stories

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/RWWqg6Hk6AZgH7jKIWVR/src/index.ts?p=stories
2. Hover on the card
3. Check tooltip tip is misaligned

### Severity

SEV 3

**Comment by najikahalsema** [comment]
Possibly related to #4728 as well
