### ISSUE TITLE
Add Spectrum Combobox Pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#478]
Track progress on this component [here](https://github.com/orgs/adobe/projects/48/views/1).

### Expected Behaviour
https://opensource.adobe.com/spectrum-css/combobox.html should be available in the library.

### Actual Behaviour
Missing

### The future
![image](https://user-images.githubusercontent.com/1156657/73966484-1331de00-48e4-11ea-8843-02f166852075.png)

**Comment by Westbrook** [comment]
The hope would be that this could be an extension of the `sp-dropdown` pattern in some way.

**Comment by CoreyDotCom** [comment]
We could definitely use this component, specifically the "quiet" variant and ability to enter value that differs from the stock values (e.g. XD's zoom level combo for example).

**Comment by Westbrook** [comment]
Thanks for the info @CoreyDotCom! Would you be able to share any screenshots of what that looks like? As a "contribution" even the newest version of this pattern has only the smallest amount of direction in the Spectrum documentation, so this information would be invaluable.

**Comment by jnurthen** [comment]
Accessibility of combo boxes is really hard to get right and hard to retrofit if not considered upfront. Please ping me when this component starts to move along.

**Comment by CoreyDotCom** [comment]
Basically just the quiet combo as found here https://opensource.adobe.com/spectrum-css/components/combobox/ 

![image](https://user-images.githubusercontent.com/701828/83896480-3fd6f480-a722-11ea-9bd7-32069e016841.png)

**Comment by Westbrook** [comment]
Revisit this comment https://github.com/adobe/spectrum-web-components/pull/1661#discussion_r679336866 while shipping this pattern.

**Comment by hunterloftis** [comment]
Review pre-1.0; ship only if meeting quality bar.

**Comment by SavoInfostream** [comment]
Any ETA for this component?

**Comment by Westbrook** [comment]
Out current target is end of Q2.

**Comment by Westbrook** [comment]
FYI: Currently, the work on this in blocked by the work going into the Overlay v2 release. Any team that was interested in leveraging a Combobox from SWC soon could smooth the process by beginning to test the [RC release](https://github.com/adobe/spectrum-web-components/discussions/2764#discussioncomment-6450198) of that code in their application.

After that, it would be great if we could collect your specific use cases in [the issue tracking this addition.](https://github.com/adobe/spectrum-web-components/issues/478) Specifically, it would be useful to know which of the various Combobox type you are looking to leverage to support scoping an initial release:
- [Select-Only Combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/): A single-select combobox with no text input that is functionally similar to an HTML select element.
- [Editable Combobox with Both List and Inline Autocomplete](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/): An editable combobox that demonstrates the autocomplete behavior known as list with inline autocomplete.
- [Editable Combobox with List Autocomplete](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/): An editable combobox that demonstrates the autocomplete behavior known as list with manual selection.
- [Editable Combobox Without Autocomplete](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-none/): An editable combobox that demonstrates the behavior associated with aria-autocomplete=none.
- [Editable Combobox with Grid Popup](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/grid-combo/): An editable combobox that presents suggestions in a grid, enabling users to navigate descriptive information about each suggestion.

With that information, and the code review for the new Overlay API wrapping up this week, we should be in a place where we could review the outstanding work required by that branch in order to possibly break it into sharable pieces later this week into next.
