### ISSUE TITLE
sp-action-button "focus" management RFC

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#480]
### Particular usage context...
When working with a "selection" and using an action button to "change" something about the selected item you _might_ expect the focus to remain on the "selection" rather than move to the action button. How should we manage that?

- Is this a functionality of `sp-action-button` that we need to take into account within the component?
- Is this a functionality of an application implementing an `sp-action-button`?
   - If so, should we publish a helper to work in this context?

**Comment by Westbrook** [comment]
This is gonna be a little tricky as we won't be able to rely on `document.activeElement` in the case that we want to _always_ return the focused element; unless we want to use it to dig down until it finds and element without shadow DOM and/or focused children.

Due to this, we may want to outline a "manager" that can be attached to the element that should maintain `focus` and the action button so that the two can know when to light up this functionality.

**Comment by Westbrook** [comment]
We'll also need to check into managing carat position, etc when this feature is applied to textareas or inputs.

**Comment by Westbrook** [comment]
So it looks like we could manage the addition of this functionality from the "outside" (without needing direct access to `this`) via the following code being attached to the `mousedown` event:
```
const onMousedown = (event: MouseEvent) => {
    const target = event.target as HTMLElement;
    target.addEventListener('focusin', onFocusin);
}

const onFocusin = (event: FocusEvent): void => {
    const target = event.target as HTMLElement;
    const relatedTarget = event.relatedTarget as HTMLInputElement;
    if (!relatedTarget || typeof relatedTarget.selectionStart === 'undefined') {
        return;
    }
    relatedTarget.focus();
    relatedTarget.setSelectionRange(
        relatedTarget.selectionStart as number,
        relatedTarget.selectionEnd as number
    );
    target.removeEventListener('focusin', onFocusin);
}
```
It currently gates specifically against returning focus to elements without the `selectionStart` et al APIs, but that can of course be changed.

### Questions
1. To what sort of non-selection bearing elements would we want to be returning focus?
    - all elements?
    - supplied elements?
    - elements with some specific attribute/property?
    - if we expand in this way, we'll need to gate the selection functionality specifically
2. Always returning focus seems like the wrong UX here, but maybe there's a specific setting for that?
3. Does this belong "internal" to the `<sp-action-button>` element, so possibly `<sp-action-button returns-focus>` or the like? 
    - Does such a property belong in any other elements?
4. Does this belong as a helper that users can add from their implementing application/components?

**Comment by benjamind** [comment]
Just to get this clear, is the issue here that we want to be able to tap a button like 'bold' in a wysiwyg style editor and it not hold on to focus after the click?

If so this feels to me definitely out of scope for the SWC library, the application specific event handler should deal with restoring focus in this case I think?

**Comment by Westbrook** [comment]
Yes, that is the problem space.

I feel that whether this belongs in library or not is a trickier question than just that. While I agree this functionality is more related to building applications as opposed to building a component, I don't believe that it's application specific or rather something one application should handle differently than another. This is one reason that the ability to support this functionality from the outside is a great win and points to this being a sort of helper method that the library ships rather than functionality of any single package, reading back I don't think I was as clear as I could have been in that area.

However, `<sp-action-button>` already being a specific extension of the `<sp-button>`, imbued with the ability to manage its `selected` state and whether that state `toggles` does in some way point to this functionality being closely related to it.

As a user of this element, @jstoeckm where from/how would you have expected to be able to leverage this functionality?

**Comment by jstoeckm** [comment]
Sorry for stirring this up. I wasn't aware of the fact that is impossible to make an element non focusable. If there would have been a way to tag the element or overwrite an event handler I would have liked it to be reflected. The use of it would be for text editing (the focus frame of this text area starts blinking too when applying a style). Sorry again and please ignore the issue.

**Comment by Westbrook** [comment]
@jstoeckm This is absolutely possible, as outlined in https://github.com/adobe/spectrum-web-components/issues/480#issuecomment-608446604. What's more, I agree that it's a valuable piece of functionality to have clearly defined and structure for use in an application. The questions I'm looking at right now are where such a thing should live and how flexible it should be.

Which of the following would you expect to be able to leverage when building a feature:
1. An attribute that is managed internal to an action button, a la: `<sp-action-button returns-focus>Bold</sp-action-button>` so that _any_ action button would be able to leverage this functionality by default. In this case, are there other elements you would expect this to be a part of by default?
2. A helper method that can be applied to just about anything:
    ```
    import {returnsFocusHandler} from '...';
    // ...
    <sp-action-button @mousedown=${returnsFocusHandler}>Bold</sp-action-button>
    ```
    - If you prefer this method, would you expect the `...` to be part of the application you were building or a part of the SWC package (or another dependency) that supported using this functionality in any application.
3. Both, because we could use the helper to ensure that `<sp-action-button>` had this by default _and_ export it to be leveraged in other cases when needed.

How expansive should such functionality be:
1. Support returning focus ALL the time
2. Support returns focus to elements where the `selectionStart` property is available, which implies they are elements accepting a `text` value.
3. Support choosing elements to return focus to:
    ```
    import {returnsFocusHelper} from '...';
    // ...
    const elementsToReturnTo = [
        ...this.querySelectorAll('input[type=text]'),
        ...this.querySelectorAll('.some-element-i-want-focus-returned-to'),
    ];
    const returnsFocusHandler = returnsFocusHelper({returnsTo: elementsToReturnTo});
    // ...
    <sp-action-button @mousedown=${returnsFocusHandler}>Bold</sp-action-button>
    ```

**Comment by jstoeckm** [comment]
@Westbrook this actually not possible cause you are talking about receiving the focus and then giving it back to something where you want to guess what the selection is meant to be. I thought there is a way of not having a focus change at all when clicking the button.

In case of receiving the focus and then deciding what to do I think the application should handle this by using an optional event handler (2.).

**Comment by Westbrook** [comment]
That's what's happening in the `focusin` event here, which comes [before focus is received](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event):
```
const onFocusin = (event: FocusEvent): void => {
    const target = event.target as HTMLElement;
    const relatedTarget = event.relatedTarget as HTMLInputElement;
    if (!relatedTarget || typeof relatedTarget.selectionStart === 'undefined') {
        return;
    }
    relatedTarget.focus();
    relatedTarget.setSelectionRange(
        relatedTarget.selectionStart as number,
        relatedTarget.selectionEnd as number
    );
    target.removeEventListener('focusin', onFocusin);
}
```
`event.relatedTarget` being a reference to the previous element with `focus`, we can simply give it focus "again".

If you still think this sort of functionality belongs in app-specific code, I'll close this issue and move the work here to that context. Thanks for the input!

**Comment by jstoeckm** [comment]
This mechanism would assume that the focus is on a text like selection. I don't think its worth adding it to a general action button and I still would see it as app-specific code.
Imo it is more important to have a general way to overwrite the behaviour.

**Comment by Westbrook** [comment]
Closing as out of scope.
