### ISSUE TITLE
[Bug]: Text suggestions appear for `sp-number-field` when using Japanese/Simplified Chinese/Traditional Chinese IME

### ISSUE THREAD

**Issue by Rocss** [adobe/spectrum-web-components#4805]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-number-field

### Expected behavior

If only digits are allowed in the field then suggestions should not appear for the same when enter inputs using IMEs.

### Actual behavior

 Although a text is not allowed to be input, Text candidates appear.

### Screenshots

![Screenshot 2024-10-07 at 15 20 17](https://github.com/user-attachments/assets/9c102a81-0531-4779-97ba-a4fff4f81368)

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/number-field/
2. Make sure to use Japanese IME (you can find this in the Keyboard settings)
3. Try to enter some text (ex. 'あい'in JP) into the numeric input box.
4. Observe the text.

### Sample code or abstract reproduction which illustrates the problem

Maybe this is due to the `input type="text"`?

### Severity

Minor

**Comment by Rocss** [comment]
@rubencarvalho I prepared a fix for this on `rocss/4805` branch, but looking at how native `input type=number` behaves, I am not sure it should be fixed in the first place? The[ HTML input type number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) allows non-numeric characters when using Japanese/Chinese IME. However, looking at the brothers next door, React Spectrum restricts to numeric characters.
Thoughts?

**Comment by rubencarvalho** [comment]
I agree with your observation, and we typically align with web standards. However, a key aspect of `<input type="number>` is that it _should_ have built-in validation to reject non-numerical entries. Given this expectation, I believe we are still in the clear here in enforcing numeric-only input, even when using an IME. Thank you for contributing the fix 👍
