### ISSUE TITLE
The value of an "sp-slider" can display outside of it's restraints

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#481]
### Expected Behaviour
The display value of an `sp-slider` should stick to its restraints.

### Actual Behaviour
![image](https://user-images.githubusercontent.com/1156657/73967120-4cb71900-48e5-11ea-81bf-8b52283794a0.png)

**Comment by Westbrook** [comment]
It's possible that the process by which `0.8300000000000001` here is more a matter of documenting the use of `getAriaValueText` than actually adding new functionality. As such, we may just start a list of helper methods that capture common patterns here, like clamping to a specific number of decimal places...

**Comment by Westbrook** [comment]
Javascript is sloppy here, but HTML isn't. It looks like if we apply the "anticipated" value to the `input` with the value for `step` applied that is will correct any inaccuracies for us, where as the current JS:
```
if (this.step) {
            value = Math.round(value / this.step) * this.step;
}
```
Can slip into "lazy JS mode" and give us back incorrectly "rounded" numbers.

**Comment by andrewhatran** [comment]
Oh interesting, good catch! 

So if we can tried something like this, the rounding will be correct? :
```
this.input.value = Math.round(value / this.step) * this.step;
```

**Comment by Westbrook** [comment]
I'm not sure the right part of the lifecycle to do this, but essentially you'd do something that amounted to:

```
this.inputElement.value = Math.round(value / this.step) * this.step; // or event just `value`;
this.value = this.inputElement.value;
```

So that you always used to `input` to sanitize the `value`...might just put it in `updated`:

```
updated() {
   // ...
   this.value = this.inputElement.value;
}
```

And just send the "rounded" values into the UI? Wanna test it out a little?
