### ISSUE TITLE
[Bug]: Picker does not animate open smoothly on Safari iOS

### ISSUE THREAD

**Issue by lehelen19** [adobe/spectrum-web-components#4819]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-picker

### Expected behavior

The picker menu should scroll into view and the underlay should transition its opacity smoothly when the picker opens. This behavior might have originated from the overlay upgrade in 0.36.0.

Please refer to https://cclight.slack.com/archives/CESK60MQD/p1728582651860229 for a video.

### Actual behavior

The picker menu and underlay appear almost immediately into view.

https://cclight.slack.com/archives/CESK60MQD/p1728582651860229 has a video of expected behavior from 0.35.0.

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/guTpKeAjgecibF150Qbg/src/index.ts?p=stories
2. Click on one of the pickers and observe

### Severity

None

**Comment by Rocss** [comment]
Happens to `sp-sidenav` as well on https://opensource.adobe.com/spectrum-web-components/index.html

**Comment by Rocss** [comment]
Reproducing to `sp-tray` as well

**Comment by Rocss** [comment]
what I managed to find out so far is that:
opening an `sp-tray` with `overlay-trigger`  as in the [Tray](https://opensource.adobe.com/spectrum-web-components/components/tray/) docs reproduces the issue. If I use the `trigger` directive, it no longer reproduces.
