### ISSUE TITLE
Slider interaction events (add or document)

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#482]
### Expected Behaviour
It should be easy to understand how to leverage `start` and `end` events when interacting with the slider.

- just a documentation question?
- need for synthetic events?

**Comment by Westbrook** [comment]
With the available events this works like so:
```
input    // start
input
input
input
input
input
change // stop
```
I like the idea of accepting the stream as it's much more akin to how you would relate to a native slider. However, I can see the benefit of encapsulating the facts here and explicitly dispatching a `sp-slider-start/stop` style set of events.

**Comment by Westbrook** [comment]
Let's document this clearly, and possibly vend a helper or two to process this and see where we stand after that!

**Comment by andrewhatran** [comment]
Totally in agreement about the `sp-slider-start` and `sp-slider-end` events. 

Currently, it's up to the consumer of the `sp-slider` to determine whether or not an `input` event was the initial `input` event. Would be easier to reason with if with explicit `start/end` events
