### ISSUE TITLE
Add functional support for the "[selected]" attribute/property in "sp-action-button"

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#483]
### Expected Behaviour
An `sp-action-button` should manage the value of "selected" internally in some way.

### Actual Behaviour
The attribute/property is available but only for management from the outside.

**Comment by Westbrook** [comment]
It's possible that the ability to set this attribute from the outside is _enough_ here. However, making the button stateful would allow us to clarify how this element relates to applications it is applied.

**Comment by Westbrook** [comment]
Let's apply a `toggles` attribute (or similar) to encapsulate accessible toggle functionality in this component.

**Comment by Westbrook** [comment]
@jnurthen, I'm planning to add a `toggles` attribute to this component which when `on` I believe deserves the self-management of the `aria-pressed` attribute. It has me wondering though if you know enough about the underlying Spectrum pattern here to take a stance on whether the fact that this component has a `selected` state means it should always apply `aria-pressed`, not just when it is set to `toggles`?

Here's the [Spectrum spec](https://spectrum.adobe.com/page/action-button/) for additional context.

**Comment by jnurthen** [comment]
If a button has `toggles` it becomes a toggle button and should have `aria-pressed="false"` when unpressed and `aria-pressed="true"` when pressed.
A button which cannot be toggled on should not have aria-pressed set at all.

**Comment by Westbrook** [comment]
Thanks @jnurthen that's how I thought it worked, but often the more I think about these attributes the less clear they become in my mind. 😓
