### ISSUE TITLE
[Bug]: Mobile keyboard causes open overlay to close when there is not enough room for it

### ISSUE THREAD

**Issue by lehelen19** [adobe/spectrum-web-components#4897]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-overlay

### Expected behavior

When we have an overlay element (popover) open, we expect it to remain open when we click on an input (such as `sp-textfield` or `sp-number-field`).

### Actual behavior

On iPads, the overlay closes when we touch an input element. The soft keyboard pushes the screen up, and that sometimes results in insufficient space for the overlay. Instead of repositioning and remaining open, it closes.

https://github.com/user-attachments/assets/0c99277e-fb19-471c-b117-b2f33b80e94e

### What browsers are you seeing the problem in?

Safari

### How can we reproduce this issue?

1. Go to the storybook for the default overlay
2. Add an editable slider to the first popover
3. Touch the input box for the slider
4. Observe the overlay closing

### Severity

None

**Comment by TarunAdobe** [comment]
Using a `modal` type overlay is recommended for these use-cases and it fixes the mentioned issue. Closing this now.
