### ISSUE TITLE
sp-textfield cannot be sized easily

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-web-components#513]
### Expected Behaviour

This should behave like any other input control, it should obey display style rules and layout rules applied to the component. 

### Actual Behaviour

Size is not adjustable without using css custom properties. This is due to width of the input control being set to a specific value from the custom variable, the `:host` styling has `display: inline-flex` and requires this display style to behave properly, and the input cannot resize.

Current workaround is to set `--spectrum-alias-single-line-width: 300px;` variable on the textfield instance to size its internal input box.

### Reproduce Scenario (including but not limited to)

Try and set `width: 500px` on any `sp-textfield` instance.

#### Steps to Reproduce

* Create an `sp-textfield` element
* Style it with `width: 300px`
* Observe textfield does not change size

**Comment by Westbrook** [comment]
This looks to be addressed in the early versions of https://www.npmjs.com/package/@spectrum-css/textfield/v/3.0.0-beta.2 🎉 

It's not completely clear when Spectrum CSS anticipates having these packages "stable" but that should also give us some time and opportunity to discuss breaking changed on our side. I'm gonna compare notes on the list of packages with breaks that I've received and opened some issues for us to discuss any changes we'd like to see on our side.
