### ISSUE TITLE
In Safari, <sp-slider> has a blue border box around it when interacting with the component.

### ISSUE THREAD

**Issue by mjkobaya** [adobe/spectrum-web-components#516]
### Expected Behaviour
Click on the thumb of the slider and move it and no blue border box appears around the slider.

### Actual Behaviour
Click on the thumb of the slider and move it and a blue border box appears around the slider.

<img width="623" alt="Screen Shot 2020-02-28 at 10 49 59" src="https://user-images.githubusercontent.com/7560303/75578097-1c602780-5a18-11ea-8071-7e7f66b92b81.png">

#### Steps to Reproduce
1. Open Safari browser.
2. Go to slider documentation page: https://opensource.adobe.com/spectrum-web-components/components/slider
3. Click on thumb of sliders and move them.

#### Platform and Version
Safari Web Browser, v13.0.5

**Comment by Westbrook** [comment]
@mjkobaya this appears to be corrected in #771. Can you take a look at https://westbrook-focusable--spectrum-web-components.netlify.app/components/slider/examples in Safari and let me know if this clears up this issue?
