### ISSUE TITLE
<sp-slider> thumb turns blue after blurring and focusing the page its on.

### ISSUE THREAD

**Issue by mjkobaya** [adobe/spectrum-web-components#517]
### Expected Behaviour
Click thumb on slider and blur the page (click another window) then come back to the page and focus it (switch back to the page but don't click directly on the slider) and the thumb stays the same color.

### Actual Behaviour
Click thumb on slider and blur the page (click another window) then come back to the page and focus it (switch back to the page but don't click directly on the slider) and the thumb turns blue.

<img width="625" alt="Screen Shot 2020-02-28 at 11 03 37" src="https://user-images.githubusercontent.com/7560303/75579132-ff2c5880-5a19-11ea-8ff4-5ebb90c09be7.png">

#### Steps to Reproduce
1. Open https://opensource.adobe.com/spectrum-web-components/components/slider in Chrome or Safari.
2. Click the thumb of the slider.
3. Click on another open window or outside the window to blur the slider page.
4. Click back to the slider page to focus the window but not on the actual slider.

#### Platform and Version
Chrome web browser, v79.0.3945.130
Safari web browser, v13.0.5

**Comment by Westbrook** [comment]
This seems to come from the use of `.is-focused` in the Spectrum CSS, which we convert to the attribute `handle-highlight` which in this specific case is managed directly on the `focus` event on the internal `input [type=range]` element, which doesn't line up directly to the `:focus-visible` interaction that is available on most other focusable UI elements in the library. This also doesn't lineup with the experience that a native `input [type=range]` element provides, which was surprising as I would have expected it a native input to show focus in this context.

I'm not sure that we want to spend any time attempting to mimic the `:focus-visible` polyfill/interaction ourselves as it's pretty fickle. To prevent that we should probably look into altering the application of these styles from being hung off of the `handle-highlight` attribute to relying on something like [`:focus-within`](https://caniuse.com/#search=focus-within). @mjkobaya, does the support (or lack thereof in IE11/pre-Chromium Edge) seem like something we would be able to get away with here?

**Comment by mjkobaya** [comment]
@Westbrook We don't really support IE11 anymore so that wouldn't be an issue. We do however try to support pre-Chromium Edge as best as we can.
