### ISSUE TITLE
<overlay-trigger> Repeatedly clicking on trigger with click-content permanently disables overlay 

### ISSUE THREAD

**Issue by msdewey** [adobe/spectrum-web-components#518]
### Overview

There is a bug where if you use an overlay-trigger, and slot an element into "click-content", and then repeatedly click the "trigger" slotted element in quick succession, it will permanently disable the overlay from appearing.

### Expected Behaviour

 Click-triggered overlays should be able to handle fast repeated clicks.

### Actual Behaviour

 Clicking repeatedly will permanently disable the overlay from appearing.

### Reproduce Scenario (including but not limited to)

`overlay-trigger` with `trigger` slotted element and a `click-content` slotted element

#### Steps to Reproduce

Click repeatedly really fast on the `trigger` element

**Comment by Westbrook** [comment]
This very likely an alternate reproduction of the issue found in #511
