### ISSUE TITLE
On iOS mobile devices, slider behavior is choppy/inconsistent.

### ISSUE THREAD

**Issue by mjkobaya** [adobe/spectrum-web-components#519]
### Expected Behaviour
Using a slider on an iOS mobile touch screen device (iPhones, iPads) should work like it does for a desktop computer.

### Actual Behaviour
Using a slider on an iOS mobile touch screen device (iPhones, iPads) doesn't work very consistently or smoothly. Touching the thumb and sliding it sometimes moves the thumb but sometimes it doesn't. And sometimes does move but then it stops moving while it's being dragged along the slider track.

#### Steps to Reproduce
1. Open https://opensource.adobe.com/spectrum-web-components/components/slider on an iOS mobile touch screen device (ie. and iPad or and iPhone). It's important it's an actual device and not a simulator.
2. Try dragging the thumb piece along the slider track.

**Comment by benjamind** [comment]
Took a quick look at this, it also occurs on windows touch devices, I believe any touch device will actually do this.

Whats happening is the pointer event is being handled by the browser to interpret pan/zoom gestures. This triggers a pointercancel event which causes the handle to be released.

Simple fix is to add `touch-action: none` to the `#handle` element in the slider css.

**Comment by mjkobaya** [comment]
Ah okay thank you for looking into that!

**Comment by Westbrook** [comment]
Updated. Sorry for the delay. Let us know if you run into any further issues here.
