### ISSUE TITLE
[RFC] `sp-theme` "default" resolution

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#532]
### Expected Behaviour
The `default` values for the `color` and `scale` in `sp-theme` should not be `const`. This would allow for sites not to have to ship "light" and "medium" in that case that they aren't actively used in their designs.

### Actual Behaviour
The `default` values are `const` and can cause errors (particularly in overlays) when attempting to resolve those values in `Theme.themeFragments`. 

## Proposal
Right now all the theme fragments are packed into `Theme.themeFragments` as `{ kind, styles }`, which means that it is difficult to discern how many fragments of a specific `kind` are available at any one time. This currently looks like the following when registering a fragment:
```
static registerThemeFragment(
        name: FragmentName,
        kind: FragmentType,
        styles: CSSResult
    ): void {
        this.themeFragments.set(name, { kind, styles });
    }
```
I'd like to move to a two dimensional map so that it looks more like:
```
static registerThemeFragment(
        name: FragmentName,
        kind: FragmentType,
        styles: CSSResult
    ): void {
        const kindFragments = this.themeFragments.get(kind);
        kindFragments.set(name, styles);
        if (kindFragments.size === 1) {
             kindFragments.set('default', styles);
        }
    }
```
Which would allow us to use the first available styles as the `default` while also offering a user customizable `default` at the same time.

### Side effects
I believe that in regards to the current functionality that this would be 100% an implementation change and that elements that leverage this functionality would go unaffected by the change. However, the following added functionalities would then be available:
- dynamically attainable `default` (automatic and explicit)
- the ability to register new `kind`s of fragments. we'd have the ability to loop through the `kind` dimension and acquire a `default` for each of those. it might be worth thinking about how to manage multiple options in those `kind`s.

### Open questions
- do we want to focus on expanding the `kind` functionality at this time or at a later date?
- currently the `default` values are exported, but I can't find anywhere that they are used, is there functionality that is expected there that we should continue to support?

### Alternatives
We could go without the larger revision here by updating:
```
export const DefaultColor = 'light';
export const DefaultScale = 'medium';
```
to 
```
export let DefaultColor = 'light';
export let DefaultScale = 'medium';
```
and then managing this in `registerThemeFragment` a la:
```
static registerThemeFragment(
        name: FragmentName,
        kind: FragmentType,
        styles: CSSResult
    ): void {
        this.themeFragments.set(name, { kind, styles });
        if (this.kind === 'color') DefaultColor = DefaultColor || name;
        if (this.kind === 'scale') DefaultScale = DefaultScale || name;
    }
```
It's a much smaller lift, but I think it's less flexible over the course. 

Thoughts?

**Comment by adixon-adobe** [comment]
My 2 cents is that your alternative seems like a really simple change to make now.

If there's not a pressing need for adding new `kind`s then I'd say adding that flexibility now might just be adding unnecessary complexity to the library (albeit not much).

That said, I'm not sure I've got my brain fully wrapped around the overlay issues you're seeing, and this is not code I'm familiar with. Would you mind sharing an example of DOM hierarchy that can cause problems with the defaults?

**Comment by benjamind** [comment]
I do not believe the default values should be exported, and I'm more infavor of the proposed change than the alternatives. It shouldn't be much code change right?

I think longer term we should probably take a step back and look at if this theme fragment and lifting approach that we're doing for overlays is the right solution overall. It might be introducing more complexity than is needed, but it'll be easier to analyze that after we've got some more miles on this.

So for now yeah this seems reasonable.

**Comment by Westbrook** [comment]
@adixon-adobe I've added an implementation of the two-dimensional map to this #540 so you can check out the complexity therein. It's a little more than I fully understood going in, and that complexity would need to be similarly addressed in the "Alternative" solution above. Particularly, I wasn't fully aware of how the no shadow DOM support worked until actually making the change.

It would also be great to hear from @cuberoot as he brought this pattern to life, originally.
