### ISSUE TITLE
Add Spectrum Dialog Pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#565]
### Expected Behaviour
https://opensource.adobe.com/spectrum-css/components/dialog/ should be available in the library

### Actual Behaviour
missing

#### The future
![image](https://user-images.githubusercontent.com/1156657/77563194-53025400-6e97-11ea-9438-916d4164cb5b.png)

**Comment by Westbrook** [comment]
Checking in on API desires for this element as it's got a lot going on and there are a number of ways to support it. If we were to take a straight JSX to DOM conversion of the version in React Spectrum, the main part of our API would look roughly like:
```
<sp-dialog
    title="Dialog title"
    confirm-label="Keep Both"
    secondary-label="Replace" 
    cancel-label="Cancel"
    footer="Content for footer"
    @confirm=${confirm}
    @secondary=${secondary}
    @cancel=${cancel}
>
    Content of the dialog
</sp-dialog>
```
Packing all of those attributes up into the element would give us a lot of flexibility over the way things get rendered, specifically taking into account that the set of buttons display inside the footer normally, but inside of the header when in one of the two fullscreen modes. However, it would severely reduce a users ability to customize the interaction with the dialog.

This would generally materialize as follows. If they wanted to set non-string values for any of the content properties (e.g. `title`, `confirm-label`, `cancel-label`, etc.), they would be SOL; the buttons wouldn't be able to accept icons, the footer content would always be a single string without links, etc. In the case that the interaction required `disabled` buttons for whatever reason, they'd also be out of luck. To enable these sorts of realities, I propose a predominately `slot` based API, a la:

```
        <sp-dialog open size="alert">
            <div slot="hero" style="background-image: url(${landscape})"></div>
            <h2 slot="title">Enable Smart Filters?</h2>
            Smart filters are nondestructive and will preserve your original
            images.
            <sp-button variant="secondary" slot="button">Cancel</sp-button>
            <sp-button variant="cta" slot="button">Enable</sp-button>
        </sp-dialog>
```

While this puts the onus on the user to ensure that the various buttons are set to the appropriate `variant` as per the Spectrum specification, it would greatly free them to do just about whatever they'd want with the various pieces of content. We would also support the `mode` attribute, like the React implementation, to support moving the buttons while in fullscreen:

```
        <sp-dialog open mode="fullscreenTakeover">
            <div slot="hero" style="background-image: url(${landscape})"></div>
            <h2 slot="title">Enable Smart Filters?</h2>
            Smart filters are nondestructive and will preserve your original
            images.
            <sp-button variant="secondary" slot="button">Cancel</sp-button>
            <sp-button variant="cta" slot="button">Enable</sp-button>
        </sp-dialog>
```

In this way we'd be able to support all of the internal preparations of the `dialog` pattern from a visual/structural perspective. From there, I can look into leveraging some form of the research Ben has been putting into dialogs in https://benjamind.github.io/wc-overlay/

**Comment by benjamind** [comment]
Definitely down for the slot approach. However it does run the risk of users not maintaining correct styling and having to hookup behavior for cancel/close buttons I think?

I'm wondering if we have like the basic dialog implementation which is slot based and open for customization in this way, and then the attribute driven version too which internally just uses the slot version but also enforces style and behavior as spectrum mandated. This way we get the really simple to use form, and the fully flexible form and it shouldn't be much additional work?

**Comment by Westbrook** [comment]
First, the eas(y/ier) part, for behavior binding, are you also seeing the two versions as being?
```
<sp-dialog
    @confirm=${confirm}
    @secondary=${secondary}
    @cancel=${cancel}
></sp-dialog>
```
or
```
<sp-dialog>
    <sp-button @click={cancel} variant="secondary" slot="button">Cancel</sp-button>
    <sp-button @click={secondary} variant="cta" slot="button">Primary</sp-button>
    <sp-button @click={confirm} variant="cta" slot="button">Enable</sp-button>
</sp-dialog>
```
Want to make sure we're seeing the same risks and I'm not missing an order of complexity here beyond the idea that you have the as many as three `sp-button` elements that the listeners are placed on rather than placing the equivalent listener on the `sp-dialog`.

**The less straight forward part**
I do like the idea of using an API that can rely on a little bit of both, thought there is some complexity that we'd want to work out before fully committing to that path. Please let me know if you have thoughts on some other patterns, but from my experience, we'd either need to use an "attributes then slots" pattern that looked like the following and I would mark as more idiomatically "web component":
```
<slot name="title"><h2 class="title">${this.title}</h2></slot>
```
or a "slots then attributes" pattern that looked like this:
```
${this.title
    ? html`<h2 class="title">${this.title}</h2>
    : html`<slot name="title"></slot>
}
```
Both of which cause issues in the way that we process the Spectrum CSS output. When encountering code like:
```
.spectrum-Dialog-title {}
```
and processing it to either:
```
::slotted([slot='title']) {}
```
or
```
.title {}
```
We would have to manually mange one of the versions or extend `yarn process-spectrum` to convert single selectors twice. This is something that is lightly discussed in #581, and while it is definitely a good bit of work and debugging would point to a number of other added possibilities in our CSS processing.

Or, we would need to leverage a template pattern like what we find in https://github.com/adobe/spectrum-web-components/blob/master/packages/card/src/card.ts#L44 which cheats a little because one or the other approach suffers from a tag stacking or tag missing issue. For example, we could place the expected `<h2>` internal of the template, like:
```
<h2 class="title">
    <slot>${this.title}</slot>
</h2>
```
Where a user slotting a `<h2 slot="title">` would get two `<h2>` elements.

Alternately, we could expect an `<h2>` in the slot, like:
```
<div class="title">
    <slot>${this.title}</slot>
</div>
```
Where a user relying on the attribute would be sans `<h2>` all together.

There are also a couple of options where we relying on properties instead of attributes, but I'm remiss to suggest a process that relies on imperative code or more heavily on the use of `lit-html` directly.

I'll take a high level thought pass on what it might look like to refactor the approach to `yarn process-spectrum`, but the scope of work there likely points to us shipping a single version (attributes or slots) and then extending the dialog to support both at a later date.

Thoughts?
