### ISSUE TITLE
Add Spectrum Search Within Pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-web-components#567]
### Expected Behaviour
https://opensource.adobe.com/spectrum-css/searchwithin.html should be available in the library

### Actual Behaviour
missing

#### The future
![image](https://user-images.githubusercontent.com/1156657/77563493-bb513580-6e97-11ea-919d-05709bfa19e2.png)

**Comment by hunterloftis** [comment]
Closing, as this pattern has been deprecated.
