### ISSUE TITLE
Order of events is inconsistent for Spectrum Slider

### ISSUE THREAD

**Issue by andrewhatran** [adobe/spectrum-web-components#576]
### Expected Behaviour
```
<sp-slider 
    @pointerdown=${ ... } 
    @input=${ ... }
></sp-slider>
```

When the track of the slider is moused down, the `pointerdown` handler should fire before the `input` handler.

### Actual Behaviour

The `input` handler will fire first

### Reproduce Scenario (including but not limited to)
1. Attach a `pointerdown` and `input` handler to a `<sp-slider>`. Add a log message to both.
2. Mouse down on the track of the slider 
3. Examine the ordering of the log messages

#### Sample Code that illustrates the problem
1. Within the shadowDOM of sp-slider, there’s a `pointerdown` handler on the `controls` element

```
<div id="controls" @pointerdown=${this.onTrackPointerDown}>
     <div class="track"></div>
     ${this.renderHandle()}
</div>
```

2. `onTrackPointerDown` will synchronously update the slider's `value` which will cause the `sp-slider` to dispatch an `input` event.

```
    private dispatchInputEvent(): void {
        const inputEvent = new Event('input', {
            bubbles: true,
            composed: true,
        });

        this.dispatchEvent(inputEvent);
    }
```

3. The `input` even will dispatch from `sp-slider` before the original `pointerdown` event has gotten a chance to bubble up

**Comment by Westbrook** [comment]
Fixed in #589
