### ISSUE TITLE
Cannot select component in docs on Edge

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#628]
### Expected Behaviour

Clicking on a component in the sidenav should take you to the page

### Actual Behaviour

In Edge, clicking on components in the sidenav doesn't do anything

#### Steps to Reproduce

Go to https://opensource.adobe.com/spectrum-web-components/ and click on a component in the sidenav

#### Platform and Version

Pre-chromium versions of Edge

**Comment by Westbrook** [comment]
Pretty sure that this is related to our use of `inert`. Check out the difference between its use in this research branch https://github.com/adobe/spectrum-web-components/blob/westbrook/11ty/projects/documentation/src/components/layout.ts as opposed to master https://github.com/adobe/spectrum-web-components/blob/master/documentation/src/components/layout.ts
