### ISSUE TITLE
The tab-list component throws an error on Edge

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#630]
### Expected Behaviour

The `sp-tab-list` should work on pre-chromium Edge with the correct polyfills

### Actual Behaviour

The `sp-tab-list` throws an error because it assumes that `document.fonts.ready` exists

#### Steps to Reproduce

Just load the docs in Edge: https://opensource.adobe.com/spectrum-web-components/

#### Platform and Version

Pre-chromium Edge on Windows

**Comment by Westbrook** [comment]
Fixed by #632
