### ISSUE TITLE
Dropdown menu doesn't constrain to visible window

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#645]
### Expected Behaviour

Dropdowns should shrink in order to keep all of the elements on on the screen.

### Actual Behaviour

Dropdowns with lots of options trail off the screen

<img width="1464" alt="Screen Shot 2020-04-24 at 10 35 22 AM" src="https://user-images.githubusercontent.com/154097/80156271-9fb48880-8617-11ea-9f3a-b4d0c2d71812.png">

#### Steps to Reproduce

1. Create an `sp-dropdown` with lots of items
2. Constrain your browser window to be short enough to cause overflow

#### Sample Code that illustrates the problem

https://webcomponents.dev/edit/7DLgYGoRTdZIlJHhSVfg

@Westbrook stole one of your projects as a template. Super cool.

**Comment by cuberoot** [comment]
This is a blocker for LrWeb using `sp-dropdown`

**Comment by Westbrook** [comment]
Published 5 days ago, ha! https://www.npmjs.com/package/popper-max-size-modifier Can it just be _that_ easy?

**Comment by cuberoot** [comment]
Man, those guys rock. It's like they fix issues before I can log them. I will take it for a spin and see if it solves the issue.

**Comment by Westbrook** [comment]
Partial work towards leveraging this with discussion points around the location/sizing of the overlay content: https://github.com/adobe/spectrum-web-components/pull/646

**Comment by FezVrasta** [comment]
> Man, those guys rock. It's like they fix issues before I can log them. I will take it for a spin and see if it solves the issue.

We are on OpenCollective by the way 🥰
