### ISSUE TITLE
It's hard to click to the start/end values of a slider

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#653]
### Expected Behaviour
You should be able to click anywhere on the track to set the value.

### Actual Behaviour
The hitbox doens't go to the edge of the slider, so it's hard to click min/max values.

#### Steps to Reproduce
Try clicking just at the beginning/end of a slider on the doc page.

**Comment by Westbrook** [comment]
It actually looks like the element you interact with for the click interaction doesn't even go to the left/right edge of the track:

![image](https://user-images.githubusercontent.com/1156657/80618207-08817380-8a11-11ea-876e-6893835d658d.png)

React-Spectrum v3 hasn't added this pattern yet, but v2 has this pattern and it exhibits the same behavior. We should bring this up with Spectrum CSS.

**Comment by adixon-adobe** [comment]
Sounds good -- I'll file an issue there.

**Comment by adixon-adobe** [comment]
I also updated the issue, since after reviewing it I don't think we need to actually allow clicking outside the track, just making sure you can actually click to the edge.

**Comment by Westbrook** [comment]
Corrected in `latest`.
