### ISSUE TITLE
Quiet variant of sp-dropdown not documented

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#663]
### Expected Behaviour
Documentation has the quiet variant included as it's already implemented 

### Actual Behaviour
https://opensource.adobe.com/spectrum-web-components/components/dropdown doesn't include the quiet variant.

**Comment by Westbrook** [comment]
Great point!

I'd really love to see if we could get a more complete representation of `@spectrum-css/dropdown/metadata/dropdown.yaml` (but for each package) included in all of our demonstration pages as part of what seems to be a broader review you're doing here. It's not always 100% possible, and is some cases a lot of work, but I've been attempting to do this with some of the more recently added packages.

**Comment by adixon-adobe** [comment]
Yep -- I'm just filing issues as I come across them right now to make sure they're tracked, but an overall audit would probably be good too.

I've also been thinking either a demo app or a suite of codepen/jsfiddle examples would be nice as a future/next level upgrade to the docs (and a great intern project if there are any candidates).

**Comment by Westbrook** [comment]
I like this a lot! I had had similar thoughts about something like: https://webcomponents.dev/org/open-wc?collection=demos-lit-1-basic but for our components! There could also be benefit in adding a page to the docs site about how the docs site it made in that it is made with our components...
