### ISSUE TITLE
sp-menu-item doesn't document value attribute

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#664]
### Expected Behaviour
sp-menu-item documentation includes <sp-menu-item value='val'> examples.

### Actual Behaviour
There aren't any examples here: https://opensource.adobe.com/spectrum-web-components/components/menu-item

**Comment by adixon-adobe** [comment]
I think it'd be nice to have the value example in the `sp-menu` page too, just because that's the first place I'd expect folks to look (even if it's not really documented there, just seeing examples with more of the possibilities in sp-menu seems like it'd be useful).

On the sp-menu-item page you also only mention value affecting `sp-action-menu`, but it also affects `sp-dropdown` (and that's the more likely place you'll want to use it).

**Comment by Westbrook** [comment]
Released.
