### ISSUE TITLE
sp-dialog docs aren't responsive

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#671]
### Expected Behaviour
The dialog examples should look nice on small screens and small widths.

### Actual Behaviour
When you resize your browser narrower or view on a 360px wide (in css-pixels) device, the examples scroll horizontally. It looks like the actual dialog is responsive to the browser width (YES!), but the docs could use a little tweaking to show this off better.

**Comment by Westbrook** [comment]
I've been working a little on a different version of the docs, can you confirm whether this is what you'd expect? https://5eb9eab94fffda00076d87cc--spectrum-web-components.netlify.app/components/dialog/ I see room to do more but wanted to see if this hits a "baseline support" yet or not.

**Comment by adixon-adobe** [comment]
That's definitely better, but doesn't quite resolve this issue since the padding in the docs is a little to high at 360px wide (so the examples still scroll horizontally when I test in the Chrome mobile debugger at that width).

**Comment by Westbrook** [comment]
Do you think we should be making the override in the demo (similar to the `force-inline` application) or in our CSS or in an issue up to Spectrum CSS?

**Comment by adixon-adobe** [comment]
We should take a look with your changes & my overall responsive changes.

Since Spectrum CSS has similar issues with their examples, I think pushing remaining issues up to them would be good.
