### ISSUE TITLE
Scrollable quiet dropdown menu items can wrap

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#696]
### Expected Behaviour
Menu items don't wrap when the menu is open.

### Actual Behaviour
On some browsers menu items can wrap to multiple lines when there's a scrollbar.

### Reproduce Scenario (including but not limited to)
Create an `<sp-dropdown quiet>` with enough menu items to scroll.

#### Platform and Version
Mac Safari, Mac Firefox, Win Firefox, Win Edge, Android Chrome, iOS Safari.

#### Screenshot

<img width="95" alt="bad-wrap" src="https://user-images.githubusercontent.com/48841507/82489965-20946200-9aa8-11ea-8def-81f5ac192abc.png">

**Comment by adixon-adobe** [comment]
I'm not sure if this is actually an issue with `sp-menu` or `sp-dropdown`. I also haven't tested non-quiet dropdowns with more text, but I wouldn't be surprised if there's an issue there too.

**Comment by Westbrook** [comment]
Can be recreated from https://webcomponents.dev/edit/Kdl7AdljWsWE3Q74qJ8f

When not leveraging `quiet` rules around `min-width` are applied that prevent this from occurring. It might be necessary to discuss applying a min-width to the quiet case with the Spectrum team as well.
