### ISSUE TITLE
A really long dropdown can grow the page size on touch scroll

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#697]
### Expected Behaviour
If you scroll down with a very long dropdown open, you can bounce the bottom of the page with touch scroll.

### Actual Behaviour
Looks like something about the popper libraries is taking up the bounce space when you touch scroll and growing the height of the page (at least on our test page).

Possible this is a subtle browser bug in Safari.

#### Platform and Version
Mac Safari, iOS Safari (possibly more but might be Safari specific).

#### Screenshots

<img width="966" alt="page-bottom-mac-safari" src="https://user-images.githubusercontent.com/48841507/82491801-c6e16700-9aaa-11ea-8fb6-4b4146154411.png">

<img width="694" alt="after-touch-scroll" src="https://user-images.githubusercontent.com/48841507/82491814-ccd74800-9aaa-11ea-8543-89cc8caceb6d.png">

**Comment by adixon-adobe** [comment]
There's a separate/related issue where if you open a scrollable dropdown menu and scroll to the bottom with a touchpad or scroll wheel, it'll keep scrolling the page once it hits the bottom. I can't remember if there's actually a way to prevent that though.

**Comment by najikahalsema** [comment]
@adixon-adobe Could you retest this issue and confirm whether this still happens?

**Comment by Westbrook** [comment]
Closing as unable to repro, please feel free to reopen or open a new issue with more information in the future.
