### ISSUE TITLE
Action button with icon/text looks wrong on pre-chromium Edge

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#699]
### Expected Behaviour
Action button looks reasonably close to other browsers on pre-chromium Edge (with polyfills)

### Actual Behaviour
There's no padding between the icon & text, which looks pretty bad.

### Screenshots
<img width="857" alt="action-button-edge" src="https://user-images.githubusercontent.com/48841507/82578627-3d856f80-9b52-11ea-893c-d9e22405c81c.png">

**Comment by cuberoot** [comment]
The ShadyDOM polyfill doesn't handle [styles applied to slots](https://github.com/adobe/spectrum-web-components/blob/master/packages/button/src/spectrum-action-button.css#L66-L83). It's a bit tricky to work around that with a combinator rule that works with the slot. I will have to ponder a bit

**Comment by adixon-adobe** [comment]
It's probably something we can live with if it's hard to fix, but if you think of something...

**Comment by Westbrook** [comment]
I could find a way to being OK with a manual fix a la:
```
#label:not(:first-child) {
    /* .spectrum-ActionButton .spectrum-Icon+.spectrum-ActionButton-label,
   * .spectrum-Tool .spectrum-Icon+.spectrum-ActionButton-label */
    padding-left: var(
        --spectrum-actionbutton-icon-padding-x,
        var(--spectrum-global-dimension-size-85)
    );
    padding-right: calc(
        var(
                --spectrum-actionbutton-text-padding-x,
                var(--spectrum-global-dimension-size-150)
            ) -
            var(
                --spectrum-actionbutton-icon-padding-x,
                var(--spectrum-global-dimension-size-85)
            )
    );
}
```
Or similar to support addressing this if you can't think of a clever PostCSS way to make this nicer. I'd thought about a way to change the processing to allow this sort of rule to be defined multiple ways, but that's definitely a bigger lift.

**Comment by cuberoot** [comment]
We are just discussing on our team this and it raises the higher-level question of how hard should we work to make a dying platform look good. I am reluctant to  support too many custom css work-arounds specifically for pre-chromium Edge. I am tempted to punt on this one unless we can find something really neat and clean. This by itself is definitely not worth the bigger lift.

**Comment by cuberoot** [comment]
That being said, maybe Spectrum-CSS should be using `#label:not(:first-child)`?

**Comment by Westbrook** [comment]
@cuberoot and @adixon-adobe with this being featured in pretty old browsers at what point can me move this to "will not fix"?

**Comment by adixon-adobe** [comment]
Yes.
