### ISSUE TITLE
Css variables should be displayed in the documentation of all components

### ISSUE THREAD

**Issue by andrewhatran** [adobe/spectrum-web-components#71]
### Expected Behavior
The documentation of our components should also display the css-variables used in that component's styling. This is so users of the components can easily restyle the component.

web-component-analyzer comes with css-variable extraction built in.

### Actual Behavior
css-variables are currently not presented in the documentation

**Comment by Westbrook** [comment]
Requirements for a final solution:
- dynamically generated from the Spectrum CSS (and/or Spectrum DNA) input
- doesn't negatively effect readability or usability of the component TS files
- attempts to "resolve" the CSS Custom Properties to a human readable value

I've created https://github.com/adobe/spectrum-css/issues/459 to see if the Spectrum CSS team is interested in more in depth support of this sort of offering at their level as well.
