### ISSUE TITLE
<sp-slider> Crashes when tick-step and range aren't divisible

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#726]
### Expected Behaviour
If I give the slider a tickstep of 5, and a max value of 92, the slider should function

### Actual Behaviour
Throws runtime error and slider is un-rendered

### Reproduce Scenario (including but not limited to)
```
<sp-slider
      value="50"
      min="0"
      max="102"
      step="5"
      variant="tick"
      tick-step="5"
      tick-labels
></sp-slider>
```

#### Platform and Version
0.4.8 (in master)

So it's real easy to take care of the error: 
Line 220 of slider.ts can either be:
`const tickCount = Math.floor((this.max - this.min) / tickStep);`
or
`const tickCount = Math.ceil((this.max - this.min) / tickStep);`

The problem is that the next line instantiates an array of length "tickCount".

I'd submit a PR myself, but I don't know the design considerations. The suggested fix above, simply adjusts the tick count and makes the length of the slider not match the track. (I can slide to 102, but that max value looks like 105 or 100 and is labeled as such).

I might think that the last tick is unevenly spread and shows the real max value, but again, that might go against how this is designed.

**Comment by Westbrook** [comment]
Nice catch here! I've love to hear more about the use case by which you ran into this to confirm my suggested path forward below.

Taking into account:
```
      max="102"
      step="5"
```
101 and 102 are technically "invalid" values based on the above parameters. My first reaction is that we should lop them off by processing this to `max=100` (as it's technically true). This would be similar to the functionality that you would get now if you used the following parameters:
```
      value="102"
      max="100"
      step="5"
```
In that 102 would be constrained by the max and corrected internally to 100.

Does that feel somewhat expected in the context of using this component? Would this interact with your use case in any negative way?

**Comment by bengfarrell** [comment]
So first of all, I shouldn't have even brought up `step`. Because you're right, I do think that when you called out that first case, anything over 100 isn't valid. 

My issue focuses on `tick-step` only really. 

So my use-case is a side-project for me. And I say this to make sure you know it's not product driven, and maybe I'm using the slider in a way nobody would ever want to use it or would design it this way.

What I'm doing is a timeline scrubber. I want it to be lightweight and simple. The slider really fits the bill here. Since a recorded duration can be an uneven number, I want the `max` value to reflect the true duration of the timeline, and `tick-steps` should be fairly even looking values that aren't too sparse or too compact for the presentation.

As a user scrubs through time, I'd really prefer they land on the last possible value when going all the way to the end. Currently, I've upped the `max` value to be even with the `tick-step`. It works, but it's just weird to be scrubbing through empty keyframes at the end.

In my use case I'd prefer that the last tick mark just wasn't evenly spaced and reflected the true length. But who knows, maybe this wouldn't look/feel right in context and its not the right solution.

I guess what I'm looking for is the slider to not only be interactive but convey how long my data set is at the same time. Adjusting the max value will probably never be perfect here with this in mind. But, if this is just a use-case you don't feel the need to cover, I think adjusting that `max` value beyond what it is so you can scrub through all of the existing keyframes will suffice as I can probably make information regarding the length of the data available on the label or elsewhere

thanks!

**Comment by Westbrook** [comment]
After much adieu this functionality is now available. Let us know if you see any other issues in this area.
