### ISSUE TITLE
Upon closing sp-menu using 'Esc' key, focus is not restored to triggering button

### ISSUE THREAD

**Issue by yalagand** [adobe/spectrum-web-components#727]
### Expected Behaviour
When sp-menu is closed, keyboard focus should go back to triggering button. 
### Actual Behaviour
Keyboard focus is restored properly to triggering button when user selects a menu item but it doesn't happen when user chooses to close the menu using 'Esc' key without selecting an item.

#### Platform and Version
Tested on https://opensource.adobe.com/spectrum-web-components/components/action-menu

**Comment by Westbrook** [comment]
Great timing on this issue! Hopefully the fix in #728 is exactly what you're looking for here.

We've been working through the finer mechanics of the API we'll be applying to make this work in #710 and you can take an early preview at the functionality in https://westbrook-overlay-focus--spectrum-web-components.netlify.app/storybook/iframe.html?id=action-menu--icon-only and https://westbrook-overlay-focus--spectrum-web-components.netlify.app/storybook/iframe.html?id=dropdown--default (action-menu is an extension of dropdown).

**Comment by yalagand** [comment]
Looks good to me!
