### ISSUE TITLE
Standard slider example needs to be labelled

### ISSUE THREAD

**Issue by yalagand** [adobe/spectrum-web-components#739]
URL: https://opensource.adobe.com/spectrum-web-components/components/slider

Please provide a label for Standard variant of slider.
There's a section 'With Label' that has sliders with visible label. Is that supposed to mean we're allowing users to have sliders with no visible label when you say 'Standard Slider'? If yes, how do I label it?

**Comment by Westbrook** [comment]
We attempt to stay as close to the Spectrum CSS documentation as possible, which outlines this distinction. As it was a contribution, it's possible that the documentation here wasn't fully vetted, or that it might get another pass as part of later edits. We should definitely confirm usage there as well being they're the ones outlining the "standard" use as not having a label: https://unpkg.com/browse/@spectrum-css/slider@3.0.0-beta.2/metadata/slider.yml

I would suppose even without the internal label, you _could_ use `aria-label` on the `sp-slider` element and still instill value on the accessibility tree. That being optimal or not is certainly a different question.

**Comment by Westbrook** [comment]
Sliders without labels removed.
