### ISSUE TITLE
should actionButton selected also set aria-pressed?

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#756]
Perhaps this is just a doc issue where we should note that if managing the selected attribute the user should also manage the aria-pressed attribute so the button is read as a toggle button correctly.
I don't think we can do this for them if they aren't using the toggles attribute

**Comment by Westbrook** [comment]
We definitely have some room to manage this for people. Help me understand the situation here.

Should _ALL_ action buttons that are "selected" have the `aria-pressed="true"` attribute? Whether we manage this via `toggles` or it is managed manually, it's hard for me to understand a case where this value is leveraged that doesn't means that `aria-pressed="true"`, but maybe this is a question more appropriately targetted toward the Spectrum specification team.

**Comment by Westbrook** [comment]
Moving to full management of `selected` has some down stream effect on the elements that extend the ActionButton pattern. We'll need to review that dependency chain to see the right places to break/fork the shared features if we really want to support this management in an `sp-action-button`.
