### ISSUE TITLE
Clicking a button, checkbox or switch applies tab-focus styling

### ISSUE THREAD

**Issue by cdvu1** [adobe/spectrum-web-components#770]
### Expected Behaviour
Clicking an element shouldn't change it to the focused styling (an outlined box)

### Actual Behaviour
Clicking it does apply focus styling until you tab or click away.

#### Steps to Reproduce
Clicking a `<sp-button>` , `<sp-checkbox>` or `<sp-switch>` element

#### Platform and Version
Mac 10.15.5, Safari 13.1.1, Firefox 78.0.2

**Comment by Westbrook** [comment]
@cdvu1, thanks for resubmitting this. We never reopened #318 after we had to revert the previous approach to this, but its an important fix to get right. Particularly, the way that the focus targeting the `:host()` element prevent keyboard interactions with the shadow DOM `focusElement` is of particular concern.

I have an idea for a new fix on this, but want to review the previous attempts (and associated issues with their approach) to ensure that we're not releasing a different bug into the library. Roughly, it works like this:

```
        this.focusElement.addEventListener('focusout', () => {
            this.refocusTimeout = setTimeout(() => {
                this.focus();
            });
        });
        this.addEventListener('focusout', () => {
            clearTimeout(this.refocusTimeout);
        });
```
Where as long as the `focusout` event passes through both the `focusTarget` and the `:host()` then the element won't be refocused, but if the focus lands on the `:host()` then we'll explicitly reenact the `focus()` method. There's lots of testing and some perf/event management to look into, but hopefully this gets us to a long term fix for this!

**Comment by Westbrook** [comment]
This is a first pass at those changes, @cdvu1 can you take a look when you have a minute and let me know if this is addressing this issue on your end as well:

https://westbrook-focusable--spectrum-web-components.netlify.app/storybook/iframe.html?id=switch--default
https://westbrook-focusable--spectrum-web-components.netlify.app/storybook/iframe.html?id=checkbox--default
https://westbrook-focusable--spectrum-web-components.netlify.app/storybook/iframe.html?id=button--default

I'll be reviewing this more later today to help ensure that we don't see drawbacks like we had with previous possible fixes.

**Comment by cdvu1** [comment]
@Westbrook I just took a look at those on both Safari and FF. They all looked good to me!
