### ISSUE TITLE
There's no error when using sp-theme without importing a color/scale

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#800]
### Expected Behaviour
It would be nice for newer users to add a console error when trying to use sp-theme and only importing '@spectrum-web-components/theme/sp-theme' (without removing the ability to delay-load or not load them).

### Actual Behaviour
There's no error to indicate you need to load more for it to properly show up. 

#### Sample Code that illustrates the problem
```
import '@spectrum-web-components/theme/sp-theme'
...
return html`
  <sp-theme color="light" scale="large">
  {...}
  </sp-theme>`
```

**Comment by adixon-adobe** [comment]
Offhand I could see adding something like this to suppress errors: `<sp-theme async-load />`

This case is probably a little less important, but I'd guess new clients will reasonably expect the sample code to "just work". The fact that it doesn't is likely to be surprising, and adding some breadcrumbs about it seems reasonable.

**Comment by Westbrook** [comment]
Gathering info in the same place, currently this is what the "easy" usage notes are:

![image](https://user-images.githubusercontent.com/1156657/89216847-25da5680-d599-11ea-8bb6-548cbacea09b.png)

I like how `<sp-theme async-load />` or `<sp-theme defer />` etc. works here. I was playing with similar in a different context that never worked out as I had hoped, but here it might be the best path forward.

**Comment by Westbrook** [comment]
There's also docs that don't say you need both: 

```
<sp-theme color="light">
```

**Comment by Westbrook** [comment]
Relates to #1170

**Comment by Westbrook** [comment]
Looking through the right messaging here, and for each of `theme`, `color`, and `scale` it seems like we can cover this set of realities:
- there is no value for the attribute available
- the value of the attribute is resolving to the _default_ for the application (the first value of that attribute with a fully registered theme fragment, e.g. loaded and usable)
- the value supplies does not have a registered theme fragment
 
By publishing these messages in the Dev Build it seems like it makes sense to publish them all, to ensure that consumers are fully equipped to make decisions for their applications' success.
