### ISSUE TITLE
sp-dropdown async loads active-overlay on open.

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#801]
### Expected Behaviour
Loading a component should load all dependencies needed for it to function by default.

### Actual Behaviour
The default behavior adds network latency to load the overlay script the first time you open a dropdown. On high latency connections this won't be a nice experience. 

While having the option to delay-load the overlay dependencies seems good, it doesn't seem like the right default behavior. I don't think it's expected, and it also adds an extra potential failure case if the async load fails.

**Comment by Westbrook** [comment]
This is a hard "expectation" to meet in that `delay-load` isn't really the sort of functionality to can "add" as much as you can take it away.

> Loading a component should load all dependencies needed for it to function by default.

Can you take a look at #804 to check out some of the longer view I had anticipated for that and the possibilities therein?
