### ISSUE TITLE
What is the purpose of this line?

### ISSUE THREAD

**Issue by morganbarrett** [adobe/spectrum-web-components#802]
[https://github.com/adobe/spectrum-web-components/blob/331149d0f15d22e841968592043137f10bf00238/packages/overlay/src/overlay-stack.ts#L172](https://github.com/adobe/spectrum-web-components/blob/331149d0f15d22e841968592043137f10bf00238/packages/overlay/src/overlay-stack.ts#L172
)
I only ask because it adds an extra weird chunk in webpack builds, so I had a poke around and traced it back to this dynamic import, that is already imported? 😕

**Comment by Westbrook** [comment]
@morganbarrett, thanks for reaching out. It's great timing as we're discussing this same line in #801. In support of both conversations, please checkout https://github.com/adobe/spectrum-web-components/pull/804 and let me know what you're thoughts are on the possibility of a slightly larger, hopefully more useful check, as well as the documentation/examples available around how to choose not to have that in webpack/rollup contexts.

**Comment by Westbrook** [comment]
This is interesting:
```
new webpack.IgnorePlugin( /^\.\.\/active\-overlay\.js$/, /\@spectrum\-web\-components\/overlay/ )
```
But, I can't seem to get it to do what I think you've done. Even with it included a webpack build still segments off that small chunk.

Are you using the component that relies on this directly or are you leveraging `@specrum-web-components/bundle/elements`?

**Comment by morganbarrett** [comment]
Yeah, I'm just importing `@spectrum-web-components/bundle`

**Comment by Westbrook** [comment]
Strange that `@spectrum-web-components/bundle` would work appropriately with that file excluded... 🤔 I'll continue my research with this info, but unless you explicitly include `@specrum-web-components/bundle/elements` the `IgnorePlugin` settings _should_ be removing important side effects when opening overlays or dropdowns, etc. 

Generally, as outlined in the docs for that package: https://opensource.adobe.com/spectrum-web-components/components/bundle, while good for prototyping, I don't think you're going to get the highest quality build when moving to production with this technique. Thanks for beating the bushes on it, however, as getting these specific cases clarified is gonna be helpful for future users.

**Comment by morganbarrett** [comment]
Just to note, I'm now importing `@spectrum-web-components/overlay/active-overlay.js`, `@spectrum-web-components/overlay/overlay-trigger.js` with no apparent issues to the functioning of the packages.

**Comment by Westbrook** [comment]
Thanks Morgan. That's in line with the documentation/helper code we're looking to vend in the future to make this clearer. Good luck with your project. If you get to a place where it's sharable, we'd love to see what you've been working on!
