### ISSUE TITLE
Overlay stack breaks `body` height 100%

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#803]
### Expected Behaviour
If you have `height: 100%` set on body, child elements can also set `height: 100%`

### Actual Behaviour
The new shadow root added to the overlay stack breaks this. Looks like this was introduced here:
https://github.com/adobe/spectrum-web-components/commit/27a0b53ea94d19bb18b7d3f89763b06dc1b42b59#diff-c3039ae6864cf1ed51034cbdfc4040deR49

#### Sample Code that illustrates the problem
This should show a red background, but doesn't:
```js
import '@spectrum-web-components/overlay/active-overlay.js'
```
```html
<body style="height: 100%">
  <div style="background-color: red; height: 100%">
  </div>
</body>
```

**Comment by adixon-adobe** [comment]
Looks like a `height: inherit` will fix this. I could see the `position: relative` and `z-index: 0` styles causing issues as well.

**Comment by Westbrook** [comment]
For clarity of testing:
```
<body style="height: 100%">
  <div style="background-color: red; height: 100%">
  </div>
</body>
```
Does not full the viewport whether the overlay code is loaded or not as body/html aren't given the whole viewport to fill by default. `100vh` would need to be used on the `body` or the `div` in this case. When applied to the `div`, this issue would be avoided, but when applied to `body` having `height: inherit` seems like a good call. Another option would be to use `height: 100%` which would allow for the element to fill the more complex rules that might come together with use of `min-height`/`max-height`/`height` on the body.

Thoughts?

**Comment by adixon-adobe** [comment]
Would `height: inherit`, `min-height: inherit`, and `max-height: inherit` work? The more this avoids taking over the better.

Also, fwiw it looks like when the body is `position: fixed` the `div#actual` in the shadow DOM is laying out with full height (at least in Chrome). This isn't something I knew the behavior of, and I'm having a little trouble confirming that it's defined behavior, though I'm guessing it is.

**Comment by Westbrook** [comment]
`inherit` is tricky, because id `<body style="height: 50%">` then your page will actually be 25% because of inherit. Whereas, `height: 100%` just fills whatever the `<body>` is set to without further thought. If you don't use the right rules on the `<body>` stays at 0, use 50%, fills that whole space, etc. 

Do you have code, or a screenshot of:
> Also, fwiw it looks like when the body is position: fixed the div#actual in the shadow DOM is laying out with full height (at least in Chrome).
As I understand it, it _should_ happen, but in my mind I may not be seeing what you're looking at.

**Comment by adixon-adobe** [comment]
What I've found is that the new shadow DOM doesn't break this layout, though I was expecting it to once I started digging in:

```
<body style="position: fixed;top=0;left=0;right=0;bottom=0;height:100%">
  <div style="height=100%"></div>
</body>
```

If I add an extra div in the main DOM though like this (similar to what's getting added to the shadow DOM) it does break: https://codepen.io/dixo0015/pen/WNwNvEG

**Comment by Westbrook** [comment]
This is why I think having the `height: 100%` _should_ address this:

https://codepen.io/Westbrook/pen/poyoJdw

The blank `div` in you example will break this because it won't inherit any sizing, and the `height: 100%` in the lowest child will have not context to resolve "100%".

With that addition, the shadow DOM would be roughly equivalent to:
```
<body style="height:100%;position: fixed;top:0;left:0;right:0;bottom:0">
  <div style="position: relative; z-index: 0; height: 100%">
    <div style="background-color:red;height:100%">
    </div>
  </div>
</body>
```

**Comment by adixon-adobe** [comment]
Yeah -- what's weird is that you don't need the `height: 100%` for the fixed case in the shadow DOM on Chrome (that's the part that tripped me up -- "why isn't this broken too?").

I.e. this is broken:
```
<body style="height:100%">
  <shadowdiv style="position: relative; z-index: 0;">
    <div style="background-color:red;height:100%">
    </div>
  </shadowdiv>
</body>
```

But this isn't (which seems weird):
```
<body style="height:100%;position: fixed;top:0;left:0;right:0;bottom:0">
  <shadowdiv style="position: relative; z-index: 0; height: 100%">
    <div style="background-color:red;height:100%">
    </div>
  </shadowdiv>
</body>
```

**Comment by adixon-adobe** [comment]
It does look like `height: 100%`. I still have some concerns that this won't necessarily work for all body styles (I can't think of a way to break it right now, but I'm not convinced there isn't yet either).

I'll run this by a few more folks on my team to see if they can poke any holes in it.

**Comment by Westbrook** [comment]
I did just recently participate in a twitter convo around the "need" for `height: stretch:` where I learned there is much in this area to know, so please do. Later this week, if this is at least iteratively better, we might move forward anyways (if there are no new holes), and then come back to it in the future if we need to.

**Comment by adixon-adobe** [comment]
yes, very much agreed! I'm actually working on a PR to move forward since this might be "fixed, practically speaking", even if it's hypothetically broken for unlikely cases.

**Comment by cuberoot** [comment]
I am a bit amazed at how hard a problem it is to get focus, tabs and all working as you would expect in all places. I cannot thing of a breaking case off the top of my head. I guess we proceed and see how we go!

I cannot remember who said that "everybody should be using web components, but very few people should be writing them," but that seems true.

**Comment by Westbrook** [comment]
@adixon-adobe did this get fully cleaned up with #807 or do we have more work you'd like to see here?

**Comment by adixon-adobe** [comment]
I'll close this out. No one has thought of anything this would break (outside of conflicting web component frameworks).
