### ISSUE TITLE
Can't open a new dropdown while one is open

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#809]
### Expected Behaviour
If you have a dropdown open, and click on another dropdown, the first dropdown closes, and the second opens.

### Actual Behaviour
The first dropdown stays open, and the second flickers open then closes immediately.

### Reproduce Scenario (including but not limited to)
Easy to repro on https://opensource.adobe.com/spectrum-web-components/components/dropdown/examples

**Comment by Westbrook** [comment]
When looking closer at this, it seems like something about the way that webpack is collapsing the asynchrony of the loading process and appending the overlay to the stack earlier than expected... gotta work out the timing in a way that both works in page and in test and I'll have PR together for this, soon.

**Comment by davidjgonzalez** [comment]
@Westbrook any idea if there is a quick way around this? ex. not minify? Or is this something more fundamental how Webpack compiles the code?

**Comment by Westbrook** [comment]
I'm not a super webpack master, but if you can _force_ it to code split at dynamic import boundaries (e.g. `import('./x.js');`) then you _should_ get this performing as expected. In an installed application context, you likely won't be seeing much difference between bundled and unbundled code, so you could just turn off bundling (in theory).

A secondary option is to move to Rollup...

I'm literally looking at this right now, so hopefully I won't be blocking you here much longer.

**Comment by davidjgonzalez** [comment]
Would I only have to break out a single, specific import (ie. the sp-action-menu.js)?  
I should beable to do that ...

**Comment by Westbrook** [comment]
The problem with messing with element internals, though, is they change.

In the current `@latest`, it's this `await import('../active-overlay.js');`. In the coming release (though hopefully we'll fix this issue holistically first), it would be `await import('./overlay.js')`.
