### ISSUE TITLE
No custom-elements.json for sp-dropdown

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#811]
### Expected Behaviour
There should be a custom-elements.json file in 0.6.4 like there was in 0.6.3

### Actual Behaviour
It's gone! https://unpkg.com/browse/@spectrum-web-components/dropdown@0.6.4/

But it was here: https://unpkg.com/browse/@spectrum-web-components/dropdown@0.6.3/

**Comment by Westbrook** [comment]
Can you confirm whether this happened across all of the releases this morning? Not sure what would have prevented it from getting generated, but if it's not systematic that'll give us a lead on where to fix this.

**Comment by adixon-adobe** [comment]
Ahhh - It happened across all releases *except* overlay (and I can see from our lint rules that `active-overlay` was affected too so I think there's less in the overlay custom-elements.json than there should be).

Since so few packages were updated didn't make the broader connection at first.
