### ISSUE TITLE
Action menu defaults icon size/color wrong

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#814]
### Expected Behaviour
The default icon size matches https://opensource.adobe.com/spectrum-css/actionmenu.html and shouldn't change size if there's a label or not. The color should also be the same regardless of whether there's a label or custom icon.

The overall size of the action menu should be 32x32 at normal scale.

### Actual Behaviour
Icon size is much larger with no label at https://opensource.adobe.com/spectrum-web-components/components/action-menu/examples (for both medium & large scales). The color is also different if you have a label or custom icon.

The overall size of the action menu is 48x32 in the icon-only mode.

**Comment by adixon-adobe** [comment]
Possible this will get fixed with the Spectrum CSS 3.0 work. Also easy to work around if you provide your own icon.

**Comment by Westbrook** [comment]
Should indeed be addressed here: https://github.com/adobe/spectrum-web-components/pull/794

The read is that the icon with label was too small and now matches the icon without label due to the update to v3.

**Comment by adixon-adobe** [comment]
Right now I think they're both wrong actually (the doc example with the label uses `xxs` instead of `s`). These should match action button (so 18x18 in medium scale, 22x22 in large).

**Comment by adixon-adobe** [comment]
@Westbrook FYI that it looks like things aren't fully fixed with the SpectrumCSS 3 changes.

I was digging into a separate issue where the icon-only size of sp-action-menu is 48x32 instead of 32x32. This was regardless of whether a custom icon was provided or not.

With the spectrum-css-3 branch, if I provide my own icon it's 32x32, but with the default icon it's 38x32 on the doc pages.

**Comment by Westbrook** [comment]
Thanks for checking. Looks like:
```
<slot name="icon">
    ${MoreIcon({ hidden: this.hasLabel })}
</slot>
```
Should likely be updated to:
```
<slot name="icon">
    <sp-icon size="s">${MoreIcon({ hidden: this.hasLabel })}</sp-icon>
</slot>
```
Or similar, internal to that component... Maybe we should bring up icon sized with Spectrum again?

**Comment by adixon-adobe** [comment]
This is the related issue (it looked like was getting picked up): https://github.com/adobe/spectrum-css/issues/753
