### ISSUE TITLE
sp-menu-item renders too slow for large menus

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#815]
### Expected Behaviour
A dropdown with 200 menu items should load quickly.

### Actual Behaviour
Each menu item takes 1-5ms to render (in Chrome on my MacbookPro). It takes ~400ms to render on my machine.

#### Steps to Reproduce
Create a large dropdown (e.g. a country selector) & profile the page.

**Comment by adixon-adobe** [comment]
I actually have a more abusive case on our test page (a checkbox that switches 20 dropdown to all have 100 items). It takes 4 seconds for the checkbox to check. I was hoping it was more of an issue with over-updating, but following the trace down it leads to a whole lot of this:

<img width="458" alt="lots-of-ms" src="https://user-images.githubusercontent.com/48841507/89552337-a08db680-d7d1-11ea-9d45-5c92728395c8.png">

**Comment by Westbrook** [comment]
I'd been tracking a similar(ish) context in the `<sp-sidenav-item>` elements, both of which handle some context resolutions synchronously in their `connectedCallback`, a la: 

https://github.com/adobe/spectrum-web-components/blob/4af755e7111da12b9ad97caef92ba7713336c470/packages/sidenav/src/SidenavItem.ts#L155-L165

Couple of options that I'd been thinking about are as follows:
- make first render lazy
  - had approached this as directly hacking the initialize functionality in `LitElement`, which I'm not super excited about, but is a possibility
- lazily resolve the value in the event
  - requires a "double render" but shouldn't be an issue in real time with `lit-html` backing up the render
- move to a `MutationOverserver` for top down, instead of bottom up, management of attributes like this
  - a deeper refactor, but likely the most powerful. not sure if mutuation observers works async by default or not. likely still requires the "double render" context

**Comment by Westbrook** [comment]
@adixon-adobe you wouldn't happen to have that `more abusive case` in a code sample that you could easily share, would ya?

**Comment by adixon-adobe** [comment]
Not in an easy to translate way, no, but I think if you use a country list selector sourced from one of these lists you'll be able to test some things out pretty easily: https://gist.github.com/incredimike/1469814

**Comment by adixon-adobe** [comment]
(also, my test page switches over ~16 dropdowns to have 100 items all at once (named `Item 1`, `Item 2`, etc).

**Comment by Westbrook** [comment]
Finally getting the repo into a place where we can fully science this sort of issue. Here we see my working branch where I've got `tachometer` perf testing the local code `<none>` to the most `latest` "remote" version of the library on NPM:
![image](https://user-images.githubusercontent.com/1156657/95754592-485fae80-0c71-11eb-90d5-f29425d03850.png)
For this specific run we see the following HTML:
```
    <sp-menu>
        <sp-menu-group>
            <span slot="header">
                Section Heading
            </span>
            <sp-menu-item>
                Action 1
            </sp-menu-item>
            <sp-menu-item>
                Action 2
            </sp-menu-item>
            <sp-menu-item>
                Action 3
            </sp-menu-item>
        </sp-menu-group>
        <sp-menu-divider></sp-menu-divider>
        <sp-menu-group>
            <span slot="header">
                Section Heading
            </span>
            <sp-menu-item>
                Save
            </sp-menu-item>
            <sp-menu-item disabled>
                Download
            </sp-menu-item>
        </sp-menu-group>
    </sp-menu>
```
Rendered to a page 100 times and then sampled for render performance 50 times against the two versions of the code base. This shows the current code clocking in at about 300ms to render 500 `sp-menu-items`, and the 400 other elements.

The `<none>` run here is using a "lazy" implementation of our focus visible polyfill usage that may help us along the way to more performant versions of a lot of our elements. More testing is needed before that's good to go, but from there, we can spend some time with other optimizations to see about getting the clocking there down even further!

**Comment by Westbrook** [comment]
@adixon-adobe, I'd like to try and outline a path towards a resolution on this issue. I've been addressing the perf testing and wanted to share some of the current results to see what if we've moved in a better direction.

First, I'm looking at an updated version of the picker benchmark, e.g.:
```
const countryList = [
    // ... the list shared from https://gist.github.com/incredimike/1469814
];

measureFixtureCreation(html`
    <sp-picker>
        ${countryList.map(country => html`
            <sp-menu-item>${country}</sp-menu-item>
        `)}
    </sp-picker>
`);
```
Running this directly in our test harness will render this markup 100 times on a page, which accounts for 24900 elements, and show a high end 4617.73ms rendering time on 0.18ms per element:
```
┌─────────┬────────────┬───────────────────────┬──────────────────────┬──────────────────────┐
│ Version │ Bytes      │              Avg time │            vs remote │                  vs  │
├─────────┼────────────┼───────────────────────┼──────────────────────┼──────────────────────┤
│ remote  │ 714.90 KiB │ 4429.52ms - 4574.31ms │                      │               unsure │
│         │            │                       │             -        │            -3% - +1% │
│         │            │                       │                      │ -144.77ms - +65.12ms │
├─────────┼────────────┼───────────────────────┼──────────────────────┼──────────────────────┤
│ <none>  │ 728.33 KiB │ 4465.77ms - 4617.73ms │               unsure │                      │
│         │            │                       │            -1% - +3% │             -        │
│         │            │                       │ -65.12ms - +144.77ms │                      │
└─────────┴────────────┴───────────────────────┴──────────────────────┴──────────────────────┘
```
Isolating this test to one 249 element render via:
```
measureFixtureCreation(html`
    <sp-picker>
        ${countryList.map(country => html`
            <sp-menu-item>${country}</sp-menu-item>
        `)}
    </sp-picker>
`, { numRenders: 1 });
```
We see peak render times at 75.53ms for the 249 elements or 0.3ms per element:
```
┌─────────┬────────────┬───────────────────┬───────────────────┬───────────────────┐
│ Version │ Bytes      │          Avg time │         vs remote │               vs  │
├─────────┼────────────┼───────────────────┼───────────────────┼───────────────────┤
│ remote  │ 714.92 KiB │ 73.32ms - 73.97ms │                   │            unsure │
│         │            │                   │          -        │         -3% - +0% │
│         │            │                   │                   │ -1.94ms - +0.04ms │
├─────────┼────────────┼───────────────────┼───────────────────┼───────────────────┤
│ <none>  │ 728.34 KiB │ 73.66ms - 75.53ms │            unsure │                   │
│         │            │                   │         -0% - +3% │          -        │
│         │            │                   │ -0.04ms - +1.94ms │                   │
└─────────┴────────────┴───────────────────┴───────────────────┴───────────────────┘
```

### LIt@2.0
The performance here shares roughly the same benefits as seen generally from the upgrade to `lit@2` in #1401. When testing the country picker, we see a 2-9% performance benefit vs the production version in both the 100 instance render:
```
┌─────────┬────────────┬───────────────────────┬─────────────────────┬─────────────────────┐
│ Version │ Bytes      │              Avg time │           vs remote │                 vs  │
├─────────┼────────────┼───────────────────────┼─────────────────────┼─────────────────────┤
│ remote  │ 714.72 KiB │ 4388.92ms - 4488.70ms │                     │              slower │
│         │            │                       │            -        │            6% - 10% │
│         │            │                       │                     │ 261.82ms - 391.76ms │
├─────────┼────────────┼───────────────────────┼─────────────────────┼─────────────────────┤
│ <none>  │ 599.86 KiB │ 4070.40ms - 4153.64ms │              faster │                     │
│         │            │                       │             6% - 9% │            -        │
│         │            │                       │ 261.82ms - 391.76ms │                     │
└─────────┴────────────┴───────────────────────┴─────────────────────┴─────────────────────┘
```
And the single instance render:
```
┌─────────┬────────────┬───────────────────┬─────────────────┬─────────────────┐
│ Version │ Bytes      │          Avg time │       vs remote │             vs  │
├─────────┼────────────┼───────────────────┼─────────────────┼─────────────────┤
│ remote  │ 714.74 KiB │ 73.92ms - 75.56ms │                 │          slower │
│         │            │                   │        -        │         2% - 9% │
│         │            │                   │                 │ 1.34ms - 6.39ms │
├─────────┼────────────┼───────────────────┼─────────────────┼─────────────────┤
│ <none>  │ 599.88 KiB │ 68.49ms - 73.27ms │          faster │                 │
│         │            │                   │         2% - 9% │        -        │
│         │            │                   │ 1.34ms - 6.39ms │                 │
└─────────┴────────────┴───────────────────┴─────────────────┴─────────────────┘
```

## Possible solutions
In "real world"-like situations the addition of this size of a list to a picker does take time. Here we see it take ~230ms (still less than 1ms an element) in this demo: https://webcomponents.dev/edit/BoakI9TW8OBJ9FufuDzc/src/index.ts
![image](https://user-images.githubusercontent.com/1156657/117446467-1ca45e80-af0a-11eb-99bb-bccc0485711b.png)

To address these sorts of use the Lit team has recently committed to researching a "lazily rendering directive" via this issue: https://github.com/lit/lit/issues/1845. However, I think this would be less about the individual items and more about an approach to adding a large amount of items at a time. The ability to append items in chunks does seem like a quality addition _generally_ and look forward to where that conversation take us.

We could take a look at this approach and pair it with the idea that an `sp-menu-item` is either most (or in a determinable heuristic, always) not visible by default. In that way, we could move lazy rendering into the element itself if the above numbers are still performing outside of acceptable bounds. In that the same number of `HTMLUnknownElements` being rendered into the above demo take 7ms vs 230ms there are certainly benefits to be had, whether we can get them without twisting ourselves about is a separate question.
