### ISSUE TITLE
Get Radio Group value

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-web-components#829]
### Expected Behaviour
Just upgraded to 0.3.2. It used to be that I could get the `value` property of `<sp-radio-group>`. My use-case was on a `@change` event, where I would get `event.target.value`

### Actual Behaviour

After upgrading, `value` was no longer defined. Though the `selected` attribute is given as an example in the markup, the API section in the docs lists `value` but not `selected`.

This is super-nitpicky, but had me scratching my head for a couple minutes while reading the docs and not getting help. Using the `selected` property IS kinda obvious given that it's the attribute I'm using.

I'm not sure if this is a regression (you intended to keep `value` working) or just an artifact of the documentation just covering the `sp-radio` API but no `sp-radio-group` and the API diverging a bit over the course of time.

Like I said, super nitpicky, but just reporting to help! Feel free to close this issue if you're like...whatever Ben :)

#### Platform and Version
0.3.2

**Comment by Westbrook** [comment]
There are a couple of realities herein that are on the list to get sorted. Thanks for reporting, as an actual user of the docs I'll probably be reaching out to you a couple times over the process to ensure we get this situation updated to best support everyone.

1. `<sp-radio-group>` isn't _technically_ listed in the documentation right now. https://opensource.adobe.com/spectrum-web-components/components/radio/api references the API of `<sp-radio>`. This is a side effect of our merging some of the packages together for simplicity, and it more a formality to correct than anything else, I'll make sure to get doing that work prioritized.
2. `<sp-radio-group>` previously did not dispatch it's own `change` event. In that way, the `change` event you would have been listening for previously would likely have been from `<sp-radio>`, but even that's a little awkward in that there is a `change` event from both the `<sp-radio>` element and the `<input>` element internal to it. With the addition of a change event of `<sp-radio-group>` would you think it a good idea to do something with the child elements' events? We could `stopPropagation()` them, for instance.
3. Taking the above into account, you _should_ be able to do something like:
```
<sp-radio-group>.addEventListener('change', function(event) {
    if (event.target !== this) {
        this.value = event.target.value; // here event.target would be a child element and thus have a value property
    }
});
```
4. Between the two options (using a child's `value` or using the parent's `selected`) we should establish a best practice, document it, and lead a user more firmly in that direction. Do you have thoughts on which you'd prefer?

**Comment by bengfarrell** [comment]
OK, this might be a bug then now that I go deeper. So, you're right, I think my initial confusion was that I wasn't observant enough to note that I was listening to the event from `<sp-radio>` prior to upgrading.

However, I'm not getting change events with the new version from the individual `<sp-radio>`s. It looks like the reason is, that the only method I'm using of changing the selection is by clicking each radio button. I think you're relying on the underlying "checked" state of the `<input>` to cause a change event. However, clicking on a radio input does not cause the checked state to change (and therefore issue an event). Neither does manually changing the attribute apparently.

So, end result is that I'm not getting ANY events from this group that have the value property now, only `sp-radio-group` events that have the selected value.

In terms of best practices, I think I like the new behavior with getting the selected value from the radio group. Generally speaking, I'm not going to care what each individual radio button is doing if I'm using a group. I really don't miss the individual radio buttons eventing out. It might actually be more annoying that I have to filter out targets like you're suggesting.

But of course, the documented API around `sp-radio` seems fairly destroyed in this context. If I start using the checked attribute on individual buttons instead of the selected attribute on the radio group, I can check multiple buttons at once with code, and without getting change events. 

Anyway, I think it'll be pretty important to document the different use of buttons in a group and buttons not in a group. I kinda want big warning flags that using "checked" on a radio group won't event, or change the parent "selected" value if that's ultimately the intention.

**Comment by Westbrook** [comment]
Consumption to date has not raised a need for additional work here.
