### ISSUE TITLE
Action menu & Dropdown closing clears focus

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#843]
### Expected Behaviour
Focus shouldn't clear elements outside the menu when the menu overlay closes.

### Actual Behavior
If (as a result of a menu choice) you focus another element like a text input, the focus is almost immediately cleared as a result of the menu overlay closing.

#### Sample PseudoCode that illustrates the problem
<sp-action-menu on-change={ textInput.focus() }>
  <sp-menu>
    <sp-menu-item>Focus</sp-menu-item>
  </sp-menu>
<sp-action-menu>
<sp-textfield ref={textInput}  />

**Comment by adixon-adobe** [comment]
I'm also not seeing a way to easily know when the overlay closes (which would help workaround this issue w/o an ugly setTimeout).

**Comment by Westbrook** [comment]
Yes the event that _would_ talk about that, `new Event('sp-overlay-closed')`, doesn't bubble. I count this as a _private_ API, but I could be convinced that this should be bubbling/composed. AND, currently, the functionality to push the focus back to the trigger comes AFTER that... 😞 

The addition of the `activeElement` check below is a quick hack:
```
if (
    document.activeElement === document.body &&
    (overlay.interaction === 'modal' ||
    ((overlay.interaction === 'replace' ||
        overlay.interaction === 'inline') &&
        !overlay.tabbingAway))
) {
    overlay.trigger.focus();
}
```
As the `active-overlay` element getting moved should always return focus to the `body`.

I have half a mind to leave it there as a safety check, but it seems the full fix I just found will work either way. Running tests/writing tests and then I can get a PR together.
