### ISSUE TITLE
Examples in documentation do not preserve formatting

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#844]
### Expected Behaviour

Sample code should be multi-line and indented

### Actual Behaviour

Sample code has all whitespace compressed

#### Steps to Reproduce

Browse to https://opensource.adobe.com/spectrum-web-components/components/button/examples

**Comment by Westbrook** [comment]
🤔 I wonder if that just happened yesterday when we updated the `html-loader`? 😞

I've been working on a new build for the docs site, which doesn't exhibit this: https://5f442edf58c55d0007387345--spectrum-web-components.netlify.app/components/button/ So there is a "fix" in the works...
