### ISSUE TITLE
Specified version of lit-element is not accurate

### ISSUE THREAD

**Issue by cuberoot** [adobe/spectrum-web-components#845]
### Expected Behaviour

Packages should depend on a version of lit-element that matches the feature set used

### Actual Behaviour

There are packages that [depend on lit-element v2.2.1](https://github.com/adobe/spectrum-web-components/blob/main/packages/radio/package.json#L58), but use `queryAssignedNodes` which was only [introduced in version 2.3](https://github.com/Polymer/lit-element/blob/master/CHANGELOG.md)

#### Steps to Reproduce

I hit this while upgrading a project that uses Parcel 2 to use yarn 2

**Comment by Westbrook** [comment]
I'm looking at centralizing the dependency/export location of these packages in #824, which _should_ address this. Would it be useful to publish an updated `alpha` release with this to ensure that it's working as expected on your end?

**Comment by cuberoot** [comment]
I am happy to wait. I've worked around the issue using a .yarnrc.yml file
