### ISSUE TITLE
Basic usage example for non command line web developers

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#878]
Is there documentation or a workflow for new or casual web developers who do not want to use the command line? 

For example, let's say grandma wants to make her first site. She wants to use Spectrum Web Components on her HTML page. But she doesn't know command line calls or anything like that. 

Can she link to the framework in her HTML page and then start using them in markup? 

For example, 

```
<html>
<head>
<script src="adobe-cdn.com/spectrum.js"/>
<style src="adobe-cdn.com/spectrum.css"/>
</head>
<body>
<sp-button>I'm a button!</sp-button>
</body>
</html>
```

**Comment by Westbrook** [comment]
Generally, the approach to this would look like:
```
<script src="https://unpkg.com/@spectrum-web-components/bundle@0.15.0/elements.js?module" type="module"></script>

<sp-theme scale="large" color="dark">
   <sp-button onclick="alert('I was clicked');">Click me!</sp-button>
</sp-theme>
```
In testing before sending this, I caught an issue with this approach in one of our dependencies: https://github.com/WICG/focus-visible/issues/240 When this gets sorted, the above code will work as intended. I found separate issue with a couple of other CDNs that I am acquainted with that I need to follow up on as well, some on our end, some on theirs. I'll try to post any issues I end up creating for them (when I fully understand them) here as well for reference. The idea being that any CDN that builds ES Modules w/ bare imports would be able to support the above, so:

- https://unpkg.com/@spectrum-web-components/bundle@0.15.0/elements.js?module
- https://jspm.dev/@spectrum-web-components/bundle@0.13.0/elements.js
- https://cdn.skypack.dev/@spectrum-web-components/bundle@0.15.0/elements.js

**Comment by Westbrook** [comment]
We've been able to close the `focus-visible` issue, but there may yet be some eccentricities in the unpkg.com approach that need some thinking on. In the interim, the jspm.dev approach is working now, and will likely be featured in a PR to update our "Getting Started" instructions to feature a "no NPM" starting place for early prototypes/quick and dirty usage of the library. In the interim, this code sample should work right off the shelf for you:
```
<script src="https://jspm.dev/@spectrum-web-components/bundle/elements.js" type="module"></script>

<sp-theme scale="large" color="dark">
   <sp-button onclick="alert('I was clicked');">Click me!</sp-button>
</sp-theme>
```
You can check it out live in this CodePen: https://codepen.io/Westbrook/pen/VwjvegG

**Comment by velara3** [comment]
In a brief test using button and theme it appears to be working! :) 
It seems the sp-theme container element is required? 

When reloading the page locally it appears the JavaScript module is fetched each time. I'm not too familiar with modules. Is that a setting I have in my browser or will it be cached normally when on a server?

**Comment by Westbrook** [comment]
As outlined here: https://opensource.adobe.com/spectrum-web-components/components/bundle working with this approach in a production environment is NOT suggested. This basic example is only appropriate for early prototyping as it loads everything that is a part of Spectrum Web Components, whether you use those elements/icons/etc or not.

If you pivot into a more "production" focused build, you should take a look at some of the tools and recommendations included here: https://modern-web.dev/ or https://web.dev/ or a number of other great online resources for more information on doing just that. We're working on a "Getting Started" page to outline this usage and those facts, so keep an eye out.

For information around "loaded" or "defined" state of a custom element, please take a look at https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined where this is outlined in great depth.

**Comment by velara3** [comment]
Thankful these work! Just curious. I went to one of the [documentation](https://opensource.adobe.com/spectrum-css/button-cta.html) pages they used classes like this:  

```
<body>
 <button class="spectrum-Button spectrum-Button--cta" onclick="alert('I was clicked');">
   <span class="spectrum-Button-label">Click me!</span>
 </button>
</body>
```

I'm trying this approach just to follow the examples and I can't get them to work.

**Comment by Westbrook** [comment]
The documentation that you've linked to here is from the Spectrum CSS project that has its own usage documentation available here: https://opensource.adobe.com/spectrum-css/get-started.html That approach is another option to achieve Spectrum Design on the web. However, the main difference is that while Spectrum CSS delivers the visual language of the Spectrum design system it doesn't deliver any of its functionality.

Our project leverages Spectrum CSS internally to produce the encapsulated component system that we ship as Spectrum Web Components, and while you _can_ leverage them together, you'll likely be better positioned for success if you choose to work directly with a fully functional implementation of Spectrum rather than a design only one, as this prevents you from having to build that functionality yourself.

**Comment by velara3** [comment]
OK I see. I searched for "Spectrum Web Components" using a search engine. The links in the readme on the project are pointing to localhost. Is this the link I want to use: 

https://opensource.adobe.com/spectrum-web-components/

**Comment by Westbrook** [comment]
Yes, that’s the documentation site for this project. We have it listed as the “URL” for this repo, but that’s a great idea to ensure that a direct link is included in the main README.me as well.
