### ISSUE TITLE
Do not sprout tabindex on sp- elements

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#880]
### Expected Behaviour
sp- elements should not have tabindex (and indeed unless they should not be in the tree should not have any global aria attributes either)

### Actual Behaviour
These elements often have tabindex=0/-1 - this causes issues

These elements should generally not be focusable. Even if focus is being delegated to other child elements when they gain focus adding tabindex causes the node to appear in the accessibility tree. This causes VO to add extra groups all over the place

### Reproduce Scenario (including but not limited to)
Run the button demo and note the extra groups being read with VO

#### Steps to Reproduce
* Use Safari
* Turn on VO (Command+F5)
* navigate to https://opensource.adobe.com/spectrum-web-components/components/button/examples
* use VO (CTRL+OPTION) and arrow right to move to the "Normal" button
* Note that it is necessary to navigate through the Normal Group first

#### Platform and Version
MacOS 10.15.6
Safari
VO

#### Logs taken while reproducing problem

Note this issue impacts more than button - but button is the simplest to illustrate the problem.
Changes also need making to checkbox, radio, switch, textfield (amongst others)

**Comment by Westbrook** [comment]
All of these instances are based on the same code base, which will make any workable changes here more unified. The code is available here: https://github.com/adobe/spectrum-web-components/blob/main/packages/shared/src/focusable.ts and specifically references some realities that needed covering during the transition from the heavily polyfilled to no polyfills needed reality of web components over the last few years and hasn't been actively reviewed for a while. 😬 Let us check if there is anything that can be done here in a small change manner and report back.

If this requires a more holistic revision of those features I may choose to take the actionable information here and structure it into a new issue that fully outlines the changes that may be required in this area.

**Comment by Westbrook** [comment]
`aria-disabled` is doubled with `button[disabled]` in a number of places.
