### ISSUE TITLE
Asset file and folder variants need a text alternative

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-web-components#881]
### Expected Behaviour
These variants should expose something to the accessibility APIs

### Actual Behaviour
Nothing is currently exposed to the APIs (it is solely an SVG)

#### Steps to Reproduce
Run the demo
https://opensource.adobe.com/spectrum-web-components/components/asset/examples
Note that the file and folder variants don't produce anything in the accessibility tree.

#### Platform and Version
N/A

#### Sample Code that illustrates the problem
https://opensource.adobe.com/spectrum-web-components/components/asset/examples

**Comment by Westbrook** [comment]
Support for default support released today. We'll address deeper customization and internationalization in follow up issues.
