### ISSUE TITLE
Menu shows focus border on click in safari

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#908]
### Expected Behaviour
A menu doesn't show a blue focus border on click.

### Actual Behaviour
On safari it does. Easy to repro in the doc pages for Menu, Action Menu, & Dropdown

#### Steps to Reproduce
1. Go to https://opensource.adobe.com/spectrum-web-components/components/menu
2. Click on a menu

#### Screenshots
<img width="276" alt="Screen Shot 2020-09-28 at 11 16 28 AM" src="https://user-images.githubusercontent.com/48841507/94458800-0ff1a800-017c-11eb-9a86-2fffe96d5e4a.png">

**Comment by Westbrook** [comment]
We're making some adjustments to this element in #905, let me take a look and see if it makes sense to address this there.

**Comment by Westbrook** [comment]
Looks like this is working in https://5f6e5921adb59e0095ccb7c2--spectrum-web-components.netlify.app/ the preview for #905. Can you confirm you're seeing the same?
