### ISSUE TITLE
[Accordion] When using multiple the accordion item can no longer be closed

### ISSUE THREAD

**Issue by daKmoR** [adobe/spectrum-web-components#920]
### Expected Behaviour

Clicking on an accordion-item should open/close it

### Actual Behaviour

Clicking on an accordion-item only opens it

### Reproduce Scenario

https://opensource.adobe.com/spectrum-web-components/components/accordion
1. Go To the  "Allow Multiple" example
2. Click two times on Heading 3
3. Item remains open

**Comment by Westbrook** [comment]
@andrewhatran you based this off of specific documentation you found in either the w3c or the aria specifications for this pattern, can you share a link to that or any other thoughts you might have on this subject to support a productive conversation here?

**Comment by andrewhatran** [comment]
@daKmoR, after inspecting the [w3 Accordion Best Practices Page](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion), it looks like you are correct. 

`Accordion` should allow expanded `AccordionItems` to collapse when they are clicked or interacted with.

Here is an excerpt from the `Keyboard Interaction` section of the w3 page:
```
When focus is on the accordion header for an expanded panel, collapses the panel
if the implementation supports collapsing. Some implementations require one panel 
to be expanded at all times and allow only one panel to be expanded; 
so, they do not support a collapse function.
```

Perhaps we need a boolean `requireOneExpanded` property (or some better name). 
When true, the Accordion will behave how it currently does.
When false, an expanded AccordionItems will collapse if it is interacted with.

**Comment by Westbrook** [comment]
This was released today. Accordion items can no be closed. Sorry for the delay.

Let us know if you run into any more issues in this area.
