### ISSUE TITLE
Spectrum components don't build in a webpack 5 project

### ISSUE THREAD

**Issue by olliejm** [adobe/spectrum-web-components#932]
### Expected Behaviour
Upgrading from webpack 4 to 5 does not cause any issues when bundling with webpack in a separate project

### Actual Behaviour
Errors occur during bundling because the component doesn't find what it expects from @spectrum-web-components/base package's exports

### Reproduce Scenario (including but not limited to)
1. Create a new project with webpack 5 + dev-server etc, install sp-theme and sp-button
2. Have an index.html which does  nothing but render the sp-button inside an sp-theme
3. Have an index.js which imports the sp-* packages and is the webpack entry point
4. Try webpack build and get the error

#### Platform and Version
Microsoft Windows Version 10.0.17763
Node v12.18.4
Yarn 1.22.5
webpack 5.0.0-rc.4
webpack-dev-server 3.11.0
@spectrum-web-components/button 0.9.2
@spectrum-web-components/theme 0.6.1

#### Sample Code that illustrates the problem
index.js:
```js
import '@spectrum-web-components/theme/theme-light.js';
import '@spectrum-web-components/theme/scale-medium.js';
import '@spectrum-web-components/theme/sp-theme.js';
import '@spectrum-web-components/button/sp-button.js';
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Platform Client</title>
    </head>
    <body>
        <sp-theme color="light" dir="ltr" scale="medium">
            <sp-button>Done</sp-button>
        </sp-theme>
    </body>
</html>

```

webpack.config.js
```js
module.exports = {
    mode: 'development',
    entry: './src/index.js',
    output: {
        filename: '[name].[chunkhash:8].js',
        path: resolve(__dirname, './dist'),
        publicPath: '/'
    },
    devtool: 'source-map'
}

```

#### Logs taken while reproducing problem

```bash
ERROR in ./node_modules/@spectrum-web-components/theme/src/theme.css.js 12:0-52
Module not found: Error: Package path . is not exported from package C:\Users\ojm\source\repos\platform-client\node_modules\@spectrum-web-components\base (see exports field in C:\Users\ojm\source\repos\platform-client\node_modules\@spectrum-web-components\base\package.json)
 @ ./node_modules/@spectrum-web-components/theme/src/Theme.js 13:0-40 251:44-54
 @ ./node_modules/@spectrum-web-components/theme/sp-theme.js 12:0-39 13:34-39
 @ ./src/index.js 3:0-52

webpack 5.0.0-rc.4 compiled with 11 errors in 683 ms
i ｢wdm｣: Failed to compile.
```

The error obviously occurred in the context of a much larger project but even stripped down to as simple of a setup and webpack config that I could think of, it remains. If you then `yarn add -D webpack@latest` to return to webpack 4.x, compilation succeeds

**Comment by olliejm** [comment]
This issue also occurs on macOS

**Comment by Westbrook** [comment]
This may be related to recent changes to our use of the `exports` field in `package.json` that I think is also causing issues with jspm.dev in #878. It's on my list to take a pass on that next, so hopefully solving one will solve the other. Thanks for getting this in a more locally reproducible shape so I have somewhere to start with the investigation!

**Comment by Westbrook** [comment]
@olliejm, I've confirmed a fix locally with your excellent recreation steps, but if you a minute to second that using `"@spectrum-web-components/bundle": "0.15.4-beta.17"` as the gateway to the code shape of our upcoming releases and confirm that the build runs smoothly for you with the packages that relates to, that would be a great help! Looking to have this update out with this update soon.
