### ISSUE TITLE
Differences Spectrum Web Components and Coral Spectrum

### ISSUE THREAD

**Issue by elrumo** [adobe/spectrum-web-components#934]
### Expected Behaviour
It's not an issue, but I wasn't sure where to ask.  What is the difference between the Spectrum Web Components and [Coral Spectrum](https://opensource.adobe.com/coral-spectrum/documentation/)? Maybe some clarification with the differences could be added to the documentation, or even a list of all the Spectrum flavours there are available, i.e. React Spectrum, Coral Spectrum, Spectrum CSS....

**Comment by Westbrook** [comment]
Duplicate of #933.

**Comment by elrumo** [comment]
Thanks for closing it, not sure why it was duplicated.
