### ISSUE TITLE
sp-card title shows up as a browser-style tip on hover

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#938]
### Expected Behaviour
The card title shouldn't show up as a tip on hover.

### Actual Behaviour
Because of the default browser handling of the `title` attribute it does.

#### Steps to Reproduce
Mouse-hover over an example with a title on https://opensource.adobe.com/spectrum-web-components/components/card

**Comment by Westbrook** [comment]
Good one. Have thoughts on an alternative as part of the breaking change that will require, e.g. `header`, `heading`, `headline`, etc?

There is a workaround where you use `<div slot=title>Your title</div>` instead, but we should fix. Luckily, these seems to be the only element that snuck into!

**Comment by adixon-adobe** [comment]
I think `heading` & `subheading` would probably be good. All I was thinking at the time I wrote this was `card-title` and I wasn't ready to suggest that...
