### ISSUE TITLE
sp-card documentation should show different cover aspect ratios

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#940]
### Expected Behaviour
We should have landscape & portrait examples in the docs at https://opensource.adobe.com/spectrum-web-components/components/card, ideally at the preferred min/max aspect ratio as defined at https://spectrum.adobe.com/page/cards/#Preview-aspect-ratio

### Actual Behaviour
There aren't any examples, though I have found the `--spectrum-card-coverphoto-height` variable now, which works to override.

**Comment by Westbrook** [comment]
Check out the Card docs in https://5fd1851025cb8815596aced1--spectrum-web-components.netlify.app/ I've added an example of the `preview` slot, which allows for the mixed aspect ration delivery. I'm working on how that change meets with #960 but wanted to see if you thought we should have something more specific as far as this.

**Comment by adixon-adobe** [comment]
This looks great. Once #960 is resolved I'd expect the `Empty` example to not show the preview section, but otherwise this is a great improvement.

We should also follow up on what changes are coming in SpectrumCSS. It looks like we're behind the designs a bit (there are learn/social/product variants in the XD design for Card that it doesn't look like are supported yet).

**Comment by Westbrook** [comment]
Regarding other card patterns here...

I like them, however Spectrum CSS hasn't implemented them yet. If these are things you think your team is going to need, let's bring them up in the next Spectrum sync and track them in a new ticket?

Beyond that the conversation in #960 should have us wrapped here?

**Comment by Westbrook** [comment]
Thanks @najikahalsema for including this in #1131. @adixon-adobe if you feel like we need more image ratios, please let us know!
