### ISSUE TITLE
Is there small scale support planned? 

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#953]
Is there any plan for support for a "small" scale? 

![image](https://user-images.githubusercontent.com/1084127/95930722-d8dee180-0d8c-11eb-87d5-d99448b6623c.png)

https://opensource.adobe.com/spectrum-css/button-over-background.html

Specifically in some of the plugin environments the buttons I'm using are around 26 to 28 pixels high. 

![image](https://user-images.githubusercontent.com/1084127/95930711-d11f3d00-0d8c-11eb-9b53-ee888770afc9.png)

**Comment by Westbrook** [comment]
Thanks for the question!

At current the Spectrum Design system only support a "Medium" and a "Large" scale, which more accurately translate to "desktop" and "mobile" respectively. You can read more about this here: https://spectrum.adobe.com/page/platform-scale/ There is a t-shirt size project coming down the pipe that would break down various components in each scale into multiple sizes in each of the scales, but we don't have a specific timeline by which that will be available in Spectrum Web Components. 

The "API" section of each component (e.g. https://opensource.adobe.com/spectrum-web-components/components/button/api) list a `CSS Custom Properties` section that lists properties that can be leveraged to "customize" the delivery of a specific component, but you are likely to have better success long term if you can be patient for the t-shirt sizing changes.

For now, I'm going to close this issue as "question answered".

**Comment by velara3** [comment]
Since this post Photoshop has added the UXP plugin environment the same as Adobe XD. These use a "small" scale theme. 

Did anything come from the T-Shirt project? What is a T-Shirt project? 

If you don't have the bandwidth for this can you describe how I can do this?

**Comment by Westbrook** [comment]
There’s not a system scale for “small” as per the Spectrum design system where medium/large are called desktop/mobile: https://spectrum.adobe.com/page/platform-scale/

Button elements do support the “t-shirt sizing” system as outlines in the “Sizes” section on this page: https://opensource.adobe.com/spectrum-web-components/components/button and exhibited here: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/button-cta-sizes--s

Whether these options line up with UXP or not is not something I know for sure. Would you be able to share more info on the “small” scale that you are referencing?

**Comment by velara3** [comment]
The small(er) scale is what is used in the UXP environment. If you have access to the IO Console you can download a UXP starter pack or follow the guide below. 

https://adobexdplatform.com/plugin-docs/tutorials/quick-start

Add a few buttons and textfields and load it into Adobe XD and you can see the default sizes for Spectrum components. 

Unfortunately, I'm having an issue where I can't launch the UXP environment at the moment but when I can I'll post images.
