### ISSUE TITLE
sp-card subheading incorrectly uses text-transform: uppercase

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#959]
### Expected Behaviour
Description isn't transformed to uppercase. The spectrum examples don't do this: https://spectrum.adobe.com/page/cards/

The web component documentation examples should also include longer descriptions.

### Actual Behaviour
We're picking up `text-transform: uppercase` from spectrum-css (which is written up as https://github.com/adobe/spectrum-css/issues/1054)

### Reproduce Scenario (including but not limited to)
1. View the examples here: https://opensource.adobe.com/spectrum-web-components/components/card
2. Inspect the css & notice the `text-transform: uppercase (I see that all the example text is all uppercase but you can also repro by changing the label text).

**Comment by adixon-adobe** [comment]
Writing this up since we'll want to override the bad css for now.

**Comment by Westbrook** [comment]
This is touched on in https://github.com/adobe/spectrum-web-components/pull/936 where we no long receive text styling as part of the component (don't ask), so we'd be able to address this there.

**Comment by Westbrook** [comment]
fixed by #1045
