### ISSUE TITLE
sp-card should hide the cover photo area if no slotted content is provided

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-web-components#960]
### Expected Behaviour
Cards without previews are supported in the designs at https://spectrum.adobe.com/page/cards/ (easiest to see if you download the UI kit).

Ideally if you omit the `cover-photo` slot, it just doesn't show up.

### Actual Behaviour
In the "Empty" example at https://opensource.adobe.com/spectrum-web-components/components/card the cover photo section still takes up space.

**Comment by Westbrook** [comment]
I feel, this is likely not documented anywhere so I can be talked down, that a "preview" should not take up space when missing, but a "cover-image" should take space when missing. Whether that's something we can agree on or not, it's not _currently_ possible to have a "standard" card with a "preview", which is a bug that needs to be fixed. From there, maybe we can come to an agreement that the version with "cover-image" can continue to display "empty" and is and the version with "preview" (or lack there of) could not leave space for an image?

**Comment by adixon-adobe** [comment]
@Westbrook I *meant* the `cover-photo` slot and must have gotten confused while digging into the designs. I've updated the issue here to properly point at the spectrum design page, and refer to the `cover-photo`.

**Comment by adixon-adobe** [comment]
Also, what is the `preview` you're referring to? I have a feeling we're actually talking about different things there. This is what I was referring to: https://spectrum.adobe.com/page/cards/#Anatomy (but if you look at the actual XD file it's clearer that this section can be omitted).

**Comment by Westbrook** [comment]
The "preview" context that is outlined in Spectrum design is applied in practice by both the [`.spectrum-Card-preview`](https://opensource.adobe.com/spectrum-css/card-asset.html#variants) and [`.spectrum-Card-coverPhoto`](https://opensource.adobe.com/spectrum-css/card.html#standard) classes in Spectrum CSS. Currently, those are surfaced via the `cover-photo` and `preview` [slots](https://opensource.adobe.com/spectrum-web-components/components/card/api) in SWC. At a point in the past there was more clarity on how you would get access to leveraging one or the other, but it seems I may have collapsed that at the last refactor without thinking.

As styled, when a `cover-photo` slot is available, it has a fixed min-height, where as the `preview` slot does not. A `preview` slot is what is needed for the "preview image" to not be restricted by the `--spectrum-card-coverphoto-height` CSS custom property, as well as a card that can have "no preview".

The steps that I think are required here are:
- confirm which APIs should surface the `preview` slot, hopefully it's not breaking, we may need to review old releases to confirm this
- build back in the capability to leverage this slot (we'll possibly need to leverage the [`ObserveSlotPresence`](https://github.com/adobe/spectrum-web-components/blob/main/packages/shared/src/observe-slot-presence.ts) mixin to make that possible)
- document both the "empty/no preview area" card and the "portrait" card to ensure complete coverage of options
- profit

**Comment by najikahalsema** [comment]
Preview: https://5ff8dac3cc57a61bd97df915--spectrum-web-components.netlify.app/components/card

@adixon-adobe , Westbrook and I discussed this issue. You can view the updated empty card at the above link. However, we are unsure about the blank state of the card. If there is no content in the card, do we still want to display it with the inner CSS intact (as it is in the preview), or do we want to just display nothing at all?

**Comment by Westbrook** [comment]
@adixon-adobe unless your opposed to it, I say we take out the documentation for "empty" and move forward with the documentation additions available above. Are there any other requirements your team has on this right now?

**Comment by adixon-adobe** [comment]
I think this makes sense.

The case I was looking at using this for would have had just a heading/subheading (but no preview). Except we decided to go with a toast instead so I no longer have a pressing need.

You can also hide the preview by setting `--spectrum-card-coverphoto-height: 0;` (and adding more bottom padding to the card).

**Comment by najikahalsema** [comment]
Okay. That sounds fine to me. If you could take a look at the PR I would be very grateful.
