### ISSUE TITLE
Do you need to set the id of the icon in an Spectrum Action Button?

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#961]
In the Spectrum Action Button documentation the icon has an id set of `spectrum-icon-18-Edit`. Does the id need to be set? Does it break anything to remove it? Alternatively and possibly related could I remove the path or use my own path? 

```
<sp-action-button>
    <svg slot="icon" id="spectrum-icon-18-Edit" viewBox="0 0 36 36">
        <path
            d="M33.567 8.2L27.8 2.432a1.215 1.215 0 0 0-.866-.353H26.9a1.371 1.371 0 0 0-.927.406L5.084 23.372a.99.99 0 0 0-.251.422L2.055 33.1c-.114.377.459.851.783.851a.251.251 0 0 0 .062-.007c.276-.063 7.866-2.344 9.311-2.778a.972.972 0 0 0 .414-.249l20.888-20.889a1.372 1.372 0 0 0 .4-.883 1.221 1.221 0 0 0-.346-.945zM11.4 29.316c-2.161.649-4.862 1.465-6.729 2.022l2.009-6.73z"
        ></path>
    </svg>
    This is an action button
</sp-action-button>

```
https://opensource.adobe.com/spectrum-web-components/components/action-button

**Comment by adixon-adobe** [comment]
No -- the id is just used for the documentation css. It's not necessary to use.

You can also include your own SVG there, or any SVG in the workflow icons: https://opensource.adobe.com/spectrum-web-components/components/icons-workflow

This example is intended to show how you can include a custom icon, but I see the examples are pretty sparse.

**Comment by adixon-adobe** [comment]
I wrote up an issue to track further work to improve the documentation. Let us know if this helps answer your questions and if so I'll close this issue out!
