### ISSUE TITLE
sp-textfield has a wrong focus & hover style

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#988]
### Expected Behaviour
When focused and hovered, the `<sp-textfield>` should have a blue border.

### Actual Behaviour
When hovered, it has a gray border, whether focused or not.
When focued but not hovered, it has a blue border,

### Reproduce Scenario (including but not limited to)

https://opensource.adobe.com/spectrum-web-components/components/textfield

spectrum-css has right preference.
https://opensource.adobe.com/spectrum-css/textfield.html

**Comment by Westbrook** [comment]
@OpportunityLiu thanks for reporting this! Looks like it was a relatively quick fix.

I submitted #989 to address this. You can check out the preview build of the change here: https://5f996ca3fb66829589728107--spectrum-web-components.netlify.app/storybook/?path=/story/textfield--default We're currently batching together a number of breaking changes from Spectrum CSS before making our next release, but hopefully we can have this out to everyone in the next couple of weeks!

**Comment by Westbrook** [comment]
This update was released today. Sorry for the delay.

Let us know if you run into any more issues here.
