### ISSUE TITLE
Looking for a component like Action Menu but with changeable icon on select

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#991]
I'd like a component that is an icon at around 28x28 that when clicked shows a dropdown menu. When the user selects a new choice the icon is updated. 

I think the Action Menu is what I would like but I'm going for. But I would be changing the icon each time. Since I'm still learning about shadow root web components I want to avoid misusing a component from it's intended purpose. 

So the component starts out with an icon like let's say, a magnifying glass. Then when the user clicks it a dropdown is shown that has a list of items, one is arrow, the second is square. The user selects the arrow and the dropdown closes and the icon changes to an arrow. 

I would use an alternative icon but not set the label. See the alternative icon example. 

https://opensource.adobe.com/spectrum-web-components/components/action-menu#alternative-icon

**Comment by Westbrook** [comment]
You could certainly wrap or extend the `<sp-action-menu>` element to do this, a la: https://webcomponents.dev/edit/HC7cQJ8MQu4RSlLvMaoC Notice the use of the `[slot="icon"]` element, but it's dynamic customization. Hopefully this is the sort of functionality that you are looking for in this case.

However, it's unclear how this will fit into the library in the future. There is a somewhat similar UI outlined in Spectrum via: https://spectrum.adobe.com/page/action-button/#Only-group-related-actions-with-a-hold-icon but we've not yet decided whether such a pattern will be delivered as a composition of the patterns available in Spectrum Web Components or as a specific component of its own. That work can be tracked in #215

**Comment by velara3** [comment]
OK. I'll use the Action Menu since it's dynamic and I can change it. It will solve my case where I want an icon that opens a list of options. Action button might work too if I can figure out how to do a pop up menu list. :)
