### ISSUE TITLE
sp-dialog-wrapper dismissed by clicking overlay, regardless the `dismissible` property

### ISSUE THREAD

**Issue by OpportunityLiu** [adobe/spectrum-web-components#992]
### Expected Behaviour
When `dismissible` is set to `false`, the dialog can only closed programmly.
### Actual Behaviour
sp-dialog-wrapper dismissed by clicking overlay, regardless the `dismissible` property.

It it designed to do so?
#### Platform and Version
@spectrum-web-components/dialog@0.3.4

**Comment by Westbrook** [comment]
This update was release today. Sorry for the delay.

Let us know if you run into any more issues here.
