### ISSUE TITLE
How to truncate the label of a list component and show overflow ellipsis

### ISSUE THREAD

**Issue by velara3** [adobe/spectrum-web-components#993]
Is there a way to set the Spectrum dropdown list component so that I can set to a max width and the label is truncated and an overflow ellipsis appears when it needs to. Here's what I have now using a regular list and then how I would like the Spectrum List to appear: 

![image](https://user-images.githubusercontent.com/1084127/97945382-03e5a100-1d4d-11eb-94d3-4d632d286b61.png)

https://opensource.adobe.com/spectrum-web-components/components/dropdown

**Update:** 
Welp, it looks like it already supports it.

**Comment by Westbrook** [comment]
If this isn’t working as expected, feel free to reopen this, but this sounds to be cleared up now.
